### ISSUE TITLE
Multiple instruments can not be searched 

### ISSUE THREAD

**Issue by proritu** [krishnavelu/alice_blue#100]
while using the below code not getting the instrument data for multiple instruments rather getting a blank list.

code:
instruments = alice.search_instruments('NFO',['NIFTY','INFY'])
print(instruments)

result:
[]

**Comment by krishnavelu** [comment]
`search_instruments()` is for searching single entity. You can either search `NIFTY` or 'INFY'. You cannot search both on a single `search_instruments()` call. Do a separate call for 'NIFTY' & 'INFY'

**Comment by krishnavelu** [comment]
Your description looks like this is a bug in the library. But this is not a bug, its a new feature request. Which supports both string data type and list data type. So please explain that. And create a pull request to develop if possible.
