### ISSUE TITLE
get_live_feed

### ISSUE THREAD

**Issue by sanjaygoyan** [krishnavelu/alice_blue#104]
Hi Krish,

I would like to fetch get_live_feed with symbol wise do not want subscribe. is there any method for that ?

**Comment by krishnavelu** [comment]
No. You’ve to subscribe for getting live feed

**Comment by krishinweb** [comment]
On trying to subscribe to live feed,this error is coming.
![livefeed](https://user-images.githubusercontent.com/63206205/82298979-89a9a600-99d2-11ea-8bc5-84dac4953624.png)
