### ISSUE TITLE
facing issue with import 

### ISSUE THREAD

**Issue by SarathKumarGandla** [krishnavelu/alice_blue#108]
>>>>> from alice_blue import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sarath/anaconda3/lib/python3.5/site-packages/alice_blue/__init__.py", line 1, in <module>
    from .alice_blue import AliceBlue, TransactionType, OrderType, ProductType, LiveFeedType, Instrument
  File "/home/sarath/anaconda3/lib/python3.5/site-packages/alice_blue/alice_blue.py", line 205
    raise Exception(f"Couldn't get profile info with credentials provided '{e}'")
                                                                                                 ^
SyntaxError: invalid syntax

**Comment by krishnavelu** [comment]
Many are able to import and use this library successfully. It should be something with your environment, anaconda. Try pure python or try importing as the document says.

`from alice_blue import *`

**Comment by ssalpure** [comment]
> Many are able to import and use this library successfully. It should be something with your environment, anaconda. Try pure python or try importing as the document says.
> 
> `from alice_blue import *`

Hi
This is a genuine problem. Same error at my end. Just adding "from alice_blue import *" throws
`Traceback (most recent call last):
  File "alicetest.py", line 1, in <module>
    from alice_blue import *
  File "C:\python35\lib\site-packages\alice_blue\__init__.py", line 1, in <module>
    from .alice_blue import AliceBlue, TransactionType, OrderType, ProductType, LiveFeedType, Instrument
  File "C:\python35\lib\site-packages\alice_blue\alice_blue.py", line 210
    raise Exception(f"Couldn't get profile info with credentials provided '{e}'")
                                                                               ^
SyntaxError: invalid syntax`

What you need to tell us is that what version of python you used and also publish the pip list so that we can cross check versions of required libraries. Because I am sure it some pip library version mismatch issue.  Pls help with the information. I am using regular python.

**Comment by krishnavelu** [comment]
Update your python installation to the latest one.

**Comment by krishnavelu** [comment]
Python <3.5 gives import error.
- [x] Add >=3.6 in setup.py

**Comment by mdkhaisar** [comment]
I am trying with pure python(3.9) environment , 

`from alice_blue import *  ` #throws
 
> Traceback (most recent call last):
> 
>   File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py:3251 in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
> 
>   Input In [6] in <module>
>     from alice_blue import *
> 
>   File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\alice_blue\__init__.py:1 in <module>
>     from .alice_blue import AliceBlue, TransactionType, OrderType, ProductType, LiveFeedType, Instrument
> 
>   File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\alice_blue\alice_blue.py:11 in <module>
>     from protlib import CUInt, CStruct, CULong, CUChar, CArray, CUShort, CString
> 
>   File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\protlib.py:220
>     raise CError, cerror, tb
>                 ^
> SyntaxError: invalid syntax

**Comment by nitishgupta08** [comment]
I am facing the same issue in Django 4.0.3 environment. Please help me in this. Struggling to solve this from last 24hrs

**Comment by nitishgupta08** [comment]
You might want to run this outside your environment. This worked for me.

**Comment by mrsprawin** [comment]
from alice_blue import *

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\alice_blue_init_.py:1 in
from .alice_blue import AliceBlue, TransactionType, OrderType, ProductType, LiveFeedType, Instrument

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\alice_blue\alice_blue.py:11 in
from protlib import CUInt, CStruct, CULong, CUChar, CArray, CUShort, CString

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\protlib.py:220
raise CError, cerror, tb
^
SyntaxError: invalid syntax


This error happening in jupyter Notebook.

**Comment by krishnavelu** [comment]
Uninstall and install the latest version
