### ISSUE TITLE
How to get the API Secret or activate the API

### ISSUE THREAD

**Issue by Parva14** [krishnavelu/alice_blue#11]
Hey,
I just opened my demat account with Alice Blue and couldn't find anything related to API on their website. I called their customer support too but did not get any proper response. It would be great if you could provide me with a link from which I can activate the API and get my API Secret.

Thankyou,
Parva

**Comment by krishnavelu** [comment]
You need to activate api in your account and get api_secret from alice blue.
Contact customer care of alice blue.
Also refer this #8

**Comment by krishnavelu** [comment]
Closing as of now.

**Comment by yogesh1236** [comment]
dear sir
i have opened account with aliceblue and am following your python script for getting access toke .with same credentials i am able to login in ant web .but am unable to get access token with api secret given by alice blue.
i am getting response to print access token as 'none'
will you please help

**Comment by SanjuKumarGupta** [comment]
class ExampleOAuth2Client:
    def __init__(self, client_id, client_secret):
        self.access_token = None

        self.service = OAuth2Service(
            name="foo",
            client_id=client_id,
            client_secret=client_secret,
            access_token_url="http://api.example.com/oauth/access_token",
            authorize_url="http://api.example.com/oauth/access_token",
            base_url="http://api.example.com/",
        )

        self.get_access_token()

    def get_access_token(self):
        data = {'code': 'bar',
                'grant_type': 'client_credentials',
                'redirect_uri': 'http://example.com/'}

        session = self.service.get_auth_session(data=data, decoder=json.loads)

        self.access_token = session.access_token

**Comment by SanjuKumarGupta** [comment]
i am trying this but its not workig, if anyone have idea please suggest.

**Comment by aatishgupta** [comment]
Hi krishna sir,
How other people can login through my website and place order from my website.
Just like people do on  this **https://www.squareoff.in/** website.
I mean which API i have to use for this.

**Comment by krishnavelu** [comment]
This library is for personal use. Not for any commercial use. Contact Alice for the same.

**Comment by rockeypandit** [comment]
> Hi krishna sir,
> How other people can login through my website and place order from my website.
> Just like people do on this **https://www.squareoff.in/** website.
> I mean which API i have to use for this.

Hi ,  @aatishgupta
I was trying to implement same but didnt got any answer yet. If u got any solution can u share it.

**Comment by aatishgupta** [comment]
Yes, you can use this https://github.com/aeron7/aliceblue-python .
In this link code is written for single user. In python flask.

**Comment by aatishgupta** [comment]
> > Hi krishna sir,
> > How other people can login through my website and place order from my website.
> > Just like people do on this **https://www.squareoff.in/** website.
> > I mean which API i have to use for this.
> 
> Hi , @aatishgupta
> I was trying to implement same but didnt got any answer yet. If u got any solution can u share it.

Yes, you can use this https://github.com/aeron7/aliceblue-python .
In this link code is written for single user. In python flask.

**Comment by rockeypandit** [comment]
> > > Hi krishna sir,
> > > How other people can login through my website and place order from my website.
> > > Just like people do on this **https://www.squareoff.in/** website.
> > > I mean which API i have to use for this.
> > 
> > 
> > Hi , @aatishgupta
> > I was trying to implement same but didnt got any answer yet. If u got any solution can u share it.
> 
> Yes, you can use this https://github.com/aeron7/aliceblue-python .
> In this link code is written for single user. In python flask.

@aatishgupta can i get your email address or any contact for any further query

**Comment by aatishgupta** [comment]
> > > > Hi krishna sir,
> > > > How other people can login through my website and place order from my website.
> > > > Just like people do on this **https://www.squareoff.in/** website.
> > > > I mean which API i have to use for this.
> > > 
> > > 
> > > Hi , @aatishgupta
> > > I was trying to implement same but didnt got any answer yet. If u got any solution can u share it.
> > 
> > 
> > Yes, you can use this https://github.com/aeron7/aliceblue-python .
> > In this link code is written for single user. In python flask.
> 
> @aatishgupta can i get your email address or any contact for any further query
 https://github.com/aeron7/aliceblue-python  Code in this link is not written by me.
I am using python alice-blue library.

**Comment by aatishgupta** [comment]
But i installed on my and tested on my machine that is working fine for me.

**Comment by aatishgupta** [comment]
> > > > > Hi krishna sir,
> > > > > How other people can login through my website and place order from my website.
> > > > > Just like people do on this **https://www.squareoff.in/** website.
> > > > > I mean which API i have to use for this.
> > > > 
> > > > 
> > > > Hi , @aatishgupta
> > > > I was trying to implement same but didnt got any answer yet. If u got any solution can u share it.
> > > 
> > > 
> > > Yes, you can use this https://github.com/aeron7/aliceblue-python .
> > > In this link code is written for single user. In python flask.
> > 
> > 
> > @aatishgupta can i get your email address or any contact for any further query
> > https://github.com/aeron7/aliceblue-python  Code in this link is not written by me.
> > I am using python alice-blue library.

if you want alice-blue library practs refer my repo of aliceblue i have written one example of 5 minutes moving average .
https://github.com/aatishgupta

**Comment by aatishgupta** [comment]
> > > > Hi krishna sir,
> > > > How other people can login through my website and place order from my website.
> > > > Just like people do on this **https://www.squareoff.in/** website.
> > > > I mean which API i have to use for this.
> > > 
> > > 
> > > Hi , @aatishgupta
> > > I was trying to implement same but didnt got any answer yet. If u got any solution can u share it.
> > 
> > 
> > Yes, you can use this https://github.com/aeron7/aliceblue-python .
> > In this link code is written for single user. In python flask.
> 
> @aatishgupta can i get your email address or any contact for any further query

Hey is your issue got resolved.
if not here is my email id **aatishg25@gmail.com** .
