### ISSUE TITLE
lot_size is coming as None for Crudeoil Fut Contract

### ISSUE THREAD

**Issue by jaydave1988** [krishnavelu/alice_blue#110]
Instrument: Instrument(exchange='MCX', token=217575, symbol='CRUDEOIL JUN FUT', name='', expiry=datetime.date(2020, 6, 19), lot_size=None)

Even I have seen for all MCX contracts, it is coming as None.

**Comment by krishnavelu** [comment]
This is the response for nse options master [contract](https://gist.github.com/krishnavelu/1beacb95bfa610c2791cd9840c38071d)
This is the response for mcx master [contract](https://gist.github.com/krishnavelu/a3ed245ae75f8e47d053e23dbd212c1d)
Alice server doesn't sent lot size for MCX. Contact alice.
