### ISSUE TITLE
SLM Order Issue

### ISSUE THREAD

**Issue by pangalanrao** [krishnavelu/alice_blue#111]
Following code gives Order Rejection saying invalid Price Type. Can you kindly point out my mistake. Same code works fine if I change order type to Market.

`  instruments=pd.read_csv('trade.csv',names=['exchange','tradingsymbol','high','low','quantity','max_trade'])
  for x in range(len(instruments['tradingsymbol'])):    
    if tradingsymbol[-1]==instruments['tradingsymbol'][x]:        
      high=float(instruments['high'][x])
      low=float(instruments['low'][x])
      quantity=instruments['quantity'][x]
      
  if real_trading == 'Y':
      print ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%Buy%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
      order_id=alice.place_order(transaction_type = TransactionType.Buy,
                   instrument = alice.get_instrument_by_symbol('NSE',instruments['tradingsymbol'][x]),
                   quantity =quantity,
                   order_type = OrderType.StopLossMarket,
                   product_type = ProductType.Intraday,
                   price = 0.00,
                   trigger_price = high,
                   stop_loss = None,
                   square_off = None,
                   trailing_sl = None,
                   is_amo = False,
                   )
      
      print(now,tradingsymbol,quantity,'BUY',order_id)
  `

**Comment by krishnavelu** [comment]
which version of the library you are using?

**Comment by pangalanrao** [comment]
I was using 0.0.6 library now updated and SLM working fine. Thanks for reply

Regards

*-- Life is Short, Make it Fast*
