### ISSUE TITLE
is there anyway to get list of rejected orders ?

### ISSUE THREAD

**Issue by keerthankumar** [krishnavelu/alice_blue#114]
when I place an order in API, even if it rejected ( whatever the reason ) but still the API command response shows success,

is there any way to get all the rejected orders for the DAY? this feature will be really helpful

**Comment by krishnavelu** [comment]
the success means order placement is success. For getting order status use [this](https://github.com/krishnavelu/alice_blue/tree/develop#getting-order-history-and-trade-details).
