### ISSUE TITLE
Error for BSE symbols

### ISSUE THREAD

**Issue by keerthankumar** [krishnavelu/alice_blue#116]
Im trying below lines of code which are given as examples in github explanations,

```
    stock = alice.get_instrument_by_token('BSE', '500112')
    stock = alice.get_instrument_by_symbol('BSE', 'Sensex')
```

which gives below error

`WARNING:root:Cannot find symbol BSE Sensex in master contract
`

**Comment by krishnavelu** [comment]
The correct code is `stock = alice.get_instrument_by_symbol('BSE', 'SENSEX')`
Even though if you couldn't find the instrument by symbol you should be able to find by `alice.search_instruments('BSE', 'SENSEX')` But that was also not working. Fixed now. And documents updated.
