### ISSUE TITLE
Banknifty spot price

### ISSUE THREAD

**Issue by keerthankumar** [krishnavelu/alice_blue#117]
Im trying to find the banknifty sport price with below code

`print(alice.get_instrument_by_symbol('NSE', 'Banknifty'))`

I get below error
`WARNING:root:Cannot find symbol NSE Banknifty in master contract
`

But for nifty it works
`print(alice.get_instrument_by_symbol('NSE', 'Nifty 50'))
`

What am i missing ?

**Comment by PythonNovice5** [comment]
First of all, you don't get spot price using  - print(alice.get_instrument_by_symbol('NSE', 'Nifty 50')) 
You just get this - Instrument(exchange='NSE', token=26000, symbol='Nifty 50', name='Nifty 50', expiry=None, lot_size=None)

For bank nifty the name you have mentioned is not correct. Try using :
print(alice.get_instrument_by_symbol('NSE', 'Nifty Bank'))

or 

print(alice.get_instrument_by_token('NSE','26009'))

**Comment by keerthankumar** [comment]
@PythonNovice5 is there any way to get snapshot data without for any stock/option without subscribing to it?

**Comment by krishnavelu** [comment]
@keerthankumar there is no way without subscribing it.
