### ISSUE TITLE
Livefeed not working in cmd

### ISSUE THREAD

**Issue by PythonNovice5** [krishnavelu/alice_blue#119]
Hi, 

After authorization and loading master contracts of NSE, I wanted to get live feed for Banknifty spot. I wrote the following code following your instructions - 
![image](https://user-images.githubusercontent.com/25523526/83326599-f48c9400-a292-11ea-9fad-44da4a013bb0.png)

The output I am getting is as following - 
![image](https://user-images.githubusercontent.com/25523526/83326622-3289b800-a293-11ea-992c-1e6983e6c7eb.png)

Am I doing anything wrong here? Please help.

**Comment by PythonNovice5** [comment]
**UPDATE**:

In cmd Use python -i file.py instead of python file.py (as it treats it like executing in python IDLE). It works.

That being said, issue is still there while running like normal .py file on cmd.

**Comment by krishnavelu** [comment]
What is your expected output in the above mentioned code? as per your code, the output is correct.

**Comment by PythonNovice5** [comment]
I think print(message) was not executed. That is my expected output.

**Comment by krishnavelu** [comment]
It won't, follow the example exactly as what its given [here](https://github.com/krishnavelu/alice_blue#subscribe-to-a-live-feed)

**Comment by PythonNovice5** [comment]
If you look at my attached screenshot it's exactly same as your example. Moreover it's working in Python IDLE without any issue. If you could please try running .py file on cmd and confirm it would be a great help.

**Comment by krishnavelu** [comment]
It’s not same. Follow exactly the same. You’ll get the output.
