### ISSUE TITLE
Add Open Interest callback and DPR callback

### ISSUE THREAD

**Issue by krishnavelu** [krishnavelu/alice_blue#120]
- [x] Both open interest callback and DPR callback needs to be added.
- [x] Remove all logging in `__on_data_callback`

**Comment by krishnavelu** [comment]
Note: OI callback and DPR callbacks are not working. The alice [document](http://antplus.aliceblueonline.com/#dpr) says we don't need to separately subscribe it. But still server doesn't any OI or DPR messages (checked during off market time).

**Comment by kumar0809** [comment]
Hi Krishnavelu, 

I am not getting OI data with  alice.subscribe(ins_scrip, LiveFeedType.MARKET_DATA). can you plesae help me how to get oi data from websocket.

**Comment by krishnavelu** [comment]
OI data is not available.
