### ISSUE TITLE
How to store live feed of multiple instruments in a variable and use it everywhere

### ISSUE THREAD

**Issue by PythonNovice5** [krishnavelu/alice_blue#121]
Hi,

I have subscribed to 2 instruments (nifty, banknifty) and ran it. It seems event_handler_quote_update method runs twice because instruments are 2. But I am not able to store the values as they get lost even if the variable is global (as you shown in main.py example code).

Please help. I tried everything to achieve this.

**Comment by Dhilipkanna** [comment]
I was about to post this. Anyone please help.
Need to know how to store ltp in a variable from livefeed and place a order with it.

**Comment by krishnavelu** [comment]
Learn python
