### ISSUE TITLE
Banknifty live feed - 3 mniutes behind actually price in Live market

### ISSUE THREAD

**Issue by PythonNovice5** [krishnavelu/alice_blue#122]
Hi,

**Prerequisite**
Do this test in live market only

**Steps to replicate**:
1. Subscribe to banknifty spot
2. Run subscribe in while loop (by doing subscribe, unsubscribe) to get the updated prices
3. Print message['exchange_time'] as well
4. Observe that exchange time and Banknifty spot price are both behind the live data on chart. 

Please help.

**Comment by krishnavelu** [comment]
Why are you doing subscribe, unsubscribe in while loop?
