### ISSUE TITLE
issue placing order in CDS

### ISSUE THREAD

**Issue by agujrathi** [krishnavelu/alice_blue#123]
Hi team,

I see error when placing order in CDS segment.

order placement status, {'status': 'error', 'message': 'CNC is not supported in CDS segment.', 'data': {}}

Order is placed as 'Delivery' 
other segments working but not CDS.. ?

Any issues ?

**Comment by krishnavelu** [comment]
The error message itself shows clearly what’s wrong, what else you need?

**Comment by agujrathi** [comment]
Hi..

So you mean orders in delivery not possible by API in cds segment..?

Same orders possible from UI and kobile app.

I remember long back there was issue in library to set CNC or NRML.

I guess something wrong around that peice..?

we just have flag *Delivery* ..
Library uses cnc or nrml, etc..

Ultimately the api to place order in delivery mode in cds segment fails..
Which is successful manual.. .

All other segments goes through..

Something is nasty or the verybold issue back in latest version?

**Comment by agujrathi** [comment]
The code should have below fix..

Original code
```
  if(product_type == ProductType.Intraday):
            prod_type = 'MIS'
        elif(product_type == ProductType.Delivery):
            if(instrument.exchange == 'NFO') or (instrument.exchange == 'MCX'):
                prod_type = 'NRML'
            else:
                prod_type = 'CNC'
```
Suggested fix...

```
  if(product_type == ProductType.Intraday):
            prod_type = 'MIS'
        elif(product_type == ProductType.Delivery):
            if(instrument.exchange == 'NFO') or (instrument.exchange == 'MCX') or **(instrument.exchange == 'CDS'**):
                prod_type = 'NRML'
            else:
                prod_type = 'CNC'
```
Above fix works & should be ideally must in code..

**Comment by krishnavelu** [comment]
@agujrathi I've fixed in develop. Please test and let me know if it work.
I don't have CDS segment enabled to test this.
