### ISSUE TITLE
Multiple instruments in subscribe for live data

### ISSUE THREAD

**Issue by psadiga** [krishnavelu/alice_blue#125]
Hello,
As per my understanding, If we subscribe to multiple instruments, event_handler_quote_update() is called twice for each instrument. Please correct me if I am wrong. But the return data is only for first instrument most of the time. Sometimes, the 2nd instruments' data pops up in between. how can we get both the data one by one? Thank you.

**Comment by krishnavelu** [comment]
Whenever there is an LTP update of any scrip you’ve subscribed, the callback function will be called.

**Comment by psadiga** [comment]
Hi, You mean to say when there is a change in LTP value of the instruments, the call-back function will be called.
If that is the case, if there is a change in LTP value of multiple instruments at one instant of time, how the data will be received? Will some data points of some instruments be skipped or all datas  would come in a serial manner? Correct me if my understanding is wrong

**Comment by krishnavelu** [comment]
Callback is called once per update per scrip. It will be called serially.
