### ISSUE TITLE
Slow execution and 

### ISSUE THREAD

**Issue by kamaleshvm** [krishnavelu/alice_blue#127]
The api access token and other execution very slow it is taking more than 5 minutes.

**Comment by kamaleshvm** [comment]
The running time give below for your reference.

01:23:39.108760 : Start time
01:25:08.925264 Svim095BtaCu7OD5SE_9k0hR_n7vHfi11P-AoAQ-WVk.ziGPnJW7XV1M5vWD-5QkpjUuALN0Yw6mWlo_y_3q1k8 :access token generated
01:28:48.470706 {'status': 'success', 'message': '' : next message

**Comment by krishnavelu** [comment]
It doesn’t take 5 mins for me. Is it consistent? Every time it takes 5 mins?

**Comment by kamaleshvm** [comment]
No the issue at backend looks like. Now it is running with in a min.
