### ISSUE TITLE
cancel_order is not cancelling mis orders.

### ISSUE THREAD

**Issue by jaydave1988** [krishnavelu/alice_blue#128]
cancel_order is not cancelling mis orders. Though status is coming is Ok
{'status': 'success', 'message': '', 'data': {'status': 'Ok'}}

**Comment by krishnavelu** [comment]
Can you show me a sample code to replicate and some logs? Like print the positions before cancelling and after?

**Comment by krishnavelu** [comment]
@jaydave1988 Is this solved or still an issue?

**Comment by krishnavelu** [comment]
@jaydave1988 So your issue solved?

**Comment by jaydave1988** [comment]
Not required to implement in library.

**Comment by krishnavelu** [comment]
What do you mean? 
If this is an issue, it needs to be fixed. in the library.
Please explain what was the issue & how did you fixed it?

**Comment by jaydave1988** [comment]
I had opened separate issue for Enhancement request #129 But you mentioned that it is not required to add in the library.
To solve this issue you need to implement exit_mis_position method.

**Comment by krishnavelu** [comment]
That issue is about exiting the mis position. This issue is about cancel_order() is not working as expected for mis positions.
Is this working now? or still cancel_order() is not working for mis position? Or what do you do for cancelling mis positions?

**Comment by jaydave1988** [comment]
If order is open and not executed then you can cancel the mis order. But order is executed then you cant cancel the order like how it behaves in case of BO order.
So, it is working as expected.

**Comment by krishnavelu** [comment]
Thank you for your explanation. I though cancel_order() is not working for mis at all.
