### ISSUE TITLE
Add method for exit mis positions.

### ISSUE THREAD

**Issue by jaydave1988** [krishnavelu/alice_blue#129]
Add method for exit mis positions like below:
def exit_mis_positions(symbol = None, instrument_token = None)

If symbol or instrument_token is given then it should square off mis position for that symbol, otherwise it should square off all mis positions.
It is useful, as alice blue is charging for mis square off.

**Comment by krishnavelu** [comment]
How is this different from getting the positions you have and calling cancel_order()/modify_order()?

**Comment by jaydave1988** [comment]
cancel_order() is cancelling orders which are open. Here we dont have any open orders when MIS orders are running. 
So you cant cancel running mis orders like BO/Co orders. where if you cancel child order will cancel the position..
This is mainly required because if you have any mis position, broker is doing square off @3.13 PM and charging for each order. 
So you have to iterate through positions book and if position is mis then you have to place reverse order. If you want then I can paste code here.

**Comment by krishnavelu** [comment]
My question was, this you can do it in your application. All necessary things to do this is already available in this library. Why do you need this function inside library? If we start including application stuffs inside library, it will go on. There is no end to it.

**Comment by bhvarshn** [comment]
krishna velu sometime i feel you ask too much questions and you show too much arrogance/unnecessary attitude.. Jayadev asked a simple question which api to use to exit all MIS orders, Instead of frustrating developers, you can politely answer his query. I am also looking for answer for this question . Which API to use for exiting all MIS orders for which trade is ongoing

**Comment by krishnavelu** [comment]
It's the same as you would exit in web interface.
