### ISSUE TITLE
Unable to Generate Access token

### ISSUE THREAD

**Issue by Parva14** [krishnavelu/alice_blue#13]
I received my API secret but I am not able to generate access token, here are some details:

resp = <Response [200]>
resp.url = https://ant.aliceblueonline.com/oauth/consent?consent_challenge=4bbd6ebdd0a4440aaf39798eb8072d51

I modified the next line to this:

try:
            code = resp.url[resp.url.index('=')+1:resp.url.index('&')]
        except:
            code = resp.url[resp.url.index('=')+1:]
as I didn't see any '&' symbol in the resp.url

without the modification, it was showing this error message:
code = resp.url[resp.url.index('=')+1:resp.url.index('&')]ValueError: substring not found

I am printing the url generated after setting the params and it looks like this:

https://ant.aliceblueonline.com/oauth2/token?client_id=********&client_secret=******************************************************************&grant_type=authorization_code&code=4bbd6ebdd0a4440aaf39798eb8072d51&redirect_uri=https://ant.aliceblueonline.com/plugin/callback&authorization_response=authorization_response

I still get access_token as 'None' only, is there any problem with my code or is it possible that they haven't activated my API yet?

Thanks,
Parva

**Comment by krishnavelu** [comment]
Try generating code manually during market time. If that works then try using this function.

**Comment by Parva14** [comment]
I am still not able to generate the access token, can you please tell me how can I generate the code manually?

**Comment by Parva14** [comment]
Hey,
I generated the code manually and in the process, I got an option to authorize the app and now it works just fine, I can generate the token using the SDK too! Thankyou for the help and quick response!
Also, do let me know if there are any example codes available for trading in live markets like ORB or SMA crossover.
Thanks,
Parva

**Comment by krishnavelu** [comment]
A simple moving average strategy.
https://gist.github.com/krishnavelu/e0df312ccf5f022edb1823461ff4230e

**Comment by Parva14** [comment]
Thankyou for sharing the amazing code, it was very helpful. To run an algo like this in multiple instruments at once, won't we need to define ltp as a dictionary?
Also, I think we should put a flag so there is alternate buying and selling or else this will just keep placing buy orders when sma(5) > sma(20) and vice-versa.

**Comment by krishnavelu** [comment]
This is just an example. You can develop your own as per your requirements.

**Comment by akashraut7** [comment]
i have same issue,  code = resp.url[resp.url.index('=')+1:resp.url.index('&')]
ValueError: substring not found, please help me, what is the problem. I don't know to generate manually. My friend code working fine not generating this problem, but why for my account this error coming

**Comment by PRAKSH24884** [comment]
Sir please help how to generate code manually

**Comment by krishnavelu** [comment]
Refer previous issue before you post something. This is not new and already answered.
