### ISSUE TITLE
Not receiving OI when subscribed to marketdata

### ISSUE THREAD

**Issue by AniketBhadane** [krishnavelu/alice_blue#131]
When I subscribe to an instrument's marketdata (such as nifty future), I get the feed of marketdata. But I do not get any message for OI. Mode in message is always 1 (marketdata).

How can we get OI for the subscriptions?
Rasind isn't replying over mail

**Comment by krishnavelu** [comment]
Open interest is not available.

**Comment by AniketBhadane** [comment]
Wished to know whether OI is now available in Sep 2021?

**Comment by krishnavelu** [comment]
No
