### ISSUE TITLE
Can't connect to HTTPS URL because the SSL module is not available

### ISSUE THREAD

**Issue by Vijendra3087** [krishnavelu/alice_blue#133]
After import of SSL module:
ImportError: DLL load failed: The specified module could not be found.

Can't connect to broker API.

**Comment by krishnavelu** [comment]
Post some sample code of what you are doing and some results. Without head & tail no body in this world can help you.

**Comment by Vijendra3087** [comment]
Codes followed as per your document. Below is input and output is already shared.
from alice_blue import *
import csv
import datetime
import ssl

username = open('username.txt','r')
password = open('password.txt','r')
api_secret = open('api_key.txt','r')

access_token = AliceBlue.login_and_get_access_token(username=username.read(),password=password.read(),twoFA='a',api_secret=api_secret.read())

f = open('access_token.txt','w')
f.write(access_token)
f.close()

acc_token = open('access_token.txt','r')
alice: AliceBlue = AliceBlue(username=username.read(),password=password.read(),access_token = acc_token.read(),master_contracts_to_download=['NSE','NFO','BSE'])

**Comment by krishnavelu** [comment]
This [code](https://gist.github.com/krishnavelu/e0df312ccf5f022edb1823461ff4230e#) works for everyone. Try using this. First make it work with simple code and then add your fancy stuffs. This library is no way related to any DLL to get this error.

`ImportError: DLL load failed: `

Why are you importing ssl module? In which example you saw this?

**Comment by krishnavelu** [comment]
Closing this as of now. Reopen if needed.
