### ISSUE TITLE
BNF futre data not came

### ISSUE THREAD

**Issue by sanjaygoyan** [krishnavelu/alice_blue#134]
Hi, 
Please find below code

bn_fut = alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=datetime.date(2020, 6, 25), is_fut=True, strike=None, is_CE = False)
print(bn_fut)
print (alice.get_instrument_by_symbol('NFO', 'BANKNIFTY JUN FUT'))
alice.subscribe(alice.get_instrument_by_symbol('NFO', 'BANKNIFTY JUN FUT'), LiveFeedType.MARKET_DATA)

#Instrument(exchange='NFO', token=95733, symbol='BANKNIFTY JUN FUT', name='', expiry=datetime.date(2020, 6, 25), lot_size='20')
#Instrument(exchange='NFO', token=95733, symbol='BANKNIFTY JUN FUT', name='', expiry=datetime.date(2020, 6, 25), lot_size='20')

event_handler_quote_update in this function data is not came.

**Comment by krishnavelu** [comment]
Do you get live data for normal equities? Try equities first.
Then get instrument of Future using get _instrument_for_fno.
See if you got the right instrument. And then pass that instrument to subscribe function.

**Comment by SanjuKumarGupta** [comment]
Sir,

Somtime i am getting wrong HIGH prices of stocks (different in Ant App & different in via API) is there is
any way to solve the problem, (yesterday i got wrong NFITY 50, today i got MFSL wrong value)

**Comment by sanjaygoyan** [comment]
Yes i getting equities data snapshots.
Now i am trying future BNF

bn_fut = alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=datetime.date(2020, 6, 25), is_fut=True, strike=None, is_CE = False)
print(bn_fut)   
alice.subscribe(bn_fut, LiveFeedType.MARKET_DATA)

Above code did not give any data in event_handler_quote_update

**Comment by krishnavelu** [comment]
```
socket_opened = False
def event_handler_quote_update(message):
    print(f"quote update {message}")

def open_callback():
    global socket_opened
    socket_opened = True

alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
while(socket_opened==False):
    pass
alice.subscribe(alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=datetime.date(2020, 6, 25), is_fut=True, strike=None, is_CE = False), LiveFeedType.MARKET_DATA)
sleep(10)
```
The above code gives me the following output.

```
quote update {'exchange': 'NFO', 'token': 95733, 'ltp': 21302.0, 'ltt': 1592646746, 'ltq': 20, 'volume': 40, 'best_bid_price': 21302.0, 'best_bid_quantity': 2020, 'best_ask_price': 0.0, 'best_ask_quantity': 0, 'total_buy_quantity': 2060, 'total_sell_quantity': 0, 'atp': 21302.0, 'exchange_time_stamp': 1592647085, 'open': 21302.0, 'high': 21302.0, 'low': 21302.0, 'close': 21308.85, 'yearly_high': 21302.0, 'yearly_low': 0.0, 'instrument': Instrument(exchange='NFO', token=95733, symbol='BANKNIFTY JUN FUT', name='', expiry=datetime.date(2020, 6, 25), lot_size='20')}
```

**Comment by krishnavelu** [comment]
Closing this as of now. Reopen if needed.

**Comment by Gautam99-ai** [comment]
Hi,

I am placing BO order from API and below if the status of the order : 

{'status': 'success', 'message': '', 'data': [{'validity': None, 'trigger_price': 2334.35, 'transaction_type': 'S', 'trading_symbol': 'RELIANCE-EQ', 'rejection_reason': '--', 'quantity': 1, 'product': 'BO', 'price_to_fill': 2334.25, 'order_status': 'complete', 'oms_order_id': '200914000077615', 'nest_request_id': None, 'filled_quantity': 1, 'exchange_time': '14-Sep-2020 10:42:20', 'exchange_order_id': '1300000004884914', 'exchange': 'NSE', 'disclosed_quantity': '0', 'client_id': 'AB080000', 'average_price': 2334.25}, {'validity': None, 'trigger_price': 2334.35, 'transaction_type': 'S', 'trading_symbol': 'RELIANCE-EQ', 'rejection_reason': '--', 'quantity': 1, 'product': 'BO', 'price_to_fill': 2334.25, 'order_status': 'open', 'oms_order_id': '200914000077615', 'nest_request_id': None, 'filled_quantity': 0, 'exchange_time': '14-Sep-2020 10:42:20', 'exchange_order_id': '1300000004884914', 'exchange': 'NSE', 'disclosed_quantity': '0', 'client_id': 'AB080000', 'average_price': 0.0}, {'validity': None, 'trigger_price': 2334.35, 'transaction_type': 'S', 'trading_symbol': 'RELIANCE-EQ', 'rejection_reason': '--', 'quantity': 1, 'product': 'BO', 'price_to_fill': 2334.25, 'order_status': 'trigger pending', 'oms_order_id': '200914000077615', 'nest_request_id': None, 'filled_quantity': 0, 'exchange_time': '14-Sep-2020 10:22:10', 'exchange_order_id': '1300000004884914', 'exchange': 'NSE', 'disclosed_quantity': '0', 'client_id': 'AB080000', 'average_price': 0.0}, {'validity': None, 'trigger_price': 2334.35, 'transaction_type': 'S', 'trading_symbol': 'RELIANCE-EQ', 'rejection_reason': '--', 'quantity': 1, 'product': 'BO', 'price_to_fill': 2334.25, 'order_status': 'open pending', 'oms_order_id': '200914000077615', 'nest_request_id': None, 'filled_quantity': 0, 'exchange_time': '--', 'exchange_order_id': None, 'exchange': 'NSE', 'disclosed_quantity': '0', 'client_id': 'AB080000', 'average_price': 0.0}, {'validity': None, 'trigger_price': 2334.35, 'transaction_type': 'S', 'trading_symbol': 'RELIANCE-EQ', 'rejection_reason': '--', 'quantity': 1, 'product': 'BO', 'price_to_fill': 2334.25, 'order_status': 'validation pending', 'oms_order_id': '200914000077615', 'nest_request_id': None, 'filled_quantity': 0, 'exchange_time': '--', 'exchange_order_id': None, 'exchange': 'NSE', 'disclosed_quantity': '0', 'client_id': 'AB080000', 'average_price': 0.0}, {'validity': None, 'trigger_price': 2334.35, 'transaction_type': 'S', 'trading_symbol': 'RELIANCE-EQ', 'rejection_reason': '--', 'quantity': 1, 'product': 'BO', 'price_to_fill': 2334.25, 'order_status': 'put order req received', 'oms_order_id': '200914000077615', 'nest_request_id': None, 'filled_quantity': 0, 'exchange_time': '--', 'exchange_order_id': None, 'exchange': 'NSE', 'disclosed_quantity': '0', 'client_id': 'AB080000', 'average_price': 0.0}]}

I see in the above JSON that the order_status is complete as this order got executed, and at the same time other 2 orders also got placed one is Stop loss order and other one is Square off price.

But there is no reference of parent order id in these 2 orders or either these 2 orders reference in the main order places, can you please let me know how these orders are referenced to the main order ?

**Comment by Naveenchandra07** [comment]
Hi Sir, I facing a problem while trying to subscribe for live feed of data for INFY stock from NSE. Because this issue was related to live feed I am posting here. I tried the sample code provided by you, but the socket is not opening. I am waited for more than 10 minutes before terminating the application. Below is the code and log

Code Snippet Starts
----------------------
ins_scrip = alice.get_instrument_by_symbol('NSE', 'INFY')
print(ins_scrip)
    
socket_opened = False
print('Before Socket Start')
alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
print('Before Socket Open')
while(socket_opened==False):    # wait till socket open & then subscribe
    pass
print('Socket Open Successful')
alice.subscribe(ins_scrip, LiveFeedType.COMPACT)
---------------------
Code Snippet ends

Logs Starts
------------
Instrument(exchange='NSE', token=1594, symbol='INFY', name='INFOSYS LIMITED', expiry=None, lot_size=None)
Before Socket Start
Before Socket Open
------------
Log Ends

**Comment by PRAKSH24884** [comment]
sir how to historical data of any stock please help

**Comment by krishnavelu** [comment]
There is no historical data available for Alice.

**Comment by dineshgurjar** [comment]
is there function available to get Open Interest? 
as per alice blue api documentation Open interest subscribed with Market data. but in response not getting open interest.

**Comment by krishnavelu** [comment]
Open interest is not available in Alice blue.

**Comment by dineshgurjar** [comment]
> Open interest is not available in Alice blue.
in API documentation it's available 
![image](https://user-images.githubusercontent.com/17480006/97910911-77e57080-1d70-11eb-87c6-d39367250467.png)

**Comment by krishnavelu** [comment]
Call and ask alice blue.

**Comment by rajukiranlr** [comment]
print(params["expirydate"])

    
  
it is able to read the params["expirydate"] from the text file. 
**datetime.date(2020, 11, 5)**

  ins_scrip = alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=**params["expirydate"]**, is_fut=False, strike=params["strike"], is_CE = params["isCE"])

but same if it is passed into above commend it is **not taking for params["expirydate"]**  but able to read other details in the same statement ( exampe params["strike"] it is able to read correctly,

**Comment by asifiqbal369r** [comment]
can you help me with code for squareoff all postion equity in aliceblue

**Comment by sekhartuku** [comment]
Hi sir i got the following errors::

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
Traceback (most recent call last):
  File "C:\Users\Himansu\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Himansu\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\Himansu\AppData\Local\Programs\Python\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Himansu\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Himansu\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Himansu\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\Himansu\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "C:\Users\Himansu\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002298FB85A30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:
