### ISSUE TITLE
Aliceblue Error

### ISSUE THREAD

**Issue by mahendran8888** [krishnavelu/alice_blue#135]
Following code
import csv
from login import *
from alice_blue import *
access_token=AliceBlue.login_and_get_access_token(username='Username',password='password',twoFA='0.25',api_secret='CY19I1U0FI5UPH9ENJGMZ52L5D3WA383OA15T8L69MAJTYAQ2QRN6LBEPQZWM')
print(access_token)

Getting following error:
Couldn't get access token {'error': 'invalid_grant', 'error_description': 'The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client', 'status_code': 400}
None

Please Help

**Comment by krishnavelu** [comment]
While using api don’t access through app.

**Comment by mahendran8888** [comment]
I resolved this by keeping same answer in 2FA. Thanks.
