### ISSUE TITLE
Error in SMA program in Aliceblue

### ISSUE THREAD

**Issue by mahendran8888** [krishnavelu/alice_blue#136]
Following program from you.
First thanks for this programs, giving lot ideas to the program in Alice Blue as a base program

import logging
import datetime
import statistics
from time import sleep
from alice_blue import *

# Config
#username = 'username'
#password = 'password'
#api_secret = 'api_secret'
#twoFA = 'a'
EMA_CROSS_SCRIP = 'TCS'
logging.basicConfig(level=logging.DEBUG)        # Optional for getting debug messages.
# Config

ltp = 0
socket_opened = False
alice = None
def event_handler_quote_update(message):
    global ltp
    ltp = message['ltp']

def open_callback():
    global socket_opened
    socket_opened = True

def buy_signal(ins_scrip):
    global alice
    alice.place_order(transaction_type = TransactionType.Buy,
                         instrument = ins_scrip,
                         quantity = 1,
                         order_type = OrderType.Market,
                         product_type = ProductType.Intraday,
                         price = 0.0,
                         trigger_price = None,
                         stop_loss = None,
                         square_off = None,
                         trailing_sl = None,
                         is_amo = False)

def sell_signal(ins_scrip):
    global alice
    alice.place_order(transaction_type = TransactionType.Sell,
                         instrument = ins_scrip,
                         quantity = 1,
                         order_type = OrderType.Market,
                         product_type = ProductType.Intraday,
                         price = 0.0,
                         trigger_price = None,
                         stop_loss = None,
                         square_off = None,
                         trailing_sl = None,
                         is_amo = False)
    
def main():
    global socket_opened
    global alice
    global username
    global password
    global twoFA
    global api_secret
    global EMA_CROSS_SCRIP
    minute_close = []
    access_token=open('access_token.txt','r').read().strip()
    alice=AliceBlue(username='',password='',access_token=access_token, master_contracts_to_download=['NSE', 'BSE'])
    
    ins_scrip = alice.get_instrument_by_symbol('NSE', EMA_CROSS_SCRIP)
    
    socket_opened = False
    alice.start_websocket(subscribe_callback=event_handler_quote_update,
                          socket_open_callback=open_callback,
                          run_in_background=True)
    while(socket_opened==False):    # wait till socket open & then subscribe
        pass
    alice.subscribe(ins_scrip, LiveFeedType.MARKET_DATA)
    
    while True:
        if(datetime.datetime.now().second == 0):
            minute_close.append(ltp)
            if(len(minute_close) > 20):
                sma_5 = statistics.mean(minute_close[-5:])
                sma_20 = statistics.mean(minute_close[-20:])
                if(sma_5 > sma_20):
                    buy_signal(ins_scrip)
                elif(sma_5 < sma_20):
                    sell_signal(ins_scrip)
            sleep(1)
        sleep(0.2)  # sleep for 200ms
    
if(__name__ == '__main__'):
    main()

ERROR as follows:

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/profile HTTP/1.1" 200 None
INFO:alice_blue.alice_blue:Downloading master contracts for exchange: NSE
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/contracts.json?exchanges=NSE HTTP/1.1" 200 None
INFO:alice_blue.alice_blue:Downloading master contracts for exchange: BSE
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/contracts.json?exchanges=BSE HTTP/1.1" 200 None

Could you please tell me how to resolve this?

And all your work is appreciated. You have done extraordinary work here. You are helping newbies in program. I am new to algo trading.

**Comment by mahendran8888** [comment]
Thanks for your wonderful job. I think i am missing in some understanding it seems

Thanks once again.

**Comment by mahendran8888** [comment]
This is one of your program. Thanks.

**Comment by krishnavelu** [comment]
What is the error here ? 

These are all debug info.

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/profile HTTP/1.1" 200 None
INFO:alice_blue.alice_blue:Downloading master contracts for exchange: NSE
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/contracts.json?exchanges=NSE HTTP/1.1" 200 None
INFO:alice_blue.alice_blue:Downloading master contracts for exchange: BSE
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/contracts.json?exchanges=BSE HTTP/1.1" 200 None
```

**Comment by krishnavelu** [comment]
Closing this as of now. Reopen if needed.
