### ISSUE TITLE
event_handler_quote_update(message)

### ISSUE THREAD

**Issue by dhayal123** [krishnavelu/alice_blue#140]
Hi Krishna,
below code prints the message for alice.subscribe(alice.get_instrument_by_symbol('NSE', 'ONGC'), LiveFeedType.FULL_SNAPQUOTE)

but when I try to access the symbol, its just printing nothing instead of "ONGC"

def event_handler_quote_update(message):
    #print(f"quote update {message}")    
    print(type(message))
    global symbol
    symbol = message['symbol']
    print("symbol is ", symbol)

**Comment by krishnavelu** [comment]
While creating an issue follow [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue)

**Comment by dhayal123** [comment]
I have gone through it and found the answer. But, I have a different problem now. i have subscribed for the below 2 scripts and the market_data list keeps appending the data of TATASTEEL not ONGC. can you tell me how to populate list with all subscribed scripts? Thanks in advance

def event_handler_quote_update(message):
    print(f"quote update {message}")        
    global ltp
    global token
    ltp = message['ltp']
    token = message['token']

    alice.subscribe(alice.get_instrument_by_symbol('NSE', 'ONGC'), LiveFeedType.MARKET_DATA)
    alice.subscribe(alice.get_instrument_by_symbol('NSE', 'TATASTEEL'), LiveFeedType.MARKET_DATA)

    while(True):
        sleep(2)
        market_data.append(token)
        market_data.append(ltp)
        print(market_data)

**Comment by krishnavelu** [comment]
The code is not clear, paste your full code using `insert code` feature of github.
or use ``` manually to insert code before & after

**Comment by dhayal123** [comment]
def event_handler_quote_update(message):
    print(f"quote update {message}")        
    global ltp
    global token
    ltp = message['ltp']
    token = message['token']
        

def open_callback():
    global socket_opened
    socket_opened = True

def connectAB():    
    global alice
    global socket_opened
    global username
    global password
    global api_secret    
    market_data = []
    
    access_token =  AliceBlue.login_and_get_access_token(username=username, password=password, twoFA=twoFA,  api_secret=api_secret)
    #print("Access token is", access_token)
    #access_token = 'hurXbLnuOrG7OaXg8RbEWcebWX7TQi-1suqNyzjIt30._bRPCU1kn0vWAjedaFkbFKOmJUP95T0-cNdppCg23hk'
    alice = AliceBlue(username='username', password='password', access_token=access_token, master_contracts_to_download=['NFO','NSE','MCX'])
        
    #print(alice.get_balance())

    socket_opened = False
    alice.start_websocket(subscribe_callback=event_handler_quote_update,
                        socket_open_callback=open_callback,
                        run_in_background=True)
    
    while(socket_opened==False):
        pass
    alice.subscribe(alice.get_instrument_by_symbol('NSE', 'ONGC'), LiveFeedType.MARKET_DATA)
    alice.subscribe(alice.get_instrument_by_symbol('NSE', 'TATASTEEL'), LiveFeedType.MARKET_DATA)
        
    while(True):
        sleep(2)
        market_data.append(token)
        market_data.append(ltp)
        print(market_data)``

**Comment by dhayal123** [comment]
posted the complete code. pls check

**Comment by dhayal123** [comment]
Hi Krishna, can you pls update on this?

**Comment by dhayal123** [comment]
found a solution for it. I have another question. Now, whatever instruments that we are subscribing, we need to mention as below 
alice.subscribe(alice.get_instrument_by_symbol('NSE', 'TATASTEEL'), LiveFeedType.MARKET_DATA)

Actually, I want to subscribe for all stocks trading in Future segment. is there a easy way to subscribe other than mentioning all 250 items one by one?

**Comment by krishnavelu** [comment]
You can give multiple instruments (as list) as argument to subscribe() function.

**Comment by krishnavelu** [comment]
Closing this, hope your problem is solved.
