### ISSUE TITLE
SMA program is placing the order every minute and not as per the indicator

### ISSUE THREAD

**Issue by mahendran8888** [krishnavelu/alice_blue#142]
Thank you for your program in Alice blue SMA strategy.

Observation as below:

I have added my credintial and run the program:

This program execute buy or sell order when SMA_Low and SMA_High meeting the condition.
Problem is that the condition is always true in each minute.  so it is executing sell buy order irrespective SMA concept.

Following program used:

import logging
import datetime
import statistics
from time import sleep
from alice_blue import *

# Config
#username = 'username'
#password = 'password'
#api_secret = 'api_secret'
#twoFA = 'a'
EMA_CROSS_SCRIP = 'INDUSINDBK'
logging.basicConfig(level=logging.DEBUG)        # Optional for getting debug messages.
# Config

ltp = 0
socket_opened = False
alice = None
def event_handler_quote_update(message):
    global ltp
    ltp = message['ltp']

def open_callback():
    global socket_opened
    socket_opened = True

def buy_signal(ins_scrip):
    global alice
    alice.place_order(transaction_type = TransactionType.Buy,
                         instrument = ins_scrip,
                         quantity = 1,
                         order_type = OrderType.Market,
                         product_type = ProductType.Intraday,
                         price = 0.0,
                         trigger_price = None,
                         stop_loss = None,
                         square_off = None,
                         trailing_sl = None,
                         is_amo = False)

def sell_signal(ins_scrip):
    global alice
    alice.place_order(transaction_type = TransactionType.Sell,
                         instrument = ins_scrip,
                         quantity = 1,
                         order_type = OrderType.Market,
                         product_type = ProductType.Intraday,
                         price = 0.0,
                         trigger_price = None,
                         stop_loss = None,
                         square_off = None,
                         trailing_sl = None,
                         is_amo = False)
    
def main():
    global socket_opened
    global alice
    global username
    global password
    global twoFA
    global api_secret
    global EMA_CROSS_SCRIP
    minute_close = []
    access_token=open('access_token.txt','r').read().strip()
    alice=AliceBlue(username='#######',password='#######',access_token=access_token, master_contracts_to_download=['NSE', 'BSE'])
    
    ins_scrip = alice.get_instrument_by_symbol('NSE', EMA_CROSS_SCRIP)
    
    socket_opened = False
    alice.start_websocket(subscribe_callback=event_handler_quote_update,
                          socket_open_callback=open_callback,
                          run_in_background=True)
    while(socket_opened==False):    # wait till socket open & then subscribe
        pass
    alice.subscribe(ins_scrip, LiveFeedType.MARKET_DATA)
    
    while True:
        if(datetime.datetime.now().second == 0):
            minute_close.append(ltp)
            if(len(minute_close) > 12):
                sma_7 = statistics.mean(minute_close[-7:])
                sma_12 = statistics.mean(minute_close[-12:])
                if(sma_7 > sma_12):
                    buy_signal(ins_scrip)
                    print("Bought",sma_7,sma_12,ltp)
                elif(sma_7 < sma_12):
                    sell_signal(ins_scrip)
                    print("Sold",sma_7,sma_12,ltp)
            sleep(1)
        sleep(0.2)  # sleep for 200ms
    
if(__name__ == '__main__'):
    main()

I think some modification required hence request you to help

**Comment by mahendran8888** [comment]
Condition is always true once required minutes rollovered, so program is executing the buy sell always in every minute

where as
This SMA crosses over below or above each other it should triggers
but this crossover is not taking but above below condition it is taking.

**Comment by mahendran8888** [comment]
Happiest thing is this program is exectuing if some condition applied.

**Comment by krishnavelu** [comment]
See [this](https://gist.github.com/krishnavelu/e0df312ccf5f022edb1823461ff4230e)

**Comment by mahendran8888** [comment]
Still Buy or Sell triggering every minute

**Comment by mahendran8888** [comment]
every minute buy or sell happening ji

**Comment by mahendran8888** [comment]
INFY-EQNSE | Buy | MKT | 1 | 0 | 10:20:56 | Rejected
-- | -- | -- | -- | -- | -- | --
INFY-EQNSE | Buy | MKT | 1 | 0 | 10:19:56 | Rejected
INFY-EQNSE | Buy | MKT | 1 | 0 | 10:18:56 | Rejected
INFY-EQNSE | Buy | MKT | 1 | 0 | 10:17:56 | Rejected
INFY-EQNSE | Buy | MKT | 1 | 0 | 10:16:56 | Rejected
INFY-EQNSE | Buy | MKT | 1 | 0 | 10:15:56 | Rejected
INFY-EQNSE | Buy | MKT | 1 | 0 | 10:14:56 | Rejected
INFY-EQNSE | Buy | MKT | 1 | 0 | 10:13:56 | Rejected
INFY-EQNSE | Buy | MKT | 1 | 0 | 10:12:57 | Rejected
INFY-EQNSE | Buy | MKT | 1 | 0 | 10:11:56 | Rejected
INFY-EQNSE | Sell | MKT | 1 | 0 | 10:10:56 | Rejected
INFY-EQNSE | Sell | MKT | 1 | 0 | 10:09:56 | Rejected
INFY-EQNSE | Sell | MKT | 1 | 0 | 10:08:56 | Rejected
INFY-EQNSE | Sell | MKT | 1 | 0 | 10:07:56 | Rejected
INFY-EQNSE | Sell | MKT | 1 | 0 | 10:06:56 | Rejected
INFY-EQNSE | Sell | MKT | 1 | 0 | 10:05:56 | Rejected
INFY-EQNSE | Sell | MKT | 1 | 0 | 10:04:56 | Rejected
INFY-EQNSE | Buy | MKT | 1 | 0 | 10:03:56 | Rejected
INFY-EQNSE | Sell | MKT | 1 | 0 | 10:02:56 | Rejected
INFY-EQNSE | Sell | MKT | 1 | 0 | 10:01:56 | Rejected
INFY-EQNSE | Sell | MKT | 1 | 0 | 10:00:56 | Rejected
INFY-EQNSE | Sell | MKT | 1 | 0 | 9:59:56 | Rejected
INFY-EQNSE | Sell | MKT | 1 | 0 | 9:58:56 | Rejected
INFY-EQNSE | Buy | MKT | 1 | 0 | 9:57:56 | Rejected
INFY-EQNSE | Buy | MKT | 1 | 0 | 9:56:56 | Rejected
INFY-EQNSE | Buy | MKT | 1 | 0 | 9:55:56 | Rejected

**Comment by jaydave1988** [comment]
can you post the code?

**Comment by mahendran8888** [comment]
If you dont i want to suggest one logic:

Logic Should be like below

(Prev_1min_SMA_5 <Prev_1min_SMA_20) & (SMA_5>SMA_20))
               Buy Signal
(Prev_1min_SMA_5 >Prev_1min_SMA_20) & (SMA_5<SMA_20))
               Sell Signal

**Comment by mahendran8888** [comment]
if dont mind*

**Comment by mahendran8888** [comment]
import logging
import datetime
import statistics
from time import sleep
from alice_blue import *

# Config
#username = 'username'
#password = 'password'
#api_secret = 'api_secret'
#twoFA = 'a'
EMA_CROSS_SCRIP = 'INFY'
logging.basicConfig(level=logging.DEBUG)        # Optional for getting debug messages.
# Config

ltp = 0
socket_opened = False
alice = None
def event_handler_quote_update(message):
    global ltp
    ltp = message['ltp']

def open_callback():
    global socket_opened
    socket_opened = True

def buy_signal(ins_scrip):
    global alice
    alice.place_order(transaction_type = TransactionType.Buy,
                         instrument = ins_scrip,
                         quantity = 1,
                         order_type = OrderType.Market,
                         product_type = ProductType.Intraday,
                         price = 0.0,
                         trigger_price = None,
                         stop_loss = None,
                         square_off = None,
                         trailing_sl = None,
                         is_amo = False)

def sell_signal(ins_scrip):
    global alice
    alice.place_order(transaction_type = TransactionType.Sell,
                         instrument = ins_scrip,
                         quantity = 1,
                         order_type = OrderType.Market,
                         product_type = ProductType.Intraday,
                         price = 0.0,
                         trigger_price = None,
                         stop_loss = None,
                         square_off = None,
                         trailing_sl = None,
                         is_amo = False)
    
def main():
    global socket_opened
    global alice
    global username
    global password
    global twoFA
    global api_secret
    global EMA_CROSS_SCRIP
    minute_close = []
    access_token=open('access_token.txt','r').read().strip()
    alice=AliceBlue(username='######',password='######',access_token=access_token, master_contracts_to_download=['NSE', 'BSE'])
     
    print(alice.get_balance()) # get balance / margin limits
    print(alice.get_profile()) # get profile
    print(alice.get_daywise_positions()) # get daywise positions
    print(alice.get_netwise_positions()) # get netwise positions
    print(alice.get_holding_positions()) # get holding positions
    
    ins_scrip = alice.get_instrument_by_symbol('NSE', EMA_CROSS_SCRIP)
    
    socket_opened = False
    alice.start_websocket(subscribe_callback=event_handler_quote_update,
                          socket_open_callback=open_callback,
                          run_in_background=True)
    while(socket_opened==False):    # wait till socket open & then subscribe
        pass
    alice.subscribe(ins_scrip, LiveFeedType.COMPACT)
    
    current_signal = ''
    while True:
        if(datetime.datetime.now().second == 0):
            minute_close.append(ltp)
            if(len(minute_close) > 20):
                sma_5 = statistics.mean(minute_close[-5:])
                sma_20 = statistics.mean(minute_close[-20:])
                if(current_signal != 'buy'):
                    if(sma_5 > sma_20):
                        buy_signal(ins_scrip)
                        current_signal == 'buy'
                if(current_signal != 'sell'):
                    if(sma_5 < sma_20):
                        sell_signal(ins_scrip)
                        current_signal == 'sell'
            sleep(1)
        sleep(0.2)  # sleep for 200ms
    
if(__name__ == '__main__'):
    main()

**Comment by mahendran8888** [comment]
> INFY-EQNSE	Buy	MKT	1	0	10:20:56	Rejected
> INFY-EQNSE	Buy	MKT	1	0	10:19:56	Rejected
> INFY-EQNSE	Buy	MKT	1	0	10:18:56	Rejected
> INFY-EQNSE	Buy	MKT	1	0	10:17:56	Rejected
> INFY-EQNSE	Buy	MKT	1	0	10:16:56	Rejected
> INFY-EQNSE	Buy	MKT	1	0	10:15:56	Rejected
> INFY-EQNSE	Buy	MKT	1	0	10:14:56	Rejected
> INFY-EQNSE	Buy	MKT	1	0	10:13:56	Rejected
> INFY-EQNSE	Buy	MKT	1	0	10:12:57	Rejected
> INFY-EQNSE	Buy	MKT	1	0	10:11:56	Rejected
> INFY-EQNSE	Sell	MKT	1	0	10:10:56	Rejected
> INFY-EQNSE	Sell	MKT	1	0	10:09:56	Rejected
> INFY-EQNSE	Sell	MKT	1	0	10:08:56	Rejected
> INFY-EQNSE	Sell	MKT	1	0	10:07:56	Rejected
> INFY-EQNSE	Sell	MKT	1	0	10:06:56	Rejected
> INFY-EQNSE	Sell	MKT	1	0	10:05:56	Rejected
> INFY-EQNSE	Sell	MKT	1	0	10:04:56	Rejected
> INFY-EQNSE	Buy	MKT	1	0	10:03:56	Rejected
> INFY-EQNSE	Sell	MKT	1	0	10:02:56	Rejected
> INFY-EQNSE	Sell	MKT	1	0	10:01:56	Rejected
> INFY-EQNSE	Sell	MKT	1	0	10:00:56	Rejected
> INFY-EQNSE	Sell	MKT	1	0	9:59:56	Rejected
> INFY-EQNSE	Sell	MKT	1	0	9:58:56	Rejected
> INFY-EQNSE	Buy	MKT	1	0	9:57:56	Rejected
> INFY-EQNSE	Buy	MKT	1	0	9:56:56	Rejected
> INFY-EQNSE	Buy	MKT	1	0	9:55:56	Rejected

Rejection is fine because Equity buy sell is  not activated in my account. That i discussed with Aliceblue.

**Comment by mahendran8888** [comment]
I dont know how to code below code in python. Help me please, I can understand few things

(Prev_1min_SMA_5 <Prev_1min_SMA_20) & (SMA_5>SMA_20))
Buy Signal
(Prev_1min_SMA_5 >Prev_1min_SMA_20) & (SMA_5<SMA_20))
Sell Signal

**Comment by mahendran8888** [comment]
You have done very good job Krishna vel sir. You are helping me.

**Comment by krishnavelu** [comment]
That example program is just for explanation, not for actual trading.

**Comment by Yugalkamesh** [comment]
print(alice.get_balance()) # get balance / margin limits
print(alice.get_profile()) # get profile
print(alice.get_daywise_positions()) # get daywise positions
print(alice.get_netwise_positions()) # get netwise positions
print(alice.get_holding_positions()) # get holding positions

ins_scrip = alice.get_instrument_by_symbol('NSE', EMA_CROSS_SCRIP)

socket_opened = False
alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
while(socket_opened==False):    # wait till socket open & then subscribe
    pass
alice.subscribe(ins_scrip, LiveFeedType.COMPACT)

current_signal = ''
while True:
    if(datetime.datetime.now().second == 0):
        minute_close.append(ltp)
        if(len(minute_close) > 20):
            sma_5 = statistics.mean(minute_close[-5:])
            sma_20 = statistics.mean(minute_close[-20:])
            **if(current_signal != 'buy'):**    # See this condition
                if(sma_5 > sma_20):
                    buy_signal(ins_scrip)
                    current_signal == 'buy'
            **if(current_signal != 'sell'):**  # and see also this condition
                if(sma_5 < sma_20):
                    sell_signal(ins_scrip)
                    current_signal == 'sell'
        sleep(1)
    sleep(0.2)  # sleep for 200ms

### it will  alwasys show everyminute as buy if sma showing buying condition if the above mentioned condition is not executed which says that **if(current_signal != 'buy'):**  show buy signal only if current postion is not buy.
