### ISSUE TITLE
return future data

### ISSUE THREAD

**Issue by dhayal123** [krishnavelu/alice_blue#143]
Hi,

I am retrieving the future data using the below code which is working fine, lets say this is Script1. every tick by tick data is captured by event_handler_quote_update(message) function. The output is future data which will have symbol, open, high, low, close. 

Now, I am returning this output to another script for further processing. This makes script1 to stop and gets called each time whenever it is called from script2. Is there a way to make script1 to continue to run and script2 pulls the output of script1 without returning from script1?

    socket_opened = False
    alice.start_websocket(subscribe_callback=event_handler_quote_update,
                        socket_open_callback=open_callback,
                        run_in_background=True)
    
    while(socket_opened==False):
        pass
    exec(open("Securitieslist.txt").read(), globals())

**Comment by krishnavelu** [comment]
Learn python.
