### ISSUE TITLE
NFO : BANKNIFTY data is coming in place of NFO : BANKNIFTY

### ISSUE THREAD

**Issue by prdatr** [krishnavelu/alice_blue#144]
Hi Krishna,
As discussed on the Unofficed forum, I'm raising this defect here which might potentially get fixed along with https://github.com/krishnavelu/alice_blue/commit/3b9f53fee333004c722c78e9be4400a710d6596c

Here is the summary of the same:

**Defect:**
`alice.get_instrument_for_fno` script is sending data for BANKNIFTY when trying to fetch data for NIFTY future for near expiry

**Steps to Reproduce:**
Do alice authentication, 
Create object named **alice** post authentication 
Then run this `print(alice.get_instrument_for_fno(symbol = 'NIFTY', expiry_date=currentExpiry, is_fut=True, strike=None, is_CE = False))`

_Outcome:_
`Instrument(exchange='NFO', token=95733, symbol='BANKNIFTY JUN FUT', name='', expiry=datetime.date(2020, 6, 25), lot_size='20')`

_Expected Outcome:_
data for symbol = 'NIFTY'

**Comment by krishnavelu** [comment]
@prdatr Fixed. Take the develop latest and see if you are getting `NIFTY` futures.
I'm able to get this.
`Instrument(exchange='NFO', token=45406, symbol='NIFTY JUL FUT', name='', expiry=datetime.date(2020, 7, 30), lot_size='75')`

**Comment by yogesh249** [comment]
How to take the develop latest?

pip install pya3?? Is that how it will download latest?

**Comment by krishnavelu** [comment]
you use pya3?
