### ISSUE TITLE
How to find last place order

### ISSUE THREAD

**Issue by karthickbala123** [krishnavelu/alice_blue#146]
Respected sir, when i placed order how to find last placed order id even if order pending or complete
Thank you

{'completed_orders': [{'average_price': 0.0,
                                'client_id': 'AB019868',
                                'disclosed_quantity': 0,
                                'exchange': 'NSE',
                                'exchange_order_id': 'NA',
                                'exchange_time': 0,
                                'filled_quantity': 0,
                                'instrument_token': '11184',
                                'leg_order_indicator': '',
                                'login_id': 'AB019868',
                                'lotsize': 1,
                                'nest_request_id': '1',
                                'oms_order_id': '200628000000723',
                                'order_entry_time': 1593340363,
                                'order_status': 'rejected',
                                'order_tag': '',
                                'order_type': 'LIMIT',
                                'price': 26.8,
                                'product': 'CNC',
                                'quantity': 1,
                                'rejection_reason': 'RMS:Margin '
                                                    'Exceeds,Required:26.80, '
                                                    'Available:0.00 for entity '
                                                    'account-AB019868 across '
                                                    'exchange across segment '
                                                    'across product ',
                                'remaining_quantity': 1,
                                'trading_symbol': 'IDFCFIRSTB-EQ',
                                'transaction_type': 'BUY',
                                'trigger_price': 0.0,
                                'user_order_id': '1',
                                'validity': 'DAY'}],
          'pending_orders': [{'average_price': 0.0,
                              'client_id': 'AB019868',
                              'disclosed_quantity': 0,
                              'exchange': 'NSE',
                              'exchange_order_id': 'NA',
                              'exchange_time': 0,
                              'filled_quantity': 0,
                              'instrument_token': '11184',
                              'leg_order_indicator': '',
                              'login_id': 'AB019868',
                              'lotsize': 1,
                              'nest_request_id': '1',
                              'oms_order_id': '200628000000720',
                              'order_entry_time': 0,
                              'order_status': 'after market order req received',
                              'order_tag': '',
                              'order_type': 'LIMIT',
                              'price': 26.8,
                              'product': 'CNC',
                              'quantity': 1,
                              'rejection_reason': '--',
                              'remaining_quantity': 1,
                              'trading_symbol': 'IDFCFIRSTB-EQ',
                              'transaction_type': 'BUY',
                              'trigger_price': 0.0,
                              'user_order_id': '1',
                              'validity': 'DAY'}]},
 'message': '',

**Comment by krishnavelu** [comment]
Next time follow [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) before creating an issue in this library.

![image](https://user-images.githubusercontent.com/38440742/85953352-b770fb80-b93d-11ea-884e-8d1c165d6bf0.png)
![image](https://user-images.githubusercontent.com/38440742/85953359-bb9d1900-b93d-11ea-8a56-78fd0c56f1a4.png)

These are order ids.
