### ISSUE TITLE
BO SL and Target Interpretation / Bug ?

### ISSUE THREAD

**Issue by bhushanjawle** [krishnavelu/alice_blue#148]
This may or may not be a bug. 
I placed BO yesterday for first time and noticed SL and target were incorrectly calculated. 
Ran same program today with print in order to make sure I am not passing wrong values but that is not the case.
Print statement showed ```at: 1400.9, **sl: 1442.9, target : 1316.8**```
Whereas actual sl was **15xx** instead of **1442.9** and target **12xx** instead of **1316.8**
Just wanted to confirm if I am misinterpreting the parameters OR if it is a bug. Found no such case reported earlier in issues.
Values output by print are actual values passed to respective parameters.
Can you please confirm ?

**Comment by jaydave1988** [comment]
I am using from quiet a long time. I have not faced this issue. I think you are passing wrong params.

**Comment by bhushanjawle** [comment]
Thank you @jaydave1988 , that is my guess as well. I have mentioned my parameters above for SL and target, is that correct interpretation of the function parameters ?

**Comment by jaydave1988** [comment]
As you mentioned Print statement showed at: 1400.9, **sl: 1442.9, target : 1316.8**. Then you must be passing these values to place order function.

**Comment by bhushanjawle** [comment]
@jaydave1988 , I **am** passing sl: 1442.9, target : 1316.8 and actual order in system is different. Hence I raised this

**Comment by jaydave1988** [comment]
Share your code.

**Comment by bhushanjawle** [comment]
Thank you for quick revert.
Here is the extract:

```
broker.place_order(transaction_type = TransactionType.Sell,
                 instrument = broker.get_instrument_by_symbol('NSE', symbol),
                quantity = quantity,
                order_type = OrderType.Limit,
                product_type = ProductType.BracketOrder,
                price = limit_px,
                trigger_price = None,
                stop_loss = stop_loss,
                square_off = target,
                trailing_sl = None,
                is_amo = False)
```
Values passed as per the print statement, just above place order were: limit_px = 1400.9, stop_loss= 1442.9, target = 1316.8.
Thank you.

**Comment by jaydave1988** [comment]
sl and target should be in points and not the actual value.
Means if sl = 1442.9 then sl = 42.9 in your case same for target = 84.1 points

**Comment by bhushanjawle** [comment]
Thank you @jaydave1988 . It was an interpretation issue. Will make the changes, execute again tomorrow and close. Thank you for your help.

**Comment by bhushanjawle** [comment]
Thank you @jaydave1988 . It worked, closing this issue.
