### ISSUE TITLE
Not able to place trigger price in Basket Order

### ISSUE THREAD

**Issue by sahildhingra221** [krishnavelu/alice_blue#149]
I am not able to place trigger price in basket order, in normal single order it is working fine, but in Basket order it raise: 16423 : Invalid Trigger price entered. I really need a solution upon this!!

**Comment by sahildhingra221** [comment]
**This is my code**

order1 = {  "instrument"        : alice.get_instrument_by_symbol('NSE', 'ZEEL'),
    "order_type"        : OrderType.StopLossMarket,
    "quantity"          : 1,
    "transaction_type"  : TransactionType.Buy,
    "trigger_price"     : 170,
    "product_type"      : ProductType.Intraday}
order2 = {  "instrument"        : alice.get_instrument_by_symbol('NSE', 'HINDPETRO'),
    "order_type"        : OrderType.StopLossMarket,
    "quantity"          : 1,
    "transaction_type"  : TransactionType.Buy,
    "trigger_price"     : 210
    "product_type"      : ProductType.Intraday}
orders = [order1, order2]
print(alice.place_basket_order(orders))

**Comment by sahildhingra221** [comment]
order1 = { "instrument" : alice.get_instrument_by_symbol('NSE', 'ZEEL'),
	"order_type" : OrderType.StopLossMarket,
	"quantity" : 1,
	"transaction_type" : TransactionType.Buy,
	"trigger_price" : 170,
	"product_type" : ProductType.Intraday}
order2 = { "instrument" : alice.get_instrument_by_symbol('NSE', 'HINDPETRO'),
	"order_type" : OrderType.StopLossMarket,
	"quantity" : 1,
	"transaction_type" : TransactionType.Buy,
	"trigger_price" : 210,
	"product_type" : ProductType.Intraday}
orders = [order1, order2]
print(alice.place_basket_order(orders))

The above code gives me the following output.

`{'status': 'success', 'message': 'Order placed successfully', 'data': {}}`

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) before you create an issue. As you've created now, modify the comments or add new comments as per the instruction.

**Comment by sahildhingra221** [comment]
![code](https://user-images.githubusercontent.com/20148469/86507713-0f08de80-bdf8-11ea-87aa-0dfd67e5c6b1.png)
![op](https://user-images.githubusercontent.com/20148469/86507740-51322000-bdf8-11ea-96de-bde1e2d56eb2.jpg)

**Comment by sahildhingra221** [comment]
![code](https://user-images.githubusercontent.com/20148469/86507766-80489180-bdf8-11ea-802d-8550b33e31a0.png)
![op](https://user-images.githubusercontent.com/20148469/86507769-850d4580-bdf8-11ea-93ed-9c578ff2a11d.jpg)

**Comment by sahildhingra221** [comment]
Please check now and let me know if I am missing something which you require!!

**Comment by sahildhingra221** [comment]
![code](https://user-images.githubusercontent.com/20148469/86507796-c69df080-bdf8-11ea-8c9b-53e50e2451da.png)
![op](https://user-images.githubusercontent.com/20148469/86507798-cd2c6800-bdf8-11ea-8918-8b6a288d5938.jpg)

**Comment by krishnavelu** [comment]
Which version of the library are you using?

**Comment by sahildhingra221** [comment]
Sorry, I am not very much aware of it. 
Can you please tell, How do I find that?

**Comment by krishnavelu** [comment]
`pip show alice-blue`

**Comment by sahildhingra221** [comment]
Version: 0.0.7

**Comment by krishnavelu** [comment]
Update the library and try.

**Comment by sahildhingra221** [comment]
Still same, SIr!!

**Comment by krishnavelu** [comment]
Now what is the version?

**Comment by supertrader123** [comment]
I am also getting error while place SLM with trigger price in basket order.

Error : 16408 : Trigger price entered has invalid characters

Version : 0.0.8

**Comment by sahildhingra221** [comment]
Version : 0.0.8

**Comment by krishnavelu** [comment]
@both give me a reproducible code. Otherwise I cannot help.

**Comment by sahildhingra221** [comment]
Sir, the code is same as mentioned in above message and screenshot!!

**Comment by krishnavelu** [comment]
Why there is a trigger_price in basket_order? Trigger price comes in BO & CO. Use limit orders in bracket order instead of using trigger price & SL-M

**Comment by sahildhingra221** [comment]
You mean your basket order doesn't support trigger price,right?

**Comment by supertrader123** [comment]
Thats strange. Why shouldnt Basket order have SLM?
I place my order as market order and place SL as basket orders with SLM

**Comment by krishnavelu** [comment]
I’ve not used SL-M in basket order. If you see the code basket’s trigger price goes as 0.
Basket order is just multiple orders placed at the same time. Please explain why would you need a basket order with SL-M?
Instead of trigger price, you can use that as limit price.

**Comment by jaydave1988** [comment]
@krishnavelu Why are you setting trigger_price as 0 in library? Fill this property from the input order.

trigger_price is required for order type = SL and SL-M. You did not consider these cases. You only considered M and Limit orders. For M and Limit order, we don't require trigger_price.

**Comment by krishnavelu** [comment]
This alice-blue's original [documentation](http://antplus.aliceblueonline.com/#place-basket-order)

`CO and BO orders are not supported in the basket order API.`

I also don't understand why trigger price is needed in basket order. Instead giving the order as SL-M why don't you give a limit order with limit price as trigger price? What difference it makes? 
Give me a valid use case.

![image](https://user-images.githubusercontent.com/38440742/89103924-8758c480-d3e3-11ea-8d5a-d085afd4a5c1.png)

**Comment by jaydave1988** [comment]
@krishnavelu I did not ask about BO and CO orders as I know they are not supported by aliceblue.

 SL and SL-M's functionality is different than Limit order.

Limit Order.
A limit order is an order to buy or sell a contract at a specified price. When you are buying, you instruct your broker not to go higher than the specified price. And when you are selling you instruct your broker not to sell below your specified price.
When placing Buy limit orders, the limit price entered must be below the current market price
When placing Sell limit orders, the limit price entered must be above the current market price

SL & SL-M Order.
A stop-loss order is a buy/sell order placed to limit the losses when you fear that the prices may move against your trade. 

There are 2 types of Stop-Loss orders:

1. SL order (Stop-Loss Limit) = Price + Trigger Price
2. SL-M order (Stop-Loss Market) = Only Trigger Price

a. SL-M order type - You will place a Sell SL-M order with trigger price = 95.
Here, when the price of 95 is triggered, a sell market order will be sent to the exchange and your position will be squared off at market price.

b. SL order type - You will place a Sell SL order with price and trigger price. Since your order needs to be triggered first, the (trigger price ≥ price.) Here, this order type gives you a range of the Stop-Loss.


Use Case:
SBIN is running @190. I want to Place Buy order @195 and sell order @185. Then you can't place Limit order as Buy Limit price should be less than the CMP and Sell Limit price should be Greater than the CMP. Otherwise it will execute @CMP.

In this scenario, we have to place SL ot SL-M order.

Hope this clarifies your question.....


Again from your screenshot, you can see alice blue is providing trigger_price for basket order, then why did you hardcoded to 0?

**Comment by krishnavelu** [comment]
I know what limit order, SL-M SL-L order is. I was asking how its use full in basket order. If you feel basket order is suppressed in library I've removed it. `place_basket_order` was created in a hurry, so I don't want to keep all options open. 

@jaydave1988 I've fixed the code and pushed in develop. Please test is during market time.

Here is the test code:

```
order1 = {"instrument" : alice.get_instrument_by_symbol('NSE', 'ZEEL'),
          "order_type" : OrderType.StopLossMarket,
          "quantity" : 1,
          "trigger_price" : 170.0,
          "transaction_type" : TransactionType.Buy,
          "product_type" : ProductType.Intraday}

order2 = {"instrument" : alice.get_instrument_by_symbol('NSE', 'HINDPETRO'),
          "order_type" : OrderType.StopLossMarket,
          "quantity" : 1,
          "trigger_price" : 210.0,
          "transaction_type" : TransactionType.Buy,
          "product_type" : ProductType.Intraday}

print(alice.place_basket_order([order1, order2]))
```

And here is the output I got.
`{'status': 'success', 'message': 'Order placed successfully', 'data': {}}`

![image](https://user-images.githubusercontent.com/38440742/89105842-ccd0be00-d3f2-11ea-8c33-47ae9b14be74.png)

![image](https://user-images.githubusercontent.com/38440742/89105863-f25dc780-d3f2-11ea-971f-1b7638c2eb2d.png)

**Comment by krishnavelu** [comment]
@Everyone Hope the issue is resolved. Reopen if needed.

**Comment by saimohan35** [comment]
i installed alice_blue via pip from instructions given. I got V1.0.0. How to get V1.0.1 using pip? becasue I need SL-M orders for basket orders which is not working in the current version I have.

**Comment by krishnavelu** [comment]
V1.0.1 is not yet released to PyPi yet.
So download the code from [develop](https://github.com/krishnavelu/alice_blue/tree/develop) branch.
and do `python setup.py install` from the directory where `setup.py` is present.

**Comment by thecodersing** [comment]
Hello,
I want use basket order for option stratagies.
Basket order are just multiple order placed at same time or we get margin benefits like Zerodha?

**Comment by krishnavelu** [comment]
Try basket order through web UI. API’s behavior will be same as web UI.
