### ISSUE TITLE
Couldn't get access token {'error': 'invalid_client' , 'error_description': 'Client authentication failed 

### ISSUE THREAD

**Issue by itrade4profit1** [krishnavelu/alice_blue#150]
Hello Sir,

Beginner query/concern:

i have got api and secret key from https://developers.zerobrokerageonline.com/main.html#/myapps and using the same key to get the access token as list on page https://pypi.org/project/alice-blue/

step#1 ....Import alice_blue and Create access_token using login_and_get_access_token() function with your username, password, 2FA and api_secret

access_token = AliceBlue.login_and_get_access_token(username='AB0xxxx', password='xxxxxx', twoFA='xxxx',  api_secret='xxxxx')

PS. i have set common passwords for all twoFA question and using api_secret which i have got from https://developers.zerobrokerageonline.com/main.html#/myapps

when i run the py file, i get below error:
Couldn't get access token {'error': 'invalid_client', 'error_description': 'Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)', 'status_code': 401}

I am sure i am either doing something incorrect or missing some details here

Thanks !

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating a new issue.

**Comment by itrade4profit1** [comment]
Thanks Sir, i went through similar issues of access token and i think i am missing this 2 things. It will be helpful, if you can please confirm it.

1. i need to use the develop branch as per issue # https://github.com/krishnavelu/alice_blue/issues/79
![image](https://user-images.githubusercontent.com/67868031/86557703-9a0ee380-bf74-11ea-8f26-09a9b17b8c09.png)

2. I am missing this resp.url but i don't see resp.url details in https://pypi.org/project/alice-blue/. It only uses AliceBlue.login_and_get_access_token ().
resp = <Response [200]>
resp.url = https://ant.aliceblueonline.com/oauth/consent?consent_challenge=4bbd6ebdd0a4440aaf39798eb8072d51

As a beginner, I will try to explore more and be more precise on issue.
Thanks Sir, Have a good Day !

**Comment by itrade4profit1** [comment]
@krishnavelu Sir, should i use the develop branch ? and do i need to use the resp.url ?

**Comment by krishnavelu** [comment]
use the resp.url output, copy and paste it in a browser. Authorize manually. You need to authorize the app the first time you use. No need after that.

**Comment by itrade4profit1** [comment]
Refer the following comment for the response url
https://github.com/krishnavelu/alice_blue/issues/22#issuecomment-554904854

as in this above comment, i manually authenticated....with my client id
https://ant.aliceblueonline.com/oauth2/auth?response_type=code&state=test_state&client_id=<'YOUR CLIENT ID'>&redirect_uri=https://ant.aliceblueonline.com/plugin/callback 

response i got is
https://ant.aliceblueonline.com/plugin/callback/?code=**t4JG9TM6AoVQI4WrBuBwcfHuBxxxxxxxxxxxxxx.66niQNrBJSB0QmvVKZUAs1Axxxxxxxxxx**&scope=&state=test_state

i used the token (i assume this is the access token)from "=" till the first "&" (those made bold) as access token in the code and run the program.

username = 'ABxxxxxx'
password = 'xxxxxxxxx'
access_token = "t4JG9TM6AoVQI4WrBuBwcfHuxxxxxxxxxxxxxxxxx.66niQNrBJSB0QmvVKZUAsxxxxxxxxxxxxxxxxxxxx"
alice = AliceBlue(username=username, password=password, access_token=access_token)

when i run this i get below exception:
`Traceback (most recent call last):
  File "C:\Anaconda3\envs\abalgo2\lib\site-packages\alice_blue\alice_blue.py", line 208, in __init__
    profile = self.get_profile()
  File "C:\Anaconda3\envs\abalgo2\lib\site-packages\alice_blue\alice_blue.py", line 445, in get_profile
    profile = self.__api_call_helper('profile', Requests.GET, None, None)
  File "C:\Anaconda3\envs\abalgo2\lib\site-packages\alice_blue\alice_blue.py", line 946, in __api_call_helper
    raise requests.HTTPError(response.text)
HTTPError: {"status":"error","message":"Request Unauthorised","data":{}}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\xxxxx\.spyder-py3\abalgo3.py", line 47, in <module>
    alice = AliceBlue(username=username, password=password, access_token=access_token)
  File "C:\Anaconda3\envs\abalgo2\lib\site-packages\alice_blue\alice_blue.py", line 210, in __init__
    raise Exception(f"Couldn't get profile info with credentials provided '{e}'")
Exception: Couldn't get profile info with credentials provided '{"status":"error","message":"Request Unauthorised","data":{}}'`

@krishnavelu Sir, not sure if this is the correct way of doing, i am not at all using my api key and api secret here and using only my client id and password.

**Comment by itrade4profit1** [comment]
Also, when i asked for API key and secret, i got this, here the app is disabled. do it related to the one above access token issue ?

name it shows as Antbridge. 
![image](https://user-images.githubusercontent.com/67868031/87171403-4132a880-c2f0-11ea-867f-3fc30a5ed7e3.png)

@krishnavelu Sir, please let me know on above 2 queries if i am missing something or i need more details from Aliceblue team.

**Comment by krishnavelu** [comment]
Once you authorized the app manually. You can use the library’s function to use access token

**Comment by itrade4profit1** [comment]
Thanks @krishnavelu Sir for the response, 
Yes, I tried to authorize using https://ant.aliceblueonline.com/oauth2/auth?response_type=code&state=test_state&client_id=<'YOUR CLIENT ID'>&redirect_uri=https://ant.aliceblueonline.com/plugin/callback 
and i got the response too
https://ant.aliceblueonline.com/plugin/callback/?code=t4JG9TM6AoVQI4WrBuBwcfHuBxxxxxxxxxxxxxx.66niQNrBJSB0QmvVKZUAs1Axxxxxxxxxx&scope=&state=test_state

so this is my access token from the response ? t4JG9TM6AoVQI4WrBuBwcfHuBxxxxxxxxxxxxxx.66niQNrBJSB0QmvVKZUAs1Axxxxxxxxxx. should i use it ?

Am i doing correct ? Also i am not sure about the redirect url. can we use redirect url something like https://localhost:5000 ?

**Comment by amitchouhan3107** [comment]
@krishnavelu hi sir ,when i had tried to get access token from https://ant.aliceblueonline.com/oauth2/auth?response_type=code&state=test_state&client_id=<'client id'>&redirect_uri=<'my custom url'>, it returns error "The "redirect_uri" parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls" , so how can i get  access token on my custom url ?

**Comment by krishnavelu** [comment]
@itrade4profit1 you don’t need to extract those from url. That function will do the job for you. It will return access_code directly.
@amitchouhan3107 you have to give the correct redirect url. Otherwise you’ll get error.

**Comment by krishnavelu** [comment]
Closing this. Hope your problem is solved

**Comment by rajanat** [comment]
> Once you authorized the app manually. You can use the library’s function to use access token

Hi 

 I tried to create the Authorisation URL :

https://ant.aliceblueonline.com/oauth2/auth?response_type=code&client_id=HVbaiSbkXl87xSu&redirect_uri=https://ant.aliceblueonline.com/plugin/callback&scope=orders&state=state_test&access_type=authorization_code


The OAuth2 request resulted in an error.
Error: invalid_client
Description: Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)
Hint: The requested OAuth 2.0 Client does not exist.
Debug:
You are seeing this default error page because the administrator has not set a dedicated error URL (environment variable OAUTH2_ERROR_URL is not set). If you are an administrator, please read [the guide](https://www.ory.sh/docs) to understand what you need to do. If you are a user, please contact the administrator.

Can you look into this asap, and give a solution to this problem
