### ISSUE TITLE
Provide option to not download master contract.

### ISSUE THREAD

**Issue by jaydave1988** [krishnavelu/alice_blue#152]
Requirement: I have multiple clients. Master contracts download is not required for all clients as it is time taking process.
Right now there is not provision to skip this. If we will pass as None then it will download all enabled contracts.

` if(master_contracts_to_download == None):
            for e in self.__enabled_exchanges:
                self.__get_master_contract(e)
        else:
            for e in master_contracts_to_download:
                self.__get_master_contract(e)`

So, please provided one function param, where we can skip this.

**Comment by krishnavelu** [comment]
Pass an empty list instead of None

**Comment by jaydave1988** [comment]
My bad. I have not noticed that.
