### ISSUE TITLE
In /oauth2/token url, we need to pass app_id instead of username

### ISSUE THREAD

**Issue by jaydave1988** [krishnavelu/alice_blue#153]
I communicated with aliceblue developer, he gave below code for generating access token using master api key and app id.

import http.client
import mimetypes
conn = http.client.HTTPSConnection("ant.aliceblueonline.com")
payload = 'grant_type=authorization_code&**client_id=<app_id**>&client_secret_post=<master_api_key>&redirect_uri=https%3A//ant.aliceblueonline.com/plugin/callback&authorization_response=authorization_response&code=@code'
headers = {
  'Authorization': 'Basic xxxx',
  'Content-Type': 'application/x-www-form-urlencoded',
  'Cookie': '__cfduid=xxx; __cfruid=xxxx'
}
conn.request("POST", "/oauth2/token", payload, headers)
res = conn.getresponse()
data = res.read()
print(data.decode("utf-8"))

I found that in code, you are using, 

#Get Access Token
        params = {'code': code, 'redirect_uri': redirect_url, 'grant_type': 'authorization_code', 'client_secret' : api_secret, **"cliend_id": username**}

so change client_id as username to app_id.

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating an issue. I cannot understand your code snippet.

**Comment by jaydave1988** [comment]
Received code from aliceblue developer to use master api key is as follow
`import http.client
import mimetypes
conn = http.client.HTTPSConnection("ant.aliceblueonline.com")
payload = 'grant_type=authorization_code&**client_id=<app_id>**&client_secret_post=<master_api_key>&redirect_uri=https%3A//ant.aliceblueonline.com/plugin/callback&authorization_response=authorization_response&code=@code'
headers = {
'Authorization': 'Basic xxxx',
'Content-Type': 'application/x-www-form-urlencoded',
'Cookie': '__cfduid=xxx; __cfruid=xxxx'
}
conn.request("POST", "/oauth2/token", payload, headers)
res = conn.getresponse()
data = res.read()
print(data.decode("utf-8"))`

And in your code:

`#Get Access Token
params = {'code': code, 'redirect_uri': redirect_url, 'grant_type': 'authorization_code', 'client_secret' : api_secret, **"cliend_id": username**}`

so change client_id as username to app_id.

**Comment by krishnavelu** [comment]
This was fixed in issue #85 .
Now you can pass app_id to login_and_get_access_token() function.
We tested this app_id too, it worked.

**Comment by jaydave1988** [comment]
Thanks for the information. It was not working in my case. But some issue was there in api key. Now it is working. Closing this issue.
