### ISSUE TITLE
about insert dataframe column data into mysql db

### ISSUE THREAD

**Issue by gaju432** [krishnavelu/alice_blue#154]
Respected Sir,
please resolve this error 
# this function is for insert data into mysql
def insert_ticks(data):
    c=db.cursor()
    for tick in data:
        c.execute(insert_into_table,{'last_price':(tick['last_price']),
                                    'date':tick['TimeStamp']})
        
    try:
        db.commit()
    except Exception:
        db.rollback()

then i insert a dataframe column name last_price and timestamp
insert_tick=insert_ticks(data)

then error is

ERROR:websocket:error from callback <bound method AliceBlue.__on_data_callback of <alice_blue.alice_blue.AliceBlue object at 0x000000F2353C6E08>>: string indices must be integers 

(I think this is problem but how can i solve this i try .value and float and int but all void)
  File "C:\ProgramData\Anaconda3\lib\site-packages\websocket\_app.py", line 343, in _callback
    callback(*args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\alice_blue\alice_blue.py", line 307, in __on_data_callback
    self.__subscribe_callback(res)
  File "C:\Users\sc-pc\Documents\abtry\multi\1\kiteticker.py", line 118, in event_handler_quote_update
    insert_tick=insert_ticks(data)
  File "C:\Users\sc-pc\Documents\abtry\multi\1\py_mysql.py", line 8, in insert_ticks
    c.execute(insert_into_table,{'last_price':(tick['last_price'].values.astype('float64')),

where is the problem ....
solanki 8104093607

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) before creating a new issue.
Your problem is not related to this library.
I can only give a generalized answer to your problem, Learn python

**Comment by Mclovin-code** [comment]
> Respected Sir,
> please resolve this error
> 
> # this function is for insert data into mysql
> def insert_ticks(data):
> c=db.cursor()
> for tick in data:
> c.execute(insert_into_table,{'last_price':(tick['last_price']),
> 'date':tick['TimeStamp']})
> 
> ```
> try:
>     db.commit()
> except Exception:
>     db.rollback()
> ```
> 
> then i insert a dataframe column name last_price and timestamp
> insert_tick=insert_ticks(data)
> 
> then error is
> 
> ERROR:websocket:error from callback <bound method AliceBlue.__on_data_callback of <alice_blue.alice_blue.AliceBlue object at 0x000000F2353C6E08>>: string indices must be integers
> 
> (I think this is problem but how can i solve this i try .value and float and int but all void)
> File "C:\ProgramData\Anaconda3\lib\site-packages\websocket_app.py", line 343, in _callback
> callback(*args)
> File "C:\ProgramData\Anaconda3\lib\site-packages\alice_blue\alice_blue.py", line 307, in __on_data_callback
> self.__subscribe_callback(res)
> File "C:\Users\sc-pc\Documents\abtry\multi\1\kiteticker.py", line 118, in event_handler_quote_update
> insert_tick=insert_ticks(data)
> File "C:\Users\sc-pc\Documents\abtry\multi\1\py_mysql.py", line 8, in insert_ticks
> c.execute(insert_into_table,{'last_price':(tick['last_price'].values.astype('float64')),
> 
> where is the problem ....
> solanki 8104093607

Did you solve this, im stuck on this too
