### ISSUE TITLE
Multiple subscribe not sending LTP for both entities

### ISSUE THREAD

**Issue by mukhi199** [krishnavelu/alice_blue#155]
Hi,

My code is as below:
alice.subscribe(alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=datetime.date(2020, 7, 23), is_fut=False, strike=23500, is_CE = True), LiveFeedType.COMPACT)
        print(ltp)
        alice.subscribe(alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=datetime.date(2020, 7, 23), is_fut=False, strike=22500, is_CE = False), LiveFeedType.COMPACT)
        print(ltp)

I am getting this o/p, code is in loop:

quote update {'exchange': 'NFO', 'token': 42330, 'ltp': 62.2, 'change': 0, 'exchange_time_stamp': 0, 'volume': 10693100, 'instrument': Instrument(exchange='NFO', token=42330, symbol='BANKNIFTY 23 JUL20 23500 CE', name='', expiry=datetime.date(2020, 7, 23), lot_size='20')}
62.2
quote update {'exchange': 'NFO', 'token': 38875, 'ltp': 151.8, 'change': 0, 'exchange_time_stamp': 0, 'volume': 12016120, 'instrument': Instrument(exchange='NFO', token=38875, symbol='BANKNIFTY 23 JUL20 22500 PE', name='', expiry=datetime.date(2020, 7, 23), lot_size='20')}
151.8
151.8
151.8
151.8
151.8
151.8

I also tried using function subscribe all, but still getting the value for last subscribed entity. Any help is appreciated.

**Comment by krishnavelu** [comment]
Read and follow [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) before creating a new issue.

**Comment by mukhi199** [comment]
I read what you have mentioned in the link. Link is talking about bank nifty future data. I am getting it, that's not my issue. My issue is when I am trying to get live feed for two entities then first time it shows the right value, but next time it always shows the LTP of entity subscribed last. As shown above in my code, I subscribed for 23500 CE first and got the value 62.2, there after I subscribed 22500 PE and got the value 151.8(ltp), but there after I am not getting the value for 23500 Ce, which was subscribed first. Thanks for your Time Krishna!!

**Comment by krishnavelu** [comment]
Read this & follow before creating a new issue.

![image](https://user-images.githubusercontent.com/38440742/88179798-6aa9d900-cbfa-11ea-95d1-7f54624cefb5.png)

I cannot read code which is not in code tab.

**Comment by mukhi199** [comment]
` socket_opened = False
    alice.start_websocket(subscribe_callback=event_handler_quote_update,
                          socket_open_callback=open_callback,
                          run_in_background=True)
    while(socket_opened==False):    # wait till socket open & then subscribe
        pass
    alice.subscribe(alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=datetime.date(2020, 7, 23), is_fut=False, strike=23500, is_CE = True), LiveFeedType.COMPACT)
    alice.subscribe(alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=datetime.date(2020, 7, 23), is_fut=False, strike=22500, is_CE = False), LiveFeedType.COMPACT)
    print(ltp)
    print(socket_opened)
    current_signal = ''
    while True:
        print(ltp)
        if(datetime.datetime.now().second == 0):
            alice.unsubscribe(alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=datetime.date(2020, 7, 23), is_fut=False, strike=22500, is_CE = False), LiveFeedType.COMPACT)
            alice.subscribe(alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=datetime.date(2020, 7, 23), is_fut=False, strike=23500, is_CE = True), LiveFeedType.COMPACT)
            print(ltp)
            minute_close.append(ltp)
            if(len(minute_close) > 20):
                sma_5 = statistics.mean(minute_close[-5:])
                sma_20 = statistics.mean(minute_close[-20:])
                if(current_signal != 'buy'):
                    if(sma_5 > sma_20):
                        buy_signal(ins_scrip)
                        current_signal = 'buy'
                if(current_signal != 'sell'):
                    if(sma_5 < sma_20):
                        sell_signal(ins_scrip)
                        current_signal = 'sell'
            alice.unsubscribe(alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=datetime.date(2020, 7, 23), is_fut=False, strike=23500, is_CE = True), LiveFeedType.COMPACT)
            alice.subscribe(alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=datetime.date(2020, 7, 23), is_fut=False, strike=22500, is_CE = False), LiveFeedType.COMPACT)
            print(ltp)
            minute_close2.append(ltp1)
            if(len(minute_close2) > 20):
                sma_5 = statistics.mean(minute_close2[-5:])
                sma_20 = statistics.mean(minute_close2[-20:])
                if(current_signal != 'buy'):
                    if(sma_5 > sma_20):
                        buy_signal(ins_scrip)
                        current_signal = 'buy'
                if(current_signal != 'sell'):
                    if(sma_5 < sma_20):
                        sell_signal(ins_scrip)
                        current_signal = 'sell'

            sleep(1)
        sleep(0.2)  # sleep for 200ms

if(__name__ == '__main__'):
    main()
`

Here is the o/p :

> 

> 0

True
0
0
quote update {'exchange': 'NFO', 'token': 42330, 'ltp': 15.1, 'change': 4294962586, 'exchange_time_stamp': 1595412000, 'volume': 22584060, 'instrument': Instrument(exchange='NFO', token=42330, symbol='BANKNIFTY 23 JUL20 23500 CE', name='', expiry=datetime.date(2020, 7, 23), lot_size='20')}
quote update {'exchange': 'NFO', 'token': 38875, 'ltp': 60.0, 'change': 4294958116, 'exchange_time_stamp': 1595412000, 'volume': 28271880, 'instrument': Instrument(exchange='NFO', token=38875, symbol='BANKNIFTY 23 JUL20 22500 PE', name='', expiry=datetime.date(2020, 7, 23), lot_size='20')}
15.1
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0
60.0

Process finished with exit code -1

I hope the code is clear now. Thanks for your time!!

**Comment by krishnavelu** [comment]
Still the code is not proper.

**Comment by mukhi199** [comment]
`
[main2.txt](https://github.com/krishnavelu/alice_blue/files/4977625/main2.txt)

`

I have attached the complete code as text file. Below is the o/p as of 07/26/2020 6:25 PM: MY question is, If OI have subscribed to two contracts 23 K CE and 22 K Pe, why I am getting feed only for last subscribed contract. Thank You!!

0
True
0
0
0
0
quote update {'exchange': 'NFO', 'token': 46054, 'ltp': 229.05, 'change': 0, 'exchange_time_stamp': 0, 'volume': 13803400, 'instrument': Instrument(exchange='NFO', token=46054, symbol='BANKNIFTY JUL 23000 CE', name='', expiry=datetime.date(2020, 7, 30), lot_size='25')}
quote update {'exchange': 'NFO', 'token': 46027, 'ltp': 165.55, 'change': 0, 'exchange_time_stamp': 0, 'volume': 11963125, 'instrument': Instrument(exchange='NFO', token=46027, symbol='BANKNIFTY JUL 22000 PE', name='', expiry=datetime.date(2020, 7, 30), lot_size='25')}
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55
165.55

**Comment by krishnavelu** [comment]
```
quote update {'exchange': 'NFO', 'token': 46054, 'ltp': 229.05, 'change': 0, 'exchange_time_stamp': 0, 'volume': 13803400, 'instrument': Instrument(exchange='NFO', token=46054, symbol='BANKNIFTY JUL 23000 CE', name='', expiry=datetime.date(2020, 7, 30), lot_size='25')}
quote update {'exchange': 'NFO', 'token': 46027, 'ltp': 165.55, 'change': 0, 'exchange_time_stamp': 0, 'volume': 11963125, 'instrument': Instrument(exchange='NFO', token=46027, symbol='BANKNIFTY JUL 22000 PE', name='', expiry=datetime.date(2020, 7, 30), lot_size='25')}
```
You are getting feed for both the scrips.

**Comment by mukhi199** [comment]
Yes first time it is showing both the entities message from event handler, but ltp is showing only last entity message. DO I have to loop in event handler, I did not see any way to handle multiple entities. Could you please guide me to any documentation.

**Comment by krishnavelu** [comment]
The output you got is what you've coded. If you don't know how to get quote updates from `event_handler_quote_update`, you need to learn python before jumping in to API trading. Try this in market time, you'll get repeated quotes of both scrips. This is off-market results.
Closing this.
