### ISSUE TITLE
Unable to invoke login_and_get_access_token twice

### ISSUE THREAD

**Issue by cdjindia** [krishnavelu/alice_blue#158]
When I made first attempt, I had mistyped the password so it failed. but all further attempts to login fail even with correct password becsuse the function seems to still attached to session that should jave expired.

Also, a very minor typo but significant from error message reporting. POV...

Line 237 of alice_blue.py reads 
logger.error("OAuth 2.0 Error occurred. Please verify your api_secret")
but all that has been verified upto that point is app_id and/or username (if app_id not provided)
Therefore the message should read
logger.error("OAuth 2.0 Error occurred. Please ensure that username and app_id are correct")

**Comment by krishnavelu** [comment]
I didn’t understand what you are saying.

Read and Follow [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue ) before creating a new issue.
