### ISSUE TITLE
unable to access the access token

### ISSUE THREAD

**Issue by dharmaraj81** [krishnavelu/alice_blue#159]
hi,

i have tried with jupyter notebook with python latest version( conda )

import logging
logging.basicConfig(level=logging.DEBUG)

from alice_blue import *

access_token = AliceBlue.login_and_get_access_token(username='AB054905', password='correct password', twoFA='a',  api_secret='correct secret')

print(access_token)

#alice = AliceBlue(username='AB054905', password='correct password', access_token=access_token)

but i got the error like follows

ERROR:alice_blue.alice_blue:Couldn't get access token {'error': 'invalid_grant', 'error_description': 'The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client', 'status_code': 400}

what is wrong which i have done in the code part??
Thanks

**Comment by krishnavelu** [comment]
Read and Follow [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue ) before creating a new issue.

**Comment by krishnavelu** [comment]
Verify your api secret, api id, redirect url

**Comment by dharmaraj81** [comment]
Hi @krishnavelu 

Anyway the problem was resolved.. thanks lot

my next question is, can i get historical data OHLC 10 min / 15 min data using API???

Advance Thanks
Dharma

**Comment by dharmaraj81** [comment]
Hi @krishnavelu 

Everything resolved, thanks lot

Dharma

**Comment by Pavan-Jadhav** [comment]
> Hi @krishnavelu
> 
> Everything resolved, thanks lot
> 
> Dharma

Hi Dharmaraj Sir,

Can you let us know how you solved it ?
