### ISSUE TITLE
Algo stops in the middle because of heartbeat error

### ISSUE THREAD

**Issue by Parva14** [krishnavelu/alice_blue#16]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\I BALL\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\I BALL\Anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\I BALL\Anaconda3\lib\site-packages\alice_blue\alice_blue.py", line 358, in __send_heartbeat
    self.__websocket.send(json.dumps(heart_beat), opcode = websocket._abnf.ABNF.OPCODE_PING)
  File "C:\Users\I BALL\Anaconda3\lib\site-packages\websocket\_app.py", line 155, in send
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

**Comment by priyakumariengineer** [comment]
Can you post you code ??

**Comment by Parva14** [comment]
https://gist.github.com/krishnavelu/e0df312ccf5f022edb1823461ff4230e

you can replicate the error while running this code too for more than 2-3 hours

**Comment by priyakumariengineer** [comment]
May be related to 
Heartbeat
A heartbeat message has to be sent every 10 seconds to keep the connection alive. If a heartbeat is not sent, server will close the connection automatically.

@krishnavelu can provide more info

**Comment by krishnavelu** [comment]
Answer these two questions
- [x] which version of library are you using?
- [x] What to you pass as for `run_in_background` argument in `start_websocket` function? `True` or `False`?

**Comment by Parva14** [comment]
Verison:
Name: alice-blue
Version: 0.0.4
Summary: Python library for Alice Blue APIs
Home-page: https://github.com/krishnavelu/alice_blue
Author: Krishna Velu
Author-email: krishnajvelu@gmail.com
License: UNKNOWN
Location: c:\users\i ball\anaconda3\lib\site-packages
Requires: requests, websocket-client, protlib, bs4
Required-by:

Updating it to 0.0.5 and will let you know if the error persists.

run_in_background is set to True
alice.start_websocket(subscribe_callback=event_handler_quote_update,
						  socket_open_callback=open_callback,
						  run_in_background=True)

**Comment by krishnavelu** [comment]
This problem was solved in 0.05. Refer #6 And #9 also if you are passing run_in_background=False try latest develop branch.

**Comment by Parva14** [comment]
It works amazingly now!! Thankyou for your help, keep up the good work!

**Comment by rishiajmera** [comment]
@Parva14 How did you resolve the issue? I am still facing the same issue. web socket gets disconnected after a few minutes.

**Comment by krishnavelu** [comment]
@rishiajmera when the websocket disconnects don’t panic and terminate the program. The library will reconnect automatically.
Enable logging and see when the web socket is disconnecting and reconnecting.

**Comment by rishiajmera** [comment]
Yes, I am not terminating the program, as currently, it's in the testing phase. Although, I have observed that it is not restarting. Any idea how much time does it generally take for re-connecting? And is re-connect is already enabled or do I need to enable it?

**Comment by krishnavelu** [comment]
It’s enabled by default. You cannot disable. Enable logging module and try logging. You’ll come to know when it’s connecting and reconnecting.
Also reconnecting depends on 2 factors.
1. Your stable internet connection.
2. Server up and running.
