### ISSUE TITLE
Incorrect LTP value is being shown every min

### ISSUE THREAD

**Issue by dhayal123** [krishnavelu/alice_blue#161]
Hi,

I am using the following code and collecting last_traded_price of all securities traded in futures. Running the below code to collect the data with a delay of 20secs. 

I checked the data thats being pulled every 20secs and there is big variation in few of the stocks' last_traded_price.

can you check from your side and see if there is any issue?

#code 
  socket_opened = False
    alice.start_websocket(subscribe_callback=event_handler_quote_update,
                        socket_open_callback=open_callback,
                        run_in_background=True)     
    while(socket_opened==False):
        pass
    exec(open("C:/Python_Webapp/backend py/Securitieslist.txt").read(), globals())  
      
    count = 1
    while(True):       
        sleep(20)
        market_data = symbol
        ltpLst_of_Lst = []
        ltpLst_of_Lst = [market_data[i:i + 7] for i in range(0, len(market_data), 7)]        
        _ltpPD = pd.DataFrame(ltpLst_of_Lst, columns=['symbol','ltp','open','high','low','close','volume'])
        #_ltpPD.to_csv("C:/Python_Webapp/backend py/bfore_sort.csv", index=False)
        _ltpPD.sort_values('symbol',inplace=True)
        _ltpPD.drop_duplicates(subset='symbol', keep='last', inplace=True)        
        _ltpPD.reset_index(inplace=True, drop = True)
        _ltpPD.to_csv("C:/Python_Webapp/backend py/ltp.csv")        

[Securitieslist.txt](https://github.com/krishnavelu/alice_blue/files/4993513/Securitieslist.txt)

**Comment by krishnavelu** [comment]
Read and Follow [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue ) before creating a new issue.

Your code is scattered. I cannot understand.

**Comment by dhayal123** [comment]
I am collecting the LTP of every script trading in futures. But, system is retrieving incorrect values. you can replicate the issue by collecting LTP of any scripts for the whole day and check it. It will show you that incorrect values are retrieved 



def event_handler_quote_update(message):
    #print(f"quote update {message}")        
    global symbol
    global ltp
    global _open
    global high
    global low
    global close
    global volume    
    symbol.append(message['instrument'][2])
    ltp.append(message['ltp'])
    _open.append(message['open'])
    high.append(message['high'])
    low.append(message['low'])
    close.append(message['close'])
    volume.append(message['volume'])

**Comment by dhayal123** [comment]
[connectAB.txt](https://github.com/krishnavelu/alice_blue/files/5004965/connectAB.txt)

Attached the code

**Comment by krishnavelu** [comment]
Incorrect values are retrieved because of the way you've written code. Not because of library.
Here is an [example](https://gist.github.com/krishnavelu/e0df312ccf5f022edb1823461ff4230e) strategy.

Again, Read and Follow [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) before creating a new issue.

**Comment by dhayal123** [comment]
Hi Krishna, I m clearing the list every 20second and adding tick data that changes within that 20seconds.. can you pls point me out the issue in my code? It will be a great help to me.. awaiting your help

**Comment by krishnavelu** [comment]
I cannot help for your application. There are so many forms available to get these kind of general `how to` questions ie. [stackoverflow](https://stackoverflow.com/)
Learn python fully and jump to trading using python.
