### ISSUE TITLE
what are the parameters are mandatory for CO order??

### ISSUE THREAD

**Issue by dharmaraj81** [krishnavelu/alice_blue#166]
alice.place_order(transaction_type = TransactionType.Buy,
                         instrument = ins_scrip,
                         quantity = TradeQuandity,
                         order_type = OrderType.Market,
                         product_type = ProductType.CoverOrder,
                         price = 0.0,
                         trigger_price = 3020,
                         stop_loss = None,
                         square_off = None,
                         trailing_sl = None,
                         is_amo = False)

above code ok for my manual input like bellow
![manual-parameters](https://user-images.githubusercontent.com/5977421/89485667-e68d4f00-d7be-11ea-9e17-e2841a33330b.png)

i decided to put a CO order, so what what is trigger_price here, and stop_loss, square_off ??

**Comment by dharmaraj81** [comment]
Hi @krishnavelu 

Also i just wanted to update order ( second leg only, if i put a BUY CO order, it will create a second leg for trigger price, i wanted to update it like follow )

alice.modify_order(transaction_type = TransactionType.Sell,
                         instrument = ins_scrip,
                         order_id = 200805000317599,
                         quantity=None,
                         order_type = OrderType.Market,
                         product_type = ProductType.CoverOrder,
                         price = 0.0,
                         trigger_price = 3030,
                         stop_loss = None,
                         square_off = None,
                         trailing_sl = None,
                         is_amo = False)

i wanted to update only trigger pirce, is it ok ?? should i order_type?? 

Thanks
Dharma

**Comment by dharmaraj81** [comment]
Hi @krishnavelu 

Also i just wanted to update order ( second leg only, if i put a BUY CO order, it will create a second leg for trigger price, i wanted to update it like follow )

alice.modify_order(transaction_type = TransactionType.Sell,
                         instrument = ins_scrip,
                         order_id = 200805000317599,
                         quantity=None,
                         order_type = OrderType.Market,
                         product_type = ProductType.CoverOrder,
                         price = 0.0,
                         trigger_price = 3030,
                         stop_loss = None,
                         square_off = None,
                         trailing_sl = None,
                         is_amo = False)

i wanted to update only trigger price, is it ok ?? should i keep order_type as market?? 

Thanks
Dharma

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue/tree/develop#read-this-before-creating-an-issue) and follow before creating a new issue.

**Comment by krishnavelu** [comment]
@dharmaraj81 Is your problem solved?

**Comment by dharmaraj81** [comment]
No, not yet resolved, i m looking for code snippet to modify trigger price (SL) IN CO order 

Thanks

**Comment by krishnavelu** [comment]
Code snippet is already there in the [document](https://github.com/krishnavelu/alice_blue#place-an-order)
Try different types of orders and explore.
