### ISSUE TITLE
What should be filled in twofa parameter to get the access token using python

### ISSUE THREAD

**Issue by harsha17116031** [krishnavelu/alice_blue#167]
Couldn't get access token {'error': 'invalid_grant', 'error_description': 'The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client', 'status_code': 400}

**Comment by krishnavelu** [comment]
Check your api_key, secret, 2fa, password & redirect url.

**Comment by harsha17116031** [comment]
Where should the redirect url be placed ??

In your documentation the method to get access token is 

access_token = AliceBlue.login_and_get_access_token(username='username', password='password', twoFA='a',  api_secret='api_secret')

So how the parameter twoFA should be filled??

**Comment by krishnavelu** [comment]
redirect url
https://github.com/krishnavelu/alice_blue/blob/master/alice_blue/alice_blue.py#L227
For 2FA, keep all your question's answer as 'a'
