### ISSUE TITLE
Need help regarding redirect URL

### ISSUE THREAD

**Issue by abhishek2111** [krishnavelu/alice_blue#169]
Hello
I have asked alice blue for the api activation.

They have asked to provide a redirect URL to provide api.
So what should be the redirect URL which i need to send to them so that they can activate my api

In you app i can see redirect URL is set as
redirect_url='https://ant.aliceblueonline.com/plugin/callback'

or i need to provide them a localhost URL ?

Can you please help

**Comment by krishnavelu** [comment]
You can provide them default URL. Which id above.
