### ISSUE TITLE
Prevent `self.__websocket.send` from sending any data while ws is disconnected & re-connection is still in progress.

### ISSUE THREAD

**Issue by krishnavelu** [krishnavelu/alice_blue#17]

**Comment by raviiiupadhyay** [comment]
Hi Krishnavelu,

I am using your alice blue code but facing issues in twoFA option of code. I am not able to describe the authentication questions.

"logging.info(f"Assuming answers for all 2FA questions are '{twoFA}', Please change it to '{twoFA}' if not")
resp = r.post(resp.url,data={'answer1':twoFA,'question_id1':question_ids,'answer2':twoFA,'login_challenge':login_challenge,'_csrf_token':csrf_token})"

Can you please elaborate this function to mentioned the answers of security questions?

Thanks and Regards,
Ravi

**Comment by krishnavelu** [comment]
The security questions cannot be extracted. So there is no interface possible to give if this is question 1, provide answer 1. 
So to make it simple change your answers to all questions same. Typically 'a'

**Comment by raviiiupadhyay** [comment]
Thanks a lot!
