### ISSUE TITLE
Bug in search_instruments and get_instrument_by_symbol functions

### ISSUE THREAD

**Issue by prateekjjw001** [krishnavelu/alice_blue#170]
if you call: 
`x=alice.search_instruments('NSE', 'NIFTY 50')` 
it returns nothing, since the code is: 
`if symbol.lower() in master_contract[contract].symbol.split(' ')[0].lower():`

I think you can change it to: 
`if symbol.lower() in master_contract[contract].symbol.lower():`

Why strip and check only 1st index word? Any reason?

**Comment by prateekjjw001** [comment]
In case it matters, this is how i initialised:
`alice = AliceBlue(username=username, password=password, access_token=access_token,master_contracts_to_download=['NSE','NFO'])`
`nifty=alice.search_instruments('NSE','NIFTY 50')`
this returns null

the below also returns null:
`nifty=alice.get_instrument_by_symbol('NSE','NIFTY 50')`

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue/tree/develop#read-this-before-creating-an-issue) and follow before creating a new issue
Try this
`nifty_nse_eq = alice.get_instrument_by_symbol('NSE', 'Nifty 50') `

**Comment by anchalsoni14** [comment]
Showing result like that

Instrument(exchange='NSE', token=26000, symbol='Nifty 50', name='Nifty 50', expiry=None, lot_size=None)

**Comment by krishnavelu** [comment]
@prateekjjw001 your problem solved?
