### ISSUE TITLE
'Not able to Retrieve ModifyOrder' error while modifying an order

### ISSUE THREAD

**Issue by ghost** [krishnavelu/alice_blue#171]
When I try to modify an an order I am receiving 'Not able to Retrieve ModifyOrder '. screenshot  attached at the end

below is my code

to place order

`order = alice.place_order(transaction_type=TransactionType.Buy,
                  instrument=instrument,
                  quantity=1,
                  order_type=OrderType.Limit,
                  product_type=ProductType.Delivery,
                  price=190.0)`

`order_id=order['data']['oms_order_id']
order_id`

to modify order

`alice.modify_order(order_id=order_id,
                   transaction_type=TransactionType.Buy,
                   instrument=instrument,
                   order_type=OrderType.Limit,
                   product_type=ProductType.Delivery,
                   price=189.0)`

![image](https://user-images.githubusercontent.com/59556194/89759554-0d71bb00-db08-11ea-89c9-e954f36e735c.png)

**Comment by krishnavelu** [comment]
Is the order filled already? Only if the order is not filled you can modify an order. I also got this message some times before, I forgot what was the reason. Try to use the latest library version and make sure order is not filled.

**Comment by krishnavelu** [comment]
Also try during market hours

**Comment by ghost** [comment]
Was missing quantity in modify order.
Now working.

Modify order args need to be same as place order.
If possible add validation for missing args in modify order

**Comment by aeron7** [comment]
This also happens if you pass the quantity in string instead of integer.
