### ISSUE TITLE
MCX - Not fetching previous day OHLC data correctly

### ISSUE THREAD

**Issue by VikramBangre** [krishnavelu/alice_blue#172]
Hi,

When I try to get fetch previous day OHLC data for MCX (Crude & Natural Gas) in the morning (before opening the market), I get wrong data for Open, High, Low and they are all having same value.  Close data comes correctly.

OHL = 22949672

It's working fine for NFO & NSE.

Regards,
Vikram

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue/tree/develop#read-this-before-creating-an-issue) and follow before creating new issue.

**Comment by VikramBangre** [comment]
```
from alice_blue import AliceBlue
from alice_blue import LiveFeedType
import datetime
import time
import os

user_name = "x"
password = "x"
two_fa = "x"
api_secret_key = "x"

with open("D:\\Algo_Trading\\_Trading_\\Access_Token.txt", "r") as f:
    access_token = f.read().strip()
alice = AliceBlue(username=user_name, password=password, access_token=access_token)

socket_opened = False
token = ""
open_price = 0
high_price = 0
low_price = 0
close_price = 0

def event_handler_quote_update(message):
    # print(f"quote update {message}")
    global token
    global open_price
    global high_price
    global low_price
    global close_price

    token = message['token']
    open_price = message['open']
    high_price = message['high']
    low_price = message['low']
    close_price = message['close']

def open_callback():
    global socket_opened
    socket_opened = True

alice.start_websocket(subscribe_callback=event_handler_quote_update, \
                      socket_open_callback=open_callback, \
                      run_in_background=True)

while (socket_opened==False):
    pass

alice.subscribe([alice.get_instrument_by_symbol('MCX', 'CRUDEOIL AUG FUT')], LiveFeedType.MARKET_DATA)

i = 0
while True:

    i = i + 1

    if (i > 2):
        break

    # Crude
    if str(token) == '218264':

        print("Crude_FUT" + "," + str(open_price) + "," + str(high_price) + "," + str(low_price) + "," + str(close_price))

    time.sleep(1)

alice.unsubscribe([alice.get_instrument_by_symbol('MCX', 'CRUDEOIL AUG FUT')], LiveFeedType.MARKET_DATA)

```

Output :
Open = 22949672 (Wrong Value)
High = 22949672 (Wrong Value)
Low = 22949672 (Wrong Value)
Close = 3131  (Correct Value)

**Comment by krishnavelu** [comment]
I cannot read/understand the above cluttered code. I’ve given a clear example of what I expect when you create a new issue.
A sample code which I can directly reproduce without extra efforts and output of the sample code.

**Comment by VikramBangre** [comment]
I have update the code, correctly please check.

**Comment by VikramBangre** [comment]
any help would be appreciated. I am trying to automate these details as my logic revolves around previous day values. 

Right now i am updating the table manually.

**Comment by krishnavelu** [comment]
Paste the output as actual output of print statement.
With the same code just by changing the scrip as any NSE-EQ scrip does it give correct ohlc?
Even in MCX did you try some other scrips? Does it give correct ohlc values?

**Comment by krishnavelu** [comment]
Also uncomment the print inside  event_handler_quote_update() function what you are getting.

**Comment by VikramBangre** [comment]
I have tried for Crude, Natural Gas, Bank Nifty, Nifty. 

Bank Nifty, Nifty are showing correct values. Pleas find the complete value. Below was taken last week. Now Crude, has expired and Sep is running. 

quote update {'exchange': 'MCX', 'token': 218264, 'ltp': 22949672.96, 'ltt': 4294947496, 'ltq': 0, 'volume': 0, 'best_bid_price': 0.0, 'best_bid_quantity': 0, 'best_ask_price': 0.0, 'best_ask_quantity': 0, 'total_buy_quantity': 0, 'total_sell_quantity': 0, 'atp': 22949672.96, 'exchange_time_stamp': 1597342500, 'open': 22949672.96, 'high': 22949672.96, 'low': 22949672.96, 'close': 3159.0, 'yearly_high': 0.0, 'yearly_low': 22949672.96, 'instrument': Instrument(exchange='MCX', token=218264, symbol='CRUDEOIL AUG FUT', name='', expiry=datetime.date(2020, 8, 19), lot_size=None)}


quote update {'exchange': 'MCX', 'token': 220568, 'ltp': 22949672.96, 'ltt': 4294947496, 'ltq': 0, 'volume': 0, 'best_bid_price': 0.0, 'best_bid_quantity': 0, 'best_ask_price': 0.0, 'best_ask_quantity': 0, 'total_buy_quantity': 0, 'total_sell_quantity': 0, 'atp': 22949672.96, 'exchange_time_stamp': 1597342500, 'open': 22949672.96, 'high': 22949672.96, 'low': 22949672.96, 'close': 162.3, 'yearly_high': 0.0, 'yearly_low': 22949672.96, 'instrument': Instrument(exchange='MCX', token=220568, symbol='NATURALGAS AUG FUT', name='', expiry=datetime.date(2020, 8, 26), lot_size=None)}


quote update {'exchange': 'NFO', 'token': 44329, 'ltp': 22189.5, 'ltt': 0, 'ltq': 0, 'volume': 4927225, 'best_bid_price': 0.0, 'best_bid_quantity': 0, 'best_ask_price': 0.0, 'best_ask_quantity': 0, 'total_buy_quantity': 0, 'total_sell_quantity': 0, 'atp': 22282.57, 'exchange_time_stamp': 0, 'open': 22401.0, 'high': 22443.95, 'low': 22122.5, 'close': 22189.5, 'yearly_high': 22443.95, 'yearly_low': 0.0, 'instrument': Instrument(exchange='NFO', token=44329, symbol='BANKNIFTY AUG FUT', name='', expiry=datetime.date(2020, 8, 27), lot_size='25')}


quote update {'exchange': 'NFO', 'token': 44330, 'ltp': 11317.35, 'ltt': 0, 'ltq': 0, 'volume': 8723100, 'best_bid_price': 0.0, 'best_bid_quantity': 0, 'best_ask_price': 0.0, 'best_ask_quantity': 0, 'total_buy_quantity': 0, 'total_sell_quantity': 0, 'atp': 11322.34, 'exchange_time_stamp': 0, 'open': 11338.2, 'high': 11366.7, 'low': 11266.85, 'close': 11317.35, 'yearly_high': 11366.7, 'yearly_low': 0.0, 'instrument': Instrument(exchange='NFO', token=44330, symbol='NIFTY AUG FUT', name='', expiry=datetime.date(2020, 8, 27), lot_size='75')}

**Comment by krishnavelu** [comment]
Its seems the server itself sends the data like that.

Raw data
```
[1, 4, 0, 3, 94, 233, 0, 4, 254, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 4, 254, 32, 136, 202, 108, 0, 136, 202, 108, 0, 0, 4, 254, 32, 0, 0, 0, 0, 136, 202, 108, 0]
```
Converted to python format
```
{'exchange': 'MCX', 'token': 220905, 'ltp': 3272.0, 'ltt': 0, 'ltq': 0, 'volume': 0, 'best_bid_price': 0.0, 'best_bid_quantity': 0, 'best_ask_price': 0.0, 'best_ask_quantity': 0, 'total_buy_quantity': 0, 'total_sell_quantity': 0, 'atp': 21474836.48, 'exchange_time_stamp': 0, 'open': 3272.0, 'high': 22949672.96, 'low': 22949672.96, 'close': 3272.0, 'yearly_high': 0.0, 'yearly_low': 22949672.96, 'instrument': Instrument(exchange='MCX', token=220905, symbol='CRUDEOIL DEC FUT', name='', expiry=datetime.date(2020, 12, 18), lot_size=None)}
```

Sample code

```
def event_handler_quote_update(message):
    print(f"quote update {message}")

socket_opened = False
def open_callback():
    global socket_opened
    socket_opened = True

alice.start_websocket(subscribe_callback=event_handler_quote_update, \
                      socket_open_callback=open_callback, \
                      run_in_background=True)

while(socket_opened==False):
    pass

i = alice.get_instrument_for_fno('CRUDEOIL', datetime.date(2020, 12, 18), is_fut=True, exchange='MCX')
print(i)
alice.subscribe(i, LiveFeedType.MARKET_DATA)
sleep(1000)
```

**Comment by krishnavelu** [comment]
Raise the issue with alice customer care.

**Comment by VikramBangre** [comment]
ok thanks
