### ISSUE TITLE
Is there any plan to implement API to get intraday or historical candles data?

### ISSUE THREAD

**Issue by rahulmr** [krishnavelu/alice_blue#173]
Hi @krishnavelu 
Is there any plan to implement API to get intraday or historical candles data?
I have written some code for that and I think it can be well embedded in your package.
Please let me know.

**Comment by krishnavelu** [comment]
Intraday candlestick:
Intraday candlesticks can be built from live data. Which this library already provides. 

Historical candlestick:
Alice Blue does not provide historical data.

I want to keep the library as simple as possible so that it can be well maintained. Candlesticks are just a kind of display method for live data. I don’t have any plans to include any application related stuffs in library.

**Comment by rahulmr** [comment]
@krishnavelu Thanks. I was just saying I already have code for getting historical data using aliceblue api. I just tried but yes it needs to be tested and validated. Live data only gives ticks for current day. But yes we can use nsetools or yfinance to get previous day data or intraday data for last 2 months.
Anyways I will implement that in my personal fork of your library. And thanks for this small library which is far more better that zerodha complicated stuff. Both are good but I like this one more

**Comment by jaydave1988** [comment]
Hi Rahul, Could you please share your code snippet to get historical data? So, it will useful to other users.

**Comment by krishnavelu** [comment]
@rahulmr For providing reliable historical data, you need to store it somewhere in the server. You need to have atleast past 5 years historical data stored in a server. 
Upstox provides past 10 years historical data. I don’t know about zerodha how much years past they provide. But they too provide historical I guess. They all have their own servers and charge you for the same. Without having atleast 5 years of data we cannot call that as historical data. Whatever code you have is not historical data without this past 5 years data.

Does alice already provide historical data from their server? Do you have code to pull out historical data from alice servers?

**Comment by jaydave1988** [comment]
@krishnavelu Correct, If he has written code like that, then we can merge that code in our library for public use.

**Comment by krishnavelu** [comment]
As per my knowledge alice doesn’t have historical data.

**Comment by jaydave1988** [comment]
They are not providing official APIs for that.. But we can get that doing some hack I think.. That's why i asked rahul to post his code here.

**Comment by rahulmr** [comment]
I am not talking about reliability but many of us still trade with alice blue charts and it gives us bars for 1min, 5min, 10min, 15min, etc. I am not talking about historical data in the sense of 5 years or 10 years. But with the code I have written I can get from Jan 2020. There are few things to be enhanced in this code which you expert can do.

**Comment by jaydave1988** [comment]
@rahulmr Please share the code if you dont have problem.

**Comment by rahulmr** [comment]
here is the code in full. If you can implement it in a better way many people can benefit out of it.
Zerodha charges 2k+2k for API and historical data. If we can have a temporary and free solution what is the problem to implement?
**Disclaimer** - It is not 100% tested and not foolproof. 

And @krishnavelu one more question do we already have screeners api? `/api/v1/screeners/gainerslosers?index=nifty_50`

```python
import pandas as pd
import datetime as dt
import numpy as np
import requests
import dateutil
import pytz

HEADERS = {
    'X-Authorization-Token': open('auth_token.txt', 'r').read().strip()
}

'''
fetch("https://ant.aliceblueonline.com/api/v1/screeners/gainerslosers?index=nifty_50", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.9",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "x-authorization-token": open('auth_token.txt', 'r').read().strip(),
    "x-device-type": "web"
  },
  "referrer": "https://ant.aliceblueonline.com/app/home",
  "referrerPolicy": "no-referrer-when-downgrade",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "include"
});


'''

def gainerslosers(index="nifty_50"):
    index = index.lower()
    try:
        r = requests.get("https://ant.aliceblueonline.com/api/v1/screeners/gainerslosers?index={}".format(index), headers=HEADERS)
        data = r.json()
        return format_intraday(data)
    except Exception as e:
        print(
            "{} Error occurred.".format(e))

def historical_data(exchange, token, starttime, endtime, interval=1):
    PARAMS = {
        'candletype': 1,
        'data_duration': interval,
        'starttime': starttime,
        'endtime': endtime,
        'exchange': exchange,
        'type': 'historical',
        'token': token
    }
    try:
        r = requests.get(
            "https://ant.aliceblueonline.com/api/v1/charts", params=PARAMS, headers=HEADERS)
        data = r.json()
        return format_intraday(data)
    except Exception as e:
        print(
            "{} Error occurred in getting intraday data for ticker :: {}".format(e,token))

def intraday_data(exchange, token, starttime, endtime, interval=1):
    PARAMS = {
        'candletype': 1,
        'data_duration': interval,
        'starttime': starttime,
        'endtime': endtime,
        'exchange': exchange,
        'type': 'live',
        'token': token
    }
    try:
        r = requests.get(
            "https://ant.aliceblueonline.com/api/v1/charts", params=PARAMS, headers=HEADERS)
        data = r.json()
        return format_intraday(data)
    except Exception as e:
        print(
            "{} Error occurred in getting intraday data for ticker :: {}".format(e, token))


def format_intraday(data):
    records = data['data']
    df = pd.DataFrame(records, columns=[
                      'datetime', 'open', 'high', 'low', 'close', 'volume'])  # , index=0)
    df['datetime'] = df['datetime'].apply(
        pd.Timestamp, unit='s', tzinfo=pytz.timezone("Asia/Kolkata"))
    df[['open', 'high', 'low', 'close']] = df[['open', 'high', 'low', 'close']].astype(float).div(100)
    df.set_index('datetime', inplace=True)
    if(df.empty):
        print("Pandas DataFrame is empty.")
    return df


tday = dt.date.today()
startTime = int(dt.datetime(tday.year, tday.month, tday.day,
                            hour=9, minute=0, second=0).timestamp())
endTime = int(dt.datetime(tday.year, tday.month, tday.day,
                          hour=23, minute=59, second=0).timestamp())

# RELIANCE 2885, ADANIPORTS 11287, CIPLA 694, GOLDM SEP FUT 220754, CRUDEOIL SEP FUT 219405, SBIN 3045
print(dt.datetime.now())
for token in [3045, 2885, 11287, 694]:
    print(intraday_data('NSE', token=token, starttime=startTime, endtime=endTime, interval=5))

for token in [220754, 219405]:
    print(intraday_data('MCX', token=token, starttime=startTime, endtime=endTime, interval=10))

print(dt.datetime.now())
# Get data from 1st January 2020 till yesterday. There might be no data for MCX FUTURES for a given token
startTime = int(dt.datetime(tday.year, 1, 1,
                            hour=9, minute=0, second=0).timestamp())
endTime = int(dt.datetime(tday.year, tday.month, tday.day-1,
                          hour=23, minute=59, second=0).timestamp())

for token in [2885, 11287, 694, 3045]:
    stock = historical_data('NSE', token=token, starttime=startTime, endtime=endTime, interval=15)
    stock.to_csv('{}_15m.csv'.format(token))

for token in [220754, 219405]:
    print(historical_data('MCX', token=token, starttime=startTime, endtime=endTime, interval=5))

print(dt.datetime.now())

```

**Comment by rahulmr** [comment]
> @rahulmr Please share the code if you dont have problem.

Added

**Comment by jaydave1988** [comment]
'X-Authorization-Token': open('auth_token.txt', 'r').read().strip()

What we need to store in this auth_token.txt file?

**Comment by rahulmr** [comment]
> 'X-Authorization-Token': open('auth_token.txt', 'r').read().strip()
> 
> What we need to store in this auth_token.txt file?

Your access_token which is is like `"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJibGFja2xpc3Rfa2V5IjoiQUIwNDQ3ODI6WHJLK3JHeWgrVURBclBqOEpvaFhkdyIsImNsaWVudF9pZCI6IkFCMDQ0NzgyIiwiY2xpZW50X3Rva2VuIjoiVXdXNWp0ZUQzbkJKMzFMUVlqaHdjZyIsImRldmljZSI6IndlYiIsImV4cCI6MTU5NzcyNjkzNDg0N30.OmknbLP3O4SisMeJ6QjromHKIyeLxrUTlFJwslVFecM"` This expires in 24 hrs

**Comment by jaydave1988** [comment]
I have tried with my access_token, but it is giving below error:
{'status': 'error', 'message': 'Request Unauthorised', 'data': {}}

**Comment by rahulmr** [comment]
@jaydave1988 Please do provide feedback whether it is working as expected maybe we can compare it with zerodha data. Also for USDINR FUT - you may have to divide by 1000 as it is upto 4 decimal places.

@krishnavelu Do you want this to be kept open? If not please close this issue from your end. I will keep it open as of now.

**Comment by rahulmr** [comment]
> I have tried with my access_token, but it is giving below error:
> {'status': 'error', 'message': 'Request Unauthorised', 'data': {}}

You are not using right token. Is your token starting with `ey` ?

**Comment by jaydave1988** [comment]
No.. It is generated using method provided in this library.. It is shorter than you have provided..
I think this is different access_token. 
How can we get this token?

**Comment by rahulmr** [comment]
In case, you still have problem. You can join group on telegram [Algo Traders Python](https://t.me/AlgoTradeAnalysis)

**Comment by rahulmr** [comment]
> No.. It is generated using method provided in this library.. It is shorter than you have provided..
> I think this is different access_token.
> How can we get this token?

Login to Alice Blue Ant using Chrome Browser and open developer tools (DevTools) by pressing control+shift+i and click on network tab.
In background click some tabs like home, orders, etc. You will see some entries in left side of DevTools - click on that and then click on cookies or check headers

**Comment by rahulmr** [comment]
> No.. It is generated using method provided in this library.. It is shorter than you have provided..
> I think this is different access_token.
> How can we get this token?

You can also use [alicebot.in](https://alicebot.in/) by their telegram bot [alicebot](https://t.me/aliceapi_bot) check their [commands](https://alicebot.in/commands/)

**Comment by jaydave1988** [comment]
@rahulmr Thanks for the informations.

**Comment by rahulmr** [comment]
@jaydave1988 Worked for you or not?

**Comment by jaydave1988** [comment]
> @jaydave1988 Worked for you or not?

No same error is coming.

**Comment by G-2-G** [comment]
Thank you @rahulmr for sharing the information.
Got the auth token as you mentioned from the steps however getting empty data frames, is anything else to be taken care of.

**Comment by krishnavelu** [comment]
@rahulmr we do not have screeners API.

**Comment by aeron7** [comment]
@rahulmr 

The point is - It has to be official. Theoretically, Every broker's API is free. Historical Data is also free. Like it is done here for 5paisa https://www.youtube.com/watch?v=2PXSfi0Rsho (Note - I had taken permission from 5Paisa.).

Now, If a human can see the data of stock from the chart, a machine can do the same. An official API can't. We can only make wrapper or share methods that are allowed by Alice. But, Alice's management is very flexible than other brokers. I already asked for permission for adding some extra functions. If We're given, We will add it.

Here is a complete list of Python Methods currently doable by AliceBlue API. https://forum.unofficed.com/t/unofficial-python-methods-for-aliceblue-api/445

But right now, It's unofficial. I will keep you guys updated if we get it approved.

**Comment by rahulmr** [comment]
@aeron7 Great!! Thanks for the updates.

**Comment by rahulmr** [comment]
> @rahulmr we do not have screeners API.

Is it difficult to implement? It will be great if we have it in the API.

**Comment by rahulmr** [comment]
@aeron7 Little off topic question here . 

The below code I have written in NodeJS and it is working great and I am getting access_token also which I am expecting.  
But I am trying something similar in python using `requests` and `http.cookiejar` but it is not working.  
Can I connect with you in unofficed slack channel?  
Basically, I am doing all this to automate strategy on a Linux container.  
```javascript
const axios = require('axios').default;
const fs = require('fs')
const axiosCookieJarSupport = require('axios-cookiejar-support').default;

// In root directory => npm install or npm i 
// Packages from the package.json will be installed

axiosCookieJarSupport(axios);

const user = require('./user.json');
// NOTE Contents of user.json should be as below
// Put your own login_id / client_id and correct password
// {
//     "login_id": "AB123456",
//     "password": "P@ssw0rd",
//     "device": "web"
// }

// STEP1: answers.json file will be generated or overwritten
axios.post('https://ant.aliceblueonline.com/api/v2/login', user)
    .then(function (response) {
        fs.writeFileSync('./answers.json', JSON.stringify(response.data));
    });

twofa = require('./twofa.json')
// NOTE Contents of twofa.json should be as below
// Put your own login_id / client_id and twofa code
// twofa code must be same for all questions
// {
//     "answers": [
//         "a",
//         "a"
//     ],
//     "login_id": "AB123456",
//     "question_ids":[11,6],
//     "device": "web",
//     "count": 2
// }

ans = require('./answers.json')

// STEP2: updating question_ids
twofa.question_ids = ans.data.question_ids

// STEP3: access_token.txt containing access_token will be generated or overwritten
axios.post('https://ant.aliceblueonline.com/api/v2/checktwofa', twofa)
    .then(function (response) {
        // console.log(response.data)
        fs.writeFileSync('./access_token.txt', response.data.data.auth_token);
    })
```

Here is the python code.  What is the thing I am doing wrong? I am not getting at all.
I see your telegram bot works in a similar way, we provide username, pwd and twofa and it returns access_token.
Have you created the bot using python?
```python
import requests
import http.cookiejar
import json

s = requests.Session()
s.cookies =  http.cookiejar.LWPCookieJar("abcookies.txt")
s.get('https://ant.aliceblueonline.com/')
s.cookies.save()

user = json.loads(open('user.json', 'r').read().rstrip())
s.cookies.load()
r = s.post('https://ant.aliceblueonline.com/api/v2/login', data=user)
print(r.json())
s.cookies.save()

qids = r.json()['data']['question_ids']

twofa = json.loads(open('twofa.json', 'r').read().rstrip())

twofa['question_ids'] = qids

print(twofa)
s.cookies.load()
r = s.post('https://ant.aliceblueonline.com/api/v2/checktwofa', data=twofa)
print(r.json())

```

**Comment by rahulmr** [comment]
Guys @jaydave1988 and @G-2-G , I have added the code in NodeJS to get the access_token using script from AliceBlue which you can use it for getting data.  
What is the exact issue you are getting? Is it Empty DataFrame?
If you are trying to get data fro today then you need to use type as live and check the start time and end time properly.

**Comment by jaydave1988** [comment]
@rahulmr , can't we do it full in python?

**Comment by rahulmr** [comment]
> @rahulmr , can't we do it full in python?

I am having problem to do it in python that's why created it in NodeJS. See above discussion.

**Comment by aeron7** [comment]
@rahulmr I am connected with brokers and without their explicit permission; If I get involved, They will strip me of my current superpowers I enjoy as their ally. Right?

The one I created for my AliceBot, I had to take permission.

Anyways it is not hard to crack. I can tell you about cracking 5Paisa as their own team is fine with it. But not Alice. One director explicitly hanging his sword over my head.

**Comment by aeron7** [comment]
@rahulmr This is because - **Some of their sub-brokers also charge for the API. As well as, they charge some of the clients!** It will hamper their business.

**Comment by rahulmr** [comment]
@aeron7 No issues Amit. I can understand. Anyways I am not blocked and using nodejs effectively. But thanks for recognizing and giving more info on this. Yes and I know how zerodha is charging 4k per month it is huge. Now, let's not affect their business. But I am using your bot for getting token I coded a python code for the same. Thanks for it.

**Comment by krishnavelu** [comment]
@rahulmr You can fork this library and add your functions to get historical data.

**Comment by rahulmr** [comment]
@krishnavelu yup

**Comment by dinesht15** [comment]
@rahulmr  
Can you please provide your email id. mine is dinesht15@gmail.com

**Comment by rahulmr** [comment]
> @rahulmr , can't we do it full in python?


Guys finally got the solution which was actually very simple, I was just making it complicated. Here is the final code.
Now you can enjoy in python!! .  
```python
# -*- coding: utf-8 -*-
"""
Alice Blue Online - Login and Get Access Token

@author: Rahul RAUT <rahulmraut@gmail.com>
"""

import requests
import json

login_url = "https://ant.aliceblueonline.com/api/v2/login"
twofa_url = "https://ant.aliceblueonline.com/api/v2/checktwofa"
s = requests.Session()

secret = json.loads(open('secret.json', 'r').read().rstrip())

# NOTE contents of secret.json must be like below
# {
#     "login_id":"AB123456",
#     "password":"PaSSw0rd@1",
#     "twofa":"a"
# }

login_json = {"device": "web"}
login_json['login_id'] = secret['login_id']
login_json['password'] = secret['password']

r = s.post(login_url, json=login_json)

twofa_json = {"device": "web", "count": 2}
twofa_json['login_id'] = secret['login_id']
twofa_json['answers'] = [secret['twofa'], secret['twofa']]
twofa_json['question_ids'] = r.json()['data']['question_ids']

r = s.post(twofa_url, json=twofa_json)

with open('access_token.txt', 'w') as wr:
    wr.write(r.json()['data']['auth_token'])

print(open('access_token.txt', 'r').read().rstrip())


```

My suggestion is to keep this separate or use it only for getting access token in a text file..
You can always read a file using below code.  
```python
access_token = open('access_token.txt', 'r').read().rstrip()
```

**Comment by jaydave1988** [comment]
Thanks Rahul for sharing this.... I will try and let you know.

**Comment by jaydave1988** [comment]
> > @rahulmr , can't we do it full in python?
> 
> Guys finally got the solution which was actually very simple, I was just making it complicated. Here is the final code.
> Now you can enjoy in python!! .
> 
> ```python
> # -*- coding: utf-8 -*-
> """
> Alice Blue Online - Login and Get Access Token
> 
> @author: Rahul RAUT <rahulmraut@gmail.com>
> """
> 
> import requests
> import json
> 
> login_url = "https://ant.aliceblueonline.com/api/v2/login"
> twofa_url = "https://ant.aliceblueonline.com/api/v2/checktwofa"
> s = requests.Session()
> 
> secret = json.loads(open('secret.json', 'r').read().rstrip())
> 
> # NOTE contents of secret.json must be like below
> # {
> #     "login_id":"AB123456",
> #     "password":"PaSSw0rd@1",
> #     "twofa":"a"
> # }
> 
> login_json = {"device": "web"}
> login_json['login_id'] = secret['login_id']
> login_json['password'] = secret['password']
> 
> r = s.post(login_url, json=login_json)
> 
> twofa_json = {"device": "web", "count": 2}
> twofa_json['login_id'] = secret['login_id']
> twofa_json['answers'] = [secret['twofa'], secret['twofa']]
> twofa_json['question_ids'] = r.json()['data']['question_ids']
> 
> r = s.post(twofa_url, json=twofa_json)
> 
> with open('access_token.txt', 'w') as wr:
>     wr.write(r.json()['data']['auth_token'])
> 
> print(open('access_token.txt', 'r').read().rstrip())
> ```
> 
> My suggestion is to keep this separate or use it only for getting access token in a text file..
> You can always read a file using below code.
> 
> ```python
> access_token = open('access_token.txt', 'r').read().rstrip()
> ```

This code is working perfectly fine...

**Comment by krishnavelu** [comment]
@rahulmr don't post any code here.

**Comment by krishnavelu** [comment]
Closing this.

**Comment by Chawdavijay** [comment]
> Intraday candlestick:
> Intraday candlesticks can be built from live data. Which this library already provides.
> 
> Historical candlestick:
> Alice Blue does not provide historical data.
> 
> I want to keep the library as simple as possible so that it can be well maintained. Candlesticks are just a kind of display method for live data. I don’t have any plans to include any application related stuffs in library.

https://github.com/krishnavelu/alice_blue/issues/173#issuecomment-674470627

Can you please guide me how can we build Intraday candlestick...?

**Comment by krishnavelu** [comment]
If you know what is candlestick, you can build candlestick of any timeframe from tick data.

**Comment by jpai7** [comment]
> > @rahulmr Please share the code if you dont have problem.
> 
> Added

I tried to use the intraday_data function from the code you provided but did not get any data for Nifty 50 with token code of 26000 and same case for other index as well. Got this message "Pandas DataFrame is empty" .
I am trying to fetch the intraday data for Nifty 50. Please suggest any other alternate.

**Comment by anheiser1997** [comment]
@krishnavelu 

> If you know what is candlestick, you can build candlestick of any timeframe from tick data.

This is true but the volume we get from tick data is not at all accurate. Is there any good way to get volumes from the tick data?

**Comment by krishnavelu** [comment]
subscribe and see different kind of tick data. you'll get more idea.

**Comment by anheiser1997** [comment]
> subscribe and see different kind of tick data. you'll get more idea.

I am already using tick data. Of course, that can only be done by subscribing, but the volume we get is erroneous and so many times in the order of 10^8, when we sum it for time frame of 3 minutes. Volume can be erroneous if we miss some ticks as well.

**Comment by arjuneshm** [comment]
> ```python
> token
> ```
@rahulmr  : Is it possible to get the historical data for the options like this . Because i am unable to get the expired options token (trying for Nifty CE and PE options). Expired option instrument creation is None. Any help you can suggest please ?

**Comment by rahulmr** [comment]
> > ```python
> > token
> > ```
> 
> @rahulmr : Is it possible to get the historical data for the options like this . Because i am unable to get the expired options token (trying for Nifty CE and PE options). Expired option instrument creation is None. Any help you can suggest please ?

You cannot get expired tokens historical data using any bypass. Either you need to purchase it or check on Telegram or Kaggle where people have uploaded historical data in 1 minute format for options and futures for past several years, there is no guarantee of this data.
