### ISSUE TITLE
How can i modify the CO order after main order executed ??

### ISSUE THREAD

**Issue by dharmaraj81** [krishnavelu/alice_blue#175]
Hi

i decided to place a CO order using following code

OrderStatus = alice.place_order(transaction_type = TransactionType.Buy,
                     instrument = ins_scrip,
                     quantity = TradeQuandity,
                     order_type = OrderType.Market,
                     product_type = ProductType.CoverOrder,
                     price = 0.0,
                     trigger_price = StopLoss, 
                     stop_loss = None,
                     square_off = None,
                     trailing_sl = None,
                     is_amo = False)

once it completed, i want to update the trigger price ( SL ) based on LTP ( like trailing SL ),

Can you pls help to modify trigger price in completed Buy/Sell order ??

Thanks
Dharma

**Comment by dharmaraj81** [comment]
Hi @krishnavelu 

Can you pls help me to fix it

Tks

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue/tree/develop#read-this-before-creating-an-issue) and follow before creating a new issue.

**Comment by krishnavelu** [comment]
CO order will create two orders internally. You can see order history and modify the open order.

**Comment by krishnavelu** [comment]
Hope your problem is solved. Reopen if needed.
