### ISSUE TITLE
How frequent we need to get the LTP (Need Info, not an issue)

### ISSUE THREAD

**Issue by VikramBangre** [krishnavelu/alice_blue#176]
```
socket_opened = False
def event_handler_quote_update(message):
    print(f"quote update {message}")

def open_callback():
    global socket_opened
    socket_opened = True

alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
while(socket_opened==False):
    pass
alice.subscribe(alice.get_instrument_by_symbol('NSE', 'ONGC'), LiveFeedType.MARKET_DATA)
sleep(10)
```

Question is -> sleep(0.2 or 0.5 or 0.8 or 1), which gives accurate results after resampling the data.

df_temp = contains LTP and Volume

`df = df_temp.resample("2min").agg({'LTP': 'ohlc', 'Volume': 'sum'})`

**Comment by krishnavelu** [comment]
You don’t need to specify any time whenever there is an update  event_handler_quote_update() will be called. However speed the data may come, Your code should be able to handle it efficiently.

**Comment by VikramBangre** [comment]
ok thanks for the information
