### ISSUE TITLE
Unable to fetch Nifty FnO series

### ISSUE THREAD

**Issue by Parva14** [krishnavelu/alice_blue#18]
Can anyone please post the result for this:

alice.get_instrument_for_fno(symbol = 'NIFTY' , expiry_date=datetime.date(2019, 11, 28), is_fut=True, strike=None)

or mention any other method that you are  using to fetch Options and Futures for NIFTY.

PS: This works for BANKNIFTY but not for NIFTY

**Comment by krishnavelu** [comment]
I'm getting proper result.
`Instrument(exchange='NFO', token='48186', symbol='BANKNIFTY NOV FUT', name='', expiry=datetime.date(2019, 11, 28), lot_size='20')`

**Comment by Parva14** [comment]
Yes, I do get proper results for BANKNIFTY FnO series, but it returns 'None' for NIFTY FnO series.

**Comment by krishnavelu** [comment]
I’m getting proper results. I’ve posted the results too.
Verify what contract notes are getting download at start. If contract notes are not downloaded you’ll get none.

**Comment by krishnavelu** [comment]
Oops, sorry, if you are getting BN, you should get nifty too.

**Comment by krishnavelu** [comment]
Which version are you using?

**Comment by Parva14** [comment]
These are the results for pip show alice_blue
Name: alice-blue
Version: 0.0.5
Summary: Python library for Alice Blue APIs
Home-page: https://github.com/krishnavelu/alice_blue
Author: Krishna Velu
Author-email: krishnajvelu@gmail.com
License: UNKNOWN
Location: c:\users\i ball\anaconda3\lib\site-packages
Requires: protlib, websocket-client, bs4, requests
Required-by:


Can you please post your result for:
alice.get_instrument_for_fno(symbol = 'NIFTY' , expiry_date=datetime.date(2019, 11, 28), is_fut=True, strike=None)

**Comment by krishnavelu** [comment]
Above, I’ve posted results for NIFTY only... :)
Didn’t notice it has BN in results. Need to investigate why its give BN as results when I give nifty as input.

**Comment by krishnavelu** [comment]
Fixed in develop branch. Take develop branch and test it.
this is my result now.
```
Instrument(exchange='NFO', token='48187', symbol='NIFTY NOV FUT', name='', expiry=datetime.date(2019, 11, 28), lot_size='75')
```

**Comment by Parva14** [comment]
Yes I saw that, it was probably because the code was checking NIFTY in 'symbol string' and BANKNIFTY was taking a priority. Thank you for fixing it! Also, are you going to push the changes to master branch soon?

**Comment by krishnavelu** [comment]
I don’t have a plan. If I get free time will push and release 0.0.6

**Comment by g1raz85** [comment]
ho can i get all instrument list from alice blue api

**Comment by g1raz85** [comment]
is there any API endpoint there to get all instrument supported by Alice blue

**Comment by krishnavelu** [comment]
A master contract will be downloaded while you create the alice-blue object. Try to look into that master contract.

**Comment by jay5deep** [comment]
Can you please move changes related to Nifty NFO from the Develop branch to the Master branch?

**Comment by krishnavelu** [comment]
Done

**Comment by gbaalaji** [comment]
@krishnavelu 

searching for the instrument in NFO for nifty50, it still returns BANKNIFTY instrument in `alice.search_instrument( )`

`alice.search_instruments(exchange='NFO',symbol='NIFTY')`
Instrument(exchange='NFO', token=62247, symbol='BANKNIFTY 01 APR21 27300.0 PE', name='', expiry=datetime.date(2021, 4, 1), lot_size='25')

Nifty future instrument is working well.

`alice.get_instrument_for_fno(symbol = 'NIFTY', expiry_date=datetime.date(2021, 3, 25), is_fut=False, strike=14500, is_CE = True)`
Instrument(exchange='NFO', token=43358, symbol='NIFTY MAR 14500.0 CE', name='', expiry=datetime.date(2021, 3, 25), lot_size='75')

How to get FnO nifty instrument in `alice.search_instrument( )`   ?

**Comment by krishnavelu** [comment]
What’s the difference between search instrument and get instrument?

**Comment by gbaalaji** [comment]
@krishnavelu 
Both search_instrument and get_instrument return the instrument as output.

while in `alice.search_instrument()`  I am searching for only nifty in NFO but in
`alice.search_instruments(exchange='NFO',symbol='NIFTY')` it gives all the instrument symbol contain nifty such as it gives instrument for BANKNIFTY, FINNIFTY and also NIFTY.

I am creating an option chain database for nifty. I can filter the Nifty option instrument from all search instrument.
Is there any other way to get ONLY nifty instruments directly from API that helps me to create a Nifty option chain?

**Comment by krishnavelu** [comment]
Just search and filter the unwanted once...
