### ISSUE TITLE
Dataframe Space issue - Just a question , this is not a issue

### ISSUE THREAD

**Issue by anshuljain2k8** [krishnavelu/alice_blue#180]
Hi,

I have somehow managed to create OHLC data from LTP provided by alice blue API. But problem is that, socket is opened continously and it sends data continously which im collecting in dataframe and then resampling it to create OHLC, but after sometime pandas dataframe size will be huge it will not be able to handle large data, does these dataframes occupy physical space in hard drives?  so what is the solution for that.

another question is that lets say i use SMA 20 , so after 20 candles i will start getting value of SMA , if there is a 15 min tf then i will get SMA values after 1-2 hours , till then if some signal comes it will be missed. what will be the solution for this kind of scenarios?

Please help me on this.

**Comment by sumit9926** [comment]
Sir multi threading can be solution for this

**Comment by krishnavelu** [comment]
Pandas is too inefficient. SMA, EMA works that way. Till there is no enough data, you won’t get any signals. Try to understand the basics of SMA, EMA and OHLC candlesticks.
