### ISSUE TITLE
Multiple Web Socket connections (inquiry) 

### ISSUE THREAD

**Issue by virafpatrawala** [krishnavelu/alice_blue#183]
How many parallel WebSocket connections are permitted using one API key?

I realize I can subscribe to multiple instruments with one open WebSocket, however, it'd be easier to have two separate codes with two separate open connections. Will creating separate access tokens for each of these codes help, or should I stick to one per day?

I'm hoping you'll have an idea, thanks a lot.

**Comment by krishnavelu** [comment]
You can have only one active token. Once you generate one more, the previous will be invalid.

**Comment by virafpatrawala** [comment]
Okay. So can I access the same token in multiple code files with multiple Websocket Connections? What is the limit on the number of these connections at the same time?

For reference: https://kite.trade/forum/discussion/2670/multiple-web-sockets

**Comment by krishnavelu** [comment]
I don’t know if you can open multiple websocket connections. You can try yourself. As the reply itself says its a wrong architecture. I also cannot think of why someone will need multiple websocket connections open for a single server. I won’t recommend. Try to stick to one.
