### ISSUE TITLE
How to combine two subscription data in a single row

### ISSUE THREAD

**Issue by dinesht15** [krishnavelu/alice_blue#184]
Hi,

I need full data for a instrument by combining two methods
LiveFeedType.MARKET_DATA  + LiveFeedType.FULL_SNAPQUOTE

or 
LiveFeedType.MARKET_DATA  + LiveFeedType.SNAPQUOTE

Is there any way I can get required data in a  single row.

I had tried to merge two dictionary but getting error 

def Merge(dict1, dict2): 
    return(dict2.update(dict1)) 

dict1 = alice.subscribe([alice.get_instrument_by_token('MCX', 219554),alice.get_instrument_by_token('MCX', 219553)], LiveFeedType.MARKET_DATA)

dict2 = alice.subscribe([alice.get_instrument_by_token('MCX', 219554),alice.get_instrument_by_token('MCX', 219553)], LiveFeedType.SNAPQUOTE)

message = Merge(dict1, dict2)

AttributeError                            Traceback (most recent call last)
<ipython-input-5-28dae1aebe4a> in <module>
    113 dict2 = alice.subscribe([alice.get_instrument_by_token('MCX', 219554),alice.get_instrument_by_token('MCX', 219553)], LiveFeedType.SNAPQUOTE)
    114 
--> 115 message = Merge(dict1, dict2)
    116 
    117 #message = AddDict(dict1, dict2)

<ipython-input-5-28dae1aebe4a> in Merge(dict1, dict2)
     20 
     21 def Merge(dict1, dict2):
---> 22     return(dict2.update(dict1))
     23 
     24 def AddDict(dict1, dict2):

AttributeError: 'NoneType' object has no attribute 'update'

**Comment by krishnavelu** [comment]
Read library’s document fully & learn python.

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue/tree/develop#read-this-before-creating-an-issue) before creating a new issue.

**Comment by dinesht15** [comment]
Hi Krishna,

I had already read the guidelines mentioned in the link and when I have not found any question related to this then only I had asked. I have read the library document but could not find any method which returns the complete data of both the subscriptions.(LiveFeedType.FULL_SNAPQUOTE and LiveFeedType.MARKET_DATA)

**Comment by krishnavelu** [comment]
If you have already read this [guidelines](https://github.com/krishnavelu/alice_blue/tree/develop#read-this-before-creating-an-issue), why didn't you follow 8, 9 & 10. I've clearly written what I'm expecting while creating an issue.

By the way you've written your code, itself says that you've not read the main document completely. When you think don't have time to read a well written document, don't try to waste others time.
