### ISSUE TITLE
Unable to get live market feeds

### ISSUE THREAD

**Issue by kalkanijayesh** [krishnavelu/alice_blue#187]
I have created test.py file and added python code according to the documentation. I have received an access token and tried to get an instrument. It works fine !!

`But the issue is when I have tried to get the live feed (market data) using the following syntax but I didn't get live data in the socket connection. I have run test.py file in the terminal. But it shows nothing then I need to press Ctrl+Z to terminate the script execution.(See below picture)`

![image](https://user-images.githubusercontent.com/10669746/91564841-de0fda80-e95e-11ea-974d-2dab75333862.png)

**Here is my code:**
```socket_opened = False
def event_handler_quote_update(message):
    print(f"quote update {message}")

def open_callback():
    global socket_opened
    socket_opened = True

alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
while(socket_opened==False):
    pass
alice.subscribe(alice.get_instrument_by_symbol('MCX', 'GOLDM SEP FUT'), LiveFeedType.MARKET_DATA)
sleep(10)
```

**Comment by krishnavelu** [comment]
Did you see what `alice.get_instrument_by_symbol('MCX', 'GOLDM SEP FUT')` returns? Is it returning an `Instrument`?
When you are trying for first time, why trying a complicated instrument. Try equity in NSE.

**Comment by rahulmr** [comment]
@krishnavelu  To me it purely seems to be problem with indentation. Since @kalkanijayesh has not shared code properly it is difficult to understand. I have given him gist link on telegram hope that helps.

**Comment by kalkanijayesh** [comment]
Hello @rahulmr, here is my complete code. Please take a look and let me know if you found any strange things.
![Screenshot 2020-08-29 at 1 26 32 PM](https://user-images.githubusercontent.com/10669746/91683518-74681a00-eb72-11ea-9b4b-ec6bd6bc3e2b.png)

**Comment by ravikumarengineer2000** [comment]
@kalkanijayesh can you add print statement before and after like:

```
print("waiting for web socket to open")
while(socket_opened==False):
    pass
print("web socket opened")
```

and see if web socket is opened , for me I am just stuck on this statement whole day.
@rahulmr suggestion is interesting , but I donwloaded complete fresh example code from readme and it is not working.
Earlier I had faced indentation related issue but I don't think this is because of that.

**Comment by krishnavelu** [comment]
@kalkanijayesh  Hope your problem is solved. Reopen if need.
