### ISSUE TITLE
Unable to get live CMP

### ISSUE THREAD

**Issue by anujsinha09** [krishnavelu/alice_blue#188]
I am getting error while extracting Live CMP stating  AttributeError: module 'websocket' has no attribute 'WebSocketApp'

![Code](https://user-images.githubusercontent.com/50544009/91694646-8ce42e80-eb8a-11ea-9395-3a0d0bc9211d.PNG)
![Error](https://user-images.githubusercontent.com/50544009/91694650-8eadf200-eb8a-11ea-97ed-6ce77364740f.PNG)

**Comment by syedasg** [comment]
Add this line 
"logging.basicConfig(level=logging.DEBUG) " and try to print and see where you are going wrong,may be it does find id,password

**Comment by krishnavelu** [comment]
@anujsinha09 hope your problem is solved. Reopen if needed.

**Comment by vishnubharath101** [comment]
Hi.

I'm facing a similar issue. My code was working fine but after some updates recently I'm getting the below error:

_module 'websocket' has no attribute 'WebSocketApp'_

I personally feel that there is some error  in the below lines of code:

_alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)

while not socket_opened:  # wait till socket open & then subscribe
    pass
alice.subscribe(scrip_data, LiveFeedType.MARKET_DATA)_
