### ISSUE TITLE
Websocket only working in IDLE or in spyder but not working VPS or in Comand Prompt 

### ISSUE THREAD

**Issue by ghost** [krishnavelu/alice_blue#190]
Here is  the code

`from alice_blue import *
from time import sleep

token = AliceBlue.login_and_get_access_token(username, password, twoFA, api_secret)

alice = AliceBlue(username, password, token, master_contracts_to_download=['NSE'])

socket_opened = False

def event_handler_quote_update(message):
    print(f"quote update {message}")

def open_callback():
    global socket_opened
    socket_opened = True

alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
while (socket_opened == False):
    pass
alice.subscribe(alice.get_instrument_by_symbol('NSE', 'AXISBANK'), LiveFeedType.COMPACT)
sleep(10)

I am getting the tick data while running it from IDLE but not working while running the same file through Command Prompt. Command Stops receiving data after 2-3 ticks.

**Comment by vijayraj-saaras** [comment]
ipython -i filename.py

**Comment by ghost** [comment]
-i flag for what?

**Comment by vijayraj-saaras** [comment]
Instead of Python exiting when the program is finished, you can use the -i flag to start an interactive session.

**Comment by ghost** [comment]
Thanks Sir

**Comment by ravikumarengineer2000** [comment]
Hello @vijayraj-saaras  I have issue with websocket can you help please I have created an issue

**Comment by ghost** [comment]
Thanks Sir For Helping Me
