### ISSUE TITLE
Hi, How can i exit/cancel a CO order ??

### ISSUE THREAD

**Issue by dharmaraj81** [krishnavelu/alice_blue#191]
Hi,
i have put a CO order with Market Type

its first leg has been completed _(ex order id is : 200902000261684 )_

Pending order id is (Second leg ) : 200902000261685

Now i want to exit / cancel the this trade, how can i do it

if i try **alice.cancel_order(PendingOrderID)**, it will give the result like following

{'status': 'success', 'message': '', 'data': {'status': 'Ok'}}

But its not exit 

Pls give a Solution for it, its very urgent @krishnavelu sir

Thanks
Dharma

**Comment by dharmaraj81** [comment]
hi @krishnavelu 

I have found the solution, anyway thank you 

Dharma

**Comment by krishnavelu** [comment]
Sorry I saw late.
