### ISSUE TITLE
How to get full data (OHLC+Order book) from API

### ISSUE THREAD

**Issue by dinesht15** [krishnavelu/alice_blue#192]
Hi,

I am trying to get full data from API. I can use the method "LiveFeedType.FULL_SNAPQUOTE" but it is useless since it does not contains any time information like exchange time stamp and ltt. If some one gives 10000 rows of FULL_SNAPQUOTE data then no conclusion can be drawn based on that because it is missing important part date and time.
Method "LiveFeedType.MARKET_DATA" provides 90% information but does not contains order book (depth) information
Method LiveFeedType.SNAPQUOTE proveds the depth information but in this I am missing market data information.

I had tried to combine these two method results into single dictionary but not able to get the desired result.

I have gone through the API document but could nto find a single method which can return the full data ie. OHLC + Order book

Other brokers(Zerodha/Upstock) API have methods to get OHLC + Order book data in a single method call? Do we have something similar  to that here in Alice Blue. I could not see any such methods in document so far.

If that is not possible then can some one can help me to correct the below code to achieve the desired result.

import datetime as datetime
import threading
CurrDate = datetime.datetime.now().date().strftime("%y-%d-%m")

count = 0
file_limit = 10000
size = 10000
h_no=1
j=1
filename = 'F:/AV Python tutorials/ST data/StockData_'+CurrDate
feed_status=datetime.datetime.now()

def toDtLocal(unix):
    timstamp = unix
    result = datetime.datetime.utcfromtimestamp(timstamp)
    result = result.replace(tzinfo=pytz.utc)
    result = result.astimezone(pytz.timezone('Asia/Kolkata'))
    result = result.strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]
    return result

socket_opened = False
def event_handler_quote_update(message):
    try:
        global count
        global file_limit
        global j
        global size
        global h_no
        if count > 100:
            return
        
        count+=1
        print("collating...",count)
        
    
        #print(message)

        # Data headers
        header = ['exchange','buyers','bid_prices','bid_quantities','ltp','ltq','best_ask_price','best_bid_price','best_ask_quantity','best_bid_quantity','open','close','high','low','total_buy_quantity','total_sell_quantity','volume','yearly_high','yearly_low','exchange_time_stamp','ltt']
        
        # Extracting header data
        myData = {x:message[x] for x in header}

        # More date: Inside Instrument
        extra = ['symbol','name']
        header += extra

        # Extracting Instrument data
        for x in extra:
            myData[x] = message['instrument'].__getattribute__(x)

        # More date: Calculated data
        #calc = ['receive_time','delay_in_ms']
        
        # Converting timestamp to datetime.datetime -> IST
        myData['exchange_time_stamp'] = toDtLocal(myData['exchange_time_stamp'])
        myData['ltt'] = toDtLocal(myData['ltt'])
        myData['receive_time'] = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]
        myData['delay_in_ms'] = ''
        
     
        # Openining file to save
        
        write_header = False
     
        if (count == h_no):
            h_no+=size
            write_header = True
        globals()['df'+str(j)] = pd.DataFrame(columns=header)
        globals()['df'+str(j)] = globals()['df'+str(j)].append(myData, ignore_index = True)
        globals()['df'+str(j)].to_csv(filename+str(j)+'.csv',mode= 'a', header = write_header)
        
       
    
        #Upper limit check
        if count == file_limit:
            j+=1
            file_limit+=size
   
    except Exception as e:
        traceback.print_exc()
        input(e)

def open_callback():
    global socket_opened
    socket_opened = True

if not socket_opened:
    alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
    while(socket_opened==False):
        pass
threading.Thread(target=feed_check).start()

nsewatch = ['Nifty 50','India VIX','HINDALCO','ACC','NTPC','APOLLOHOSP','AMBUJACEM','BANDHANBNK','BEL','FEDERALBNK','BPCL']
bsewatch = ['500440','500410','532555','500520','130270468','128108804','138535172','128012548','128120068','128140036']

alice.subscribe([alice.get_instrument_by_symbol('BSE', 'SENSEX')], LiveFeedType.MARKET_DATA)
for i in nsewatch:
    alice.subscribe([alice.get_instrument_by_symbol('NSE', i)], LiveFeedType.MARKET_DATA)
    alice.subscribe([alice.get_instrument_by_symbol('NSE', i)], LiveFeedType.SNAPQUOTE)
    
for j in bsewatch:
    alice.subscribe([alice.get_instrument_by_token('BSE', j)], LiveFeedType.MARKET_DATA)
    alice.subscribe([alice.get_instrument_by_token('BSE', j)], LiveFeedType.SNAPQUOTE)
                     
if (datetime.datetime.now().time() > datetime.time(hour=15,minute=30,second=01)):
    nsewatch = ['Nifty 50','India VIX','HINDALCO','ACC','NTPC','APOLLOHOSP','AMBUJACEM','BANDHANBNK','BEL','FEDERALBNK','BPCL']
    bsewatch = ['500440','500410','532555','500520','130270468','128108804','138535172','128012548','128120068','128140036']
#alice.subscribe([alice.get_instrument_by_token('MCX', 219554),alice.get_instrument_by_token('MCX', 219553)], LiveFeedType.MARKET_DATA)
    alice.unsubscribe([alice.get_instrument_by_symbol('BSE', 'SENSEX')], LiveFeedType.MARKET_DATA)
    for i in nsewatch:
        alice.unsubscribe([alice.get_instrument_by_symbol('NSE', i)], LiveFeedType.MARKET_DATA)
        alice.unsubscribe([alice.get_instrument_by_symbol('NSE', i)], LiveFeedType.SNAPQUOTE)
    
    for j in bsewatch:
        alice.unsubscribe([alice.get_instrument_by_token('BSE', j)], LiveFeedType.MARKET_DATA)
        alice.unsubscribe([alice.get_instrument_by_token('BSE', j)], LiveFeedType.SNAPQUOTE)

**Comment by krishnavelu** [comment]
Alice doesn’t provide historical data

**Comment by dinesht15** [comment]
Hi @krishnavelu 

I am not looking historical data. I am trying to store complete one day (9:00 AM to 3;30 PM) live data for few selected stocks on my computer. I am not looking past data.

I am looking only current day live data for OHLC and Order book in a single row.

All other API providers have methods to get this data in one call, but I have not seen any method in Alice Blue which can provide me this data.

Thanks & regards
Dinesh Tiwari

**Comment by krishnavelu** [comment]
You get live data, create OHLC from live data.

**Comment by dinesht15** [comment]
@krishnavelu 

I think I have mentioned above that I am getting OHLC data from 
Method "LiveFeedType.MARKET_DATA" provides 90% information but does not contains order book (depth) information
and 
Method LiveFeedType.SNAPQUOTE provides the depth information but in this I am missing market data information.

I can easily extract OHLC form LiveFeedType.MARKET_DATA method and I am getting it.
Also I am getting order book values from LiveFeedType.SNAPQUOTE 

But I am getting issue when I am combining them into one row. Below is my code. Here I am trying store live data (OHLC+Orderbook) for my analysis.

Usually this information is available in other brokers API in single method call. But I can not find anything in Alice blue which gives this combined data by calling method from Alice API.
So I have written below code. Which is working fine with one instrument. But when I am trying to add multiple instruments in subscribe it is not bale to find the correct pairs.

def checkKey(dict, key): 
      
    if key in dict.keys(): 
        return 1
    else: 
        return 0 
 

def obdata(message):
    try:
       
        m1 = message
    
        #print(m1)

        # Data headers readily available
        header = ['exchange','token','buyers', 'bid_prices', 'bid_quantities', 'sellers', 'ask_prices', 'ask_quantities','exchange_time_stamp']

        # Extracting header data
        myData = {x:m1[x] for x in header}

        # More date: Inside Instrument
        extra = ['join_key']
        header += extra

        # Converting timestamp to datetime.datetime -> IST
        myData['join_key'] = str(myData['exchange']) +''+ str(myData['token']) +''+ str(myData['exchange_time_stamp'])
    
        return(myData)
        
    except Exception as e:
        import traceback
        traceback.print_exc()
        input(e) 
        
def ohlcdata(message):
    try:
        m1 = message
       
        # Data headers readily available
        header = ['exchange','token','ltp','ltt','ltq','volume', 'best_bid_price', 'best_bid_quantity','best_ask_price', 'best_ask_quantity', 'total_buy_quantity', 'total_sell_quantity', 'atp', 'exchange_time_stamp', 'open', 'high', 'low', 'close', 'yearly_high', 'yearly_low']

        # Extracting header data
        myData = {x:m1[x] for x in header}

        # More date: Inside Instrument
        extra = ['join_key']
        header += extra

        # Converting timestamp to datetime.datetime -> IST
        myData['join_key'] = str(myData['exchange']) +''+ str(myData['token']) +''+ str(myData['exchange_time_stamp'])
    
        return(myData)
        
    except Exception as e:
        import traceback
        traceback.print_exc()
        input(e)

def mergeDict(d1,d2):
    d3 = dict(d1)
    d3.update(d2)
    for i, j in d1.items():
        for x, y in d2.items():
            if i == x:
                d3[i]=(j)
    return(d3)

ohlc = pd.DataFrame()
ob = pd.DataFrame()
    
socket_opened = False
def event_handler_quote_update(message):
    global count
    msg = {}
    msg = message
    key = 'buyers'
    #if count > 2:
     #   return
    
    #count+=1 
    if (checkKey(message,key)):
        ob = obdata(msg)
        
    else:
        ohlc = ohlcdata(msg)
    
    #combine both data
    finalmsg = mergeDict(ohlc,ob)
    print(finalmsg)
    

def open_callback():
    global socket_opened
    socket_opened = True

alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
while(socket_opened==False):
    pass

alice.subscribe([alice.get_instrument_by_symbol('NSE', 'ACC')], LiveFeedType.MARKET_DATA)
alice.subscribe([alice.get_instrument_by_symbol('NSE', 'ACC')], LiveFeedType.SNAPQUOTE)

time.sleep(1)

alice.unsubscribe([alice.get_instrument_by_symbol('NSE', 'ACC')], LiveFeedType.MARKET_DATA)
alice.unsubscribe([alice.get_instrument_by_symbol('NSE', 'ACC')], LiveFeedType.SNAPQUOTE)

**Comment by krishnavelu** [comment]
You get what the alice server provides. If you want something special contact alice.

**Comment by dinesht15** [comment]
How to contact Alice? I do not have idea. Can you please tell

**Comment by krishnavelu** [comment]
Instead of asking here and waiting for reply, if you would've done a little google search, you might've got the answer long before.

**Comment by dinesht15** [comment]
I am sorry to asking questions. I though that you are representing Alice blue API team here. So just asked. But now it's clear to me.
Thanks

**Comment by moganraj** [comment]
@dinesht15 Hi Sir, It would be very helpful if you share you experience how did you resolve the issue. I am planning to get 15min and 30min candle for 1 hour after market start. I am having some decimal errors for ohlc.

**Comment by AllenRobinHubert** [comment]
@moganraj Hi, Alice doesn't provide historical data, I'm trying to do the same using [NSEpy](https://nsepy.xyz/). I suggest you do your analysis based on NSEpy History feed and based on that result pass the buy/sell signal to Alice API. Its how i would do it. 
If you want OHLC, i suggest you refer to @krishnavelu comment [here](https://github.com/krishnavelu/alice_blue/issues/26#issuecomment-564532198)

**Comment by dinesht15** [comment]
@moganraj 

Can you please share your code to see where you are getting issues.

Thanks
Dinesh

**Comment by moganraj** [comment]
@Byuzki Thank you, I will try with NSEpy.

@dinesht15 Kindly find my piece of code used to fetch OHLC

candle_OHCL_Exchange_Start_Time = "09:15:00"
candle_OHCL_Exchange_End_Time = "09:20:00"

if candle_OHCL_Exchange_Start_Time < Exchange_ts <= candle_OHCL_Exchange_End_Time:
            if float(fl_ltp) > 0 and str_symbol == alice_Symb:
                lst_back.insert(backup_cnt, fl_ltp)
                print("Exchange_ts: {}; str_symbol: {}; LTP: {}".format(Exchange_ts, str_symbol, fl_ltp))
                backup_cnt += 1

    open_Back = lst_back[0]
    high_Back = max(lst_back)
    low_Back = min(lst_back)
    close_Back = lst_back[-1]
    print("OHLC: O -> {}; H -> {}; L -> {}; C -> {}".format(open_Back, high_Back, low_Back, close_Back))

**Comment by arjuneshm** [comment]
@dinesht15 : I am trying to get the ltp and bid ask spread together. But i am struggling to subscribe to both MARKET_DATA and FULL_SNAPQUOTE . If you have any slution by now, would be great if you can share with us.
