### ISSUE TITLE
Basket order returns no order id(s)

### ISSUE THREAD

**Issue by virafpatrawala** [krishnavelu/alice_blue#193]
Compared to a normal order, a basket order does not return order id(s). Is there a workaround for this? Can this be implemented in the API as well?

**Comment by supremekale** [comment]
Hi sir!
i recently taken alice api i want data feed we r unable get live data feed can you pls guide me for work code well, as i am writing code this way for getting live data feed, but we dont get any out put only program is running

socket_opened = False
def event_handler_quote_update(message):
    print(f"quote update {message}")

def open_callback():
    global socket_opened
    socket_opened = True

alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
while(socket_opened==False):
    pass
alice.subscribe(alice.get_instrument_by_symbol('NSE', 'ONGC'), LiveFeedType.MARKET_DATA)

**Comment by krishnavelu** [comment]
@virafpatrawala it cannot be provided unless alice-blue implements it.

@supremekale Read the document fully and try out the example code first.

**Comment by virafpatrawala** [comment]
@krishnavelu understood. Any workarounds that you can recommend?

**Comment by krishnavelu** [comment]
Get order ids from order history.
