### ISSUE TITLE
How to calculate VWAP from output data, can you pls add VWAP in output, its useful data.

### ISSUE THREAD

**Issue by nobody31985** [krishnavelu/alice_blue#194]
How to calculate VWAP from output data, can you pls add VWAP in output, its useful data.

quote update {'exchange': 'NFO', 'token': 95733, 'ltp': 21302.0, 'ltt': 1592646746, 'ltq': 20, 'volume': 40, 'best_bid_price': 21302.0, 'best_bid_quantity': 2020, 'best_ask_price': 0.0, 'best_ask_quantity': 0, 'total_buy_quantity': 2060, 'total_sell_quantity': 0, 'atp': 21302.0, 'exchange_time_stamp': 1592647085, 'open': 21302.0, 'high': 21302.0, 'low': 21302.0, 'close': 21308.85, 'yearly_high': 21302.0, 'yearly_low': 0.0, 'instrument': Instrument(exchange='NFO', token=95733, symbol='BANKNIFTY JUN FUT', name='', expiry=datetime.date(2020, 6, 25), lot_size='20')}

**Comment by krishnavelu** [comment]
atp is vwap.
