### ISSUE TITLE
Modify order is not working for MCX for delivery.

### ISSUE THREAD

**Issue by jaydave1988** [krishnavelu/alice_blue#196]
Modify order is not working for MCX for delivery.

` elif(product_type == ProductType.Delivery):
            if(instrument.exchange == 'NFO'):
                product_type = 'NRML'
            else:
                product_type = 'CNC'`

You should add product_type as NRML for MCX and CDS too.

**Comment by ravikumarengineer2000** [comment]
hi @jaydave1988 , is live feed data working for you ?

**Comment by jaydave1988** [comment]
> hi @jaydave1988 , is live feed data working for you ?

Hi @ravikumarengineer2000  I have not tried that today, but it was working before 2 days.

**Comment by krishnavelu** [comment]
@jaydave1988 fixed in develop. Please test it.

**Comment by krishnavelu** [comment]
@jaydave1988 Is this issue good to close?
