### ISSUE TITLE
what are the Different states of an order as it goes through the alice blue?

### ISSUE THREAD

**Issue by adityarudrawar** [krishnavelu/alice_blue#198]
I want to know the different/all 'order_status' for different orders type like Regular, AMO, CO, BO.

for Example. when an AMO is requested it goes in the pending order and the order_status  in get_order_history gives 'after market order req received' and when you cancel an AMO order it goes in completed orders and the 'order_status' is 'cancelled after market order'.

I want to know this status of different orders with the exact format of it, I wasn't able to find them on the internet.

**Comment by krishnavelu** [comment]
The only status which are important are 

- open
- rejected
- cancelled
- completed

So look for only those.
