### ISSUE TITLE
Error on unstable internet connectivity: socket is already closed

### ISSUE THREAD

**Issue by Parva14** [krishnavelu/alice_blue#20]
Run an ltp printing code and turn off your internet, connect the net again after 10 seconds and you should be able to replicate the error.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\I BALL\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\I BALL\Anaconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\I BALL\Anaconda3\lib\site-packages\alice_blue\alice_blue.py", line 358, in __send_heartbeat
    self.__websocket.send(json.dumps(heart_beat), opcode = websocket._abnf.ABNF.OPCODE_PING)
  File "C:\Users\I BALL\Anaconda3\lib\site-packages\websocket\_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "C:\Users\I BALL\Anaconda3\lib\site-packages\websocket\_core.py", line 253, in send
    return self.send_frame(frame)
  File "C:\Users\I BALL\Anaconda3\lib\site-packages\websocket\_core.py", line 278, in send_frame
    l = self._send(data)
  File "C:\Users\I BALL\Anaconda3\lib\site-packages\websocket\_core.py", line 448, in _send
    return send(self.sock, data)
  File "C:\Users\I BALL\Anaconda3\lib\site-packages\websocket\_socket.py", line 135, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.

**Comment by krishnavelu** [comment]
Which version are you using? Some improvements are checked in recently related to ping. Refer #17 
This is not yet released and still in develop.

**Comment by Parva14** [comment]
pip show alice_blue

Name: alice-blue
Version: 0.0.5
Summary: Python library for Alice Blue APIs
Home-page: https://github.com/krishnavelu/alice_blue
Author: Krishna Velu
Author-email: krishnajvelu@gmail.com
License: UNKNOWN
Location: c:\users\i ball\anaconda3\lib\site-packages
Requires: bs4, websocket-client, requests, protlib
Required-by:

I will test the same using develop branch and let you know the results!

**Comment by krishnavelu** [comment]
@Parva14 is the issue solved for you? Going to close this.

**Comment by Parva14** [comment]
@krishnavelu not able to test with develop branch, are you merging it with the master branch?

**Comment by krishnavelu** [comment]
What problem you are facing in installing develop branch?

**Comment by krishnavelu** [comment]
@Parva14 is this issue solved? I'm closing this.

**Comment by Parva14** [comment]
Tried with the develop branch, just doesn't print the error but it is still not able to continue with the while loop after reconnection

**Comment by krishnavelu** [comment]
Can you describe the problem exactly? With some error logs to reproduce.
Is your internet connection stable?
FYI: I’m using this everyday without any problems.

**Comment by Parva14** [comment]
@krishnavelu  there was a problem with my internet connection, sorted now. sorry for the trouble.

**Comment by raakeshtomarnew** [comment]
Sir
there is problem in web socket 1st time extract right data bat after some time
ltp not update properly pls advice me.
