### ISSUE TITLE
Cancel Order Not Working

### ISSUE THREAD

**Issue by VikramBangre** [krishnavelu/alice_blue#200]
Hi,

Placing orders Buy/ Sell works perfectly, but when I try to cancel the Order it will get executed but order will be still active in Alice Blue. So I have to manually cancel the Order again.

Buy Order Output:
`{'status': 'success', 'message': 'Order placed successfully', 'data': {'oms_order_id': '2009xxxxxxxxx'}}`

Cancel Order also says successful
`{'status': 'success', 'message': '', 'data': {'status': 'Ok'}}`

Code:
`order_status = alice.cancel_order('2009xxxxxxxxx')`

Please help.

Regards,
Vikram

**Comment by VikramBangre** [comment]
I got the issue. When I place the CO Buy order what I get is OMS Order ID of Buy order.

Sell OMS Order ID is different.

So how do I get the Sell OMS Order ID ?

**Comment by VikramBangre** [comment]
I was able to get the Sell OMS Order ID for my CO Buy Order. But below code is exiting the order.

`order_status = alice.cancel_order('2009xxxxxxxxx')`

Please help

**Comment by krishnavelu** [comment]
Cancel order has leg_order_id and is_CO arguments. Try [that](https://github.com/krishnavelu/alice_blue/blob/master/alice_blue/alice_blue.py#L692).

**Comment by VikramBangre** [comment]
ok. will try that.

Does `alice.cancel_all_orders()` exit all pending orders ? i.e. If I Place BUY CO Order, then their will be SELL LIMIT Order pending. Will it exit SELL LIMIT Order ?

**Comment by krishnavelu** [comment]
Yes

**Comment by VikramBangre** [comment]
After placing BUY CO Order, "Pending Order" is empty and "alice.cancel_all_orders()" is not working due to this. SELL order is under "completed_orders". 

Below "Order History" was taken after placing the BUY CO Order. Please advice.

```
{'status': 'success', 'message': '', 'data': 

{'pending_orders': [], 

'completed_orders': [{'validity': 'DAY', 'user_order_id': '1', 'trigger_price': 23188.0, 'transaction_type': 'BUY', 'trading_symbol': 'BANKNIFTY20OCTFUT', 'remaining_quantity': 50, 'rejection_reason': '--', 'quantity': 50, 'product': 'CO', 'price': 0.0, 'order_type': 'MARKET', 'order_tag': 'order1', 'order_status': 'open pending', 'order_entry_time': xxxx, 'oms_order_id': 'xxxx', 'nest_request_id': '1', 'lotsize': 25, 'login_id': 'xxxx', 'leg_order_indicator': '', 'instrument_token': '50836', 'filled_quantity': 0, 'exchange_time': 0, 'exchange_order_id': 'NA', 'exchange': 'NFO', 'disclosed_quantity': 0, 'client_id': 'xxxx', 'average_price': 0.0}, 

{'validity': 'DAY', 'user_order_id': '1', 'trigger_price': 23188.0, 'transaction_type': 'SELL', 'trading_symbol': 'BANKNIFTY20OCTFUT', 'remaining_quantity': 50, 'rejection_reason': '--', 'quantity': 50, 'product': 'CO', 'price': 0.0, 'order_type': 'SL-M', 'order_tag': '', 'order_status': 'open pending', 'order_entry_time': xxxx, 'oms_order_id': 'xxxx', 'nest_request_id': '1', 'lotsize': 25, 'login_id': 'xxxx', 'leg_order_indicator': 'xxxx', 'instrument_token': '50836', 'filled_quantity': 0, 'exchange_time': 0, 'exchange_order_id': 'NA', 'exchange': 'NFO', 'disclosed_quantity': 0, 'client_id': 'xxxx', 'average_price': 0.0}]}}
```
