### ISSUE TITLE
Having API Login Error on New Accounts (Not starting with AB Ones)

### ISSUE THREAD

**Issue by Pavan-Jadhav** [krishnavelu/alice_blue#202]
Hi Team,

I'm having weird issues while logging through API where UserID which is only in Numeric throwing following errors:

OAuth 2.0 Error occurred. Please verify your api_secret
Check details for user =>1XXXXX.0 .No access token generated

And

Couldn't get access token {'error': 'invalid_grant', 'error_description': 'The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client', 'status_code': 400}

Please let me know how can I fix this ASAP.

**Comment by jaydave1988** [comment]
You are reading user =>1XXXXX.0 It is float. It should be string without .0

**Comment by Pavan-Jadhav** [comment]
Thank you so much Sir -- Issue Resolved.
