### ISSUE TITLE
Getting the access token

### ISSUE THREAD

**Issue by dhananjayayit** [krishnavelu/alice_blue#203]
Hi,

Thank you for this api, made my life easier for sure.  The issue I am raising is not with this api but with my implementation in java

I am trying to develop same in java, since my algo application in java. I completed most of it but stuck at one place, i.e getting the access token

The following line in python I am not able to get output in java

 resp = r.post(url,auth=(app_id, api_secret),data=params)

The request and response which I have in java is below

request : Request{method=POST, url=https://ant.aliceblueonline.com/oauth2/token?client_id=xxx&client_secret=xxx&grant_type=authorization_code&code=41O0DZ4VBC_1pTSJfDo38zOMLFjQQ_pCKID7q3heKXw.vMADqfxOwYwtPflguyMEVIwq6ZEg_vyD46D5LGHxX7g&redirect_uri=https://ant.aliceblueonline.com/plugin/callback&authorization_response=https://ant.aliceblueonline.com/plugin/callback/?code=41O0DZ4VBC_1pTSJfDo38zOMLFjQQ_pCKID7q3heKXw.vMADqfxOwYwtPflguyMEVIwq6ZEg_vyD46D5LGHxX7g&scope=&state=test_state, headers=[Content-Type:application/json, Cache-Control:no-cache]}

resp:  {"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed","error_hint":"The \"redirect_uri\" from this request does not match the one from the authorize request.","status_code":400}

My java code for the same is below

params = new HashMap<>();
params.put("code", code);
params.put("redirect_uri", response.url().toString());
params.put("grant_type", "authorization_code");
params.put("client_secret", secret);
params.put("cliend_id", clientid);

String ur = String.format("https://ant.aliceblueonline.com/oauth2/token?client_id=xxx&client_secret=xxx&grant_type=authorization_code&code=" + code + "&redirect_uri=" + callbackURL + "&authorization_response=%s", response.url());

String bodyString = new JSONObject(params).toString();  

OkHttpClient client = new OkHttpClient.Builder().connectTimeout(30, TimeUnit.SECONDS)
                    .writeTimeout(30, TimeUnit.SECONDS).readTimeout(30, TimeUnit.SECONDS)
                    .addInterceptor(new Interceptor() {
                        @Override
                        public okhttp3.Response intercept(Chain chain) throws IOException {
                            Request request = (chain.request().newBuilder().header("Authorization",
                                    okhttp3.Credentials.basic(clientid, secret))
                                    .build());
                            return chain.proceed(request);
                        }
                    }).build();

            okhttp3.MediaType mediaType = okhttp3.MediaType.parse("application/json");
            System.err.println(bodyString + "  new JSONObject(params).toString()");
//            RequestBody body = RequestBody.create(mediaType, bodyString); // same error as above
            okhttp3.RequestBody formBody = new okhttp3.FormBody.Builder()
                    .add("code", code)
                    .add("redirect_uri", response.url().toString())
                    .add("grant_type", "authorization_code")
                    .add("client_secret", secret)
                    .add("cliend_id", clientid)
                    .build();

            Request request = new Request.Builder().url(ur).post(formBody)
                    .addHeader("Content-Type", "application/json").addHeader("Cache-Control", "no-cache")
                    .build();
            okhttp3.Response respnse = null;
            try {
                System.err.println("request : " + request.toString());
                respnse = client.newCall(request).execute();

                String resp = respnse.body().string();

                System.err.println("resp " + resp);

            } catch (Exception e) {
                e.printStackTrace();
            }

Spent a few days on it, but couldnt crack it. Any pointers will be great. Thanks

**Comment by krishnavelu** [comment]
`The "redirect_uri" from this request does not match`
Give the correct redirect_url

**Comment by dhananjayayit** [comment]
Thanks Krishna .. got this thing done.

This was the final code in Java if someone wants to use it

                  OkHttpClient client = new OkHttpClient.Builder().connectTimeout(30, TimeUnit.SECONDS)
                    .writeTimeout(30, TimeUnit.SECONDS).readTimeout(30, TimeUnit.SECONDS)
                    .addInterceptor(new Interceptor() {
                        @Override
                        public okhttp3.Response intercept(Chain chain) throws IOException {
                            Request request = (chain.request().newBuilder().header("Authorization",
                                    okhttp3.Credentials.basic(clientid, secret))
                                    .build());
                            return chain.proceed(request);
                        }
                    }).build();

          
            okhttp3.RequestBody formBody = new okhttp3.FormBody.Builder()
                    .add("grant_type", "authorization_code")
                    .add("code", code)
                    .add("client_secret", secret)
                    .add("cliend_id", clientid)
                    .add("redirect_uri", callbackURL)
                    .build();
            
            ur = "https://ant.aliceblueonline.com/oauth2/token";
            Request request = new Request.Builder().url(ur).post(formBody)
                    .addHeader("Content-Type", "application/x-www-form-urlencoded")
                    .build();
            okhttp3.Response respnse = null;
            try {
                
                respnse = client.newCall(request).execute();
		String resp = respnse.body().string();
                JsonParser parser = new JsonParser();
                JsonObject tdObject = (JsonObject) parser.parse(resp);
                String token = tdObject.get("access_token").getAsString();    
                System.err.println("token " + token);
