### ISSUE TITLE
Bulk Orders Placing Incompletely or Getting Cloudflare Temporary Ban Error Sometimes.

### ISSUE THREAD

**Issue by Pavan-Jadhav** [krishnavelu/alice_blue#204]
Hello Sir, 

**In the morning, all 44 accounts got placed with Order but after 2 PM - Got Following Error:**

- What I did was: Split file in 2 and Ran 2 instances and placed order at same time.

`<title>Access denied | ant.aliceblueonline.com used Cloudflare to restrict access</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<script src="/cdn-cgi/apps/head/j5Zlzx6_OOKPw7hBySdF8kfQh-U.js"></script><link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" type="text/css" media="screen,projection" />

</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error hidden" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="p-0">
      <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-15 antialiased">
         <h1 class="inline-block md:block mr-2 md:mb-2 font-light text-60 md:text-3xl text-black-dark leading-tight">
           <span data-translate="error">Error</span>
           <span>1015</span>
         </h1>
         <span class="inline-block md:block heading-ray-id font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 5db5279eef9e2e4c &bull;</span>
         <span class="inline-block md:block heading-ray-id font-mono text-15 lg:text-sm lg:leading-relaxed">2020-10-01 09:28:39 UTC</span>
        <h2 class="text-gray-600 leading-1.3 text-3xl lg:text-2xl font-light">You are being rate limited</h2>
      </header>

      <section class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
          <div id="what-happened-section" class="w-1/2 md:w-full">
            <h2 class="text-3xl leading-tight font-normal mb-4 text-black-dark antialiased" data-translate="what_happened">What happened?</h2>
            <p>The owner of this website (ant.aliceblueonline.com) has banned you temporarily from accessing this website.</p>

          </div>
      </section>

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">5db5279eef9e2e4c</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: XXXXXXXXXXXXXX</span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
</div>
    </div>
  </div>

  <script type="text/javascript">
  window._cf_translation = {};
</script>
</body>
</html>
`

**Although, after that I merged both files to one and placed Sample MIS order by RMS Sq.off time and it got Rejected by 23 Accounts from 44 and Remaining Orders were not placed / rejected on the account as I have Count of 23 Orders in Log File.**

So, What can be the issue so far? 

- I want to place same order for multiple orders as Account Handling Concept. 
- Please let me know Alice Blue API limitations in terms of the No. of connections handling and When it temporary bans the API
- Any way or what you suggest on this.

And Thank you in advance for the support 👍

**Comment by krishnavelu** [comment]
Cloud fare issue is nothing to do with alice or this library.
Alice has no rate limit as of now I know.
Know the limitations of cloud fare & play within that limit.
