### ISSUE TITLE
Websocket not opening for live feed subscription

### ISSUE THREAD

**Issue by Naveenchandra07** [krishnavelu/alice_blue#205]
Hi Sir, I facing a problem while trying to subscribe for live feed of data for INFY stock from NSE. I tried the sample code provided by you, but the socket is not opening. I am waited for more than 10 minutes before terminating the application. Below is the code and log

Code Snippet Starts
----------------------
ins_scrip = alice.get_instrument_by_symbol('NSE', 'INFY')
print(ins_scrip)
    
socket_opened = False
print('Before Socket Start')
alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
print('Before Socket Open')
while(socket_opened==False):    # wait till socket open & then subscribe
    pass
print('Socket Open Successful')
alice.subscribe(ins_scrip, LiveFeedType.COMPACT)
---------------------
Code Snippet ends

Logs Starts
------------
Instrument(exchange='NSE', token=1594, symbol='INFY', name='INFOSYS LIMITED', expiry=None, lot_size=None)
Before Socket Start
Before Socket Open
------------
Log Ends

**Comment by krishnavelu** [comment]
Follow the example code exactly. It works.

**Comment by Naveenchandra07** [comment]
I am sorry, I was having some bad day with alice blue creds or my net or dono what it was. Today it is working fine, I am able to subscribe. We can close this ticket. 

Thank You for all the great work!
