### ISSUE TITLE
How to listen for access token refresh

### ISSUE THREAD

**Issue by be-thomas** [krishnavelu/alice_blue#207]
I need to run this on a server. so it is going to run continuously for a long time.
The access token expires after 24hrs. is there a way to trigger re-login, when access token expires.

**Comment by krishnavelu** [comment]
Start the script at 9:00 end the script after market close.

**Comment by be-thomas** [comment]
Thanks, also one quick question :-

Is there any API to check if today is a trading day or not?

**Comment by krishnavelu** [comment]
No
