### ISSUE TITLE
Getting BrokenPipeError: [Errno 32] Broken pipe exception after few hour of run.

### ISSUE THREAD

**Issue by dibyajyotidash** [krishnavelu/alice_blue#209]
ISSUE:
**Getting exception broken pipe 3 to 4 times a day ,dont have any idea what is the issue , Any help on this.
Api : python3.8 aliceblue**

def open_callback():
    global socket_opened
    socket_opened = True

def strategy(alice,user_id):
    try:
        ConfigGlobal.alice_obj = alice

        ConfigGlobal.instrument = alice.get_instrument_by_symbol(str(ConfigGlobal.lstrategy[0]["EXCHANGE"]),
                                                                     str(ConfigGlobal.lstrategy[0]["SYMBOL"]))
        logger("Function: start_websocket()")
        alice.start_websocket(subscribe_callback=event_handler_quote_update,
                              socket_open_callback=open_callback,
                              run_in_background=True)

        while(socket_opened==False):
             pass
        alice.subscribe(ConfigGlobal.instrument, LiveFeedType.COMPACT)
        logger("Function: Subscribe()")
        sleep(10)

        while True:
            if not socket_opened:
                pass
    except BrokenPipeError:
           pass
    except Exception as e:
        logger("Function: strategy , Exception :" + str(e))

*********************************************************************************
Oct 21 15:13:07 Exception in thread Thread-1:
Oct 21 15:13:07 Traceback (most recent call last):
Oct 21 15:13:07   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Oct 21 15:13:07     self.run()
Oct 21 15:13:07   File "/usr/lib/python3.8/threading.py", line 870, in run
Oct 21 15:13:07     self._target(*self._args, **self._kwargs)
Oct 21 15:13:07   File "/home/dib/.local/lib/python3.8/site-packages/alice_blue/alice_blue.py", line 389, in __send_heartbeat
Oct 21 15:13:07     self.__ws_send(json.dumps(heart_beat), opcode = websocket._abnf.ABNF.OPCODE_PING)
Oct 21 15:13:07   File "/home/dib/.local/lib/python3.8/site-packages/alice_blue/alice_blue.py", line 403, in __ws_send
Oct 21 15:13:07     ret = self.__websocket.send(*args, **kwargs)
Oct 21 15:13:07   File "/home/dibya/.local/lib/python3.8/site-packages/websocket/_app.py", line 154, in send
Oct 21 15:13:07     if not self.sock or self.sock.send(data, opcode) == 0:
Oct 21 15:13:07   File "/home/dib/.local/lib/python3.8/site-packages/websocket/_core.py", line 253, in send
Oct 21 15:13:07     return self.send_frame(frame)
Oct 21 15:13:07   File "/home/dib/.local/lib/python3.8/site-packages/websocket/_core.py", line 279, in send_frame
Oct 21 15:13:07     l = self._send(data)
Oct 21 15:13:07   File "/home/dib/.local/lib/python3.8/site-packages/websocket/_core.py", line 449, in _send
Oct 21 15:13:07     return send(self.sock, data)
Oct 21 15:13:07   File "/home/dib/.local/lib/python3.8/site-packages/websocket/_socket.py", line 157, in send
Oct 21 15:13:07     return _send()
Oct 21 15:13:07   File "/home/dib/.local/lib/python3.8/site-packages/websocket/_socket.py", line 139, in _send
Oct 21 15:13:07     return sock.send(data)
Oct 21 15:13:07   File "/usr/lib/python3.8/ssl.py", line 1173, in send
Oct 21 15:13:07     return self._sslobj.write(data)
Oct 21 15:13:07 BrokenPipeError: [Errno 32] Broken pipe

**Comment by krishnavelu** [comment]
Check if your internet connection is stable. move to VPS for a stable internet connection.

**Comment by krishnavelu** [comment]
Closing this. Hope your problem is solved.
