### ISSUE TITLE
Unable to close websocket manually

### ISSUE THREAD

**Issue by SurajDonthi** [krishnavelu/alice_blue#21]
Hi @krishnavelu,

I'm unable to close the websocket object once I unsubscribe the instrument. I had been prototyping in jupyter notebook and see that the websocket does not close once subscribed.

How can I manually close it?

**Comment by krishnavelu** [comment]
I never bothered to close the websocket manually.
Once you exit your python program websocket will get closed in the background.

**Comment by SurajDonthi** [comment]
So is it possible to expose it? It would be extremely helpful for prototyping.

Even if not, can you please point out where I can quickly modify so that I can close the connection. It will be really helpful.

Thanks.

**Comment by krishnavelu** [comment]
What you want me to expose?
Didn’t get you...

**Comment by SurajDonthi** [comment]
Expose the websocket object so that I can manually close it.

**Comment by krishnavelu** [comment]
You can access websocket object using this `alice._AliceBlue__websocket`
`alice` is your AliceBlue object. It has a private object `__websocket`.
