### ISSUE TITLE
15-17% data loss from Alice Blue API

### ISSUE THREAD

**Issue by be-thomas** [krishnavelu/alice_blue#210]
Im running a loop which consists of 1 second sleep, and then bulk insert to database using SQLAlchemy.

However, I dont know whether websockets stop while Querying database. I think atleast the OS must been keeping the messages buffered. Because its TCP, I suppose? In 2020 UDP has less than 1% packet loss on typical hardware.

And I suppose, TCP is being used(which is promises to be give "guaranteed delivery"), on a server with 500 Mbps port speed.
Also, I observed lots of duplicates. I had to filter all duplicate "exchange_time_stamp" before inserting

![Screenshot_2020-10-23_20-09-15](https://user-images.githubusercontent.com/36351384/97026517-1b67a180-1577-11eb-97a9-ad11714ace64.png)

Has anyone else experienced this same issue? I will be offloading the SQLAlchemy insertion code to another thread and see if that helps. However, it might not be the problem, I think.

This 1sec precision is not that useful(because of data loss). I think there should be atleast 1min OHLC data available after every minute.

a 15% data loss is too much, atleast thats what I think.

This stock below got 16.5% data loss -

![Screenshot_2020-10-23_21-36-14](https://user-images.githubusercontent.com/36351384/97027063-dbed8500-1577-11eb-99f0-6778e1324a92.png)

I want collect and use these data for personal R&D.

**Comment by krishnavelu** [comment]
What is this expected count/actual count? I didn't get it. Do you expect 1 data per seconds? Tick datas comes faster than this in actual. More than 1 per second.
Why do you insert 1 second delay loop? You have to handle tick data without any loop, in a handler function.

**Comment by be-thomas** [comment]
Yes I expected to get 1 data per second.
The Queue I'm using is supposedly thread safe.

Currently I the loop as -

while True:
    time.sleep(1)
    # get everything in queue to a list
    # sqlalchemy bulk insert the data in list

And my websocket onMessage function is like -
def onMessage():
    if not duplicate:
        add data to queue

**Comment by krishnavelu** [comment]
your expectations is wrong. No where it has written that you get only one 1 data per second. You receive multiple ticks per second.

**Comment by krishnavelu** [comment]
Hope your issue is solved. Closing this as of now.
