### ISSUE TITLE
Oauth

### ISSUE THREAD

**Issue by rjra2611** [krishnavelu/alice_blue#211]
Once you have got access token through oauth Authorization grant code flow of your clients, you still need to generate Alice instance using : alice = AliceBlue(username='username', password='password', access_token=access_token).
Then what is the point to getting client access token if you still need username, password (which are confidential) 
What is the workaround to this ?

**Comment by krishnavelu** [comment]
Just noticed. Password is not used anywhere. Try passing username/password as None. If didn't work only pass password as none.

**Comment by rjra2611** [comment]
working fine if both username, password are given as None. Thanks
