### ISSUE TITLE
Data Is delayed by more than 5 minutes and reaches 1 hour delay

### ISSUE THREAD

**Issue by mukhi199** [krishnavelu/alice_blue#212]
Hi Krishnavelu,

I have already sent the logs to alice blue. But just checking here, if anyone else encountered the same problem . I did the windows upgrade and after that I am getting data delayed by more than 1-2 minutes. It starts with real time date and then keeps delaying. I have seen difference in system time stamp and exchange time stamp by more than 1 hour. 

Please see the attached log. If you have encountered this problem or has seen this problem. Please let me know what needs to be done to fix this?
[logtill940.txt](https://github.com/krishnavelu/alice_blue/files/5472916/logtill940.txt)

**Comment by krishnavelu** [comment]
Enhance your data handling. Try only one scrip for testing.

**Comment by mukhi199** [comment]
EDIT: Yes when I subscribed for one script, data is only 1-2 second late, but when I am subscribiing for 20-30 scripts, data is close to 1000 seconds late. 
In this particular script, I have just two lines of code, Subscribe and Event Handler. See this: What extra I can do to enhance this 

alice.subscribe(alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=datetime.date(2020, 11, 5), is_fut=False, strike=23500, is_CE = True), LiveFeedType.COMPACT)

def event_handler_quote_update(message):

    print('current time',datetime.datetime.now())
    print('current time exch format:',int(time.time()))
    print("message", message)


Still the difference is 400 seconds:
current time exch format: 1604375663
message {'exchange': 'NFO', 'token': 40001, 'ltp': 374.45, 'change': 4294946156, 'exchange_time_stamp': 1604375218, 'volume': 37200, 'instrument': Instrument(exchange='NFO', token=40001, symbol='BANKNIFTY 5 NOV20 25100 PE', name='', expiry=datetime.date(2020, 11, 5), lot_size='25')}

I have subscrrbed for 20 tokens. So does that mean, If subscirbe for 20 tokens, I will get the 400 seconds delayed data.?

**Comment by mukhi199** [comment]
Okay so looks like,,,,, the database that i was dumping the tick data was causing the delay ... I did remove everything and then compared the time.... even in that there is a delay of 1-2 seconds. which may be due to since it is a free API.   closing this ticket, will try to see how I have to store the tick data to get minimum delay.....

**Comment by nrameshy** [comment]
@mukhi199 I am facing the same issue when I subscribe for 100+ instruments. I am just printing the message to the console in the event handler but the streaming data is getting delayed as the time goes on. Were you able to fix the issue?

**Comment by krishnavelu** [comment]
Print is heavy. Just to a simple store. Measure each and every line of code execution's time. Optimize.

**Comment by mukhi199** [comment]
@nrameshy , if it is a simple store then how would you know whether the data is delayed or not. You have to do multi threading and that is very bad in python. Run multiple scripts and store data , using this you will reduce the delay, but let me tell you one odd day, ALICE BLUE DATA will be delayed and you cannot do any thing in that. So, I have stopped using my algo in Alice Blue. You cannot rely on free stuff, bottom line.

**Comment by nrameshy** [comment]
Thank you @mukhi199 . I too feel the same. Alice Blue websocket API is not reliable.
