### ISSUE TITLE
Index Expiry

### ISSUE THREAD

**Issue by prith1990** [krishnavelu/alice_blue#214]
Hi Sir,

How to get the nearest expiry for Bank Nifty and Nifty index. 
This is needed to place orders in CE and PE contracts. 

Thanks in advance,
Prithiv Venkatesh

**Comment by mukhi199** [comment]
this question is not related with API bro, this is logical question, you can get the nearest thursday date and pull token info with that date.

**Comment by krishnavelu** [comment]
There is no direct API available. Get the nearest Thursday date and get the instrument.

**Comment by VineetKillerX** [comment]
import datetime

def get_next_expiry():
    today = datetime.date.today()
    thursday = today + datetime.timedelta( (3-today.weekday()) % 7 )
    return thursday

**Comment by ashivapp** [comment]
instruments=alice.search_instruments('NFO','NIFTY')
instruments=pd.DataFrame(instruments)
get_monthly_expiry=instruments['expiry'].iloc[-1]
weekly_expiry=instruments.expiry.unique()
get_weekly_expiry=min(weekly_expiry)

**Comment by ashivapp** [comment]
instruments=alice.search_instruments('NFO','BANKNIFTY')
instruments=pd.DataFrame(instruments)
get_monthly_expiry=instruments['expiry'].tail(3)
get_monthly_expiry=min(get_monthly_expiry)
weekly_expiry=instruments.expiry.unique()
get_weekly_expiry=min(weekly_expiry)

Above is working for me

**Comment by khodeprasad** [comment]
I have created two methods to get the monthly and weekly expiry, below is the snippet

```
def get_monthly_expiry(symbol, expiry='current'):
    instruments = pd.DataFrame(alice.search_instruments('NFO', symbol))
    instruments = instruments.loc[instruments['symbol'].str.contains('FUT', regex=False)]
    instruments = instruments.loc[instruments['symbol'].str.startswith(symbol)]

    if expiry == 'current':
        return min(instruments.expiry)
    elif expiry == 'next':
        return max(instruments[instruments.expiry != max(instruments.expiry)].expiry)
    else:
        return max(instruments.expiry)


def get_weekly_expiry(symbol, expiry='current'):
    instruments = pd.DataFrame(alice.search_instruments('NFO', symbol))
    instruments = instruments.loc[~instruments['symbol'].str.contains('FUT', regex=False)]
    instruments = instruments.loc[instruments['symbol'].str.startswith(symbol)]

    expiry_dates = instruments.sort_values(by='expiry', axis=0).expiry.unique()

    if expiry == 'current':
        return expiry_dates[0]
    elif expiry == 'next':
        return expiry_dates[1]
```

it gives the current or next expiry

**Comment by krishnavelu** [comment]
Closing this, reopen if needed.
