### ISSUE TITLE
'event_handler_quote_update' gives output only once instead of continuous streaming live data

### ISSUE THREAD

**Issue by PythonNovice5** [krishnavelu/alice_blue#216]
`socket_opened = False

def event_handler_quote_update(message):
    print("trading data ..")
    print(f"quote update {message}")

def open_callback():
    global socket_opened
    socket_opened = True

alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
               
while(socket_opened==False):
    print("The socket is closed")
    pass
print("The socket is Open now..")    
alice.subscribe(alice.get_instrument_by_symbol('NSE', 'ONGC'), LiveFeedType.MARKET_DATA)
print("Subscribed instrument...")
time.sleep(1)
print("Checking if socket is closed")`

The above code gives the following output but only once: 

The socket is closed
The socket is closed
The socket is Open now..
Subscribed instrument...
trading data ..
quote update {'exchange': 'NSE', 'token': 2475, 'ltp': 72.0, 'ltt': 0, 'ltq': 0, 'volume': 51155955, 'best_bid_price': 0.0, 'best_bid_quantity': 0, 'best_ask_price': 0.0, 'best_ask_quantity': 0, 'total_buy_quantity': 0, 'total_sell_quantity': 0, 'atp': 72.0, 'exchange_time_stamp': 0, 'open': 78.5, 'high': 86.35, 'low': 72.0, 'close': 72.0, 'yearly_high': 134.55, 'yearly_low': 50.0, 'instrument': Instrument(exchange='NSE', token=2475, symbol='ONGC', name='OIL AND NATURAL GAS CORP.', expiry=None, lot_size=None)}
Checking if socket is closed

During live stream using websocket, isn't it supposed to stream continuous live data ?

**Comment by krishnavelu** [comment]
Try during Market time.

**Comment by krishnavelu** [comment]
@PythonNovice5 Hope your issue is solved. Reopen if needed. Closing this.
