### ISSUE TITLE
How to Exit Options MIS Market Order

### ISSUE THREAD

**Issue by VikramBangre** [krishnavelu/alice_blue#217]
Hi,

Due to new SEBI rules I have started trading in Options instead of Futures.

I am able trigger the MIS Market Buy Order using the API but unable to exit the Order. 

MIS order are not part of Pending Orders they stay under Positions.

Below code is not working. Could you please help how to exit MIS orders

`order_status = alice.cancel_all_orders()`

**Comment by sasikanuri** [comment]
BUY Order placed as MARKET order would be executed immediately hence you would be observing them in Open Day Positions.

If you want to close DAY Open Position you need to initiate fresh reverse (SELL) order to square off the open position.

**Comment by VikramBangre** [comment]
So I have to use OMS Order ID of Buy Order and then trigger a Sell Order. Is my understanding correct.

Can this Sell Order be at a specific price (Limit price) ?

**Comment by sasikanuri** [comment]
Order Types

   - LIMIT
   - MARKET
   - SL
   - SLM

**Comment by VikramBangre** [comment]
I know the order types but how to have a reverse Sell order for Buy MIS Position ?

**Comment by sasikanuri** [comment]
If you want to set target for your open position (BUY).

MIS SELL LIMIT order. (This order would be in pending state till that price
is matched).

Else you want to squareoff open position(BUY) immediately.

MIS SELL MARKET order has to be placed.

**Comment by VikramBangre** [comment]
Ok. thanks for the info. So below code should do then for Option Buy and Sell. Please confirm.

First Buy and then set the target or exit by placing the Sell Limit order or Market order if you want to Exit immediately:

```
order_status = alice.place_order(transaction_type=TransactionType.Buy,
                                          instrument=alice.get_instrument_by_symbol(ins_type, stock_name),
                                          quantity=stock_quantity,
                                          order_type=OrderType.Market,
                                          product_type=ProductType.Intraday,
                                          price=0.0,
                                          trigger_price=None,
                                          stop_loss=None,
                                          square_off=None,
                                          trailing_sl=None,
                                          is_amo=False)

order_status = alice.place_order(transaction_type=TransactionType.Sell,
                                          instrument=alice.get_instrument_by_symbol(ins_type, stock_name),
                                          quantity=stock_quantity,
                                          order_type=OrderType.Limit,
                                          product_type=ProductType.Intraday,
                                          price= ** give the limit price here **
                                          trigger_price=None,
                                          stop_loss=None,
                                          square_off=None,
                                          trailing_sl=None,
                                          is_amo=False)
```

**Comment by sasikanuri** [comment]
SELL STOPLOSS LIMIT ORDER trigger_price also has to be passed. Rest is fine.
Ideally trigger_price should be your stoploss value and PRICE value should be further away from trigger price.

Note: If the market price has crossed PRICE quoted then your order may not be executed while using LIMIT ORDER.

**Comment by VikramBangre** [comment]
ok thanks for the help. Much appreciated. I tested Live today and it worked.

For me Buy at Limit price and Sell at Market price is required. It works like a charm 👍 

Closing the ticket.
