### ISSUE TITLE
Open Interest of Option Strike Price not receiving

### ISSUE THREAD

**Issue by sasikanuri** [krishnavelu/alice_blue#218]
As per API documentation, it was mentioned as OPEN INTEREST will be received while subscribed for MarketData or Compact Data feed. 

However i am not able to see Open Interest received along with MarketData/Compact Data event on websocket.

**Comment by krishnavelu** [comment]
Open interest is not available in alice.

**Comment by sasikanuri** [comment]
May i know when that would be made available.

**Comment by krishnavelu** [comment]
I don't know contact Alice customer care.

**Comment by krishnavelu** [comment]
Closing this.
