### ISSUE TITLE
How to know if part of an order is filled and remaining pending

### ISSUE THREAD

**Issue by rjamitsharma01** [krishnavelu/alice_blue#219]
Hello sir

Sir for example I place limit buy order INFY at ₹1000.50 of  200 qty  out of this 200 , 150 qty is filled and remaining pending and market goes up and remaining 50 qty is pending how do I know the pending and filled qty 

Please help

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) before creating a new issue.

**Comment by krishnavelu** [comment]
Use this function [get_order_history](https://github.com/krishnavelu/alice_blue/blob/master/alice_blue/alice_blue.py#L466)
