### ISSUE TITLE
How to get PNL

### ISSUE THREAD

**Issue by srtwou** [krishnavelu/alice_blue#220]
Hi,

For example, I entered straddle
bn_call = alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=datetime.date(2020, 12, 10), is_fut=False, strike=30100, is_CE = True)
bn_put = alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=datetime.date(2020, 12, 10), is_fut=False, strike=30100, is_CE = False)

print ("%%%%%%%%%%%%%%%%%   Basket Order    %%%%%%%%%%%%%%%%%%%")
order1 = {  "instrument"        : alice.get_instrument_by_symbol('NFO', bn_put[2]),
            "order_type"        : OrderType.Market,
            "quantity"          : 25,
            "transaction_type"  : TransactionType.Sell,
            "product_type"      : ProductType.Intraday}
order2 = {  "instrument"        : alice.get_instrument_by_symbol('NFO', bn_call[2]),
            "order_type"        : OrderType.Market,
            "quantity"          : 25,
            "transaction_type"  : TransactionType.Sell,
            "product_type"      : ProductType.Intraday}
order = [order1, order2]
print(alice.place_basket_order(order))

Now, how can I track profit and loss? Say for example, if loss is less than -1000 INR, I want to exit straddle.

Please help.

Regards
Sriram

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) before creating a new issue.

**Comment by krishnavelu** [comment]
There are 3 functions available [`get_balance`](https://github.com/krishnavelu/alice_blue/blob/master/alice_blue/alice_blue.py#L450), [`get_daywise_positions`](https://github.com/krishnavelu/alice_blue/blob/master/alice_blue/alice_blue.py#L454) and [`get_netwise_positions`](https://github.com/krishnavelu/alice_blue/blob/master/alice_blue/alice_blue.py#L458). See which one suits you and try to calculate PNL from that.
