### ISSUE TITLE
Unable to Fetch NIFTY FNO data - It showing Banknifty Only

### ISSUE THREAD

**Issue by jay5deep** [krishnavelu/alice_blue#222]
Please publish the changes so other users can use this. Request!!

**Comment by jay5deep** [comment]
ins_scrip = alice.get_instrument_by_symbol('NFO', 'BANKNIFTY 17 DEC20 30500 PE')
-- Working fine..

ins_scrip1 = alice.get_instrument_by_symbol('NFO', 'NIFTY 17 DEC20 13500 PE')
-- Not Working 

Please check.

**Comment by krishnavelu** [comment]
what should I publish?

**Comment by jay5deep** [comment]
I think latest changes related to Nifty FNO data are present in DEV branch.
So if you can publish to master then good.

Anyways I used Dev one and working fine. Thank you.

**Comment by krishnavelu** [comment]
Done
