### ISSUE TITLE
Please verify your api_secret

### ISSUE THREAD

**Issue by kauteetech** [krishnavelu/alice_blue#224]
I have generated the secret key using the link - http://develop-api.aliceblueonline.com/

kept the 2fa password same for all 5 questions. getting below error.
I see unknown client. please help

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth2/auth?response_type=code&state=test_state&client_id=180018&redirect_uri=https://ant.aliceblueonline.com/plugin/callback HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth2/fallbacks/error?error=invalid_client&error_description=Client+authentication+failed+%28e.g.%2C+unknown+client%2C+no+client+authentication+included%2C+or+unsupported+authentication+method%29&error_hint=The+requested+OAuth+2.0+Client+does+not+exist. HTTP/1.1" 200 None
ERROR:alice_blue.alice_blue:OAuth 2.0 Error occurred. Please verify your api_secret
None

**Comment by Pranjal310** [comment]
Facing the same issue.

**Comment by khodeprasad** [comment]
Even I have the same issue, I get the following error

```
OAuth 2.0 Error occurred. Please verify your api_secret
Traceback (most recent call last):
  File "/home/prasadkhode/miniconda3/envs/OI-Spurt/lib/python3.7/site-packages/alice_blue/alice_blue.py", line 208, in __init__
    profile = self.get_profile()
  File "/home/prasadkhode/miniconda3/envs/OI-Spurt/lib/python3.7/site-packages/alice_blue/alice_blue.py", line 445, in get_profile
    profile = self.__api_call_helper('profile', Requests.GET, None, None)
  File "/home/prasadkhode/miniconda3/envs/OI-Spurt/lib/python3.7/site-packages/alice_blue/alice_blue.py", line 946, in __api_call_helper
    response = self.__api_call(url, http_method, data)
  File "/home/prasadkhode/miniconda3/envs/OI-Spurt/lib/python3.7/site-packages/alice_blue/alice_blue.py", line 954, in __api_call
    if(len(self.__access_token) > 100):
TypeError: object of type 'NoneType' has no len()

```
When I check in http://develop-api.aliceblueonline.com/ it is not showing any app

I am stuck for 1 week and even I raised the same with AliceBlue support but no response yet

**Comment by kauteetech** [comment]
this is very discouraging.. I have been begging for getting this done for last 3 days. they gave +91 80 2217 4615, looks like the api team has typical government mentality from support or they are all frustrated working for aliceblue or not taken care, they have poor attitude towards customers.. or wrong hire in first place for customer support. They blindly disconnect the call. since Monday i have easily tried 10 times daily, yet get there DARSHAN... will wait for today EOD.

**Comment by khodeprasad** [comment]
finally able to solve the issue, pass app id that gets generated when you create the app to get the access token something like below

```
access_token = AliceBlue.login_and_get_access_token(username=user_name, password=pass_word, twoFA=two_fa, api_secret=api_secret, app_id=app_id)
```

This resolved my issue...

**Comment by kauteetech** [comment]
I tried that too, after reading the function.. but still no luck.. I don't know if they need to enable API access for my client ID. 
from the function I can see, if we don't provide the APP ID it takes user ID as the input.

good you got through...

**Comment by Pranjal310** [comment]
What code are you using? I am getting error.

Traceback (most recent call last):
  File "acc_token.py", line 12, in <module>
    access_token = AliceBlue.login_and_get_access_token(username=user_name, password=pass_word, twoFA=two_FA, api_secret=api_secret, app_ID=app_ID)
TypeError: login_and_get_access_token() got an unexpected keyword argument 'app_ID'

**Comment by kauteetech** [comment]
Looks like Krishna velu is US time zone.. so we may have to wait till then..

**Comment by khodeprasad** [comment]
> I tried that too, after reading the function.. but still no luck.. I don't know if they need to enable API access for my client ID.
> from the function I can see, if we don't provide the APP ID it takes user ID as the input.
> 
> good you got through...

Yes, you need to send an email to the support team to activate the API access to your client id.  Send an email to api@aliceblueindia.com asking to activate by mentioning your client id

**Comment by khodeprasad** [comment]
> What code are you using? I am getting error.
> 
> Traceback (most recent call last):
> File "acc_token.py", line 12, in
> access_token = AliceBlue.login_and_get_access_token(username=user_name, password=pass_word, twoFA=two_FA, api_secret=api_secret, app_ID=app_ID)
> TypeError: login_and_get_access_token() got an unexpected keyword argument 'app_ID'

I am on Alice Blue version 1.0.0 and used the same sample code that is given on the read me page...

**Comment by kauteetech** [comment]
> > I tried that too, after reading the function.. but still no luck.. I don't know if they need to enable API access for my client ID.
> > from the function I can see, if we don't provide the APP ID it takes user ID as the input.
> > good you got through...
> 
> Yes, you need to send an email to the support team to activate the API access to your client id. Send an email to [api@aliceblueindia.com](mailto:api@aliceblueindia.com) asking to activate by mentioning your client id

yep... did that 4 to five times since Monday ;-).. looks like I am sending it to a blackhole, no replay yet for any of them. Just now sent one more request to enable API access.

**Comment by rjamitsharma01** [comment]
guys in morning I got the same issue while login in python but letteron I coud login 

but neither I could place orders nor I could get live tick data as it says 

Cannot find symbol NSE BHARATFORG in master contract

if anyone got the solution please let everyone know

**Comment by rjamitsharma01** [comment]
@khodeprasad  could you please tell where did you get app id as I got my api on email from aliceblue and there is no app id

**Comment by khodeprasad** [comment]
I have created the app at http://develop-api.aliceblueonline.com/ here you will get all the details required, try once...

**Comment by rjamitsharma01** [comment]
> I have created the app at http://develop-api.aliceblueonline.com/ here you will get all the details required, try once...

thank you 

but when I create app there It says successful
but latter on it does not show deshboard

**Comment by kauteetech** [comment]
> > I have created the app at http://develop-api.aliceblueonline.com/ here you will get all the details required, try once...
> 
> thank you
> 
> but when I create app there It says successful
> but latter on it does not show deshboard

Don't worry on that, just create the app, use the app_id and app_secret, when you get the token successfully. the app gets registered. use your ANT web platform, go to profile and check for registered app. you should see the one recently created app..

**Comment by rjamitsharma01** [comment]
> > > I have created the app at http://develop-api.aliceblueonline.com/ here you will get all the details required, try once...
> > 
> > 
> > thank you
> > but when I create app there It says successful
> > but latter on it does not show deshboard
> 
> Don't worry on that, just create the app, use the app_id and app_secret, when you get the token successfully. the app gets registered. use your ANT web platform, go to profile and check for registered app. you should see the one recently created app..

one more thing please tell me how to use app id and app secreat as I have been using like 

`access_token = AliceBlue.login_and_get_access_token(username=username, password=password, twoFA=twofa,  api_secret=api_secret)`

and this used to work but no longer now 

and thanx again

**Comment by kauteetech** [comment]
When creating the keys, please set the redirect URL as https://ant.aliceblueonline.com/plugin/callback

access_token = AliceBlue.login_and_get_access_token(username=clientcode, password=passwd, twoFA="a", api_secret=xxxxx, app_id="Value you get at the time of generating the token")

**Comment by rjamitsharma01** [comment]
> https://ant.aliceblueonline.com/plugin/callback

thanx again 

but getting error like 

Couldn't get access token {'error': 'invalid_client', 'error_description': 'Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)', 'status_code': 401}


my code is as follows
`access_token = AliceBlue.login_and_get_access_token(username=username, password=password, twoFA=twofa,  api_secret=api_secret , app_id="xvelawNiB8", )`

**Comment by kauteetech** [comment]
here are the steps.

1. set all 5 2fa passwords as same.
2. go to http://develop-api.aliceblueonline.com/  - create new app using redirect url with https://ant.aliceblueonline.com/plugin/callback
3.create code as below

from alice_blue import *

access_token = AliceBlue.login_and_get_access_token(username=clientcode, password=passwd, twoFA="a", api_secret=xxxxx, app_id='Value you get at the time of generating the token')

print(access_token)

if the steps are followed and api access is enabled from aliceblue side this should work.
else raise a ticket with api@aliceblueindia.com

**Comment by krishnavelu** [comment]
To All.
Verify the following for getting access token.
1. username
2. password
3. 2FA
4. redirect url.
5. api key.

If all are proper you should get access token without any problem. If any of them are wrong you may not able to generate access token.

**Comment by saikiran0901** [comment]
Hi @krishnavelu , with new accounts created with user id's as number like '126971' instead of AB126971, alice blue is asking to create an app_id inside the development consol. After that giving the same details as you mentioned was not working. Upon giving the app_id in the below function we are able to generate the access token

def login_and_get_access_token(username, password, twoFA, api_secret,redirect_url='https://ant.aliceblueonline.com/plugin/callback',app_id):

in the current aliceblue library the app_id is defaulted to None
api_secret,redirect_url='https://ant.aliceblueonline.com/plugin/callback',app_id=None):

after the app id is passed, I am able to get the access token and get the balance as well.But, upon placing orders, I am getting the below response from the request

{'status': 'error', 'message': ' is not supported in NSE segment.', 'data': {}}

Could you please let me know if there is any change in using the code with the new aliceblue clients who need to generate an app_id to get the secret key? Earlier we did not have this app_id created. only api_secret was shared with us

**Comment by saikiran0901** [comment]
> To All.
> Verify the following for getting access token.
> 
> 1. username
> 2. password
> 3. 2FA
> 4. redirect url.
> 5. api key.
> 
> If all are proper you should get access token without any problem. If any of them are wrong you may not able to generate access token.

Hi @krishnavelu , with new accounts created with user id's as number like '126971' instead of AB126971, alice blue is asking to create an app_id inside the development consol. After that giving the same details as you mentioned was not working. Upon giving the app_id in the below function we are able to generate the access token

def login_and_get_access_token(username, password, twoFA, api_secret,redirect_url='https://ant.aliceblueonline.com/plugin/callback',app_id):

in the current aliceblue library the app_id is defaulted to None
api_secret,redirect_url='https://ant.aliceblueonline.com/plugin/callback',app_id=None):

after the app id is passed, I am able to get the access token and get the balance as well.But, upon placing orders, I am getting the below response from the request

{'status': 'error', 'message': ' is not supported in NSE segment.', 'data': {}}

Could you please let me know if there is any change in using the code with the new aliceblue clients who need to generate an app_id to get the secret key? Earlier we did not have this app_id created. only api_secret was shared with us

**Comment by krishnavelu** [comment]
Once you get the access token there is no difference. You should be able to place order.

**Comment by kauteetech** [comment]
Did you complete the below two steps?

1. Physical copy of POA to be sent aliceblue
2. Place request for NEST platform trading request from you bot.aliceblue
url.

Last I checked, they have blocked api access to new user accounts.

**Comment by krishnavelu** [comment]
Closing this. Reopen if needed.

**Comment by MaheshGulavani** [comment]
Hello @krishnavelu ,
After following steps as described by you in this forum, I am getting below error, please help.

_ERROR:alice_blue.alice_blue:Couldn't get access token {'error': 'invalid_grant', 'error_description': 'The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client', 'status_code': 400}_

Thanks

**Comment by krishnavelu** [comment]
Again I'm going to write the same.

Verify the following for getting access token.

1. username
2. password
3. 2FA
4. redirect url.
5. api key.
6. api secret.

**Comment by MaheshGulavani** [comment]
> Again I'm going to write the same.
> 
> Verify the following for getting access token.
> 
> 1. username
> 2. password
> 3. 2FA
> 4. redirect url.
> 5. api key.
> 6. api secret.

Thank you @krishnavelu, it worked as  I replied in #228.

**Comment by dattatak** [comment]
I solved The Problem

1st Step :
http://develop-api.aliceblueonline.com/
go and log in.

while creating the App please enter redirect url as 
https://ant.aliceblueonline.com/plugin/callback

then create app
please keep app id and api secrete at secure place

use following code 



`from alice_blue import *`
`user_name='enter ur client id'`
`pass_word='enter ur passwoard'`
`two_fa='enter ur two factor'`
`API_Secret='ur secrete '`
`App_id='enter ur app id'`
`access_token = AliceBlue.login_and_get_access_token(username=user_name, password=pass_word, twoFA=two_fa,  api_secret=API_Secret,app_id=App_id)`
`print(access_token)
`

**Comment by Mk2187** [comment]
i am getting error:OAuth-2.0-Error-occurred.-Please-verify-your-api_secret Getting this error which fetching accesss token

I have generated the secret key using the link - http://develop-api.aliceblueonline.com/

from alice_blue import *
import account_details

username = account_details.username
password = account_details.password
twoFA = account_details.twoFA
api_secret = account_details.api_secret

app_id = '4ly1GWcvW'

access_token = AliceBlue.login_and_get_access_token(username= username, password= password, twoFA= twoFA, api_secret= api_secret ,app_id=app_id)

print(access_token)

**Comment by sudhanshu8833** [comment]
> Looks like Krishna velu is US time zone.. so we may have to wait till then..

bro.. has the issue solved ... I am still not able to get access_token on Alice Blue

**Comment by Thomasssibi** [comment]
Hi sir,
I am getting the below error can you please help me
---------------------------

---------------------------

<html>
<head>
	<title>An OAuth 2.0 Error Occurred</title>
<script src="/cdn-cgi/apps/head/-KUw3PxRvRZv2QhNc47Gwn5LIsM.js"></script></head>
<body>
<h1>
	The OAuth2 request resulted in an error.
</h1>
<ul>
	<li>Error: invalid_request</li>
	<li>Description: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed</li>
	<li>Hint: The "redirect_uri" parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls.</li>
	<li>Debug: </li>
</ul>
<p>
	You are seeing this default error page because the administrator has not set a dedicated error URL (environment variable <code>OAUTH2_ERROR_URL</code> is not set). 
	If you are an administrator, please read <a href="https://www.ory.sh/docs">the guide</a> to understand what you
	need to do. If you are a user, please contact the administrator.
</p>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"rayId":"6664efc2ffe24ed4","token":"46191df1e0324e209e0003a259ebc24f","version":"2021.5.2","si":10}'></script>
</body>
</html>


---------------------------
OK   
---------------------------

**Comment by tejasnavalkhe** [comment]
I am also getting the same error, but now it is working, To work it properly make sure you use `'https://ant.aliceblueonline.com/plugin/callback'` as redirect url and not extra `'/'` after callback. Beacuse, I was doing this stupid thing in my app creation process.

**Comment by kv-cache** [comment]
@tejasnavalkhe1810  thanks for the tip. That was the issue for me.

**Comment by manishgupta-ind** [comment]
> finally able to solve the issue, pass app id that gets generated when you create the app to get the access token something like below
> 
> ```
> access_token = AliceBlue.login_and_get_access_token(username=user_name, password=pass_word, twoFA=two_fa, api_secret=api_secret, app_id=app_id)
> ```
> 
> This resolved my issue...

Thanks buddy. This resolved my issue.

**Comment by rahultandale3** [comment]
> I have generated the secret key using the link - http://develop-api.aliceblueonline.com/
> 
> kept the 2fa password same for all 5 questions. getting below error. I see unknown client. please help
> 
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443 DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth2/auth?response_type=code&state=test_state&client_id=180018&redirect_uri=https://ant.aliceblueonline.com/plugin/callback HTTP/1.1" 302 0 DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth2/fallbacks/error?error=invalid_client&error_description=Client+authentication+failed+%28e.g.%2C+unknown+client%2C+no+client+authentication+included%2C+or+unsupported+authentication+method%29&error_hint=The+requested+OAuth+2.0+Client+does+not+exist. HTTP/1.1" 200 None ERROR:alice_blue.alice_blue:OAuth 2.0 Error occurred. Please verify your api_secret None



hey i faced the same problem , but i got simple solution of this problem simply login to the https://develop-api.aliceblueonline.com/dashboard   

just do below step 
1 . click on create new app 
2. enter the app name and redirect url as https://ant.aliceblueonline.com/plugin/callback
3. copy the api id , api secret in any txt file 
4. use that api id and secret for generating  your access token 
5. delete the previous app (its your choice )



have a good day , emjoy

**Comment by rs-amundaware** [comment]
> print(access_token)



> I am also getting the same error, but now it is working, To work it properly make sure you use `'https://ant.aliceblueonline.com/plugin/callback'` as redirect url and not extra `'/'` after callback. Beacuse, I was doing this stupid thing in my app creation process.

This one worked for me

**Comment by tejasnavalkhe** [comment]
This is just the remainder to you all that old API will get discontinued from 15th Sep. So please use the new API key. Maybe this Python Package does not provide a new API right now (27/08/2022).

New API Key documentation:
**Create APP:** https://developers.aliceblueonline.com/apps
**Documentation:**  https://v2api.aliceblueonline.com/introduction
