### ISSUE TITLE
Cannot find symbol NSE  BHARATFORG in master contract

### ISSUE THREAD

**Issue by rjamitsharma01** [krishnavelu/alice_blue#225]
I am getting this error while trying to get live tick data for some stocks and some stocks are working fine

Cannot find symbol NSE  BHARATFORG in master contract
Cannot find symbol NSE  ASHOKLEY in master contract
Cannot find symbol NSE  BHARTIARTL in master contract
Cannot find symbol NSE  TATACHEM in master contract
Cannot find symbol NSE  ITC in master contract

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) before creating a new issue.
Post a sample code and what's the output you are getting.

**Comment by krishnavelu** [comment]
Hope your issue is solved. Reopen if needed.
