### ISSUE TITLE
Please verify your api_secret

### ISSUE THREAD

**Issue by arunprakashpj** [krishnavelu/alice_blue#227]
I am trying to get the access token using the following statement

`access_token = AliceBlue.login_and_get_access_token(username=user_name, password=pass_word, twoFA=two_fa, api_secret=api_secret, app_id=app_id)`

I am getting following error

```
  File "...\Python37-32\lib\site-packages\requests\models.py", line 380, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "...\Python\Python37-32\lib\site-packages\urllib3\util\url.py", line 392, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: {config['host']}{config['routes']['authorize']}?response_type=code&state=test_state&client_id={app_id}&redirect_uri={redirect_url}
```

I have explored the forum to solve this issue but I am yet to figure out the actual root cause ! Any help on this will be much appreciated !

**Comment by krishnavelu** [comment]
Verify your username, password, api_secret, redirect url, 2FA. If everything is perfect you should get the access token.

**Comment by arunprakashpj** [comment]
@krishnavelu I reset few parameters and now, things seem to work fine !! Thanks :)
