### ISSUE TITLE
Order placement in another account

### ISSUE THREAD

**Issue by Parva14** [krishnavelu/alice_blue#23]
I just got to know that it is possible to generate access token and place order in another (2nd account which doesn't have an activated API) account with the API details of one account. (of course if the APP is authorized in another account) 

If anyone has tried that, can you please quickly tell me how to proceed with it using this library?

TIA,
Parva

**Comment by krishnavelu** [comment]
For generating access tokens, APP needs to be authorized from alice side. For that we need to pay.

**Comment by Parva14** [comment]
@krishnavelu  do they have any documentation or guidelines available for that? Also, what are the charges for the same?

**Comment by krishnavelu** [comment]
I said we need to pay to alice. Getting API access from alice is APP authorization.

**Comment by Parva14** [comment]
@krishnavelu I talked to Mr. Rasind from Alice Blue, who deals with the API and stuff. He told me that we can generate access token for another account using the APP of the first one because they use Oauth2, so it is easily possible. Do you have any idea about this?

**Comment by krishnavelu** [comment]
I don't have any idea about this.
