### ISSUE TITLE
 alice.get_daywise_positions() 

### ISSUE THREAD

**Issue by gagan3211** [krishnavelu/alice_blue#232]
Hi Krishna
Thanks so much for this amazing API and base example .
I am using this past 3 weeks and results are amazing. 

I need to know your views on  alice.get_daywise_positions() frequency.
Can we call this function every 5 mins to see max loss on each position ? will this cause any server load ?

**Comment by krishnavelu** [comment]
5 mins will not cause any server load. But don't reduce below that.

**Comment by krishnavelu** [comment]
Closing this.
