### ISSUE TITLE
How to subscribe a quote Dynamically

### ISSUE THREAD

**Issue by Vijaya-Sankar-Challa** [krishnavelu/alice_blue#235]
I was trying to get live feed of Bank Nifty Options 2000 points above and below of Spot price using BankNifty Future Price.

from alice_blue import *
from time import *
from datetime import *

access_token = AliceBlue.login_and_get_access_token(username=username, password=password, twoFA=twofa, app_id=appid, api_secret=apisecret)
alice = AliceBlue(username=username, password=password, access_token=access_token, master_contracts_to_download=['NSE', 'NFO'])

#print(access_token)

socket_opened = False
BankNifty_ATM = 0
def event_handler_quote_update(message):
    global BankNifty_ATM
    BankNifty_ATM = (message['ltp']//1000)*1000
    print(f"quote update {message}")

def open_callback():
    global socket_opened
    socket_opened = True

alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
while(socket_opened==False):
    pass

alice.subscribe(alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=date(2021, 1, 28), is_fut=True, strike=None, is_CE = False), LiveFeedType.MARKET_DATA)

**for strike in range((BankNifty_ATM-2000), (BankNifty_ATM+2000+100), 100):
         print(BankNifty_ATM) # when I print here It return 0
         bn_call = alice.get_instrument_for_fno(symbol='BANKNIFTY', expiry_date=date(2021, 1, 14), is_fut=False,strike=strike, is_CE=True)
         bn_put = alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=date(2021, 1, 14), is_fut=False, strike=strike, is_CE = False)
         alice.subscribe(bn_call, LiveFeedType.MARKET_DATA)
         alice.subscribe(bn_put, LiveFeedType.MARKET_DATA)**
sleep(10)

**Comment by krishnavelu** [comment]
I didn’t get what’s your question here. Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow while creating new issue.

**Comment by Vijaya-Sankar-Challa** [comment]
No problem! Got the solution

**Comment by shushant** [comment]
Hello @Vijaya-Sankar-Challa,

Can you please tell us how did you manage to subscribe to the scrip on demand?
