### ISSUE TITLE
Error; 'Instrument' object is not callable

### ISSUE THREAD

**Issue by mallinlr** [krishnavelu/alice_blue#236]
Hi sir,

I am getting the error; 'Instrument' object is not callable, please suggest;

with the below code;

def get_ce_curr_price(atm_ce):
    print('get_ce_curr_price')
    global bn_call,token_ce,ce_order_placed,ce_sl_price
    bn_call = alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=datecalc,is_fut=False,strike=atm_ce,is_CE = True)
    alice.subscribe(bn_call,LiveFeedType.COMPACT)
    sleep(1)
    ce_price = ltp
    print("before sell_ce_option..............)
    sell_ce_option(bn_call,ce_price)

    print(f"sell ce order placed at price : {ltp}")
    alice.unsubscribe(bn_call,LiveFeedType.COMPACT)

#sell_ce option code here
def sell_ce_option(bn_call,ce_price):
    quantity = no_of_lots=int(bn_call(1))

    sell_order = alice.place_order(transaction_type = TransactionType.Sell,
                                    instrument = bn_call,
                                    quantity = quantity,
                                    order_type = OrderType.Market,
                                    product_type = ProductType.Intraday,
                                    price = 0.0,
                                    trigger_price = None,
                                    stop_loss = None,
                                    square_off = None,
                                    trailing_sl = None,
                                    is_amo = False)
    sleep(1)
    if sell_order['status'] == 'success':
        sl_order = alice.place_order(transaction_type = TransactionType.Buy,
                                     instrument = bn_call,
                                     quantity = quantity,
                                     order_type = OrderType.StopLossLimit,
                                     product_type = ProductType.Intraday,
                                     price = 0.0,
                                     trigger_price = 1.5+ce_price,
                                     stop_loss = None,
                                     square_off = None,
                                     trailing_sl = None,
                                     is_amo = False)

**Comment by krishnavelu** [comment]
Code is not readable. Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow while creating a new issue.

**Comment by krishnavelu** [comment]
@mallinlr Hope your issue is solved. Reopen if needed.
