### ISSUE TITLE
Historical data

### ISSUE THREAD

**Issue by dhayal123** [krishnavelu/alice_blue#237]
Hi, is it possible to get historical data for the last 1 year with the following information. Lets say we had 250 trading days in the last 1 year. can we get 250 below points for each day?
Day high, low, close, open, volume

Thanks in advance

**Comment by krishnavelu** [comment]
Alice doesn’t provide historical data

**Comment by Vijaya-Sankar-Challa** [comment]
I think we can get these values from nsepy.

**Comment by krishnavelu** [comment]
@dhayal123 Hope your issue is solved. Reopen if needed.
