### ISSUE TITLE
TypeError: Required parameter instrument not of type Instrument

### ISSUE THREAD

**Issue by architpandita** [krishnavelu/alice_blue#238]
_**Both below cmd are failing, (it was working till last Thursday):**_
alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=date(2021, 1, 14), is_fut=False, strike=32000, is_CE = True)
alice.get_instrument_for_fno(symbol = 'NIFTY', expiry_date=date(2021, 1, 14), is_fut=False, strike=14000, is_CE = True)

Error:  
File "C:\Users\archit\Anaconda3\lib\site-packages\alice_blue\alice_blue.py", line 664, in subscribe    
raise TypeError("**Required parameter instrument not of type Instrument**")
TypeError: Required parameter instrument not of type Instrument

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating a new issue.

**Comment by architpandita** [comment]
```from alice_blue import *
import logging
from datetime import datetime,date
import time
import json    

dd = str(datetime.now().strftime('%d%b%Y'))
with open("..//rexxxx//xx_access_token.json","r") as f:
    acc = json.load(f)
print(acc)

access_token = AliceBlue.login_and_get_access_token(username=u, password=p,twoFA='a',  api_secret=secret)
alice = AliceBlue(username=u, password=p, access_token=access_token)


socket_opened = False
o =""
def event_handler_quote_update(message):
    global o
    o= message

    print("message ..",message)
    print(f"quote update {message}")

def open_callback():
    global socket_opened
    socket_opened = True

alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)

while(socket_opened==False):
    pass

```
### This is working
```
out1 = alice.subscribe(alice.get_instrument_by_symbol('NSE', 'RELIANCE'), LiveFeedType.COMPACT)
time.sleep(5)
print("-out1 -->", out1)

# out2=alice.subscribe([alice.get_instrument_by_symbol('NFO', 'BANKNIFTY 14 JAN21 32500 PE')], LiveFeedType.COMPACT)
```
### This is NOT working
```
out2=alice.subscribe([alice.get_instrument_for_fno(symbol="BANKNIFTY", expiry_date=date(2021,1,21), is_fut=False, strike=34000, is_CE=False)], LiveFeedType.COMPACT)

time.sleep(5)

print("-out2 -->", out2, o)
```
### ERROR:

-out1 --> None
message .. {'exchange': 'NSE', 'token': 2885, 'ltp': 1966.0, 'change': 540, 'exchange_time_stamp': 1610696226, 'volume': 5020451, 'instrument': Instrument(exchange='NSE', token='2885', symbol='RELIANCE', name='RELIANCE INDUSTRIES LTD', expiry=None, lot_size=None)}
quote update {'exchange': 'NSE', 'token': 2885, 'ltp': 1966.0, 'change': 540, 'exchange_time_stamp': 1610696226, 'volume': 5020451, 'instrument': Instrument(exchange='NSE', token='2885', symbol='RELIANCE', name='RELIANCE INDUSTRIES LTD', expiry=None, lot_size=None)}

#### Traceback (most recent call last):
  File "C:/Users/path/gen_access_token.py", line 55, in <module>
    out2=alice.subscribe([alice.get_instrument_for_fno(symbol="BANKNIFTY", expiry_date=date(2021,1,21), is_fut=False, strike=34000, is_CE=False)], LiveFeedType.COMPACT)
  File "C:\Users\archit\AppData\Local\Programs\Python\Python36-32\lib\site-packages\alice_blue\alice_blue.py", line 657, in subscribe
    raise TypeError("Required parameter instrument not of type Instrument")
TypeError: Required parameter instrument not of type Instrument

Process finished with exit code 1

**Comment by krishnavelu** [comment]
Separate subscribe() and get_instrument() functions. Before subscribing see if you got the correct instrument. Print the instrument and see.

**Comment by krishnavelu** [comment]
@architpandita Hope your issue is solved. Reopen if needed.

**Comment by pshubham8595** [comment]
@krishnavelu can you please give an example for the same please.

I have tried as you said to separate the methods. But still it is returning `None`.
Following is my code snippet.
`bn_call = alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=datetime.date(2021, 2, 3), is_fut=True, strike=33500, is_CE = True)`
`print(bn_call)`
and this is its output
`DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/profile HTTP/1.1" 200 None
INFO:alice_blue.alice_blue:Downloading master contracts for exchange: BSE
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/contracts.json?exchanges=BSE HTTP/1.1" 200 None
INFO:alice_blue.alice_blue:Downloading master contracts for exchange: BFO
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/contracts.json?exchanges=BFO HTTP/1.1" 200 2
INFO:alice_blue.alice_blue:Downloading master contracts for exchange: NSE
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/contracts.json?exchanges=NSE HTTP/1.1" 200 None
INFO:alice_blue.alice_blue:Downloading master contracts for exchange: NFO
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/contracts.json?exchanges=NFO HTTP/1.1" 200 None
INFO:alice_blue.alice_blue:Downloading master contracts for exchange: CDS
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/contracts.json?exchanges=CDS HTTP/1.1" 200 None
INFO:alice_blue.alice_blue:Downloading master contracts for exchange: MCX
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/contracts.json?exchanges=MCX HTTP/1.1" 200 None
None
`  
 or correct me if iam doing it wrong.btw good job and thanks for being around.

**Comment by krishnavelu** [comment]
Is `date(2021, 2, 3)` an expiry?

**Comment by pshubham8595** [comment]
Well I was trying to fetch the data for the same day, Hence had put it as expiry date. Correct me sir if I am wrong. Thankyou...

**Comment by krishnavelu** [comment]
enter the correct expiry date.

**Comment by pshubham8595** [comment]
Thanks a lot I was putting wrong expiry date. It is working smooth. 👍
