### ISSUE TITLE
BO order not getting placed

### ISSUE THREAD

**Issue by abhijitmamarde** [krishnavelu/alice_blue#24]
I am trying to place the BO order, and below is the order dict which is finally getting posted:

```python
{'exchange': 'MCX', 'order_type': 'LIMIT', 'instrument_token': 214909, 'quantity': 10, 'disclosed_quantity': 0, 'price': 4132.35, 'transaction_type': 'BUY', 'validity': 'DAY', 'source': 'web', 'order_tag': 'order1', 'stop_loss_value': 4130.35, 'square_off_value': 4150.35}
```

but getting below error always:

```python
{'status': 'error', 'message': ' is not supported in MCX segment.', 'data': {}}
```

While Market order types are getting placed successfully.

Please let me know if any more info required for looking into this issue.

Thanks!

**Comment by agujrathi** [comment]
There was issue in BO order placement.
The socket endpoint or BO order was also getting /v2/order instead of /api/v2/bracketorder

This was a code issue as below..

`if product_type is ProductType.BracketOrder:
            **helper = 'place_bracket_order'**
            del order['product'] 
            if not isinstance(stop_loss, float):
                raise TypeError("Required parameter stop_loss not of type float")

            if not isinstance(square_off, float):
                raise TypeError("Required parameter square_off not of type float")
            
        if(is_amo == True):
            helper = 'place_amo'
        else:
            helper = 'place_order'`

The is_amo check was overwriting the  correct helper for BracketOrder..
This check should be above or used properly..

This fixes the issue..

**Comment by abhijitmamarde** [comment]
Yes, the above fix mentioned does work for me. Would be happy to have this fix incorporated into main repo code. 

Thanks for quick response and the fix.

**Comment by krishnavelu** [comment]
@abhijitmamarde @agujrathi This issue #19 is already fixed in develop.
But not yet released.
