### ISSUE TITLE
Need to place option order in BN index socket 

### ISSUE THREAD

**Issue by swapnillondhe123** [krishnavelu/alice_blue#240]
I am trying to order Bank nifty option order while checking market data from Bank Nifty inex data.
How can be this achieved.

Thanks in advance.

**Comment by swapnillondhe123** [comment]
This is my socket of Bank Nify Index

def event_handler_quote_update(message):
    global lastcandletaken
    global lastcandle
    global currentCandle
    global entry
    SnapQuote = "\n" + str(datetime.datetime.now()) + " : " + str(message)
    print(SnapQuote)
    atp=message['ltp']
    print(atp)
    tm=time.localtime()
    print(tm)
    print(tm.tm_min)
    print(round(tm.tm_min/5,0))
    print (round(tm.tm_min/5,2))
    print (tm.tm_sec)
    readsignal()
    if round(tm.tm_min/5,0)==round(tm.tm_min/5,2) and tm.tm_sec<=1:
        if lastcandletaken==False:
            lastcandle=atp
            lastcandletaken=True
            with open("D:\Python\BankNiftyFutureS5Min.txt", "a") as text_file: strCandleData = "\n" + str(datetime.datetime.now())  + " : " + str(lastcandle)
            text_file.write("%s" % strCandleData)
        else:
            currentCandle=atp
            with open("D:\Python\BankNiftyFutureS5Min.txt", "a") as text_file: strCandleData = "\n" + str(datetime.datetime.now()) + " : " + str(currentCandle)
            text_file.write("%s" % strCandleData)
    else:
       lastcandletaken=False               
    print('Entry')
    print (lastcandle)
    print (currentCandle)
    bn_future = alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=datetime.date(2021, 1, 28), is_fut=True, strike=None, is_CE = False)
    futData=alice.subscribe(bn_future,LiveFeedType.MARKET_DATA)
    print(futData['ltp'])
    if(sellLevel>lastcandle and entry==0):
        entry=-1    #Sell Future at Market Rate. SL will be sellSL-atp #make entry in file of Sell Future in file
    if(buyLevel<lastcandle and entry==0):
        entry=1 #Buy Future at Market Rate. SL will be atp-buySL #make entry in file of Buy Future in file
    if(entry==1 or entry==-1):
        print(futData['ltp'])


I need to fetch future first and check ltp. Also want to get order price after placing order.

**Comment by krishnavelu** [comment]
Your code is not readable without indentation. Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) before creating a new issue.

**Comment by swapnillondhe123** [comment]
I want to place orders in Bank Nifty options in Bank Nifty index socket. For this I want to get ltp of Option and then want to place order. My question is within Bank Nifty index socket, can I subsribe market data of option.

Thanks in Advance.

**Comment by krishnavelu** [comment]
Yes
