### ISSUE TITLE
I am not getting live feed. Yesterday live feed was working. Can you please guide. Code is just keep running. NO output even after 2-3 min.

### ISSUE THREAD

**Issue by pramodtrade48** [krishnavelu/alice_blue#241]
alice = AliceBlue(username='username', password='password', access_token=access_token, master_contracts_to_download=['NSE','NFO'])

bn_fut =pd.DataFrame(bn_fut)

print (bn_fut)

print(tradingsymbol)

data = alice.subscribe(alice.get_instrument_by_symbol('NSE', 'SBIN'), LiveFeedType.MARKET_DATA)

print (data)

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/profile HTTP/1.1" 200 None
INFO:alice_blue.alice_blue:Downloading master contracts for exchange: NSE
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/contracts.json?exchanges=NSE HTTP/1.1" 200 None
INFO:alice_blue.alice_blue:Downloading master contracts for exchange: NFO
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/contracts.json?exchanges=NFO HTTP/1.1" 200 None
                   0
0                NFO
1              49534
2  BANKNIFTY JAN FUT
3                   
4         2021-01-28
5                 25
   0
 NFO

<ipython-input-32-ece5c447c000> in <module>()
     21 
     22 print(tradingsymbol)
---> 23 data = alice.subscribe(alice.get_instrument_by_symbol('NSE', 'SBIN'), LiveFeedType.MARKET_DATA)
     24 print (data)
     25 

1 frames
/usr/local/lib/python3.6/dist-packages/alice_blue/alice_blue.py in __ws_send(self, *args, **kwargs)
    399     def __ws_send(self, *args, **kwargs):
    400         while self.__websocket_connected == False:
--> 401             sleep(0.05)  # sleep for 50ms if websocket is not connected, wait for reconnection
    402         with self.__ws_mutex:
    403             ret = self.__websocket.send(*args, **kwargs)

KeyboardInterrupt:

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating a new issue.

**Comment by pramodtrade48** [comment]
Sorry but could not find the solution

**Comment by krishnavelu** [comment]
I also don’t know what you need.

**Comment by pramodtrade48** [comment]
Issue resolved Krishna ji.
Thanks . 
I just didn't upgraded Alice blue library
