### ISSUE TITLE
maximum no of tickers can be subcribed in webstreaming?

### ISSUE THREAD

**Issue by keerthankumar** [krishnavelu/alice_blue#242]
1. what is the max number of tickers can be subscribed in web streaming ?

**Comment by krishnavelu** [comment]
250

**Comment by keerthankumar** [comment]
thanks for responding. is there any sandbox setup where post market I could get dummy data for testing ?  currently I'm getting nothing post market .. is this behaviour by design ?

**Comment by krishnavelu** [comment]
No.
