### ISSUE TITLE
Exiting partially filled positions

### ISSUE THREAD

**Issue by ghost** [krishnavelu/alice_blue#245]
1. does a partially filled order shown in pending orders via order history?

2. when we exit the partially filled position, will order for remaining quantity get cancelled or need to be cancelled manually?

3. or vice versa when we cancel partially filled order, will the position gets squared off or need to be exited manually?

**Comment by krishnavelu** [comment]
1. Yes
2. Don't know, check yourself.
3. Same as 2.
