### ISSUE TITLE
websocket realtime stream 

### ISSUE THREAD

**Issue by keerthankumar** [krishnavelu/alice_blue#246]
understanding the WebSocket behaviour -

in the realtime WebSocket streaming,
 1. whats the streaming speed?
2. say I subscribed for INFY streaming at 10.00.00 am and streaming started. if the price didn't change for the next 3 sec. (till 10.00.03), will I get stream update for 10.00.01 and 10.00.02?

**Comment by krishnavelu** [comment]
Whenever there is a tick update you'll get through web sockets. its not constant. that comes from exchange -> broker -> Websocket.

**Comment by keerthankumar** [comment]
1. One more question Here - When you say tick update do you mean price, or any parameter like , 
bid/ask price, bid/ask quant etc?
