### ISSUE TITLE
Unable to unsubscribe 

### ISSUE THREAD

**Issue by come2niks** [krishnavelu/alice_blue#247]
Hi Krishna,

I've subscribed to the live ticker and its working fine, but I'm not able to unsubscribe it. 
Now I have multiple subscriptions running.

 # Getting access token
    alice = auth()
    print('unsubscribe')
    print(optionNameCall)
    print(optionNamePut)
    alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
    while(socket_opened==False):
        pass
    # alice.unsubscribe(alice.get_instrument_by_symbol('NFO', optionNameCall), LiveFeedType.MARKET_DATA)

    alice.unsubscribe([alice.get_instrument_by_symbol('NFO', optionNameCall), alice.get_instrument_by_symbol('NFO', optionNamePut)], LiveFeedType.MARKET_DATA)
    print('socket_opened')
    # socket_opened = False
    print('after unsubscribe')
    return 'subscription is closed'

Code is working but unable to unsubscribe, continue to get the ticker data.

**Comment by krishnavelu** [comment]
In the above code you didn't subscribe at all.

**Comment by come2niks** [comment]
# Getting access token
    alice = auth()
    # positionsResponse = alice.get_daywise_positions()
    # print("positionsResponse = ", positionsResponse)

    alice.start_websocket(subscribe_callback = event_handler_quote_update,
                      socket_open_callback = open_callback,
                      run_in_background = True)
    while(socket_opened==False):
        pass
    # alice.subscribe(alice.get_instrument_by_symbol('NFO', optionNameCall), LiveFeedType.MARKET_DATA)
    alice.subscribe([alice.get_instrument_by_symbol('NFO', optionNameCall), alice.get_instrument_by_symbol('NFO', optionNamePut)], LiveFeedType.MARKET_DATA)

I did subscribe as well

**Comment by come2niks** [comment]
I had sent you the code which was used for unsubscribe

**Comment by krishnavelu** [comment]
The subscribe/unsubscribe code is correct. It does unsubscribe for me.

**Comment by come2niks** [comment]
I do continue to get the ticker. To stop the ticker, I had to restart the server every time.

**Comment by krishnavelu** [comment]
Post a fully reproducible code, with both subscribe and unsubscribe, with print statements and also the print statement output, showing the behavior you say. Read [this](https://youtu.be/110x5rMHCIw) to see what I’m expecting.

**Comment by prith1990** [comment]
I have a similar question. Below are the things which I did 

1. Subscribe to multiple scripts (say 10)
2. Later unsubscribed them
3. Now subscribing to another set of scripts (say 5). 

By doing this I am getting both sets subscribed in point 1 and point 3. 
Can you please help me with how I can get data only for those subscribed in point 3?

**Comment by krishnavelu** [comment]
Just Follow the above comments.
