### ISSUE TITLE
OAuth 2.0 Error occurred. Please verify your api_secret

### ISSUE THREAD

**Issue by APRATIMMANDAL** [krishnavelu/alice_blue#248]
Hi Team, I am unable to get access token using the below credentials:

![image](https://user-images.githubusercontent.com/49467176/107142389-9d2be100-6954-11eb-84b2-00106c4b081c.png)

In the python code I am using the same as mentioned above:
![image](https://user-images.githubusercontent.com/49467176/107142413-c6e50800-6954-11eb-9fb3-0ae5a1d9b4c6.png)

rest twoFA and Password are being entered correct as per my profile.

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating a new issue

**Comment by Mk2187** [comment]
Sir, I  am getting same error.
Please hepl
  mukesh
Email id-kumarmk2187@gmail.com
<img width="1221" alt="2021-02-11_01h09_14" src="https://user-images.githubusercontent.com/78743326/107562392-c757fa00-6c05-11eb-9373-0ce00e6fd7d8.png">

**Comment by krishnavelu** [comment]
Verify your credentials.

**Comment by Mk2187** [comment]
Sir,
i chacked all credential  using print function

**Comment by Mk2187** [comment]
all are correct

**Comment by krishnavelu** [comment]
If all are correct you should get access token.

**Comment by Mk2187** [comment]
Yes Sir ,you are right but from last 5 days am getting this error.NO one from aliceblue responded so far on this issue.
May you try with my ID and password

**Comment by Mk2187** [comment]
Sir today,alice customer care contacted.now problem get resolved .Access token generated with same code,Still why it was not working reason is not known.
Thank for Support

**Comment by krishnavelu** [comment]
Because they didn't enable the api in your account. After you've contacted they've enabled.
