### ISSUE TITLE
Get Quote [LTP / Marketdepth (ASK & BID)] without subscribing to websocket

### ISSUE THREAD

**Issue by qFactorin** [krishnavelu/alice_blue#249]
Hi Krishna,

Is there a way to fetch just quote information without having to subscribe to web socket streaming.

Not trying to compare products here, but on Zerodha Kite I use kite.quote to fetch this information. And is quite convenient.

I just need LTP and Market depth of a symbol in every 5 minutes, Subscribing to symbol streaming is an overkill for my purpose. And the connection termination / unsubscribing is not always clean.

Any assistance here would be really helpful. Thank you in advance.

**Comment by krishnavelu** [comment]
No. You've to subscribe to get quote.

**Comment by qFactorin** [comment]
Ok, thank you for confirming.

**Comment by Piyushjoshi007** [comment]
Hi @qFactorin have you got any solution to this? Also @krishnavelu it would be very convenient if you can do something like what zerodha had done for LTP values.Thanks

**Comment by krishnavelu** [comment]
Zerodha has implemented in it’s server. That’s why api also provides the same. Alice doesn’t provide this. So cannot be done in api. Make a small function which subscribes and unsubscribe immediately.
