### ISSUE TITLE
Not getting Nifty spot and FUT and live data

### ISSUE THREAD

**Issue by grsb007** [krishnavelu/alice_blue#25]
Hello Krishna Velu,

I am very thankful for this github repo, it is really good. Need your help trying to get the details for Nifty spot price and nifty FUT
<Response [200]>
nifty_nse_eq = alice.get_instrument_by_symbol('NFO', 'NIFTY'), it is giving following warning
WARNING:root:Cannot find symbol NFO NIFTY in master contract
or 
nifty_nse_eq = alice.get_instrument_by_symbol('NSE', 'NIFTY'), it is giving following warning
WARNING:root:Cannot find symbol NSE NIFTY in master contract

niftyput = alice.get_instrument_for_fno(symbol = 'NIFTY', expiry_date=datetime.date(2019, 12, 26), is_fut=True, strike=12000, is_CE = False) 
This is giving BANKNIFTY not NIFTY details 

RuntimeWarning: Enable tracemalloc to get the object allocation traceback
quote update {'exchange': 'NFO', 'token': 48891, 'ltp': 32412.9, 'ltt': 1575090670, 'ltq': 20, 'volume': 3760, 'best_bid_price': 32412.9, 'best_bid_quantity': 1140, 'best_ask_price': 32412.95, 'best_ask_quantity': 400, 'total_buy_quantity': 7600, 'total_sell_quantity': 3500, 'atp': 32262.57, 'exchange_time_stamp': 1575090673, 'open': 31990.0, 'high': 33000.05, 'low': 31880.0, 'close': 32003.85, 'yearly_high': 17012772.81, 'yearly_low': 18356255.04, 'instrument': Instrument(exchange='NFO', token='48891', symbol='BANKNIFTY DEC FUT', name='', expiry=datetime.date(2019, 12, 26), lot_size='20')}
quote update {'exchange': 'NFO', 'token': 48891, 'ltp': 32412.9, 'ltt': 1575090670, 'ltq': 20, 'volume': 3760, 'best_bid_price': 32412.9, 'best_bid_quantity': 1140, 'best_ask_price': 32412.95, 'best_ask_quantity': 400, 'total_buy_quantity': 7600, 'total_sell_quantity': 3520, 'atp': 32262.57, 'exchange_time_stamp': 1575090674, 'open': 31990.0, 'high': 33000.05, 'low': 31880.0, 'close': 32003.85, 'yearly_high': 17012772.81, 'yearly_low': 18356255.04, 'instrument': Instrument(exchange='NFO', token='48891', symbol='BANKNIFTY DEC FUT', name='', expiry=datetime.date(2019, 12, 26), lot_size='20')}
quote update {'exchange': 'NFO', 'token': 48891, 'ltp': 32412.9, 'ltt': 1575090670, 'ltq': 20, 'volume': 3760, 'best_bid_price': 32412.9, 'best_bid_quantity': 1140, 'best_ask_price': 32412.95, 'best_ask_quantity': 400, 'total_buy_quantity': 7940, 'total_sell_quantity': 3520, 'atp': 32262.57, 'exchange_time_stamp': 1575090679, 'open': 31990.0, 'high': 33000.05, 'low': 31880.0, 'close': 32003.85, 'yearly_high': 17012772.81, 'yearly_low': 18356255.04, 'instrument': Instrument(exchange='NFO', token='48891', symbol='BANKNIFTY DEC FUT', name='', expiry=datetime.date(2019, 12, 26), lot_size='20')}

Also can you help me getting nifty spot price details 

Thanks,

**Comment by krishnavelu** [comment]
For getting nifty FNO, refer this issue #18 . Its fixed in develop not yet release in an official version.
For getting nifty spot try this.
`nifty_nse_eq = alice.get_instrument_by_symbol('NSE', 'Nifty 50')`

**Comment by grsb007** [comment]
Thanks for reply ifty_nse_eq = alice.get_instrument_by_symbol('NSE', 'Nifty 50') is working. 

Could you please tell me about 
niftyput = alice.get_instrument_for_fno(symbol = 'NIFTY', expiry_date=datetime.date(2019, 12, 26), is_fut=True, strike=12000, is_CE = False)

**Comment by krishnavelu** [comment]
I told you to refer issue #18 .
Its fixed in issue #18 and pushed to develop.
Take develop branch latest.

**Comment by krishnavelu** [comment]
A simple EMA cross strategy.

https://gist.github.com/krishnavelu/e0df312ccf5f022edb1823461ff4230e

**Comment by krishnavelu** [comment]
Join [unofficed](https://unofficed.com/chat/) if you want to learn more.
