### ISSUE TITLE
Not able to retrieve master contracts

### ISSUE THREAD

**Issue by chanxuze** [krishnavelu/alice_blue#251]
I'm able to successfully log in and retrieve data related to my account like positions, orders , profile etc but retrieving master contracts returns None. This has been happening since yesterday.
![IMG_20210209_123228](https://user-images.githubusercontent.com/70112387/107360410-e8342880-6afb-11eb-9307-2f5493095716.jpg)

**Comment by krishnavelu** [comment]
Master contract is stored internally. It’s not for user’s use
