### ISSUE TITLE
How to convert ws.on('message', function incoming(data) {}) binary-data into JSON in NodeJS ?

### ISSUE THREAD

**Issue by amarendhar** [krishnavelu/alice_blue#252]
I'm trying to connect to websocket from NodeJS with access_token.
Connection is successful, and sending message is successful, but received message in Binary-Format, how to convert into JSON in NodeJS ?

```
import WebSocket from 'ws'

const ws = new WebSocket(
  'wss://ant.aliceblueonline.com/hydrasocket/v2/websocket?access_token={access_token},
)

ws.on('open', function open() {
  ws.send('{"a": "subscribe", "v": [[1, 2475]], "m": "marketdata"}')
})

ws.on('message', function incoming(data) {
  console.log('message -> ', data)
})
```

Here received `message` is `<Buffer 01 01 00 00 09 ab 00 00 27 74 60 22 64 11 00 00 00 0a 02 5c d6 81 00 00 27 74 00 00 2f 70 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2f 70 00 00 00 00 ... 36 more bytes>`

How to convert that into JSON data.

**Comment by krishnavelu** [comment]
Read [this](http://antplus.aliceblueonline.com/#feeds-api) document.

**Comment by amarendhar** [comment]
> Read [this](http://antplus.aliceblueonline.com/#feeds-api) document.

I already have gone through the documentation before asking the question.
that documentation is lack of information, that's why i asked question over here.

i'm using `ws-npm` in NodeJS.
if possible provide some code-snippet to decode `Buffer` response when received message from websocket.

in python, `data.toString()` works just fine.

But in NodeJS, it doesn't work

the code-snippet which i shared is very simple to run, just need to add `access_token`, then inside message-event you can check `data.toString()` won't decode properly.

**Comment by krishnavelu** [comment]
You need to interpret it as binary. Not as a string. binary.toString() is not going to work.
This library is created based on that document only. 
Refer [this](https://github.com/krishnavelu/alice_blue/blob/master/alice_blue/alice_blue.py#L322-L366) function, which converts all binary data from server to json.

**Comment by cq-ubaid-khan** [comment]
simply `JSON.parse(message)`

**Comment by vasily-mishanin** [comment]
```
...
ws.on('message', function message(data) {
    const creds = JSON.parse(data.toString());
    const userData = JSON.parse(creds.data);
    console.log({ userData });
...
```
