### ISSUE TITLE
Authentication Json Request

### ISSUE THREAD

**Issue by nad29cob** [krishnavelu/alice_blue#254]
In the link : https://antplus.aliceblueonline.com/#authentication

There is no information for URL/Method and json header on how to get the access token.

For example to Place Order there are URL/Method and json header as below
 
![image](https://user-images.githubusercontent.com/78902107/107617125-52240d80-6c75-11eb-96d8-b2bc3a5a3d7c.png)

I would like to know what would be the URL/Method and json header to get the access token in the authentication 

Right now this area is blank for Authentication as in the below pic

![image](https://user-images.githubusercontent.com/78902107/107617292-a16a3e00-6c75-11eb-9da9-799d8f527d77.png)

Kindly let me know the json header to get the access token and the URL / Method 

Thanks & Regards
Naren

**Comment by krishnavelu** [comment]
I'm not sure what you are trying to do. Try the examples provided [here](https://github.com/krishnavelu/alice_blue).

**Comment by nad29cob** [comment]
Thank you for your comment. I had already read the examples you mentioned above.
I'm trying to get the Access Token through POSTMAN using the URL/METHOD/ PARAMETERS and json
Once I succeed in POSTMAN I'll develop an App in Visual Studio C#
I don't use Python.

I need json header like in the below picture for Authentication (this is the example json to place order)

![image](https://user-images.githubusercontent.com/78902107/107728221-7cc4a380-6d13-11eb-828e-6a554839277e.png)

This is the link for the above Picture : https://antplus.aliceblueonline.com/#place-order

For Authentication there is no such json : https://antplus.aliceblueonline.com/#authentication

All I need is URL, Method, Parameteres : Key, Value and json for this Authentication step

Please let me know if you are still unclear about what I expect.
Thanks in Advance
Naren

**Comment by krishnavelu** [comment]
Look at the python code in this library and try to replicate the same.

**Comment by nad29cob** [comment]
Thank you for your time...
