### ISSUE TITLE
How to convert binary data to JSON coming on websocket feed api in java

### ISSUE THREAD

**Issue by Ajaylal7** [krishnavelu/alice_blue#255]

**Comment by Ajaylal7** [comment]
I am receiving data like this [1, 2, 0, 0, -16, -109, 0, 0, -45, 34, 96, 43, -105, -98, 0, 0, 5, 20, 0, 55, -118, -64, 0, 0, -45, 4, 0, 0, 5, 20, 0, 0, -45, 44, 0, 0, 5, 20, 0, 0, 0, 0, 0, 3, -70, -80, 0, 0, 0, 0, 0, 10, 40, 0, 0, 0, -45, -45, 96, 43, -105, -98, 0, 0, -46, -16, 0, 0, -43, -54, 0, 0, -46, 50, 0, 0, -46, -61, 0, 0, -43, -54, 0, 0, 0, 0, 0, 0, -67, -80, 0, 0, -25, -37, 1, 20, 41, -88, 6, -61, 96, 108]

**Comment by krishnavelu** [comment]
Refer [this](http://antplus.aliceblueonline.com/#introduction) document.

**Comment by Ajaylal7** [comment]
Hi @krishnavelu I refered those docs, but they didn't provided any information about decoding binary data. Please provide those details.

**Comment by krishnavelu** [comment]
All details are in that document. This library is created referring that document.

**Comment by Ajaylal7** [comment]
Hi @krishnavelu thankyou for your kind response. Switched to Angelbroking 👍
