### ISSUE TITLE
Heartbeat request not send after subscribing

### ISSUE THREAD

**Issue by Gnaneshwaran** [krishnavelu/alice_blue#256]
from alice_blue import *
from time import *
from datetime import *

alice = AliceBlue(username='AB089836', password='sidjjdsdax', access_token='audjijfijdfdfdf.sidjijdijsfijdifidjfijdifjdifjidjfijdifjidjfidjfi',master_contracts_to_download=['NSE', 'NFO'])

socket_opened = False
def event_handler_quote_update(message):
    print(f"quote update {message}")

def open_callback():
    global socket_opened
    socket_opened = True
    print("opened")

alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
while(socket_opened==False):
    pass
alice.subscribe(alice.get_instrument_by_symbol('NSE', 'ONGC'), LiveFeedType.MARKET_DATA)
sleep(10)

Here data get received only for 10 seconds after that websocket stops.

**Comment by krishnavelu** [comment]
Learn python
