### ISSUE TITLE
websocket run forever ended in exception, socket is already opened

### ISSUE THREAD

**Issue by akashiitd** [krishnavelu/alice_blue#257]
`alice.subscribe(alice.get_instrument_by_symbol('NSE', 'ONGC'), `LiveFeedType.MARKET_DATA)``

I am getting this error **websocket run forever ended in exception, socket is already opened**

Not able to fetch live market data

**Comment by krishnavelu** [comment]
Try the example code provided in the document as it is.

**Comment by Mclovin-code** [comment]
> `alice.subscribe(alice.get_instrument_by_symbol('NSE', 'ONGC'), `LiveFeedType.MARKET_DATA)``
> 
> I am getting this error **websocket run forever ended in exception, socket is already opened**
> 
> Not able to fetch live market data

Its because you are trying to open a WebSocket that's already open

**Comment by akashiitd** [comment]
Please tell me what i need to do

**Comment by Mclovin-code** [comment]
> Please tell me what i need to do

Easy bro, don't open it more than once
