### ISSUE TITLE
How to get instrument for MCX Futures (GOLDM or CRUDEOIL)

### ISSUE THREAD

**Issue by jay5deep** [krishnavelu/alice_blue#258]
instrument = a.get_instrument_for_fno(symbol = inst, expiry_date=get_monthly_expiry, is_fut=True, strike=None, is_CE = False)
           
inst="GOLDM"

This is not working. Please help.

**Comment by krishnavelu** [comment]
Try this https://github.com/krishnavelu/alice_blue#search-for-symbols
