### ISSUE TITLE
Delay in order_history

### ISSUE THREAD

**Issue by adityarudrawar** [krishnavelu/alice_blue#259]
Im calling  order history of a account
```
while True:
      morders = malice.get_order_history()
      read_new_orders(morders)
      time.sleep(0.5)

```
But there has been a delay of 1 min, 
I placed an order at 10:27:12, I have also submitted the  logs for it as well. It didn't respond for almost 1 min

DEBUG:2021-02-23 10:27:12,851:MainThread:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:2021-02-23 10:28:13,159:MainThread:https://ant.aliceblueonline.com:443 "GET /api/v2/order HTTP/1.1" 200 None

There wasn't any issue yesterday. It started since this morning
Is there any server side issue?

**Comment by krishnavelu** [comment]
Learn python.
