### ISSUE TITLE
Is there any api available to get candlestick data 

### ISSUE THREAD

**Issue by Jeyanthinath** [krishnavelu/alice_blue#26]
Hi is there any api available to get historical candle data for 5 minutes and 15 minutes.

**Comment by Parva14** [comment]
@Jeyanthinath Not Really, Zerodha does provide a historical API for getting candlestick data but No API streams Candlestick data in real time, you will have to re-sample the ticks to generate candles of specific timeframe on your local system only.

**Comment by krishnavelu** [comment]
Alice-blue doesn't provide historical data. Historical data are provided by upstox & zerodha.

**Comment by PSAlmighty** [comment]
Is there any sample code available to recreate candlestick using websocket data?

**Comment by amit-kumar27742** [comment]
If you dont want to write more lines of code, most simplest way is to store every tick in a dataframe and use the resample function.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html

**Comment by krishnavelu** [comment]
If you understand what is candle stick you can easily recreate using tick data.
Candle stick is nothing but OHLC, open, high, low, close.
Store the tick data in a list (as per the time frame you want).

`open = lst[0]` 
`high = max(lst)`
`low = min(lst)`
`close = lst[-1]`

**Comment by krishnavelu** [comment]
Hope this is answered. Reopen if you need something else related to this question.

**Comment by mallinlr** [comment]
sir, Can you please provide code snippet to get OHLC data for a stock.

**Comment by krishnavelu** [comment]
I've explained above, how to get OHLC.

**Comment by mallinlr** [comment]
Sir, this is half code, can you please write what should be above lst[0],

open = lst[0]
high = max(lst)
low = min(lst)
close = lst[-1]

**Comment by krishnavelu** [comment]
> 
If you understand what is candle stick you can easily recreate using tick data.
Candle stick is nothing but OHLC, open, high, low, close.
Store the tick data in a list (as per the time frame you want).


Yes it’s half code. I cannot write code for your application. You’ve to write your own.
lst is list

**Comment by mallinlr** [comment]
Hi Sir,

Is there any sample script to access aliceblue Oauth2 access, please let me
know.


Thank you
Mallikarjuna M

**Comment by krishnavelu** [comment]
What do you mean by alice blue Oauth2 access?

**Comment by sasi143** [comment]
@krishnavelu Is there any way we can get the last one month data?

**Comment by krishnavelu** [comment]
Alice blue doesn’t provide historical data.

**Comment by SanketGanvir** [comment]
> If you dont want to write more lines of code, most simplest way is to store every tick in a dataframe and use the resample function.
> 
> https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html

Can you write a small snippet showing how it's done?

**Comment by venkateshr23** [comment]
Hi Krishna, Is there a method exposed to get the open position, and modify or close the position ?

**Comment by pbrijesh26** [comment]
This means that if i am trading in 1 min TF(suppose) ,i won't be able to make a 20 moving average until i gets 20 ticks therefore i have to wait for 20 mins for a my system (algo) to work.

**Comment by krishnavelu** [comment]
Thats how moving average works. You cannot take average till all data points are available.

**Comment by pbrijesh26** [comment]
Does Aliceblue has a plan to come up with historical data api in the near future??

**Comment by krishnavelu** [comment]
Nope.
