### ISSUE TITLE
How to exit existing position without placing counter order?

### ISSUE THREAD

**Issue by souviksamanta1995** [krishnavelu/alice_blue#260]
If I have executed an order, and then I want to close that position, is there any specific function for that? I can't find any, please update that function, otherwise I generally need to put a counter order which is not convenient specially when I want to exit all the positions. Fyers have a separate exit function. Can it be incorporated here also?? it will be very helpful. Thank you

**Comment by krishnavelu** [comment]
There is no such thing. You’ve to make a counter order.
