### ISSUE TITLE
How to place IOC order

### ISSUE THREAD

**Issue by keerthankumar** [krishnavelu/alice_blue#262]
Hi Im looking into order placing command, there is no attribute to place Immediate or cancel orders (IOC orders) .can you please help me on this

**Comment by krishnavelu** [comment]
That’s hardcoded in [this](https://github.com/krishnavelu/alice_blue/blob/master/alice_blue/alice_blue.py#L540) line. As I didn’t get a valid use case for immediate or cancel order, I hardcoded it.
Let me know what’s your use case. If it’s valid, I can modify and add an optional parameter for you. Or else you can just modify that line of code.

**Comment by keerthankumar** [comment]
This is a valid scenario. I want to place **Limit-IOC** order. make it an optional argument so that it won't impact existing systems.

**Comment by keerthankumar** [comment]
Hi I made the modification as you suggested, added validity as optional argument. 
so with my code response for **order** in line 532 is  (for placing order limit- IOC-intraday)
`{'exchange': 'NSE', 'order_type': 'LIMIT', 'instrument_token': 1594, 'quantity': 1, 'disclosed_quantity': 0, 'price': 7.0, 'transaction_type': 'BUY', 'trigger_price': 6.5, 'validity': 'IOC', 'product': 'MIS', 'source': 'web', 'order_tag': 'order1'}`

still the response validity shows none ?

response - 
`{'status': 'success', 'message': '', 'data': [{'**validity': None**, 'trigger_price': 6.5, 'transaction_type': 'B', 'trading_symbol': 'INFY-EQ', 'rejection_reason': 'RMS: Auto Square Off Block', 'quantity': 1, 'product': 'MIS', 'price_to_fill': 7.0, 'order_status': 'rejected', 'oms_order_id': '210308000259547', 'nest_request_id': None, 'filled_quantity': 0, 'exchange_time': '--', 'exchange_order_id': None, 'exchange': 'NSE', 'disclosed_quantity': '0', 'client_id': '****', 'average_price': 0.0}, {'validity': None, 'trigger_price': 6.5, 'transaction_type': 'B', 'trading_symbol': 'INFY-EQ', 'rejection_reason': '--', 'quantity': 1, 'product': 'MIS', 'price_to_fill': 7.0, 'order_status': 'validation pending', 'oms_order_id': '210308000259547', 'nest_request_id': None, 'filled_quantity': 0, 'exchange_time': '--', 'exchange_order_id': None, 'exchange': 'NSE', 'disclosed_quantity': '0', 'client_id': '*******', 'average_price': 0.0}, {'validity': None, 'trigger_price': 6.5, 'transaction_type': 'B', 'trading_symbol': 'INFY-EQ', 'rejection_reason': '--', 'quantity': 1, 'product': 'MIS', 'price_to_fill': 7.0, 'order_status': 'put order req received', 'oms_order_id': '210308000259547', 'nest_request_id': None, 'filled_quantity': 0, 'exchange_time': '--', 'exchange_order_id': None, 'exchange': 'NSE', 'disclosed_quantity': '0', 'client_id': '******', 'average_price': 0.0}]}`


please have a look why validity is none

**Comment by krishnavelu** [comment]
> This is a valid scenario


What is a valid scenario. Give me a valid use case for IOC order.

**Comment by keerthankumar** [comment]
I don't understand your question. during trading, I place all IOC limit orders. Its a type of order. This is like asking "give me a valid scenario for limit order/cover order".

I use IOC orders to handle slippage.

**Comment by krishnavelu** [comment]
IOC order is not available right now. You've tried modifying the code. But what value you'll send in `'validity': 'IOC'`? there is no documentation available for this.

**Comment by keerthankumar** [comment]
couple of things here - 
1. IOC is supported in ANT Web so that should be available on API, every single broker with API have support. It's ridiculous not to have it because Its hardcoded.
2. When I modified the code to have **order** "**IOC**" instead of "**DAY**". API call does take it otherwise it would have thrown an error, the order is placed in ANTWEB. 
3. order response I get in day/IOC is exactly the same. with validity as **none**. this was my concern does the trading platform recognizing this as IOC and placing or not ?

**Comment by krishnavelu** [comment]
Contact Alice-Blue customer care.

**Comment by keerthankumar** [comment]
Okay i will raise ticket with aliceblue.

**Comment by hardiks2310** [comment]
@keerthankumar I absolutely agree with you that IOC order is a basic necessity in trading. I too use it frequently. Have you found any solution?
@krishnavelu is there any workaround?

**Comment by keerthankumar** [comment]
refer to the comment - https://github.com/krishnavelu/alice_blue/issues/262#issuecomment-792450684 #

**Comment by krishnavelu** [comment]
@keerthankumar you were able to place IOC order by modifying [this](https://github.com/krishnavelu/alice_blue/blob/master/alice_blue/alice_blue.py#L540) line to `IOC` ? Was it working?

**Comment by keerthankumar** [comment]
yes! It works

*/Keerthan*

**Comment by krishnavelu** [comment]
I'll make necessary modification in library.

**Comment by krishnavelu** [comment]
@keerthankumar `place_order` function has `is_ioc` argument now. Please test and let me know if it's working.
Test the latest develop branch.

**Comment by krishnavelu** [comment]
@keerthankumar Did you test? Is the modification ok?

**Comment by keerthankumar** [comment]
havenot tested yet!  im still using the old library with my local changes.
will let you in 2 days

*/Keerthan*

**Comment by krishnavelu** [comment]
@keerthankumar Is it tested? working?
