### ISSUE TITLE
Whenever there is a tick update you'll get through web sockets. its not constant. that comes from exchange -> broker -> Websocket.

### ISSUE THREAD

**Issue by keerthankumar** [krishnavelu/alice_blue#266]
Whenever there is a tick update you'll get through web sockets. its not constant. that comes from exchange -> broker -> Websocket.

_Originally posted by @krishnavelu in https://github.com/krishnavelu/alice_blue/issues/246#issuecomment-770242976_

when you say tick update, do you mean price or anyother pramaers like bid price/quantity or ask price/quantity  For any type of stream?

**Comment by krishnavelu** [comment]
Whatever you subscribe.

**Comment by keerthankumar** [comment]
Its a very cryptic answer. Let me elaborate on the question, If i subscribe symbol say ,

`alice.subscribe(alice.get_instrument_by_symbol('NSE', 'TATASTEEL'), LiveFeedType.MARKET_DATA)`

1. Here if the price remains same for couple of seconds, if bid quantity/price or ask quantity/price changes do i get new data in those seconds ? 


2. Here if i change feed type to `LiveFeedType.COMPACT` Since i will get only price volume, if  if bid quantity/price or ask quantity/price changes do i get new data in those seconds where price remains same? 


Would be great if you could answer.

**Comment by krishnavelu** [comment]
LTP, bid ask changes more frequent than what you expect. So exchange sends only a snapshot of LTP, bid/ask to brokers 3,4 times per second. That’s what you get through this api. If you need ltp bid/ask in actual speed in which it comes, you need a high capacity server, a leased line and you should be near by exchange. Which is co-location servers.

**Comment by keerthankumar** [comment]
thanks for the elaborated answer.
My aim is to get at least 1 snapshot per second. So My understanding
1. if i opt for `LiveFeedType.MARKET_DATA` **i will get 1 snapshot/second.** since _bid/ask to brokers 3,4 times per second_ 
2. If i opt for `LiveFeedType.COMPACT` i will get snapshots only when theres price changes. so 1 snapshot/second not gurenteed. 

Let me know if my above understandings are wrong.

**Comment by krishnavelu** [comment]
In both you’ll get multiple ticks per second.

**Comment by keerthankumar** [comment]
thanks !
