### ISSUE TITLE
Unified API access

### ISSUE THREAD

**Issue by qFactorin** [krishnavelu/alice_blue#269]
Hi Krishna,

Reaching out to you to check if a unified API key pair could be provided for startups. We are working on a product that has potential to take platforms like NEST head on. 

However, since it is heavily reliant on API calls, we are looking for API access that would work for multiple accounts. Looking forward to hear a positive update from you on this.

If you are not the right person to contact on this, could you please suggest the process to get this done. I am expecting a good number of users to be on boarded.

**Comment by krishnavelu** [comment]
Contact Alice customer care.

**Comment by qFactorin** [comment]
Sure, thank you for the quick reply.
