### ISSUE TITLE
get order history, return multiple sections

### ISSUE THREAD

**Issue by keerthankumar** [krishnavelu/alice_blue#272]
Hi Im trying below code,

`print(alice.get_order_history(order_id))`

to fetch order infor for a particular order, But it return the info
```
{'status': 'success', 'message': '', 'data': [{'validity': None, 'trigger_price': 0.0, 'transaction_type': 'B', 'trading_symbol': 'PNB-EQ', 'rejection_reason': '16387 : Security is not allowed to trade in this market  ', 'quantity': 1, 'product': 'MIS', 'price_to_fill': 34.95, 'order_status': 'rejected', 'oms_order_id': '**210416000000375**', 'nest_request_id': None, 'filled_quantity': 0, 'exchange_time': '16-Apr-2021 08:25:34', 'exchange_order_id': '1200000000000219', 'exchange': 'NSE', 'disclosed_quantity': '0', 'client_id': 'AB059409', 'average_price': 0.0}, {'validity': None, 'trigger_price': 0.0, 'transaction_type': 'B', 'trading_symbol': 'PNB-EQ', 'rejection_reason': '--', 'quantity': 1, 'product': 'MIS', 'price_to_fill': 34.95, 'order_status': 'open pending', 'oms_order_id': '**210416000000375**', 'nest_request_id': None, 'filled_quantity': 0, 'exchange_time': '--', 'exchange_order_id': None, 'exchange': 
'NSE', 'disclosed_quantity': '0', 'client_id': 'AB059409', 'average_price': 0.0}, {'validity': None, 'trigger_price': 0.0, 'transaction_type': 'B', 'trading_symbol': 'PNB-EQ', 'rejection_reason': '--', 'quantity': 1, 'product': 'MIS', 'price_to_fill': 34.95, 'order_status': 'validation pending', 'oms_order_id': '**210416000000375**', 'nest_request_id': None, 'filled_quantity': 0, 'exchange_time': '--', 'exchange_order_id': None, 'exchange': 'NSE', 'disclosed_quantity': '0', 'client_id': 'AB059409', 'average_price': 0.0}, {'validity': None, 'trigger_price': 0.0, 'transaction_type': 'B', 'trading_symbol': 'PNB-EQ', 'rejection_reason': '--', 'quantity': 
1, 'product': 'MIS', 'price_to_fill': 34.95, 'order_status': 'put order req received', 'oms_order_id': '**210416000000375**', 'nest_request_id': None, 'filled_quantity': 0, 'exchange_time': '--', 'exchange_order_id': None, 'exchange': 'NSE', 'disclosed_quantity': '0', 'client_id': 'AB059409', 'average_price': 0.0}]}
```

Why its showing the info multiple times ? This looks to me a bug, Please confirm

**Comment by krishnavelu** [comment]
Where it’s showing multiple times?

**Comment by keerthankumar** [comment]
check the data element i pasted above, Why it is list of 4, when im calling a `alice.get_order_history(order_id)` , It will give me the info of that orderId, Am i correct on this expectation ?

**Comment by krishnavelu** [comment]
It is list of 4, but all are different. Check carefully.

**Comment by keerthankumar** [comment]
order id is same! so cant be different

**Comment by krishnavelu** [comment]
Order id is same. There are some differences.

**Comment by keerthankumar** [comment]
correct! In some elements, some fields are shown as "--" .
e.g `exchange_time` parameter. In first element Its '16-Apr-2021 08:25:34' . While In others Its "--" . When Order_id is same 
1. How can you consider these are different?
2.  Why would `Alice.get_order_history(order_id)`, when specifically fetching for particular order Id, gives me 4 different information which are conflicting with each other. 
3. What's the need of giving multiple pieces of information for a particular order ID.?

Are you saying the current behaviour is intended, where you are giving multiple conflicting pieces of information?

**Comment by krishnavelu** [comment]
Inspect all the elements and find out what’s the difference between all 4. This comes from exchange. Not even from alice side. And this library is just a bridge to alice server.

**Comment by keerthankumar** [comment]
differences are -
1. In the first element few parameters like exchange_time, rejection reason etc has values, where in others it doesn't, It shows "--".
2. for parameter `'order_status': 'rejected',` while in remaining 3 elements `'order_status': 'open pending'`  .

Even this comes from exchange this looks to me like a bug, unless they have any reason to give 4 elements for this. 

For now, should we go ahead and take the first element as the correct one and proceed?

**Comment by krishnavelu** [comment]
It’s not a bug. These are all stages of an order.

**Comment by krishnavelu** [comment]
You still didn’t decode it correctly.
`while in remaining 3 elements 'order_status': 'open pending'  . `

this is not true.

**Comment by keerthankumar** [comment]
`It’s not a bug. These are all stages of an order.`

got it! So in summary **first element is the final stage of the order**. is this assumption correct or order may change?

**Comment by krishnavelu** [comment]
That’s sent by exchange. We don’t have any documents confirming that. For now you can assume.

**Comment by chandu4955** [comment]
You can simply use below code to get the latest status of the order.

alice.get_order_history(orderid)['data'][0]['order_status']
