### ISSUE TITLE
Why login and password required to init Aliceblue object 

### ISSUE THREAD

**Issue by agujrathi** [krishnavelu/alice_blue#273]
Hi,

I noticed, this seems to be not exactly oath2 model.
Once token is generated, further to make api calls,  username and password should not be required.

As we have an App running. 
Customers can come in morning and generate token.

Application could later run anything with the help of bearer token. Clients would not be saving their password and would just generate token via URL and go away..

Asking login, password, secret ques to do anything would not make sense..
This seems to be corrected and just token based bearer authentication should be enough to make API calls.  Login, password should not be required other than token generation which is anyhow done by aliceblue URL.

**Comment by krishnavelu** [comment]
I made a mistake in including password argument in `__init__` while creating this library. But now I cannot change this because it will break compatibility. Username is used for different purpose which you can ignore. Try passing None to both username and password. It should work.
