### ISSUE TITLE
Unable to sell Holdings 

### ISSUE THREAD

**Issue by dnaveen2018** [krishnavelu/alice_blue#277]
Hi Krishna,

I am trying to sell my positional holding through Alice blue API but I am not able to do so.

Thank you
Naveen Dasari

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating new issue.

**Comment by dnaveen2018** [comment]
Hi Krishna,

I am getting the below error, is this API not valid for CNC?

{'status': 'error', 'message': 'CNC SELL is not allowed here, use https://ant.aliceblueonline.com Web or Mobile', 'data': {}}

Thank you
Naveen Dasari

**Comment by krishnavelu** [comment]
It’s available for CNC also.

**Comment by dnaveen2018** [comment]
I am getting the above error while placing the market order for CNC.

**Comment by krishnavelu** [comment]
Should be some problem with POA. Try selling through web or mobile app, then try with api.
