### ISSUE TITLE
Best way to extract OHLC data given the time interval.

### ISSUE THREAD

**Issue by ForAlgo** [krishnavelu/alice_blue#278]
Hi All,
I need help in pulling OHLC data from the API real time...please suggest an already inbuilt api function in python to get ohlc data.
Currently I am using tick data of ltp and store for given interval and then make a OHLC out of it...but this is having some little losses due to system bottle neck....request for help on this.

Thank you

**Comment by krishnavelu** [comment]
There is no already inbuilt api function available. You have create from tick data…

**Comment by ForAlgo** [comment]
Sure Thanks for information.
Any best practices for it to ensure there is no delay.
To give with less delay, do we need to run in cloud...and any way to do in
local machine and yet get data without delay...
Please let me know.Thanks in advance 🙏

**Comment by krishnavelu** [comment]
run in cloud and optimize you code for performance.

**Comment by moganraj** [comment]
@ForAlgo Hi Sir/Madam, Can you please confirm if the issue was resolved once you ran in cloud. I am also planning to do the same if it’s resolved.

**Comment by ForAlgo** [comment]
@Moganraj

No..I still needs to do lot of optimization of code I think...

Sure I will let you know if I find...please do the same thank you

**Comment by moganraj** [comment]
@ForAlgo Thank you. Sure I will let you know.

**Comment by ForAlgo** [comment]
Are there any restrictions from nse for running the code in cloud?

**Comment by krishnavelu** [comment]
No. Many does that.
