### ISSUE TITLE
Alice Blue Updated the Authentication Mehod

### ISSUE THREAD

**Issue by ahdbala** [krishnavelu/alice_blue#28]
Hi,

This was really helpful and i wanted to shift my system to Alice Blue from Upstox. But once the account is opened i come to know that they have updated API, and Im looking for sample code according to new method.

**Comment by Parva14** [comment]
A simple moving average strategy by @krishnavelu .
https://gist.github.com/krishnavelu/e0df312ccf5f022edb1823461ff4230e

**Comment by krishnavelu** [comment]
> that they have updated API,

Who has updated API?

**Comment by krishnavelu** [comment]
Hope this is resolved. Closing this. Reopen if you need.
