### ISSUE TITLE
Web socket is always False so the next line of code is not getting executed. 

### ISSUE THREAD

**Issue by moganraj** [krishnavelu/alice_blue#282]
Hi Sir,

while socket_opened == False: become a Infinit loop since the socket is not open. Can you please help me. 

def event_handler_quote_update(message):
    print(f"quote update {message}")

def open_callback():
    global socket_opened
    socket_opened = True

alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
while socket_opened == False:
    pass
alice.subscribe(alice.get_instrument_by_symbol('NSE', 'ONGC'), LiveFeedType.MARKET_DATA)

**Comment by krishnavelu** [comment]
Check your internet connection and check during market hours.

**Comment by kspranava** [comment]
@krishnavelu I am facing the same issue. I tried during market hours and the internet is working fine as well. Am able to get my details and profile successfully.

socket_opened = False
alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)


#print('websocket status is ' + str(socket_opened))
lcount = 0

while (socket_opened == False):
    print('websocket status is ' + str(socket_opened))
    time.sleep(1)
    lcount = lcount + 1
    if lcount == 60:
        print("Exiting as not getting web socket connection")
        exit()
    pass

**Comment by moganraj** [comment]
Thank you Sir. It working for me too. I believe there was internet  connectivity issue

**Comment by krishnavelu** [comment]
@kspranava Why are you exiting. Use the example code as it is without any modifications. And check the internet connection. It works for all.
