### ISSUE TITLE
getting error while generating access token

### ISSUE THREAD

**Issue by DarshanCha** [krishnavelu/alice_blue#284]
Hello,

I am getting following error while api call for access token. I am using php language.

{"error":"invalid_client","error_description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)","error_hint":"The OAuth 2.0 Client supports client authentication method \"client_secret_basic\", but method \"client_secret_post\" was requested. You must configure the OAuth 2.0 client's \"token_endpoint_auth_method\" value to accept \"client_secret_post\".","status_code":401}

Please help.

**Comment by krishnavelu** [comment]
The error message itself gives you the hint. What else you need?

**Comment by krishnavelu** [comment]
Reopen if you need. closing for clean up.
