### ISSUE TITLE
how to get total pnl

### ISSUE THREAD

**Issue by PRAKSH24884** [krishnavelu/alice_blue#286]
i want to pnl i try alice.get_netwise_positions() but its return individual stock pnl iwant total pnl please help

**Comment by krishnavelu** [comment]
[These](https://github.com/krishnavelu/alice_blue/blob/master/alice_blue/alice_blue.py#L450-L464) are the 4 functions to get balances and positions. Try all 4. If you didn't get (directly) what you need, you need to calculate yourself. Calculating PNL is not tough. Just iterate a for loop through all your positions.

**Comment by aeron7** [comment]
Follow this - https://unofficed.com/how-to-get-aliceblue-mtm-and-pl-from-aliceblue-api/

More derivative functions on the algo and usage documentation are long due.
