### ISSUE TITLE
How yo caculate RSI of a given stock

### ISSUE THREAD

**Issue by ForAlgo** [krishnavelu/alice_blue#287]
I want to get a line plot ( or values) realtime of rsi of a given stock. 

Any leads will be helpful.

Thank you

**Comment by krishnavelu** [comment]
There should be so many python libraries available for technical analysis. One such is [this](https://pypi.org/project/ta/)
Note: I’m not recommending this and not using this. It just came up with a quick google search.
Try out tensor flow library from google. Heard it’s too good.

**Comment by ForAlgo** [comment]
Thank you very much for your quick revert...
