### ISSUE TITLE
I want add crossover MACD >0 with MFI 25 length with close >ema21 

### ISSUE THREAD

**Issue by archana25rajendran** [krishnavelu/alice_blue#289]
I want add crossover MACD >0 with MFI 25 length with close >ema21 . please help me how to code 

import logging
import datetime
import statistics
import pandas
from time import sleep
from alice_blue import *
# Config
username = 
password = '
api_secret = 
twoFA = 
app_id = 
EMA_CROSS_SCRIP = 'SILVERM JUN FUT'
logging.basicConfig(level=logging.DEBUG)  # Optional for getting debug messages.
# Config
ltp = 0
socket_opened = False
alice = None
def event_handler_quote_update(message):
    global ltp
    ltp = message['ltp']
def open_callback():
    global socket_opened
    socket_opened = True
def buy_signal(ins_scrip):
    global alice
    alice.place_order(transaction_type=TransactionType.Buy,
                      instrument=ins_scrip,
                      quantity=1,
                      order_type=OrderType.Market,
                      product_type=ProductType.Intraday,
                      price=0.0,
                      trigger_price=None,
                      stop_loss=None,
                      square_off=None,
                      trailing_sl=None,
                      is_amo=False)
def sell_signal(ins_scrip):
    global alice
    alice.place_order(transaction_type=TransactionType.Sell,
                      instrument=ins_scrip,
                      quantity=1,
                      order_type=OrderType.Market,
                      product_type=ProductType.Intraday,
                      price=0.0,
                      trigger_price=None,
                      stop_loss=None,
                      square_off=None,
                      trailing_sl=None,
                      is_amo=False)
def main():
    global socket_opened
    global alice
    global username
    global password
    global twoFA
    global api_secret
    global app_id
    global EMA_CROSS_SCRIP
    minute_close = []
    access_token = AliceBlue.login_and_get_access_token(username=username, password=password, twoFA=twoFA,
                                                        api_secret=api_secret, app_id=app_id)
    alice = AliceBlue(username=username, password=password, access_token=access_token,
                      master_contracts_to_download=['MCX'])
    print(alice.get_balance())  # get balance / margin limits
    print(alice.get_profile())  # get profile
    print(alice.get_daywise_positions())  # get daywise positions
    print(alice.get_netwise_positions())  # get netwise positions
    print(alice.get_holding_positions())  # get holding positions
    ins_scrip = alice.get_instrument_by_symbol('MCX', EMA_CROSS_SCRIP)
    socket_opened = False
    alice.start_websocket(subscribe_callback=event_handler_quote_update,
                          socket_open_callback=open_callback,
                          run_in_background=True)
    while (socket_opened == False):  # wait till socket open & then subscribe
        pass
    alice.subscribe(ins_scrip, LiveFeedType.COMPACT)
    current_signal = ''
    while True:
        if (datetime.datetime.now().second == 0):
            minute_close.append(ltp)
            if (len(minute_close) > 20):
                sma_20 = statistics.mean(minute_close[-20:])
            if ta.trend.MACD(close=pandas.core.series.Series, window_slow=26, window_fast=12, window_sign=9):
                MACD = statistics.mean(minute_close[-26:])
                if (current_signal != 'buy'):
                    if ((minute_close) > sma_20):
                        if MACD > 0: buy_signal(ins_scrip)
                        current_signal = 'buy'
                if (current_signal != 'sell'):
                    if ((minute_close) < sma_20):
                        if MACD < 0: sell_signal(ins_scrip)
                        current_signal = 'sell'
                sleep(1)
                sleep(0.2)  # sleep for 200ms
        if __name__ == '__main__':
            main()
not working

**Comment by jaydave1988** [comment]
You should not post your password and API key.. Anybody can misuse it..

**Comment by archana25rajendran** [comment]
> You should not post your password and API key.. Anybody can misuse it..

sorry i removed , please guide me sir.

**Comment by archana25rajendran** [comment]
strategy("S1-R1-GAIL-pivot",  overlay=true, pyramiding=0)

//Time Conditions
t=time(timeframe.period,"0930-1510")
t2=time(timeframe.period,"0930-1500")
timecond=(t) or (t2)
et=time(timeframe.period,"1500-1505")
symbol=syminfo.ticker
qty1=input(50, title="Input Quantity")




Source = input(close)

// EMA
len = input(21, minval=1, title="Length")
src2 = input(close, title="Source")
offset = input(title="Offset", type=input.integer, defval=0, minval=-500, maxval=500)
out = ema(src2, len)
plot(out, title="EMA", color=color.blue, offset=offset)


//AD
length = input(9, minval=1)
isUp = (close - open) >= 0.0
upBars = sum(isUp ? 1 : 0, length)
downBars = sum(not isUp ? 1 : 0, length)
ad = downBars == 0 ? upBars : upBars / downBars
plot(ad, "ADR_B", #674EA7)
hline(1.0, "Equality Line", #4985E7)

//CCI
length2 = input(20, minval=1)
src1 = input(close, title="Source")
ma = sma(src1, length2)
cci = (src1 - ma) / (0.015 * dev(src1, length2))

// MFI

length3 = input(title="Length", type=input.integer, defval=20, minval=1, maxval=2000)
src3 = hlc3
upper = sum(volume * (change(src3) <= 0 ? 0 : src3), length3)
lower = sum(volume * (change(src3) >= 0 ? 0 : src3), length3)
_rsi(upper, lower) =>
    if lower == 0
        100
    if upper == 0
        0
	100.0 - (100.0 / (1.0 + upper / lower))
mf = _rsi(upper, lower)


higherTF = input("D", type=input.resolution)
prevCloseHTF = security(syminfo.tickerid, higherTF, close[1], lookahead=true)
prevOpenHTF = security(syminfo.tickerid, higherTF, open[1], lookahead=true)
prevHighHTF = security(syminfo.tickerid, higherTF, high[1], lookahead=true)
prevLowHTF = security(syminfo.tickerid, higherTF, low[1], lookahead=true)
pLevel = (prevHighHTF + prevLowHTF + prevCloseHTF) / 3
r1Level = pLevel * 2 - prevLowHTF
s1Level = pLevel * 2 - prevHighHTF
var line r1Line = na
var line pLine = na
var line s1Line = na
if pLevel[1] != pLevel
	line.set_x2(r1Line, bar_index)
	line.set_x2(pLine, bar_index)
	line.set_x2(s1Line, bar_index)
	line.set_extend(r1Line, extend.none)
	line.set_extend(pLine, extend.none)
	line.set_extend(s1Line, extend.none)
	r1Line := line.new(bar_index, r1Level, bar_index, r1Level, extend=extend.right)
	pLine := line.new(bar_index, pLevel, bar_index, pLevel, width=3, extend=extend.right)
	s1Line := line.new(bar_index, s1Level, bar_index, s1Level, extend=extend.right)
	label.new(bar_index, r1Level, "R1", style=label.style_none)
	label.new(bar_index, pLevel, "P", style=label.style_none)
	label.new(bar_index, s1Level, "S1", style=label.style_none)
if not na(pLine) and line.get_x2(pLine) != bar_index
	line.set_x2(r1Line, bar_index)
	line.set_x2(pLine, bar_index)
	line.set_x2(s1Line, bar_index)
	

r2Level = pLevel + (prevHighHTF- prevLowHTF)
s2Level = pLevel - (prevHighHTF- prevLowHTF)
var line r2Line = na

var line s2Line = na
if pLevel[1] != pLevel
	line.set_x2(r2Line, bar_index)
	line.set_x2(pLine, bar_index)
	line.set_x2(s2Line, bar_index)
	line.set_extend(r2Line, extend.none)
	line.set_extend(pLine, extend.none)
	line.set_extend(s2Line, extend.none)
	r2Line := line.new(bar_index, r2Level, bar_index, r2Level, extend=extend.right)
	pLine := line.new(bar_index, pLevel, bar_index, pLevel, width=3, extend=extend.right)
	s2Line := line.new(bar_index, s2Level, bar_index, s2Level, extend=extend.right)
	label.new(bar_index, r2Level, "R2", style=label.style_none)
	label.new(bar_index, pLevel, "P", style=label.style_none)
	label.new(bar_index, s2Level, "S2", style=label.style_none)
if not na(pLine) and line.get_x2(pLine) != bar_index
	line.set_x2(r2Line, bar_index)
	line.set_x2(pLine, bar_index)
	line.set_x2(s2Line, bar_index)	

	
 
r3Level = pLevel *2 + (prevHighHTF - 2 * prevLowHTF)
s3Level = pLevel *2 - (2 * prevHighHTF - prevLowHTF)
var line r3Line = na

var line s3Line = na
if pLevel[1] != pLevel
	line.set_x2(r3Line, bar_index)
	line.set_x2(pLine, bar_index)
	line.set_x2(s3Line, bar_index)
	line.set_extend(r3Line, extend.none)
	line.set_extend(pLine, extend.none)
	line.set_extend(s3Line, extend.none)
	r3Line := line.new(bar_index, r3Level, bar_index, r3Level, extend=extend.right)
	pLine := line.new(bar_index, pLevel, bar_index, pLevel, width=3, extend=extend.right)
	s3Line := line.new(bar_index, s3Level, bar_index, s3Level, extend=extend.right)
	label.new(bar_index, r3Level, "R3", style=label.style_none)
	label.new(bar_index, pLevel, "P", style=label.style_none)
	label.new(bar_index, s3Level, "S3", style=label.style_none)
if not na(pLine) and line.get_x2(pLine) != bar_index
	line.set_x2(r3Line, bar_index)
	line.set_x2(pLine, bar_index)
	line.set_x2(s3Line, bar_index)
	
f_getState(Source,  r3Level, r2Level, r1Level, pLevel, s1Level, s2Level, s3Level)=>
    state =
    
     Source > r3Level ? 3 : 
     Source > r2Level ? 2 :
     Source > r1Level ? 1 :
     Source > pLevel ? 0 :
     Source > s1Level ? -1 :
     Source > s2Level ? -2 :
     Source > s3Level ? -3 :-4
     
    state
	

buy1 = crossover(close,r1Level) and (ad>3) and (cci>50) and (close>out) and (mf>50) and (t) 
sell1 =crossunder(close,s1Level)and (ad<2) and (cci<-50) and (close<out) and(mf<50) and (t) 

this is pine script strategy, same strategy how to code in python. help me

**Comment by krishnavelu** [comment]
I cannot help you for your own application…
