### ISSUE TITLE
Not receiving ticks

### ISSUE THREAD

**Issue by Parva14** [krishnavelu/alice_blue#29]
Is anyone else facing a problem of websocket stopping randomly around 10 AM in the morning?
My algo was trading and I suddenly stopped receiving ticks even though websocket is open.

**Comment by krishnavelu** [comment]
Which version are you using? some problems related to WS are solved in 0.0.5.
I'm able to receive ticks throughout the day from 9:00am to 3:30pm.

**Comment by Parva14** [comment]
I am using 0.0.5 only.

Also, are you able to replicate this error while placing order, happens rarely?
using the same sell signal function you showed in the sma code, just returning order id from it.

 soid[t] = sell_signal(inst_list[t], qty[t])
  File "GL.py", line 392, in sell_signal
    is_amo = False)
  File "C:\Users\I BALL\Anaconda3\lib\site-packages\alice_blue\alice_blue.py", line 527, in place_order
    return self.__api_call_helper(helper, Requests.POST, None, order)
  File "C:\Users\I BALL\Anaconda3\lib\site-packages\alice_blue\alice_blue.py", line 823, in __api_call_helper
    raise requests.HTTPError(response.text)
requests.exceptions.HTTPError: {"errors":{"detail":"Internal server error"}}

**Comment by krishnavelu** [comment]
Try 0.0.6. Just released last weekend.
This happens sometimes off market time, when servers are down.

**Comment by krishnavelu** [comment]
@Parva14 Are you still facing this issue? I'm closing this as of now. Reopen if you are still facing this issue.

**Comment by ns931** [comment]
Hi Parva14,
i'm facing the issue of not receiving the ticks especially around 10:00 AM the ticks are being stopped.
Pls let me know the fix if u have identified.

**Comment by krishnavelu** [comment]
No issues on ticks right now. I'm getting tick from market start to end.
