### ISSUE TITLE
Dear krishnavelu sir i so many try about our sma 5 and 20 crossover program but still not working 

### ISSUE THREAD

**Issue by dishacheck** [krishnavelu/alice_blue#290]
Continue show following error please give solution

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth2/auth?response_type=code&state=test_state&client_id=2a4CBLYTFI&redirect_uri=https://ant.aliceblueonline.com/plugin/callback HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth/login?login_challenge=ecd67f21d40a4b2bb673626f4af17310 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "POST /oauth/login?login_challenge=ecd67f21d40a4b2bb673626f4af17310 HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth/twofa?login_challenge=ecd67f21d40a4b2bb673626f4af17310&login_id=189278&question_ids=35%7C19&questions=Your+Spouses+email-Id+provider+%3F+%28e.g.+gmail%2C+rediffmail%2C+etc%29%7CWhich+company+was%2Fis+your+first+life+insurance+service+provider%3F+%28e.g.+LIC%2C+Bajaj+Allianz%2C+etc.%29 HTTP/1.1" 200 None
INFO:alice_blue.alice_blue:Assuming answers for all 2FA questions are '1', Please change it to '1' if not
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "POST /oauth/twofa?login_challenge=ecd67f21d40a4b2bb673626f4af17310&login_id=189278&question_ids=35%7C19&questions=Your+Spouses+email-Id+provider+%3F+%28e.g.+gmail%2C+rediffmail%2C+etc%29%7CWhich+company+was%2Fis+your+first+life+insurance+service+provider%3F+%28e.g.+LIC%2C+Bajaj+Allianz%2C+etc.%29 HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth2/auth?client_id=2a4CBLYTFI&login_verifier=54620d53a37d4aa4b83681aa8f2131c3&redirect_uri=https%3A%2F%2Fant.aliceblueonline.com%2Fplugin%2Fcallback&response_type=code&state=test_state HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth/consent?consent_challenge=1e42e144ce8844ef91746bbbb8f10b4d HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth2/auth?client_id=2a4CBLYTFI&consent_verifier=a250bff850fe4096bcbd22746cf4146c&redirect_uri=https%3A%2F%2Fant.aliceblueonline.com%2Fplugin%2Fcallback&response_type=code&state=test_state HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /plugin/callback?code=SBXav9o8AaV5wLTW-vaFqzr-AkqqotO58zQgLDeLWhw.wD5rCvKuwPv57GvKl5Vij9RkiSBneXHENyzvlsHitpI&scope=&state=test_state HTTP/1.1" 301 None      
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): ant.aliceblueonline.com:80
DEBUG:urllib3.connectionpool:http://ant.aliceblueonline.com:80 "GET /plugin/callback/?code=SBXav9o8AaV5wLTW-vaFqzr-AkqqotO58zQgLDeLWhw.wD5rCvKuwPv57GvKl5Vij9RkiSBneXHENyzvlsHitpI&scope=&state=test_state HTTP/1.1" 301 None       
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /plugin/callback/?code=SBXav9o8AaV5wLTW-vaFqzr-AkqqotO58zQgLDeLWhw.wD5rCvKuwPv57GvKl5Vij9RkiSBneXHENyzvlsHitpI&scope=&state=test_state HTTP/1.1" 200 None     
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "POST /oauth2/token?client_id=2a4CBLYTFI&client_secret=pwLULQG7G2GiXYNoEfYWlhkwpzqb9rWHajrvYYFcwaEjoHB9B7gIGtvM5UHrWzKw&grant_type=authorization_code&code=SBXav9o8AaV5wLTW-vaFqzr-AkqqotO58zQgLDeLWhw.wD5rCvKuwPv57GvKl5Vij9RkiSBneXHENyzvlsHitpI&redirect_uri=https://ant.aliceblueonline.com/plugin/callback&authorization_response=https://ant.aliceblueonline.com/plugin/callback/?code=SBXav9o8AaV5wLTW-vaFqzr-AkqqotO58zQgLDeLWhw.wD5rCvKuwPv57GvKl5Vij9RkiSBneXHENyzvlsHitpI&scope=&state=test_state HTTP/1.1" 200 None
INFO:alice_blue.alice_blue:access_token - tEreq5cciJ3Z4iWi71y-lBnabgj52AZUKZH6-U-ODDQ.fh37pqI5cHlOAvM1iMeCmaYxYQSckam25AYs92HA0mU
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/profile HTTP/1.1" 200 None
INFO:alice_blue.alice_blue:Downloading master contracts for exchange: NSE
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/contracts.json?exchanges=NSE HTTP/1.1" 200 None
Instrument(exchange='NSE', token=3456, symbol='TATAMOTORS', name='TATA MOTORS LIMITED', expiry=None, lot_size=None)

**Comment by krishnavelu** [comment]
Read this document and try the examples.

 https://github.com/krishnavelu/alice_blue
