### ISSUE TITLE
blocked scripts

### ISSUE THREAD

**Issue by keerthankumar** [krishnavelu/alice_blue#292]
In Aliceblue i see there are lot of scipts are blocked for MIS. like around 1600-2000 stocks blocked. https://aliceblueonline.com/rms-live-updates/

is there anyway to check in api whether the stock is blocked or not ?

Because otherwise we have to keep firing the wrong orders/

**Comment by aeron7** [comment]
```
import pandas as pd

all_tables=pd.read_html("https://aliceblueonline.com/rms-live-updates/")

print("Total Number of Tables: "+ str(len(all_tables)))

#Print Table Number 1
print(all_tables[0])
```

There is no API. You need to scrape the webpage like this. First, scrape all the tables. Then see which table and parse it.
