### ISSUE TITLE
How to handle OHLC data delay and optimize the code for speed

### ISSUE THREAD

**Issue by ForAlgo** [krishnavelu/alice_blue#293]
I thought we can run the code in server and optimize the code for required speed.
Are there any NSE restrictions from individuals running in cloud....how are all people managing this...
Thanks in advance.

**Comment by krishnavelu** [comment]
You can run your code in cloud.

**Comment by ForAlgo** [comment]
Sure Thanks for the reply....is there any good forums/ groups where algotraders interact.

**Comment by krishnavelu** [comment]
https://unofficed.com/chat/
