### ISSUE TITLE
Example code for squaring off/ exiting cover order

### ISSUE THREAD

**Issue by james8865** [krishnavelu/alice_blue#294]
There were two questions regarding exiting the cover order but none actually have a proper solution code/script.

Suppose one has got oms order id from response message and manages to get the oms order id from pending orders, how does one exit after target is met?

**Comment by krishnavelu** [comment]
Refer #56  and #65

**Comment by james8865** [comment]
Sir I was left even more confused after those two threads, I have mentioned in my first comment also.

`alice.cancel_all_orders()` 

Will the above square off/exit the CO position?

**Comment by krishnavelu** [comment]
It should.
