### ISSUE TITLE
Got Internal server error, please try again after sometimes

### ISSUE THREAD

**Issue by Abhishek-code3** [krishnavelu/alice_blue#297]
![image](https://user-images.githubusercontent.com/63147765/121996424-35841780-cdc6-11eb-8680-db81dba6149e.png)

I try so many times in a day.

It's almost a month still getting this error also I tried in market hour , so many mails to customer support but not solved yet.

please Help @krishnavelu sir

Regards
Abhi ..!!

**Comment by krishnavelu** [comment]
Is api enabled in your account? Is answers to all twoFA questions same? ‘ak’? Is remaining credentials correct? Verify all and try during market time.

**Comment by Abhishek-code3** [comment]
> Is api enabled in your account? Is answers to all twoFA questions same? ‘ak’? Is remaining credentials correct? Verify all and try during market time.

yes I enabled api , all answer of twoFA is same "ak" .other credentials are also correct and also I tried in market time. But still  getting this error

**Comment by krishnavelu** [comment]
If everything is correct it should work. It works for everyone. Check with alice if it’s enabled properly.
