### ISSUE TITLE
Rate limits of API

### ISSUE THREAD

**Issue by vishnubharath101** [krishnavelu/alice_blue#298]
Does Alice blue have any rate limitations? How many times we can ping the API in a sec/min/hour/day? I searched quite a lot but couldn't find any but I didn't want to just assume that there are no rate limitations.

**Comment by krishnavelu** [comment]
There is no rate limit currently. But that doesn’t mean you can do every ms. Them alice will be forced to do rate limit. Use it responsibly. Ping the server only beyond 5 seconds, like 30 seconds.

**Comment by viswanath514** [comment]
Hi Krishnavelu, 
Is this still true or rate limits implemented now?

**Comment by krishnavelu** [comment]
Not that I’m aware of.

**Comment by viswanath514** [comment]
Thanks krishnavelu.
