### ISSUE TITLE
How long access tocken stay valid ??

### ISSUE THREAD

**Issue by priyakumariengineer** [krishnavelu/alice_blue#30]
so , how log the access tocken stay valid ?? do we have to generate it once daily similar to upstox and zeordha ?? once generate can we save and use it agin throug out the day ??

**Comment by Parva14** [comment]
Yes, it stays valid throughout the day. You can use it multiple times just like zerodha and upstox.

**Comment by krishnavelu** [comment]
Yes, You should generated only once. stored it and use it throughout the day.

**Comment by krishnavelu** [comment]
Closing as of now.
