### ISSUE TITLE
How to apply leverage for Intraday? I am trying to retrieve the number of shares that can be bought using leverage. Right now i'm only able to retrieve the number shares by dividing the price with balance. But its not accounting for leverage.

### ISSUE THREAD

**Issue by AllenRobinHubert** [krishnavelu/alice_blue#300]

**Comment by krishnavelu** [comment]
It’s automatically applied.

**Comment by AllenRobinHubert** [comment]
Thank you my good sir for the quick reply.
So to clarify, If its automatically applied how do I specify the number of quantity, to use in the code below?
For example, say I want to place an order with the amount 30,000. If the leverage is automatically applied how do i find the number of shares that can be bought? Do i have to manually calculate the number of share, by multiplying the 30,000 with leverage of 10 and then divided by the price of a single share. Or is there a function or method to retrieve that automatically?

`print(
   alice.place_order(transaction_type = TransactionType.Buy,
                     instrument = alice.get_instrument_by_symbol('NSE', 'INFY'),
                     quantity = 1,
                     order_type = OrderType.Market,
                     product_type = ProductType.Intraday,
                     price = 0.0,
                     trigger_price = None,
                     stop_loss = None,
                     square_off = None,
                     trailing_sl = None,
                     is_amo = False)
)`

**Comment by krishnavelu** [comment]
https://aliceblueonline.com/margin-calculator/commodity/

**Comment by AllenRobinHubert** [comment]
Thanks pal
