### ISSUE TITLE
How to place Modify Order?

### ISSUE THREAD

**Issue by codewithraviteja** [krishnavelu/alice_blue#301]
I have placed an order and want to modify the order with a stoplossMarket

Getting Order ID from this code 
```
get_current_order_id = alice.get_daywise_positions()['data']['positions'][0]['oms_order_id']
print("Current Order ID "+ str(get_current_order_id))
```
But oms_order_id is getting NONE
```
print(alice.modify_order(transaction_type = TransactionType.Buy,order_id = get_current_order_id,
                     instrument = bn_call,
                     quantity = 25,
                    order_type = OrderType.StopLossMarket,
                     product_type = ProductType.Intraday,
                     price = 0.0,
                     trigger_price = 50.00,
                     stop_loss = None,
                     square_off = None,
                     trailing_sl = None,
                     is_amo = False))
```
How can I place the modified order?

**Comment by krishnavelu** [comment]
While placing the order you’ll get oms order id. Modify using that.

**Comment by codewithraviteja** [comment]
Could you please explain in detail. I am getting NONE. I have first placed an order and then I want to modify it but when I am trying to get order ID, it shows NONE. It will be in the positions right. PLease help me here and could you please tell me how to exit the placed order with sl?

**Comment by krishnavelu** [comment]
You are doing get_daywise_postion thats why you are getting none. While placing the order the function will return order id
