### ISSUE TITLE
How to use the scripting API and get detailed data of a script

### ISSUE THREAD

**Issue by sohamkumarbanik** [krishnavelu/alice_blue#303]
Hi, I need detailed info about a script and I see that Alice has got an API named "scriptinfo". How do I use that. Please let me know. Thank you.

**Comment by krishnavelu** [comment]
Try this function 
`get_scrip_info`

**Comment by sohamkumarbanik** [comment]
Thank you, and what are the arguments to be passed.

**Comment by krishnavelu** [comment]
https://github.com/krishnavelu/alice_blue/blob/master/alice_blue/alice_blue.py#L473

**Comment by sohamkumarbanik** [comment]
Thank you. Its done!
