### ISSUE TITLE
Order book from API

### ISSUE THREAD

**Issue by sseshank** [krishnavelu/alice_blue#304]
Hi,  

Web interface provides Bid/Ask order book upto 20 depth. Are there any plans to implement that. 

Thanks in advance.

Regards,
Seshank

**Comment by krishnavelu** [comment]
Not coming anytime soon. Alice should implement this in this server. The I can do feature additions in this library.
Contact alice blue.

**Comment by krishnavelu** [comment]
@sseshank update for you. Alice has some updates. This library is going to get a huge update. Order update is also coming on that. For now closing this issue. Follow issue #2
