### ISSUE TITLE
Got an error while Modifying the current pending order

### ISSUE THREAD

**Issue by codewithraviteja** [krishnavelu/alice_blue#305]
I got an error when modifying the current pending order 

TypeError: modify_order() got an unexpected keyword argument 'stop_loss'

`print(
            alice.modify_order(transaction_type = TransactionType.Buy,order_id = get_current_order_id,
                               instrument = enter_strike,
                               quantity = enter_quantity,
                               order_type = OrderType.StopLossMarket,
                               product_type = ProductType.Intraday,
                               price = 0.0,
                               trigger_price = 50.00,
                               stop_loss = None,
                               square_off = None,
                               trailing_sl = None,
                               is_amo = False))`

Please help me here

**Comment by krishnavelu** [comment]
This is a python error. You are passing wrong arguments.

**Comment by codewithraviteja** [comment]
Could you please tell me where did I do mistake?

**Comment by krishnavelu** [comment]
The error itself says that clearly.
`TypeError: modify_order() got an unexpected keyword argument 'stop_loss' `

**Comment by codewithraviteja** [comment]
So, I have to assign only these? modify_order( transaction_type, instrument, product_type, order_id, order_type, quantity, price=0.0,
                     trigger_price=0.0)

**Comment by krishnavelu** [comment]
Learn python fully and then enter into automated trading. Without this you’ll make a huge loss.

**Comment by codewithraviteja** [comment]
I got the answer. Thank you for your feedback.
