### ISSUE TITLE
Not able to sell CNC

### ISSUE THREAD

**Issue by Somenath24** [krishnavelu/alice_blue#307]
I am not able to sell CNC using this, getting below error, is this API doesn't work for CNC sell? 

{'status': 'error',
 'message': 'CNC SELL is not allowed here, use https://ant.aliceblueonline.com Web or Mobile',
 'data': {}}

**Comment by krishnavelu** [comment]
Check if you are able to do the same using web. You should be having POA issue.

**Comment by Somenath24** [comment]
I tried, I can do it through web (https://ant.aliceblueonline.com) , but from API, I am getting this error.

**Comment by krishnavelu** [comment]
Did you enter any OTP through web? Is your POA intact?

**Comment by Somenath24** [comment]
I tried through OTP. so is POA activation needed for API sell?

**Comment by krishnavelu** [comment]
Yes.

**Comment by keerthankumar** [comment]
Hi, Im facing the same issue Not able to sell CNC holding getting error - 
{'status': 'error', 'message': 'CNC SELL is not allowed here, use https://ant.aliceblueonline.com Web or Mobile', 'data': {}}

I can do it in ANT Web without OTP ?
My POA is complete

**Comment by krishnavelu** [comment]
There are some problems in CNC sell using API across all brokers. Contact Alice.

**Comment by Santunav** [comment]
I'm also facing same error,My POA is active,  I could able to sell via web without OTP. 
@krishnavelu   what is the solution, please suggest

**Comment by krishnavelu** [comment]
There is no solution currently for this. Contact Alice.

**Comment by Santunav** [comment]
> 

ok
