### ISSUE TITLE
Issue in market_data

### ISSUE THREAD

**Issue by prith1990** [krishnavelu/alice_blue#308]
Hi Sir,

When I subscribe to any scrips using market_data, I see you a gap in the open, high, low, close of Alice blue when compared to other brokers and even trading view. Is this data not reliable?

example: I checked this on a saturday evening around 7:30. 
SBIN:  the LTP was 385 in Alice blue, whereas in kite and tradingview it was 423. 

Is this data not reliable or it works only when the market is open?
Can you please explain?

**Comment by krishnavelu** [comment]
After market close there is no use of LTP. So do not consider. Also the close price is a little different in different brokers. Some shows previously close and some shows current close. Try market time
