### ISSUE TITLE
Not able to find index (spot) prices in live/historical data. but able to find instrument details in get_instrument_by_symbol

### ISSUE THREAD

**Issue by kamadinesh** [krishnavelu/alice_blue#309]
Here details which I am talking about.

	Able to find index instrument details using below
# print(sas.get_instrument_by_token('NSE','26009'))
# print(sas.get_instrument_by_token('NSE','26000'))
# print(sas.get_instrument_by_symbol('NSE', 'Nifty Bank'))
# print(sas.get_instrument_by_symbol('NSE', 'Nifty 50'))

exchange='NSE'
symbol='NiftyBank'

	Not able to get data in historical candles
data = sas.get_historical_candles(exchange,symbol,start_time,end_time,1)

C:\Users\admin\anaconda3\python.exe F:/algo/aphatrade1/alphatrade/examples/occ_v1.py
Instrument(exchange='NSE', token=26009, symbol='Nifty Bank', name='Nifty Bank', expiry=None, lot_size=None)
Empty DataFrame
Columns: [date, open, high, low, close, volume]
Index: []

Process finished with exit code 0

	Not able to get index data in intraday candles data
data = sas.get_intraday_candles(exchange,symbol,1)
C:\Users\admin\anaconda3\python.exe F:/algo/aphatrade1/alphatrade/examples/occ_v1.py
Cannot find symbol NSE NIFTY BANK in master contract
Traceback (most recent call last):
  File "F:/algo/aphatrade1/alphatrade/examples/occ_v1.py", line 41, in <module>
    data = sas.get_intraday_candles(exchange,symbol,1)
  File "F:\algo\aphatrade1\alphatrade\examples\alphatrade.py", line 1103, in get_intraday_candles
    'token': instrument.token
AttributeError: 'NoneType' object has no attribute 'token

Thanks

**Comment by krishnavelu** [comment]
This library doesn’t have a function named `get_historical_candles`
Read the document fully.

**Comment by kamadinesh** [comment]
issue is resolved now. we can close this issue. thanks krishnavelu

**Comment by Tyrostir** [comment]
> This library doesn’t have a function named `get_historical_candles` Read the document fully.

@krishnavelu Hello sir. He may be mistyped the function name as `get_historical_candles`. But **the question still remains unanswered**. I am also not able to get historical data for **Nifty Bank** or **Nifty 50** index. But I am able to get historical data for **HDFCBANK-EQ** or **INFY-EQ**.
I use below code snippet for that.

`from alice_blue import *`
`session_id = AliceBlue.login_and_get_sessionID(username='username',
password='password',
twoFA='1993',
app_id='app_id',
api_secret='api_secret')`
`alice = AliceBlue(username='username', session_id=session_id)`
`hData = alice.historical_data(alice.get_instrument_by_symbol('NSE', 'NIFTY BANK'), datetime.now(), datetime.now(), HistoricalDataType.Minute)`
`print(hData)`

And below is the output I got.
`{'emsg': 'No data available', 'stat': 'Not_Ok'}`

But if I try the same for INFY-EQ or HDFCBANK-EQ, I am able to see valid data.

Please comment on this to help us.

Thanks in advance.

**Note**: I am trying this after IST 5:30 PM only.

**Comment by krishnavelu** [comment]
See if you are able to get instrument properly. Also not sure if we can get history for index in Alice. Need to test. Try both indexes.

```
nifty50_nse_index = alice.get_instrument_by_symbol('NSE', 'NIFTY 50')
banknifty_nse_index = alice.get_instrument_by_symbol('NSE', 'NIFTY Bank')
```
