### ISSUE TITLE
How to get the option chain data from Alice Blue

### ISSUE THREAD

**Issue by grsb007** [krishnavelu/alice_blue#31]
Hello Team,

How to get the option chain data from Alice blue API to say Nifty, referring following URL from NSE.

https://www.nseindia.com/live_market/dynaContent/live_watch/option_chain/optionKeys.jsp

Could you please share some sample program for this.

Thanks,

**Comment by krishnavelu** [comment]
alice-blue doesn't provide option chain data.
You can scrap from nse itself using [request](https://pypi.org/project/requests/). But soon you'll get blocked from nse.

**Comment by grsb007** [comment]
Understood, but May I know what is use of following class in the code and how get this data and fill this data, can you pl help me on this 
class OpenInterest(CStruct):
    exchange = CUChar()
    token = CUInt()
    current_open_interest = CUChar()
    initial_open_interest = CUChar()
    exchange_time_stamp = CUInt()

**Comment by krishnavelu** [comment]
As per this [document](http://antplus.aliceblueonline.com/#open-interest) I created the structure.
But as per [this](http://antplus.aliceblueonline.com/#modes), we cannot subscribe OI.

**Comment by grsb007** [comment]
Understood, can we get some help from AB. Because the Market is not giving all the data

**Comment by krishnavelu** [comment]
Contact alice.
Also this is similar to #35
