### ISSUE TITLE
Error while getting live feed

### ISSUE THREAD

**Issue by krisnapradeep** [krishnavelu/alice_blue#310]
I am getting the below error while getting live feed. This error arises once in a while only.

error from callback <bound method AliceBlue.__on_error_callback of <alice_blue.alice_blue.AliceBlue object at 0x000001A2351C28B0>>: on_error() takes 1 positional argument but 2 were given

error from callback <bound method AliceBlue.__on_close_callback of <alice_blue.alice_blue.AliceBlue object at 0x000001A2351C28B0>>: __on_close_callback() takes from 1 to 2 positional arguments but 4 were given

**Comment by krishnavelu** [comment]
If you are using those callbacks, give the arguments correcty.
