### ISSUE TITLE
Error in Authentication - Correct login Credentials

### ISSUE THREAD

**Issue by SudhagarR** [krishnavelu/alice_blue#312]
Hi Krishna,

I have created obtained API keys from Aliceblue and Followed based on you documentation., Getting below error and not getting through .. My login credential and API key details are correct but still facing issue .. Could you please assist on this 

`PS D:\LAB\Conda\envs\Alice> & D:/LAB/Conda/envs/Alice/python.exe d:/LAB/Conda/envs/Alice/Alice.py
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth2/auth?response_type=code&state=test_state&client_id=C4YwnmGb2O&redirect_uri=https://ant.aliceblueonline.com/plugin/callback HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth/login?login_challenge=e14eaa08fc3a4ebea321d8885682a272 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "POST /oauth/login?login_challenge=e14eaa08fc3a4ebea321d8885682a272 HTTP/1.1" 200 None
ERROR:alice_blue.alice_blue:Please enter a valid password`

**Comment by krishnavelu** [comment]
ERROR:alice_blue.alice_blue:Please enter a valid password

**Comment by SudhagarR** [comment]
@krishnavelu Thanks for reply ., Actually credential is correct.. I found workaround solution manual token request by Postman., You can close the case ..
