### ISSUE TITLE
Lag while Fetching data for more scripts

### ISSUE THREAD

**Issue by MaticAlgos** [krishnavelu/alice_blue#313]
Hello,
While using websocket, if I subscribe for more scripts, the data fetching lags. 
Is there anyway we can create threads so that tick data is loaded for all the scripts at the same time? 

Again thank you for creating this amazing library.

**Comment by krishnavelu** [comment]
Read this comment and the whole issue.
https://github.com/krishnavelu/alice_blue/issues/145#issuecomment-650796613
