### ISSUE TITLE
Websocket reconnection

### ISSUE THREAD

**Issue by PhoenixNK** [krishnavelu/alice_blue#318]
Hi, I can trade when the internet is working continuously. once the internet is disconnected, the algo stops and does not reconnect again. It gives below error.
ERROR:websocket:error from callback <bound method AliceBlue.__on_close_callback of <alice_blue.alice_blue.AliceBlue object at 0x0000020D913DBB48>>: __on_close_callback() takes from 1 to 2 positional arguments but 4 were given
  File "C:\ProgramData\Anaconda3\lib\site-packages\websocket\_app.py", line 407, in _callback
    callback(self, *args)
Could you please help me out to solve this issue.

**Comment by krishnavelu** [comment]
I've also faced this during 11th and 12th dates. But on 13th it was ok. Something was changed in Alice end. Due to this it was getting this exception. Let me know if you are facing this on going forward.

**Comment by PhoenixNK** [comment]
Hi, Thanks for your reply. This problem in not only for 11th and 12th. On any day if my internet disconnects due to any reason, then when i get the internet back, I do not get the feed again. And the shown error is displayed instead of reconnecting. 
Normally I do restart the kernel (in Spyder IDE). But this is not reliable thing as whatever orders are placed in algo, I need to monitor those manually and if internet is disconnected, I have to exit those manually.

**Comment by vinutshetty** [comment]
same here same errors

**Comment by krishnavelu** [comment]
Home internet is always unreliable. Use cloud computing like AWS or GCP.

**Comment by PhoenixNK** [comment]
Thanks a lot for your help . I will explore the options you suggested.
