### ISSUE TITLE
subscribe function is not working

### ISSUE THREAD

**Issue by kumarraditya** [krishnavelu/alice_blue#320]
Hi,
I am able to download # print(alice.get_master_contract('NSE')), But as soon as I fire this one its got hanged nothing coming up. is there any problem in sbscribe function . infant in debug also stopped seem nothing is rolling. 
rel=alice.subscribe(alice.get_instrument_by_symbol('NSE', 'TATASTEEL'), LiveFeedType.COMPACT)
====
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/profile HTTP/1.1" 200 None
INFO:alice_blue.alice_blue:Downloading master contracts for exchange: NSE
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/contracts.json?exchanges=NSE HTTP/1.1" 200 None
INFO:alice_blue.alice_blue:Downloading master contracts for exchange: BSE
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /api/v2/contracts.json?exchanges=BSE HTTP/1.1" 200 None

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating new issue.

**Comment by krishnavelu** [comment]
Hope your issue is resolved, reopen if not.
