### ISSUE TITLE
Activiatuon of API key aliceblue

### ISSUE THREAD

**Issue by ForAlgo** [krishnavelu/alice_blue#321]
I have received an email to accept the terms and conditions of API usage...

In that it says APIs are not meant for fully automated trades ( without manual intervention )....
So APIs can't be used for full Algotrading?..I mean u inbuilt a strategy and based on the output of that strategy your buy and sell gets executed....
Is this not allowed?

**Comment by krishnavelu** [comment]
Contact alice blue.

**Comment by krishnavelu** [comment]
Hope your issue is resolved, reopen if not.
