### ISSUE TITLE
.NET Support or Package for Alice Blue 

### ISSUE THREAD

**Issue by vijaysahu12** [krishnavelu/alice_blue#323]
Badly looking for .net Support. 

I am able to get the **code** but facing so many issue while getting access token. 

`{"error":"invalid_client","error_description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)","status_code":401}`

**Comment by krishnavelu** [comment]
Try your credential with python library first. If it's working slowly move each and every code part to .NET. I can help you if you find any difficulty in understanding any part of code.

**Comment by krishnavelu** [comment]
Hope your issue is resolved, reopen if not.

**Comment by vijaysahu12** [comment]
Able to generate the CODE but not able to get the AccessToken using The Code. 

Here is the code sample which I am using to get the access token.

string AccessToken = "";
            string encoder = ClientID + ":" + ClientSecret;
            var plainTextBytes = System.Text.Encoding.UTF8.GetBytes(encoder);
            string basicauthentication = System.Convert.ToBase64String(plainTextBytes);
            var client = new RestClient("https://ant.aliceblueonline.com/oauth2/token");
            var request = new RestRequest(Method.POST);
            request.AddHeader("Authorization", "Basic " + basicauthentication + "");
            request.AddHeader("Content-Type", "application/x-www-form-urlencoded");
            request.AddParameter("undefined", "grant_type=authorization_code&code=" + Code + "&client_id=" + ClientID + "&client_secret_post=" + ClientSecret + "&redirect_uri=" + redirectURL + "&authorization_response=authorization_response", ParameterType.RequestBody);
            IRestResponse response = client.Execute(request);
            AccessToken = response.Content;
            return AccessToken;
            
Here is the response error code 
{"error":"invalid_client","error_description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)","status_code":401}
            
Let me know if you want me to open a new ticket....

**Comment by krishnavelu** [comment]
> Try your credential with python library first. If it's working slowly move each and every code part to .NET

Did you try this?

**Comment by indibar** [comment]
You can contact http://algo2trade.com/ for .NET support

**Comment by indibar** [comment]
You can contact http://algo2trade.com/ for .NET support

**Comment by krishnavelu** [comment]
Closing. Reopen if needed.
