### ISSUE TITLE
How to call Simultaneous calls to API for multiple users

### ISSUE THREAD

**Issue by codewithraviteja** [krishnavelu/alice_blue#324]
I have placed AliceBlue API in Webserver , and created multiple user session and while I am calling to API using different users API keys , the orders are passing to latest user session Account .. how to overcome this to place orders to individual accounts?

**Comment by krishnavelu** [comment]
Create single Alice blue object for every single user. Use that particular object for that user. Learn OOPS concept and python deeply.

**Comment by krishnavelu** [comment]
Hope your issue is resolved, reopen if not.
