### ISSUE TITLE
ERROR:websocket:error from callback <bound method AliceBlue.__on_close_callback of <alice_blue.alice_blue.AliceBlue object at 0x7fc429844430>>: __on_close_callback() takes from 1 to 2 positional arguments but 4 were given

### ISSUE THREAD

**Issue by vsdeepazzz** [krishnavelu/alice_blue#325]
socket_opened = False

def event_handler_quote_update(message):
    print(f"quote update {message}")

def open_callback():
    global socket_opened
    socket_opened = True

alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
while (socket_opened == False):
    pass
alice.subscribe(alice.get_instrument_by_symbol('CDS', 'USDINR SEP FUT'), LiveFeedType.MARKET_DATA)
sleep(10)

i am getting below error in loop

ERROR:websocket:error from callback <bound method AliceBlue.__on_close_callback of <alice_blue.alice_blue.AliceBlue object at 0x7fb74d874a90>>: __on_close_callback() takes from 1 to 2 positional arguments but 4 were given
ERROR:websocket:error from callback <bound method AliceBlue.__on_close_callback of <alice_blue.alice_blue.AliceBlue object at 0x7fb74d874a90>>: __on_close_callback() takes from 1 to 2 positional arguments but 4 were given
ERROR:websocket:error from callback <bound method AliceBlue.__on_close_callback of <alice_blue.alice_blue.AliceBlue object at 0x7fb74d874a90>>: __on_close_callback() takes from 1 to 2 positional arguments but 4 were given
ERROR:websocket:error from callback <bound method AliceBlue.__on_close_callback of <alice_blue.alice_blue.AliceBlue object at 0x7fb74d874a90>>: __on_close_callback() takes from 1 to 2 positional arguments but 4 were given

Mac
Pycharm
Python 3.9.6

**Comment by krishnavelu** [comment]
Alice recently changed their callback in their end. Need to fix in library. wait for few days.

**Comment by vsdeepazzz** [comment]
Thank you for looking into this.. I later changed the code to spyder IDE and it is working fine with same library. Am not sure why this  was showing error in pycharm. In pycharm, i tried to introduce passing parameters in implementation and this error was gone but socket was not connecting. Anyway i will wait for the library update and for the time being i will continue with spyder . Thank you

**Comment by vinutshetty** [comment]
@krishnavelu First of all thank you for this project. Same issue faced by me as well. Is there an ETA for this?

![image](https://user-images.githubusercontent.com/68838765/133656087-1decf04c-8514-4d8d-b58a-b3cac8049da9.png)
