### ISSUE TITLE
Unable to access historic api using token

### ISSUE THREAD

**Issue by Pavantejapenugonda** [krishnavelu/alice_blue#327]
I am trying to access historic api (to get candles data per second)

URL : https://ant.aliceblueonline.com/api/v1/charts?exchange=NSE&token=3045&candletype=1&starttime=1596825000&endtime=1598121000&type=historical&data_duration=10
error : Unauthorized error
I provided token that generated using this method: AliceBlue.login_and_get_access_toke()

can you help me to resolve this issu

**Comment by krishnavelu** [comment]
Historic api is not supported by this library.

**Comment by Pavantejapenugonda** [comment]
Then how can I generate token to access historic api

**Comment by krishnavelu** [comment]
I said Historic api is not supported.

**Comment by Pavantejapenugonda** [comment]
I got it and asking how can I acces Historic api Alice blue not providing Historic api ?

**Comment by krishnavelu** [comment]
No
