### ISSUE TITLE
V2 api update

### ISSUE THREAD

**Issue by mehtakrunal19** [krishnavelu/alice_blue#328]
Hello
Will the codes be updated as per new version of api as mail from aliceblue ..?
I guess there are changes in the order placement

**Comment by krishnavelu** [comment]
which one you are referring to?

**Comment by mehtakrunal19** [comment]
![Uploading Screenshot_20210831-203029.jpg…]()

**Comment by mehtakrunal19** [comment]
![Uploading Screenshot_20210831-203029.jpg…]()

**Comment by mehtakrunal19** [comment]
Hi,
As part of our ongoing commitments to security and enhancement, we are making updates in our API platform. You can find the new API documentation here https://antplus2.aliceblueonline.com/. Feeds API will remain the same. API keys and secrets will remain the same. Authentication process is also the same. This changes will be effective from September 4, 2021.

Only the Modify order functionality will not work for that you need to use the new API. All the other API functionality will work fine without any issues. However I would suggest you to start migrating to the new API platform as it is more robust and contains additional features. Previously created API Keys will work fine without any issues. However the API keys created after Saturday need to use the new API. /
Regards
Aliceblue Financial Service Pvt Ltd

**Comment by amit-kumar27742** [comment]
Dear all, the upgrade email received from Aliceblue is quite confusing. The requests url they have mentioned seems to be old one as its v1 in the url...  'api/**v1**/order**s**' where as we are already using v2 in '/api/**v2**/order'. Also observe the 'orders' vs 'order'.

If above is ignored, then in modify order 'order_side' looks to be an additional parameter.

Have dropped email to them, not sure if proper response will be received before changes.

Can any of you working on this, post any pointers here in this issue log. It will be of great help. Thanks.

**Comment by amit-kumar27742** [comment]
Any update please?

**Comment by amit-kumar27742** [comment]
looks like no changes done by aliceblue. Order modifications working as usual.

**Comment by krishnavelu** [comment]
Nothing yet

**Comment by krishnavelu** [comment]
No V2 api is coming as far as I know. I’ll update the library if it coming. Closing this as of now.
