### ISSUE TITLE
Storing Live ltp into SQL database

### ISSUE THREAD

**Issue by tejasnavalkhe** [krishnavelu/alice_blue#329]
How to store live ltp of given stocks into database? I am unable to do so. Please try to solve as soon as possible.
[abc.txt](https://github.com/krishnavelu/alice_blue/files/7110201/abc.txt)

Thank You

**Comment by krishnavelu** [comment]
Learn python.

**Comment by tejasnavalkhe** [comment]
I know flask and python. Please check above file, there I am using websocket but when I am searching into database for particular stock I am unable to get any result in event_handler_quote_update function. Please solve my issue.

**Comment by krishnavelu** [comment]
I cannot help for your application. Follow the examples given in the documentation. If it works then add whatever you want on top of that.

Also Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating a new issue.

**Comment by tejasnavalkhe** [comment]
For better performance to store live ltp into database please user nsetools https://nsetools.readthedocs.io/en/latest/introduction.html It's preety simple to use.
