### ISSUE TITLE
how to get callback when socket disconnected

### ISSUE THREAD

**Issue by rajeshjoshi8792** [krishnavelu/alice_blue#332]
i want to know how i get callback when socket disconnected or any other reason i unable to get any response from api?

**Comment by krishnavelu** [comment]
When you start websocket, you can give a bunch or arguments. Refer this line.

https://github.com/krishnavelu/alice_blue/blob/master/alice_blue/alice_blue.py#L404

**Comment by krishnavelu** [comment]
Hope your issue is solved, reopen if not.
