### ISSUE TITLE
API Timeout configuration?

### ISSUE THREAD

**Issue by vinutshetty** [krishnavelu/alice_blue#333]
hi, I have seen cases where API can take several minutes to come back slowing down the whole process.  is there a way to configure timeout for the APIs.?

I saw the API CALL module and currently no timeout configured as such.

def __api_call(self, url, http_method, data):
        #logger.debug('url:: %s http_method:: %s data:: %s headers:: %s', url, http_method, data, headers)
        headers = {"Content-Type": "application/json"} 
        if(len(self.__access_token) > 100):
            headers['X-Authorization-Token'] = self.__access_token
            headers['Connection'] = 'keep-alive'
        else:
            headers['client_id'] = self.__username
            headers['authorization'] = f"Bearer {self.__access_token}"
        r = None
        if http_method is Requests.POST:
            r = requests.post(url, data=json.dumps(data), headers=headers)
        elif http_method is Requests.DELETE:
            r = requests.delete(url, headers=headers)
        elif http_method is Requests.PUT:
            r = requests.put(url, data=json.dumps(data), headers=headers)
        elif http_method is Requests.GET:
            r = requests.get(url, headers=headers)
        return r

Is it ok if we make an edit like below -

requests.post(x,y,z,.., timeout=10)

Do you see any issues?

**Comment by krishnavelu** [comment]
There is a default timeout. Not sure where it is. About modifications, if you know what you are doing, you can do that. In your personal fork.
Fork the library and do whatever changes you need.

**Comment by vinutshetty** [comment]
I have made this change locally and will test it out over the next few days. Thank you Krishna.
