### ISSUE TITLE
2FA login password changed from Aliceblue side - any API change?

### ISSUE THREAD

**Issue by vsdeepazzz** [krishnavelu/alice_blue#334]
Hi Krishna,

Today i received an email from AB saying

"ALICEBLUE changed the 2fa login mechanism into single question(YEAR OF BIRTH). After entering the password instead of 2 fa you have to enter the 4-digit your year of birth."

Does that mean backend api will also change?

Thanks
Deepa

**Comment by krishnavelu** [comment]
New version 1.0.2 released fixing this.
