### ISSUE TITLE
API Changes From Alice - Not Able to generate token

### ISSUE THREAD

**Issue by tulkodo** [krishnavelu/alice_blue#335]
Hi 
I received email below from Alice on 31st Aug 2021. Today, I created app and trying to retrieve token as per instructions provided within this repository document, but getting Error => OAuth 2.0 Error occurred. Please verify your api_secret .. Exception: Couldn't get profile info with credentials provided 'object of type 'NoneType' has no len()'.
With same process I was able to generate token last month (Aug 2021).

Please could you help?
Thank You!

Alice Email Content:
******************************************
Hi,
As part of our ongoing commitments to security and enhancement, we are making updates in our API platform. You can find the new API documentation here https://antplus2.aliceblueonline.com/. Feeds API will remain the same. API keys and secrets will remain the same. Authentication process is also the same. This changes will be effective from September 4, 2021.

Only the Modify order functionality will not work for that you need to use the new API. All the other API functionality will work fine without any issues. However I would suggest you to start migrating to the new API platform as it is more robust and contains additional features.

Previously created API Keys will work fine without any issues. However the API keys created after Saturday need to use the new API.

Regards
Aliceblue Financial Service Pvt Ltd
******************************************

**Comment by krishnavelu** [comment]
New version 1.0.2 released fixing this.
