### ISSUE TITLE
Getting None for Nifty option strike 

### ISSUE THREAD

**Issue by grsb007** [krishnavelu/alice_blue#34]
Using latest code i.e. 0.0.6, for Nifty option/s getting None, please see the sample code

Nifty_call = alice.get_instrument_for_fno(symbol = 'NIFTY', expiry_date=datetime.date(2019, 12, 12), is_fut=False, strike=11950, is_CE = True)
Nifty_put = alice.get_instrument_for_fno(symbol =  'NIFTY', expiry_date=datetime.date(2019, 12, 12), is_fut=False, strike=11950, is_CE = False)

Could you please help me with this.

**Comment by krishnavelu** [comment]
@grsb007 fixed in develop. Please take latest develop and test.

**Comment by grsb007** [comment]
the fix is working
