### ISSUE TITLE
High Memory Usage: master_contracts_to_download 

### ISSUE THREAD

**Issue by vinutshetty** [krishnavelu/alice_blue#340]
Hi Krishna and team,

I am observing high memory usage depending on the number of master contracts we download. Just an example - Currently I am only downloading NSE and NFO and it's around 100M RAM consumed. When I use the same script and login with 2 Alice Trading accounts memory doubles to 200M RAM consumed. 

The question I have is what happens if I don't download any master contracts? What scenarios master contracts stired in AliceBlue object is being used. 

Is it possible to use AliceBlue object-1 with master contract but AliceBlue object-2 without a master contarct and still place orders using both connection objects?

Thank you in advance.

**Comment by krishnavelu** [comment]
This library uses downloaded master contracts. So downloading master contract is must. Just download whatever you need as per segment. 200M RAM is nothing nowadays. When I made this library, no consideration was made regarding ram consumption, as this is not an embedded systems program. This is going to be run in a PC where you have plenty of ram available.

```
Is it possible to use AliceBlue object-1 with master contract but AliceBlue object-2 without a master contarct and still place orders using both connection objects?
``` 
Not possible
