### ISSUE TITLE
Is it possible to implement single code and can be used by multiple users by accessing that same code with AliceBlue?

### ISSUE THREAD

**Issue by codewithraviteja** [krishnavelu/alice_blue#347]
Hello Krishnavelu, 
                      We have developed a small strategy and using through using Aliceblue API. We have deployed it in server. I have created session management but when user is accessing same code, it's not working. Example : If 1st user connects with his API and then the second user connects with his API, then all the orders from 1st and 2nd user are placing in 2nd user account. Could you please give me some idea on how to implement multiple users can connect and access the same code which was deployed in the server?

**Comment by krishnavelu** [comment]
I don't know what session management you've done. But if you create different Alice blue objects for different users, it should work.

**Comment by codewithraviteja** [comment]
Thank you
