### ISSUE TITLE
Error calling modify_order

### ISSUE THREAD

**Issue by RajeshSivadasan** [krishnavelu/alice_blue#349]
I am getting the below error while calling alice.modify_order(). I am not passing the quantity argument as I want only to change the price. But as per the procedure documentation, quantity is optional. Kindly check and confirm.

"missing 1 required positional argument: 'quantity'"

**Comment by krishnavelu** [comment]
Learn python.

**Comment by RajeshSivadasan** [comment]
quantity does not seem to be an optional argument as its not initialized and you are using the "quantity" parameter in the creation of order object. Please check once again and sorry for the inconvenience.  Below is the code from the package.

    def modify_order(self, transaction_type, instrument, product_type, order_id, order_type, quantity, price=0.0,
                     trigger_price=0.0):
        """ modify an order, transaction_type, instrument, product_type, order_id & order_type is required, 
            rest are optional, use only when when you want to change that attribute.
        """
        if not isinstance(instrument, Instrument):
            raise TypeError("Required parameter instrument not of type Instrument")

        if not isinstance(order_id, str):
            raise TypeError("Required parameter order_id not of type str")

        if not isinstance(quantity, int):
            raise TypeError("Optional parameter quantity not of type int")

        if type(order_type) is not OrderType:
            raise TypeError("Optional parameter order_type not of type OrderType")

        if ProductType is None:
            raise TypeError("Required parameter product_type not of type ProductType")

        if price is not None and not isinstance(price, float):
            raise TypeError("Optional parameter price not of type float")

        if trigger_price is not None and not isinstance(trigger_price, float):
            raise TypeError("Optional parameter trigger_price not of type float")

        product_type = self.__get_product_type_str(product_type, instrument.exchange)
        # construct order object with order id
        order = {  'oms_order_id': str(order_id),  
                   'instrument_token': int(instrument.token),
                   'exchange': instrument.exchange,
                   'transaction_type':transaction_type.value,
                   'product':product_type,
                   'validity':'DAY',
                   'order_type': order_type.value,
                   'price':price,
                   'trigger_price':trigger_price,
                   'quantity':quantity,
                   'disclosed_quantity':0,
                   'nest_request_id' : '1'}
        return self.__api_call_helper('modify_order', Requests.PUT, None, order)

**Comment by krishnavelu** [comment]
Where it’s written quantity is optional?

**Comment by RajeshSivadasan** [comment]
Please look at the procedure comment.  It says rest are optional but it seems quantity is mandatory.

""" modify an order, transaction_type, instrument, product_type, order_id & order_type is required, 
        rest are optional, use only when when you want to change that attribute.
    """

**Comment by krishnavelu** [comment]
Sorry for my “Learn python” comment. I overlooked. That’s wrong. Quantity is not optional.  You’ve to pass quantity.

**Comment by krishnavelu** [comment]
- [x] fix documentation.

**Comment by krishnavelu** [comment]
@RajeshSivadasan if you find anymore let me know. I’ll fix all.

**Comment by RajeshSivadasan** [comment]
No Problems Krishna. Thanks for the consideration !
I will definitely bring into your notice if I find anything else.

**Comment by krishnavelu** [comment]
@RajeshSivadasan Fixed in develop, closing this.
