### ISSUE TITLE
How to get the Option price details 

### ISSUE THREAD

**Issue by grsb007** [krishnavelu/alice_blue#35]
How to get the option price details as per below screenshot, could you please help me on this 

![photo6305437815516801296](https://user-images.githubusercontent.com/4687573/70540056-96f07800-1b8a-11ea-8d89-758327185ba6.jpg)

**Comment by krishnavelu** [comment]
See what type of [live feed](https://github.com/krishnavelu/alice_blue#four-types-of-feed-data-are-available) fits your need, and subscribe that.

**Comment by grsb007** [comment]
LiveFeedType.MARKET_DATA is not having the Current OI, it having all other fields 

quote update {'exchange': 'NFO', 'token': 44125, 'ltp': 136.95, 'ltt': 1576210364, 'ltq': 75, 'volume': 301200, 'best_bid_price': 136.75, 'best_bid_quantity': 150, 'best_ask_price': 137.35, 'best_ask_quantity': 600, 'total_buy_quantity': 94350, 'total_sell_quantity': 60300, 'atp': 129.74, 'exchange_time_stamp': 1576210377, 'open': 121.85, 'high': 141.35, 'low': 115.05, 'close': 102.9, 'yearly_high': 17012772.81, 'yearly_low': 18356255.04, 'instrument': Instrument(exchange='NFO', token='44125', symbol='NIFTY 19 DEC19 11950.0 CE', name='', expiry=datetime.date(2019, 12, 19), lot_size='75')}

Could you please help me with this.

**Comment by krishnavelu** [comment]
I already answered you. See what type of [live](https://github.com/krishnavelu/alice_blue#four-types-of-feed-data-are-available) feed fits your need, and subscribe that.
If OI is not there, it not there... Contact alice if you need it. If they implement in their servers I'll include that in my library.
