### ISSUE TITLE
Delay in streaming data from Alice Blue websocket

### ISSUE THREAD

**Issue by nrameshy** [krishnavelu/alice_blue#352]
@krishnavelu 
When I subscribed for multiple instruments(100+) I have observed that the streaming data from Alice Blue websocket is getting delayed. Is there any solution to fix the issue?

Here is my code:
`
```
def event_handler_quote_update(message):

    trading_symbol = message['instrument'].symbol
    data = {}
    if trading_symbol == 'ZEEL':
        data['ltt'] = time.ctime(float(message['ltt'])) 
        data['ltp'] = message['ltp']
        data['trading_symbol'] = trading_symbol
        data['current_time'] = time.ctime(float(time.time()))
        data['delay_in_ms'] =  int(time.time())-int(message['ltt'])
        print(data)

def open_callback():
    global socket_opened
    socket_opened = True

def get_quote_info():

    alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)

    csvfile = open(scrip_dir + 'scrips.csv', 'r')
    scrips = list(csv.reader(csvfile))
    scrips = scrips[1:]
    csvfile.close()
    sub_list = []

    for scrip in scrips:
        inst = alice.get_instrument_by_symbol('NSE',scrip[0])
        if inst:
            sub_list.append(inst)
    while(socket_opened==False):pass
    alice.subscribe(sub_list, LiveFeedType.MARKET_DATA)
    
    while True:pass

if __name__ == '__main__':
    get_quote_info()
```
`
and the output is:

{'ltt': 'Tue Oct 26 10:00:56 2021', 'ltp': 306.75, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:00:58 2021', 'delay_in_ms': 2}
{'ltt': 'Tue Oct 26 10:00:56 2021', 'ltp': 306.75, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:00:59 2021', 'delay_in_ms': 3}
{'ltt': 'Tue Oct 26 10:00:58 2021', 'ltp': 306.95, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:00:59 2021', 'delay_in_ms': 1}
{'ltt': 'Tue Oct 26 10:01:00 2021', 'ltp': 306.95, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:00 2021', 'delay_in_ms': 0}
{'ltt': 'Tue Oct 26 10:01:00 2021', 'ltp': 306.8, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:02 2021', 'delay_in_ms': 2}
{'ltt': 'Tue Oct 26 10:01:00 2021', 'ltp': 306.8, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:03 2021', 'delay_in_ms': 3}
{'ltt': 'Tue Oct 26 10:01:00 2021', 'ltp': 306.8, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:03 2021', 'delay_in_ms': 3}
{'ltt': 'Tue Oct 26 10:01:03 2021', 'ltp': 306.8, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:04 2021', 'delay_in_ms': 1}
{'ltt': 'Tue Oct 26 10:01:04 2021', 'ltp': 307.0, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:05 2021', 'delay_in_ms': 1}
{'ltt': 'Tue Oct 26 10:01:04 2021', 'ltp': 307.0, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:07 2021', 'delay_in_ms': 3}
{'ltt': 'Tue Oct 26 10:01:04 2021', 'ltp': 307.0, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:07 2021', 'delay_in_ms': 3}
{'ltt': 'Tue Oct 26 10:01:07 2021', 'ltp': 306.7, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:09 2021', 'delay_in_ms': 2}
{'ltt': 'Tue Oct 26 10:01:08 2021', 'ltp': 306.75, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:09 2021', 'delay_in_ms': 1}
{'ltt': 'Tue Oct 26 10:01:08 2021', 'ltp': 306.75, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:11 2021', 'delay_in_ms': 3}
{'ltt': 'Tue Oct 26 10:01:10 2021', 'ltp': 306.75, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:12 2021', 'delay_in_ms': 2}
{'ltt': 'Tue Oct 26 10:01:11 2021', 'ltp': 306.5, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:13 2021', 'delay_in_ms': 2}
{'ltt': 'Tue Oct 26 10:01:12 2021', 'ltp': 306.35, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:14 2021', 'delay_in_ms': 2}
{'ltt': 'Tue Oct 26 10:01:13 2021', 'ltp': 306.4, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:15 2021', 'delay_in_ms': 2}
{'ltt': 'Tue Oct 26 10:01:13 2021', 'ltp': 306.4, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:16 2021', 'delay_in_ms': 3}
{'ltt': 'Tue Oct 26 10:01:15 2021', 'ltp': 306.55, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:17 2021', 'delay_in_ms': 2}
{'ltt': 'Tue Oct 26 10:01:15 2021', 'ltp': 306.55, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:18 2021', 'delay_in_ms': 3}
{'ltt': 'Tue Oct 26 10:01:17 2021', 'ltp': 306.5, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:18 2021', 'delay_in_ms': 1}
{'ltt': 'Tue Oct 26 10:01:19 2021', 'ltp': 306.35, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:20 2021', 'delay_in_ms': 1}
{'ltt': 'Tue Oct 26 10:01:19 2021', 'ltp': 306.35, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:20 2021', 'delay_in_ms': 1}
{'ltt': 'Tue Oct 26 10:01:19 2021', 'ltp': 306.35, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:22 2021', 'delay_in_ms': 3}
{'ltt': 'Tue Oct 26 10:01:22 2021', 'ltp': 306.4, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:23 2021', 'delay_in_ms': 1}
{'ltt': 'Tue Oct 26 10:01:23 2021', 'ltp': 306.35, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:24 2021', 'delay_in_ms': 1}
{'ltt': 'Tue Oct 26 10:01:23 2021', 'ltp': 306.35, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:25 2021', 'delay_in_ms': 2}
{'ltt': 'Tue Oct 26 10:01:25 2021', 'ltp': 306.3, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:26 2021', 'delay_in_ms': 1}
{'ltt': 'Tue Oct 26 10:01:25 2021', 'ltp': 306.2, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:32 2021', 'delay_in_ms': 7}
{'ltt': 'Tue Oct 26 10:01:26 2021', 'ltp': 306.35, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:33 2021', 'delay_in_ms': 7}
{'ltt': 'Tue Oct 26 10:01:28 2021', 'ltp': 306.4, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:38 2021', 'delay_in_ms': 10}
{'ltt': 'Tue Oct 26 10:01:28 2021', 'ltp': 306.4, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:41 2021', 'delay_in_ms': 13}
{'ltt': 'Tue Oct 26 10:01:30 2021', 'ltp': 305.75, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:43 2021', 'delay_in_ms': 13}
{'ltt': 'Tue Oct 26 10:01:31 2021', 'ltp': 306.0, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:47 2021', 'delay_in_ms': 16}
{'ltt': 'Tue Oct 26 10:01:32 2021', 'ltp': 306.0, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:51 2021', 'delay_in_ms': 19}
{'ltt': 'Tue Oct 26 10:01:32 2021', 'ltp': 306.0, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:55 2021', 'delay_in_ms': 23}
{'ltt': 'Tue Oct 26 10:01:33 2021', 'ltp': 305.95, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:55 2021', 'delay_in_ms': 22}
{'ltt': 'Tue Oct 26 10:01:34 2021', 'ltp': 306.0, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:01:56 2021', 'delay_in_ms': 22}
{'ltt': 'Tue Oct 26 10:01:35 2021', 'ltp': 305.75, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:02:00 2021', 'delay_in_ms': 25}
{'ltt': 'Tue Oct 26 10:01:35 2021', 'ltp': 305.75, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:02:01 2021', 'delay_in_ms': 26}
{'ltt': 'Tue Oct 26 10:01:37 2021', 'ltp': 305.65, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:02:05 2021', 'delay_in_ms': 28}
{'ltt': 'Tue Oct 26 10:01:38 2021', 'ltp': 305.7, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:02:07 2021', 'delay_in_ms': 29}
{'ltt': 'Tue Oct 26 10:01:39 2021', 'ltp': 305.55, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:02:09 2021', 'delay_in_ms': 30}
{'ltt': 'Tue Oct 26 10:01:40 2021', 'ltp': 305.7, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:02:11 2021', 'delay_in_ms': 31}
{'ltt': 'Tue Oct 26 10:01:41 2021', 'ltp': 305.7, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:02:16 2021', 'delay_in_ms': 35}
{'ltt': 'Tue Oct 26 10:01:42 2021', 'ltp': 305.8, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:02:19 2021', 'delay_in_ms': 37}
{'ltt': 'Tue Oct 26 10:01:43 2021', 'ltp': 305.9, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:02:24 2021', 'delay_in_ms': 41}
{'ltt': 'Tue Oct 26 10:01:44 2021', 'ltp': 306.0, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:02:26 2021', 'delay_in_ms': 42}
{'ltt': 'Tue Oct 26 10:01:45 2021', 'ltp': 306.0, 'trading_symbol': 'ZEEL', 'current_time': 'Tue Oct 26 10:02:28 2021', 'delay_in_ms': 43}

The delay is getting increased as the time goes on. Could you please suggest how can we get live feed without too much delay for multiple instruments

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) before creating a new issue. I've replied in multiple issues regarding this.

**Comment by nrameshy** [comment]
@krishnavelu The handler function has a very simple print statement. I am not sure what can be done to overcome this delay. Could you please help?

**Comment by krishnavelu** [comment]
Did you ever measured how much time a print statement takes? Print is heavy.

**Comment by nrameshy** [comment]
@krishnavelu I have used the print function to see the delay in live feed in my example. However I have measured the total handler function execution time and it is just ~0.0002 seconds. I believe the handler function is not the culprit for the delay in live feed.

**Comment by krishnavelu** [comment]
~0.0002 seconds. So do the math and you'll understand.
0.0002 x 100 = 0.02 - that's 20 milliseconds. This is for 100 scrips. Assuming that you get only 1 tick data per scrip, per second.
Now assume at least 5 tick data per scrip, per seconds. In actual it may not be 5 it can be less or more depends upon market execution.
Now it becomes 100milliseconds. 100 milliseconds just for the event handler. Do your CPU goes to 10% usage, I don't know. But execution time will not get for only python to execute, there are other things in windows or linux to execute. That's why the delay.
If you optimize the event handler function. You may get the expected results.

**Comment by nrameshy** [comment]
Thank you @krishnavelu for the explanation . I am not quite sure what can be optimized in my handler function. I have decided not to use Alice Blue websocket for live feed.
