### ISSUE TITLE
FRESS SELL AND SQUARE OFF 

### ISSUE THREAD

**Issue by vijaysahu12** [krishnavelu/alice_blue#354]
Hello Krishna 

After last discussion with you I was able to fix my login , generate token issue and now I am able to place buy order automatically. 

Now I stuck in selling the stocks I means (SHORT or Sell).. 

1. 
Getting an response error from api like 
          "Internal server error"

Here is the request json object for placing the fres SELL Order. 

{"exchange":"NSE","order_type":"LIMIT","instrument_token":3812,"quantity":1,"price":298.6,"order_side":"SELL","validity":"DAY","product":"CNC","user_order_id":0,"device":"WEB"}

2. When I am replacing the sell keyword to SHORT IN order_side for fresh sell then I am getting an error like 

{
    "data": {},
    "error_code": 44000,
    "message": "`order_side` is invalid",
    "status": "error"
}

  
I have gone through your documents for placing the order but still no luck. 

Regards,
Vijay Sahu

**Comment by krishnavelu** [comment]
Where did you get the keys for json dictionary? `order_side` Is wrong. It should be `order_type`

Also refer the code [here](https://github.com/krishnavelu/alice_blue/blob/master/alice_blue/alice_blue.py#L531)

**Comment by vijaysahu12** [comment]
I got the reference from their official documents only… 

here is the link for the same..
https://documenter.getpostman.com/view/6567634/U16dRU8u#d04b890f-f9b8-47b1-9143-040618168aa0

**Comment by krishnavelu** [comment]
This document is different. Different version. This library is different version.
