### ISSUE TITLE
API ISSUE 

### ISSUE THREAD

**Issue by mahesh-solanke** [krishnavelu/alice_blue#356]
Hi, please find the error which we have faced many times.
the credentials are correct.

File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\alice_blue\alice_blue.py", line 252, in login_and_get_access_token
    if(len(err) > 0):
TypeError: object of type 'NoneType' has no len()

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating a new issue.

**Comment by mahesh-solanke** [comment]
> Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating a new issue.

Hello Krishna, can you please have look into the error which i have got.

**Comment by krishnavelu** [comment]
For looking in to error, I need you to follow what I've written. Without that I cannot help. With just that error, no one can help.
