### ISSUE TITLE
Orders not passed console hangs after some time, Continues when any pressed

### ISSUE THREAD

**Issue by vetri-trading** [krishnavelu/alice_blue#357]
Hi,
I have developed a algo trading strategy using python code and running it in alice blue.

Some times it hangs up and does not pass any orders until I press any key.

Can anyone please give the solution the order passes seamlessly without manual intervention

I am using VPS which has 8 core and 8GB RAM and CPU utilization is 30%.

Thanks in advance.

Regards,
Vignesh Vetrivel
9944675983

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating a new issue.
