### ISSUE TITLE
How  to export live aliceblue data in csv or excel

### ISSUE THREAD

**Issue by ABHISHEK830STAR** [krishnavelu/alice_blue#358]
Hi , I got live market data in output but I don't know how to export live data in excel or csv. what is the code for exporting live streaming data into excel or csv file.

**Comment by krishnavelu** [comment]
> how to export live data in excel or csv

This is a general python question. Instead of asking here and waiting, if you ask in general software forums like stack over flow. You may get a fast and better response.

**Comment by krishnavelu** [comment]
Also, Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating a new issue.

**Comment by ABHISHEK830STAR** [comment]
> > how to export live data in excel or csv
> 
> This is a general python question. Instead of asking here and waiting, if you ask in general software forums like stack over flow. You may get a fast and better response.

Hi @krishnavelu , i have also tried to ask in  stack over flow and other forum but not getting answer. please help me to write code  to export live streaming data into excel or csv. anyone can help plz

**Comment by ABHISHEK830STAR** [comment]
my code is :
from alice_blue import *
import pandas as pd

username = "xyz"
password = "xyz"
access_token = "xyz"
alice = AliceBlue(username, password, access_token, ['NSE'])
def event_handler_quote_update(ticks):
    print(ticks)
def open_callback():
    global socket_opened
    socket_opened = True
alice.start_websocket(event_handler_quote_update, open_callback, run_in_background=True)
while True:
     #from DATABSE import DATABASE
 alice.subscribe(alice.get_instrument_by_symbol('NSE', 'KOTAKBANK'), LiveFeedType.MARKET_DATA)
 alice.subscribe(alice.get_instrument_by_symbol('NSE', 'ICICIBANK'), LiveFeedType.MARKET_DATA)

**Comment by krishnavelu** [comment]
Sorry I cannot help with your application. Learn python fully and then jump into automated trading. Otherwise you are risking your account to go to 0.
