### ISSUE TITLE
Placing order for buying and selling call options of BANKNIFTY, STOCK OPTIONS

### ISSUE THREAD

**Issue by venkat-cma** [krishnavelu/alice_blue#359]
Krishnavelu sir,

I have issue of placing order for buying and selling call options of BANKNIFTY, STOCK OPTIONS.
My code template is :

from alice_blue import *
user_name='my_user_name_given'
pass_word='my_password_given'
two_fa='my_yr_of_birth_given'
API_Secret='my_api_secret_given'
App_id='my_app_id_given'
access_token=open(r'e:\access_token.txt','r').read().strip()

alice = AliceBlue(username=user_name, password=pass_word, access_token=access_token)
# TransactionType.Buy, OrderType.Limit, ProductType.Delivery
instrument = alice.get_instrument_for_fno(symbol='BANKNIFTY', expiry_date=datetime.date(2021, 11, 25), is_fut=False,
                                          strike=40000, is_CE=True)

print ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%1%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
print(
   alice.place_order(transaction_type = TransactionType.Buy,
                     instrument,
                     quantity = 25,
                     order_type = OrderType.Limit,
                     product_type = ProductType.Delivery,
                     price = 90.0,
                     trigger_price = None,
                     stop_loss = None,
                     square_off = None,
                     trailing_sl = None,
                     is_amo = False)
   )

On running the above program, I get the following error :

"C:\Program Files\Python310\python.exe" E:/Buy-Order/main.py
  File "E:\Buy-Order\main.py", line 26
    is_amo = False)
                  ^
SyntaxError: positional argument follows keyword argument

Process finished with exit code 1

I do not understand how to solve the issue. I want to buy, sell, square off for Stock Options, Nifty Options, BankNifty Options.
Please help me. Thank you very much for your support.

**Comment by krishnavelu** [comment]
Its just a syntax error, nothing to do with this library. If you know python vert well you should be able to solve this.
Learn python well and jump in to trading with python.

**Comment by venkat-cma** [comment]
Sir.
I solved the above issue. But, I cannot place orders for MCX Commodities. My code is :

from alice_blue import *
import datetime
user_name='my_user_name_given'
pass_word='my_password_given'
two_fa='my_yr_of_birth_given'
API_Secret='my_api_secret_given'
App_id='my_app_id_given'
access_token=open(r'e:\access_token.txt','r').read().strip()

alice = AliceBlue(username=user_name, password=pass_word, access_token=access_token)
# TransactionType.Buy, OrderType.Limit, ProductType.Delivery
instrument = alice.get_instrument_for_fno(symbol='CRUDEOIL', expiry_date=datetime.date(2021, 11, 18), is_fut=False,
                                          strike=6100, is_CE=True)

print ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%1%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
print(alice.place_order(transaction_type = TransactionType.Buy,
                     instrument,
                     quantity = 1,
                     order_type = OrderType.Limit,
                     product_type = ProductType.Delivery,
                     price = 10.0,
                     trigger_price = None,
                     stop_loss = None,
                     square_off = None,
                     trailing_sl = None,
                     is_amo = False)
   )

On running the above program, I get the following error :

"C:\Program Files\Python310\python.exe" E:/Buy-Order/main.py
File "E:\Buy-Order\main.py", line 16, in <module>
%%%%%%%%%%%%%%%%%%%%%%%%%%%%1%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    alice.place_order(transaction_type = TransactionType.Buy,
  File "C:\Program Files\Python310\lib\site-packages\alice_blue\alice_blue.py", line 512, in place_order
    raise TypeError("Required parameter instrument not of type Instrument")
TypeError: Required parameter instrument not of type Instrument

Process finished with exit code 1

Please advise me sir. Thank you in advance.

**Comment by krishnavelu** [comment]
Read and follow [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) before creating a new issue...

**Comment by venkat-cma** [comment]
Thank you very much sir. I solved it. I close the issue.
