### ISSUE TITLE
Search an instrument using trading symbol

### ISSUE THREAD

**Issue by RajeshSivadasan** [krishnavelu/alice_blue#361]
This is a feature request which will enable searching of instruments using the common trading symbol used across brokers. This will be beneficial for those who are looking to use multiple broker interfaces in their program and want to place orders across brokers easily. Usage will be like below e.g
ins_opt = alice.get_instrument_by_trading_symbol('NFO', 'NIFTY21D0217000CE')  
Infernally, dictionary with trading symbol as key will be created. I can try a shot to develop this method.

**Comment by krishnavelu** [comment]
This library is only for Alice blue, integrating or trying to communize will create more problems and efforts than the benefit we get out of it.
