### ISSUE TITLE
 API to get intraday candles data?

### ISSUE THREAD

**Issue by reds4glory** [krishnavelu/alice_blue#362]
Hi ,

The below code works for getting intraday candle data for any stock symbols but not for index like 'Nifty Bank'  

 HEADERS = {'X-Authorization-Token': open(r'C:\Users\SAYAK\Desktop\Python\Alice Blue\API_token.txt', 'r').read().strip()}
 def intraday_data_CE(exchange, token, starttime, endtime, interval=1):
               PARAMS_CE = {'candletype': 1,'data_duration': interval, 'starttime': starttime, 'endtime': endtime, 'exchange': 'NSE','type': 'live','token':     token}
               try:
                 r_CE = requests.get("https://ant.aliceblueonline.com/api/v1/charts", params=PARAMS_CE, headers=HEADERS)
                 
                 print(r_CE)
                 data_CE = r_CE.json()
                 return format_intraday_CE(data_CE)
                 #print(data_CE)    
               except Exception as e:
                 print("{} Error occurred in getting intraday data for ticker :: {}".format(e, 1330))

           

 def format_intraday_CE(data_CE):
              records_CE = data_CE['data']
    
              df = pd.DataFrame(records_CE, columns=[
                             'datetime', 'open','high', 'low', 'close', 'volume'])  # , index=0)
              df['datetime'] = df['datetime'].apply(
               pd.Timestamp, unit='s', tzinfo=pytz.timezone("Asia/Kolkata"))
              df[['open', 'high', 'low', 'close']] = df[['open' , 'high', 'low', 'close']].astype(float).div(100)
              
              df.set_index('datetime', inplace=True)
              if(df.empty):
                 print("Pandas DataFrame is empty.")
              
              return df
    
 tday = dt.date.today()
 startTime = int(dt.datetime.now().timestamp()-300)
 #startTime = int(dt.datetime(tday.year, tday.month, tday.day,hour=9, minute=0, second=0).timestamp())
 endTime = int(dt.datetime(tday.year, tday.month, tday.day,hour=23, minute=59, second=0).timestamp())  

 print(intraday_data_CE('NSE', token=token, starttime=startTime, endtime=endTime, interval=5))

Thanks
Sayak

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating a new issue.

**Comment by krishnavelu** [comment]
Closing...
