### ISSUE TITLE
How to get Live LTP and BID ASK spread together?

### ISSUE THREAD

**Issue by arjuneshm** [krishnavelu/alice_blue#363]
Hi,
Krishna

In alice blue, is there any possibility to get the live MARKETDATA of the Bid ask spread also for specific FNO positions?

As of now MARKET_DATA is not giving the ask_prices and bid_prices (like in the SNAPQUOTE) .
Whether the FULL_SNAPQUOTE is also a live data ?

Regards
Arjunesh

**Comment by krishnavelu** [comment]
MARKET_DATA will give both LTP & Bid, Ask. Try all type of data & pickup what suites your need.

**Comment by arjuneshm** [comment]
Hi,
Krishna

Sorry for  creating the confusion by using the Bid Ask Spread wording.
Best bid and Best ask is  available from the Market data. I was looking for the worst Bid and Worst Ask too from the first 5 quantity . (if the 5 can be parameterized then it would have been even more good - present feed is also awesome)

Market_data : 
message is {'exchange': 'NFO', 'token': 71321, 'ltp': 17340.05, 'ltt': 1639648799, 'ltq': 50, 'volume': 9365650, 'best_bid_price': 17340.1, 'best_bid_quantity': 50, 'best_ask_price': 17344.8, 'best_ask_quantity': 50, 'total_buy_quantity': 240150, 'total_sell_quantity': 255500, 'atp': 17306.53, 'exchange_time_stamp': 1639648800, 'open': 17390.0, 'high': 17400.0, 'low': 17233.0, 'close': 17260.8, 'yearly_high': 17400.0, 'yearly_low': 0.0, 'instrument': Instrument(exchange='NFO', token=71321, symbol='NIFTY DEC FUT', name='', expiry=datetime.date(2021, 12, 30), lot_size='50')}

While in snapquote we are able to get the 5 bid prices and 5 ask price. Actually we can get the best and worst bid/ask from this  while we have only best ask and best bid(which is the acual bid ask spread - my bad in using that wording)

FULL_SNAPQUOTE:
message is {'exchange': 'NFO', 'token': 71321, 'buyers': [1, 5, 13, 1, 1], 'bid_prices': [17340.1, 17340.05, 17340.0, 17338.75, 17338.7], 'bid_quantities': [50, 1600, 2400, 100, 150], 'sellers': [1, 1, 1, 1, 1], 'ask_prices': [17344.8, 17345.0, 17345.05, 17345.25, 17345.6], 'ask_quantities': [50, 50, 200, 50, 100], 'atp': 17306.53, 'open': 17390.0, 'high': 17400.0, 'low': 17233.0, 'close': 17260.8, 'total_buy_quantity': 240150, 'total_sell_quantity': 255500, 'volume': 9365650, 'instrument': Instrument(exchange='NFO', token=71321, symbol='NIFTY DEC FUT', name='', expiry=datetime.date(2021, 12, 30), lot_size='50')}

Can bid_prices and ask_prices be pushed into the Market_data feed? 

Thanks a lot for the response

Regards
Arjunesh

**Comment by krishnavelu** [comment]
There is no worst bid, worst ask. The one which you are thinking is actually not worst bid/ask. This is just 5 bid asks, zerodha give 20 bid/asks. So if you are taking 20 the last 20th will be the worst? Its only the first 5 bid/ask or the first 20 bid/ask is taken as a snapshot and provided as tick data. In actual the depth is more, which just goes on. So there is actually no worst bid/ask.
Theoretically worst bid would be 0 and worst ask would be ~ infinity.
To you question
> Can bid_prices and ask_prices be pushed into the Market_data feed?

No. This is how the server provides. This library is just a bridge to communicate with the server.
I'm closing this for now for clean up purposes. Reopen if needed.
