### ISSUE TITLE
CNC sell order

### ISSUE THREAD

**Issue by baru352** [krishnavelu/alice_blue#366]
Hi 

When i tried to sell -CNC a stock which was bought earlier using a CNC order .
I am getting an error "CNC SELL is not allowed here, use https://ant.aliceblueonline.com Web or Mobile'". 

Please help 

Regards,
Baru

**Comment by MaheshPunna** [comment]
@krishnavelu 
I get the same error "CNC Sell is not allowed here", even after activating POA(as suggested in issue #307 ) Is there anything we need to do after activating POA??

**Comment by krishnavelu** [comment]
There is some recent restrictions in CNC sell order. I'm too not sure what's that. It's across all brokers. Even in upstox I'm not able to do CNC sell. Contact Alice blue regarding this.

**Comment by krishnavelu** [comment]
Hope you problem is resolved. Closing this.
