### ISSUE TITLE
Wrong Instrument Returned.

### ISSUE THREAD

**Issue by vinitshetty** [krishnavelu/alice_blue#368]
For Below Instrument: 
  Symbol: NIFTY 50
  Expiry:  30 DEC21 
  Strike: 16500.0 
  Option Type: PE

get_instrument_for_fno()
returns NIFTY DEC 16500.0 PE which is correct.

But now reverse lookup fails -

get_instrument_by_symbol('NFO','NIFTY DEC 16500.0 PE')
returns 
Instrument(exchange='NFO', token=35589, symbol='NIFTY DEC 16500.0 PE', name='', expiry=datetime.date(_2022_, 12, 29), lot_size='50')

Which is wrong (expiry is of 2022/12/29).

This is hard to trace as for some symbols it works fine and returns 2021 expiry as expected.

I am guessing - because of Alice symbol representation object is getting replaced in __master_contracts_by_symbol.

**Comment by vinitshetty** [comment]
I wrote a quick fix for this problem using below logic- 

convert expiry to none if it's non-existent
                if('expiry' in scrip):
                    expiry = datetime.datetime.fromtimestamp(scrip['expiry']).date()
                    if (expiry-today) > datetime.timedelta(days=90): ###VINUT EDIT
                        continue

**Comment by krishnavelu** [comment]
Is this still a problem? With some latest expiry scrip? or only that scrip?

**Comment by vinitshetty** [comment]
Yes it's still a problem. You can refer to my examples. Using Alice symbols
as key is not a good idea given they don't have Year part of it. Multi year
Options data is causing the problem.

**Comment by krishnavelu** [comment]
why are you using get_instrument_by_symbol for FNO? when there is a separate function for FNO?

**Comment by krishnavelu** [comment]
Hope you problem is resolved. Closing this.
