### ISSUE TITLE
websocket hangs

### ISSUE THREAD

**Issue by keerthankumar** [krishnavelu/alice_blue#370]
Im using below code for subscribing websocket

```
alice = AliceBlue(username=username, password=password, access_token=access_token, master_contracts_to_download=['NSE', 'BSE'])
print(alice)
b = alice.get_instrument_by_symbol('NSE', 'INFY')
print(b)



a = alice.subscribe(b, LiveFeedType.MARKET_DATA)
print(a)
```

the code hangs at the command - alice.subscribe(b, LiveFeedType.MARKET_DATA).

**Comment by keerthankumar** [comment]
@krishnavelu Please look at this issue as a priority. am I missing something here?

**Comment by keerthankumar** [comment]
@krishnavelu any response this query ?

**Comment by krishnavelu** [comment]
Yes, you are missing. Try to use the example as it is. It works for everyone. Once the example works, then try to modify/add your code.

**Comment by krishnavelu** [comment]
Hope you problem is resolved. Closing this.
