### ISSUE TITLE
Regarding some problem in tick by tick realtime data

### ISSUE THREAD

**Issue by vishvesh098** [krishnavelu/alice_blue#371]
Hi, I have been using aliceblue api for some time. I have noticed some problems as under. Notice that the results posted are fetched from ticks saved my database. If I save the ticks in simple txt or csv file the same problem can be observed.

**Problem-1:**
In live streaming tick by tick data, during market hours many times the volume of instruments consists of some very strange value. Highlighted in yellow. It happens with all instruments, I have just shown an example of AARTIIND.

![alice_1](https://user-images.githubusercontent.com/36956759/148193062-b15ff1cd-7800-44a8-8341-f6e35c5d0741.png)

**Problem-2:**
In live streaming tick by tick data, sometimes the previous tick comes after some time. This creates problems and variation in my calculated OHLC values. As you can see in the data below, tick of 06:52:05.000 came after tick of 
06:52:06.000. This happens with all instruments. Also you can observe the time when the tick is received at db highlighted in green.

![alice_2](https://user-images.githubusercontent.com/36956759/148193096-b51c2f10-aa6d-45ca-a188-0d2226189358.png)

**Regarding Relevent Python code**
I am running 156 symbols (all FNO symbols like TCS, INFY, RELIANCE etc) in LiveFeedType.COMPACT mode. The relevant python code is as below. (As per my understanding the python code may not have problem but the data from main server sends incorrect data)
I just attached the part which sends data to my db or to text file.

If you need more code please feel free to contact me.

```
def event_handler_quote_update(message):
    """
    msg = {'exchange_time_stamp': (int(message['exchange_time_stamp'])*1000000 + int(datetime.datetime.now().strftime('%f')))*1000,
           'instrument': message['instrument'].symbol,
           'ltp': message['ltp'],
           'volume': message['volume']}
    #print(msg)
    #print(message)
    """
    try:  
        s.run("tableInsert(t, (convertTZ(timestamp({3}),'Asia/Kolkata','Asia/Kolkata')), `{0}, {1}, {2}, convertTZ(now(),'Asia/Kolkata','Asia/Kolkata'));".format(str(message['instrument'].symbol).replace("-","_").replace("&", "__"),float(message['ltp']),int(message['volume']),int(message['exchange_time_stamp'])*1000))
        #print("tableInsert(t, (convertTZ(timestamp({3}),'Asia/Kolkata','Asia/Kolkata')), `{0}, {1}, {2}, convertTZ(now(),'Asia/Kolkata','Asia/Kolkata'));".format(str(message['instrument'].symbol).replace("-","_").replace("&", "__"),float(message['ltp']),int(message['volume']),int(message['exchange_time_stamp'])*1000))
    except Exception as e:
        print(e)
```

@krishnavelu bro, Please solve the aforementioned queries as soon as possible.

Thanks and regards,
Vishvesh Upadhyay.

**Comment by krishnavelu** [comment]
I've replied in many issue related to this issue. Your event_handler should be designed as very efficient. you cannot use a database or even a print statement. The whole even_handler should be able to execute in 1ms or <1ms if you are subscribing > 100 scrips.

**Comment by vishvesh098** [comment]
@krishnavelu but what about Problem-1, that random volume data ?

**Comment by krishnavelu** [comment]
that might be due to improper handling of data and storing.

**Comment by krishnavelu** [comment]
Hope you problem is resolved. Closing this.
