### ISSUE TITLE
Alice Blue V2 API updates

### ISSUE THREAD

**Issue by krishnavelu** [krishnavelu/alice_blue#373]
These are the documentation from Alice blue.

https://aliceblueonline.com/antplus2

https://documenter.getpostman.com/view/6567634/U16dRU8u

**Comment by krishnavelu** [comment]
- [ ] Add issue tracker

    project_urls={
        "Documentation": "https://sslkeylog.readthedocs.io/",
        "Issue Tracker": "https://github.com/segevfiner/sslkeylog/issues",
    },

**Comment by RemyaAnin** [comment]
Would you be supporting the APIv2 https://v2api.aliceblueonline.com/introduction ?
Is https://github.com/krishnavelu/alice_blue/issues/418 a duplicate?
When I enquired about API v2, support team send me the YouTube link# https://www.youtube.com/watch?v=CVCMIHlFkoI

**Comment by krishnavelu** [comment]
No updates as of now.

**Comment by RemyaAnin** [comment]
Hi Sir,

This is the official API of AliceBlue. Currently, if one were to use Ant Mobi 2 app, Algo V1 token becomes invalid. This leads to authentication failure on Algo. Support mentioned V2 websocket is still being tested.  

How can existing API customers migrate to V2 in under 2 months with no proper wrapper developed in V2? As the official developer,  could you please check what is the plan to support API customers from September 1st?

**Comment by krishnavelu** [comment]
The API document changed after I created this issue. From Alice Blue side there are so many changes.
Still the document for order updates through web socket is pending.
Once everything in place I think of rewriting the API.

**Comment by rajamurugan44** [comment]
AliceBlue will not support existing API after August, 2022. Any idea when this API will support V2.

It may affect lot many existing customers who are using AliceBlue API.

**Comment by RemyaAnin** [comment]
> 

Join https://t.me/aliceblueapi

**Comment by siwaugh** [comment]
We are getting emails from Alice Blue saying that old version will no longer work from Aug 9, 2022. How to continue our algo-trading with python from Aug 9, 2022? Anyone has any sample code to show how to code for the new version? Please share.

**Comment by krishnavelu** [comment]
New api updates maybe around this month end.
