### ISSUE TITLE
Java Support

### ISSUE THREAD

**Issue by csunith** [krishnavelu/alice_blue#374]
Hi,

I am trying to rewrite the python SDK using Java, Can you suggest or point how do we need to convert the Marketfeed data to JSON or String as currently sends data in byte/binary.

Thanks,
Sunith

**Comment by vvbch** [comment]
+1. I also want this. I spent a lot of time making the login API work. It has taken like 30+ hours. please provide a Java SDK or JSON format to work with.

**Comment by krishnavelu** [comment]
You can see [this](https://github.com/krishnavelu/alice_blue/blob/master/alice_blue/alice_blue.py#L321-L365) function, how it's getting converted.

**Comment by Sauradyuti** [comment]
@csunith @vvbch 
In Java, if you're extending `okhttp3.WebSocketListener`, the `onMessage(WebSocket webSocket, ByteString bytes)` method will get triggered on receiving the market data. 

To convert the bytes to actual values, you can do this,
```
byte byteArray[] = bytes.toByteArray();
// Compact Marketdata
int token = parseBytes(byteArray, 2, 6);
double ltp = parseBytes(byteArray, 6, 10)/NSE_MULTIPLIER;
double change = parseBytes(byteArray, 10, 14)/NSE_MULTIPLIER;
int timestamp = parseBytes(byteArray, 14, 18);
```

where,
```
private int parseBytes(byte bytes[], int from, int to) {
    byte result[] = new byte[to - from];
    for (int i=from; i<to; i++)
        result[i-from] = bytes[i];
    return ByteBuffer.wrap(result).getInt();
}
```

**Comment by krishnavelu** [comment]
Closing this, reopen if needed
