### ISSUE TITLE
Not able to sell CNC holding

### ISSUE THREAD

**Issue by keerthankumar** [krishnavelu/alice_blue#376]
Hi, I'm facing the issue Not able to sell CNC holding getting error -
`{'status': 'error', 'message': 'CNC SELL is not allowed here, use https://ant.aliceblueonline.com Web or Mobile', 'data': {}}
`
I can do it in ANT Web without OTP?
My POA is complete

**Comment by krishnavelu** [comment]
There are some problems in CNC sell using API across all brokers. Contact Alice.

**Comment by Santunav** [comment]
I contacted Alice about this error, I got reply to use https://aliceblueonline.com/antplus2 ..   Is this now implemented now. If not when can we expect support for this antplus2 . @krishnavelu 

Thank in advance

**Comment by krishnavelu** [comment]
It’s not implemented yet. Maybe in 6 months.
