### ISSUE TITLE
FNO Instrument details from symbol

### ISSUE THREAD

**Issue by Vijayrathi** [krishnavelu/alice_blue#377]
How to get Intrument object to be used in modify order from available FNO Symbol e.g. BANKNIFTY22FEB39000PE.
 instrument = alice.get_instrument_by_symbol('NFO', "BANKNIFTY22FEB39000PE") is giving Typerror "Required parameter instrument not of type Instrument"
and can't use alice.get_instrument_for_fno as I do not have readily available expiry date.

**Comment by krishnavelu** [comment]
what do you mean by `I do not have readily available expiry date`?

**Comment by Vijayrathi** [comment]
in other words .. can I get instrument details for FNO options using token ... eg: alice.get_instrument_by_token('NFO', 43015) 
rather than using get_instrument_for_fno ... reason being .. "get_order_history" provide token.
am creating a function for modifying open orders

**Comment by krishnavelu** [comment]
No
