### ISSUE TITLE
Web Socket Error from Call back - CoInitialize has not been called

### ISSUE THREAD

**Issue by Vijayrathi** [krishnavelu/alice_blue#379]
I am facing error from callback when writing the ticks value into excel sheet. using following Code
def gettingData(ticks):
    
    ltp = ticks['ltp']
    col_no = None
    if ticks['instrument'].exchange == "NSE":
        col_no = "F"
    elif ticks['instrument'].exchange == "NFO":
        col_no = "G"
    
    sheet_config.range(col_no+"2").value = ltp

def event_handler_quote_update(ticks):
    gettingData(ticks)

def open_callback():
    global socket_opened
    socket_opened = True
 

def open_socket_now():
	alice.start_websocket(
		subscribe_callback=event_handler_quote_update,
		socket_open_callback=open_callback,
		run_in_background=True)
	while socket_opened == False:
		pass

nifty = []
date_new = 24-02-2022
mon_expiry_date = date(date_new.year,date_new.month,date_new.day)

nifty.append(alice.get_instrument_by_symbol('NSE','Nifty Bank'))
nifty.append(alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=mon_expiry_date, is_fut=True, strike=None, is_CE =False))    

def start_ticks():
    
    while True:
        alice.subscribe(nifty,LiveFeedType.COMPACT)
        time.sleep(.5)
    
t1=threading.Thread(target=start_ticks())
t1.start()

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating a new issue...
