### ISSUE TITLE
Need Help- How to get the OHLC candlestick data

### ISSUE THREAD

**Issue by grsb007** [krishnavelu/alice_blue#38]
Is there any API for getting the OHLC candlestick data?, looks like it is not available currently. If no is there sample program that can be shared in this group

**Comment by krishnavelu** [comment]
Refer this [issue and comment](https://github.com/krishnavelu/alice_blue/issues/26#issuecomment-564532198). Before opening a new issue scan through already created issues. This is a duplicate of #26
