### ISSUE TITLE
Modify an open order

### ISSUE THREAD

**Issue by srinidhihebbar260297** [krishnavelu/alice_blue#380]
How to modify an open order I'm simulating trailing SL at my end but i cannot modify an open order ... I feel it is better that you provide it at your end instead of user checking if the Sl order is completed or not and cancelling old order and placing a new one 

Any help or code is highly appreciated

**Comment by krishnavelu** [comment]
You can get the status of order and do whatever you want.

**Comment by srinidhihebbar260297** [comment]
Krishna,the modify order is already in the API documentation,so why not add it to python sdk as well

**Comment by krishnavelu** [comment]
Modify order is already there.

https://github.com/krishnavelu/alice_blue/blob/master/alice_blue/alice_blue.py#L648-L688
