### ISSUE TITLE
Error in place_order method

### ISSUE THREAD

**Issue by krisnapradeep** [krishnavelu/alice_blue#381]
Hi @krishnavelu 

I am getting the below error while placing order 

Traceback (most recent call last):
  File in place_order
    order_placed= self.__api_call_helper('place_order', Requests.POST, None, payload)
  File in __api_call_helper
    raise requests.HTTPError(response.text)
requests.exceptions.HTTPError: {"errors":{"detail":"Internal server error"}}

But if I changes the service_config URL 'place_order': '/api/v2/order' to 'place_order': '/api/v1/orders' (This is as mentioned in API document reference in https://aliceblueonline.com/antplus2 ) it is working fine.

Is this related to User API app created in https://develop-api.aliceblueonline.com/dashboard.

Or is there anything need to be done to use API v2 version in order_placing also?

All other methods get_balance, get_order_historym get_trade_book, get_daywise_positions are working fine in API v2 URL.

Thanks in advance

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating a new issue...
