### ISSUE TITLE
unable to access the access token

### ISSUE THREAD

**Issue by sadashiva123s** [krishnavelu/alice_blue#382]
hi,

i have tried with jupyter notebook with python latest version( conda )

import logging
logging.basicConfig(level=logging.DEBUG)

from alice_blue import *

access_token = AliceBlue.login_and_get_access_token(username='AB054905', password='correct password', twoFA='a', api_secret='correct secret')

print(access_token)

#alice = AliceBlue(username='username', password='correct password', access_token=access_token)

but i got the error like follows

ERROR:alice_blue.alice_blue:Couldn't get access token {'error': 'invalid_grant', 'error_description': 'The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client', 'status_code': 400}

what is wrong which i have done in the code part??
Thanks

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating a new issue...
