### ISSUE TITLE
Memory not optimized

### ISSUE THREAD

**Issue by Nahas-N** [krishnavelu/alice_blue#384]
why it takes so much memory around 300 mb while creating aliceblue object with credentials and tokens ?

**Comment by Nahas-N** [comment]
master contract downloading thing have to be handled and cached in another way. instead of putting all in memory

**Comment by krishnavelu** [comment]
This library is provided for minimal functionality between server and client. Memory optimization is not considered during developing. If you don’t want all master contracts, you can download selectively.
