### ISSUE TITLE
How to Trial SL based on Option premium

### ISSUE THREAD

**Issue by rajamurugan44** [krishnavelu/alice_blue#385]
My script placing sell order and also placing SL order for my option leg.
How I can trial my SL if my option premium is reduced 50% from my selling price.
Please help.

**Comment by krishnavelu** [comment]
Learn python

**Comment by rajamurugan44** [comment]
Thanks for ur reply.. I just asked is there any APi available for trailing SL...

**Comment by krishnavelu** [comment]
No. You’ve to write your own code
