### ISSUE TITLE
Sell Order not working

### ISSUE THREAD

**Issue by dnaveen2012** [krishnavelu/alice_blue#387]
Hi Krishna, 

i am using the below code for selling my holdings but it is not working. can you please tell me any issue or maintenance is going on for this alice bluce api.

             ins_scrip = alice.get_instrument_by_symbol(
                'NSE', 'VEDL')
            print(ins_scrip)
            try:
                alice.place_order(transaction_type=TransactionType.Sell,
                             instrument=ins_scrip,
                             quantity=10,
                             order_type=OrderType.Limit,
                             product_type=ProductType.Delivery,
                             price=390.0,
                             trigger_price=None,
                             stop_loss=None,
                             square_off=None,
                             trailing_sl=None,
                             is_amo=False)
            except Exception as e:
                print(ValueError(e))
                raise ValueError(e)

Thank you
Naveen Dasari

**Comment by krishnavelu** [comment]
Sell Delivery has some limitations across all brokers through API. Contact Alice-blue. Make sure if you have POA.
