### ISSUE TITLE
master_contracts_to_download is this mandatory for all object creation?

### ISSUE THREAD

**Issue by rajamurugan44** [krishnavelu/alice_blue#388]
alice = AliceBlue(username='userName', password='password', access_token=access_token, master_contracts_to_download=['NSE', 'NFO'])

in above line is it mandatory to download contract for all the users?
I am running my bot for multiple clients and for each user its downloading NSE and NFO contract and if I remove that line then its downloading all the contracts(NSE, NFO, BSE, CDS)

Can I download the contract detail for 1 user object and reuse it for others? downloading same data for multiple users is getting out of memory issue.

Could you please provide solution for this.

**Comment by krishnavelu** [comment]
This library is not optimized for memory usage or multiple user login. This is for single user login.
