### ISSUE TITLE
Instrument Advanced search for commodity ?

### ISSUE THREAD

**Issue by gagan3211** [krishnavelu/alice_blue#389]
I use below code to get Futures ,generally last 10 records gives me right future instrument but for commodity this logic is not working
 all_sensex_scrips = alice.search_instruments(index, script)
 dfinstru = pd.DataFrame(all_sensex_scrips)
 pprint(dfinstru.tail(10))

For Crude current month contract is around position 200. Is there any other way to get only 1 relevant month record in search 
Refere attacthed image to get some clarity on my question
       
![image](https://user-images.githubusercontent.com/12957196/161249180-1a45ec2a-961d-472b-a163-616c240f5af7.png)

**Comment by krishnavelu** [comment]
Search is for searching instrument. After searching do get_instrument. It should return only 1
