### ISSUE TITLE
Access token not generated.

### ISSUE THREAD

**Issue by Aniruddha1980** [krishnavelu/alice_blue#392]
Sir,

I got the Alice blue API, And I have generated the api ID using the documentation provided by Alice blue.
When I tried to execute the code with below

access_token = AliceBlue.login_and_get_access_token(username="user_name",
                                                    password='password',
                                                    twoFA='Two_FA',
                                                    api_secret="api_secret",
                                                    app_id="app_id")
I am getting below error.

raceback (most recent call last):
  File "c:\Users\aniru\Dropbox\Gann calculation\Python project\AliceBlue.py", line 1, in <module>
    from alice_blue import *
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\site-packages\alice_blue\__init__.py", line 1, in <module>   
    from .alice_blue import AliceBlue, TransactionType, OrderType, ProductType, LiveFeedType, Instrument
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\site-packages\alice_blue\alice_blue.py", line 11, in <module>
    from protlib import CUInt, CStruct, CULong, CUChar, CArray, CUShort, CString
  File "C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\site-packages\protlib.py", line 220
    raise CError, cerror, tb
                ^
SyntaxError: invalid syntax

I tried connecting with Alice blue team, They were saying its syntax error check your code. But I just used their code to generate the Access token.

Could you please help me to resolve this issue?

**Comment by krishnavelu** [comment]
use python 3.9. protlib has issue with Python 3.10.

https://github.com/EliAndrewC/protlib/issues/2

**Comment by Aniruddha1980** [comment]
Thank you Very much Sir for your inputs, Yes I can able to get the access token now, However could you please guide or provide the document on how to access full LIVE Option chain from Alice blue API using Python?

**Comment by krishnavelu** [comment]
Full option chain is not available in Alice-bliue. Its only available in NSE website.

**Comment by Aniruddha1980** [comment]
Ok thank you very much Sir, But at least can we get 10-15 strike price option data ? As if we try to hit NSE website interim getting 401 error :-(

**Comment by krishnavelu** [comment]
Try

**Comment by krishnavelu** [comment]
Issue resolved. Try the latest version.
