### ISSUE TITLE
Facing issue at 'from alice_blue import *' on Mac

### ISSUE THREAD

**Issue by chaithu4k** [krishnavelu/alice_blue#393]
1. I've created the app and got my app_id and app_secret.
2. Then I did `pip3 install alice_blue`
3. Then created a new file and started with the first line `from alice_blue import *` and most of the other initialisation code to login and get access token from alice blue.

When I run the file, I get this error in the import line - 

```
Traceback (most recent call last):
  File "/Users/chaitanyateja/KCT/Trading/AliceBlue/kct_learning.py", line 4, in <module>
    from alice_blue import *
  File "/usr/local/lib/python3.9/site-packages/alice_blue/__init__.py", line 1, in <module>
    from .alice_blue import AliceBlue, TransactionType, OrderType, ProductType, LiveFeedType, Instrument
  File "/usr/local/lib/python3.9/site-packages/alice_blue/alice_blue.py", line 11, in <module>
    from protlib import CUInt, CStruct, CULong, CUChar, CArray, CUShort, CString
  File "/usr/local/lib/python3.9/site-packages/protlib.py", line 220
    raise CError, cerror, tb
                ^
SyntaxError: invalid syntax
[Finished in 423ms with exit code 1]
```

So unable to proceed further.

**Comment by krishnavelu** [comment]
use python 3.9. protlib has issue with Python 3.10.

https://github.com/EliAndrewC/protlib/issues/2

**Comment by chaithu4k** [comment]
Hello Krishna,

I've tried as you suggested. Tried to match your python version as well. But not sure of any luck here.
<img width="569" alt="Screenshot 2022-04-05 at 4 00 33 PM" src="https://user-images.githubusercontent.com/66135144/161735265-217046d2-41b2-4fd6-9993-de5da6251175.png">

**Comment by krishnavelu** [comment]
Not sure then. If I get more details about this I'll keep posted. Your Clang is 6.0, mine was 12.0. Does that make any difference? try install/use python from brew. I was using brew to install python instead of direct from website.

**Comment by chaithu4k** [comment]
I tried looking if Clang will make any difference but it apparently doesn't I guess. I'll try to uninstall and install python through brew then lets see. Please keep posted.

**Comment by krishnavelu** [comment]
Issue resolved. Try the newest version.
