### ISSUE TITLE
Error "Maximum Recursion Depth Exceeded"

### ISSUE THREAD

**Issue by codewithraviteja** [krishnavelu/alice_blue#396]
Hello, I've got this error. Could you please clarify on where did I made a mistake?
I have attached an Image. Please do check it

![image](https://user-images.githubusercontent.com/57951049/161921205-f3e8453b-042a-401f-8322-15276db2947f.png)

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating a new issue...
