### ISSUE TITLE
how do i fix oauth error.

### ISSUE THREAD

**Issue by Akshattanishq** [krishnavelu/alice_blue#397]
<img width="455" alt="image" src="https://user-images.githubusercontent.com/102853523/162439392-300cf091-c6b5-45ab-8983-39f5f8c9ce36.png">

**Comment by bhvarshn** [comment]
1)go to https://develop-api.aliceblueonline.com/
2) login with ur aliceblue credentials 
3) click on create app 
4) very important point . Give this link in url "https://ant.aliceblueonline.com/plugin/callback"
