### ISSUE TITLE
WHEN IM GENERATING ACCESS TOKEN IM GETTING ERROR 

### ISSUE THREAD

**Issue by Akshattanishq** [krishnavelu/alice_blue#398]
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth2/auth?response_type=code&state=test_state&client_id=app_id&redirect_uri=https://ant.aliceblueonline.com/plugin/callback HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth2/fallbacks/error?error=invalid_client&error_description=Client+authentication+failed+%28e.g.%2C+unknown+client%2C+no+client+authentication+included%2C+or+unsupported+authentication+method%29&error_hint=The+requested+OAuth+2.0+Client+does+not+exist. HTTP/1.1" 200 None
ERROR:alice_blue.alice_blue:OAuth 2.0 Error occurred. Please verify your api_secret

**Comment by bhvarshn** [comment]
1)go to https://develop-api.aliceblueonline.com/
2) login with ur aliceblue credentials
3) click on create app
4) very important point . Give this link in url "https://ant.aliceblueonline.com/plugin/callback"
