### ISSUE TITLE
__init__() got an unexpected keyword argument 'on_data'

### ISSUE THREAD

**Issue by Vijendra3087** [krishnavelu/alice_blue#404]
File "C:\ProgramData\Python\lib\site-packages\alice_blue\alice_blue.py", line 495, in start_websocket
    self.__websocket = websocket.WebSocketApp(url,

code written as per ones available in repository.

**Comment by krishnavelu** [comment]
Learn python

**Comment by Vijendra3087** [comment]
Very helpful response.

**Comment by krishnavelu** [comment]
I’m not here to teach python to everyone. There are many places you can learn python easily than here. Learn/practice python fully and jump into automated trading. 
It’s much better to not help a half baked python learner, than help him and make a way to make his account 0.
Just 1 wrong code, wrong loop, your account will go to 0.

**Comment by Vijendra3087** [comment]
Looking at the choice of words, Won't bother to check here again.. My codes were working well, after a week's break code not working so checked the documentation. You can have your point view EXPERT, thank you for your concern.
