### ISSUE TITLE
exchange timestamp showing date as 1970-01-18

### ISSUE THREAD

**Issue by srinidhihebbar260297** [krishnavelu/alice_blue#405]
def event_handler_quote_update(message):
    # print(f"quote update {message}")
    ltp=message['ltp']
    volume=message['volume']
    token=message['token']
    name=message['instrument'][2]
    ts=datetime.fromtimestamp(message['exchange_time_stamp']

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating a new issue...

**Comment by krishnavelu** [comment]
Try the new version of library. 1.0.5

**Comment by sunil0209** [comment]
> Try the new version of library. 1.0.5

Installed new version still "exchange_time_stamp" is printing incorrect values.

**Comment by krishnavelu** [comment]
Give me the sample code and the results you are getting as mentioned [here](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue).

**Comment by krishnavelu** [comment]
This is related to #410 
Update to latest version 1.0.6 and check.

**Comment by srinidhihebbar260297** [comment]
Working Fine now ,Thanks for the help brother

**Comment by srinidhihebbar260297** [comment]
The first tick of the day is still throwing incorrect values brother ,will show the output tomorrow as deleted it from database today

**Comment by yugavarmank** [comment]
Pls anyone help me to automate sasonline trading..

**Comment by srinidhihebbar260297** [comment]
@yugavarmank don't steal thread you can find thousands of coders on fivver

**Comment by yugavarmank** [comment]
My intention is not steal it srinidhi bro, just want to learn. Starting problem..

**Comment by srinidhihebbar260297** [comment]
This is not the place brother ..This thread is limited to the issue..If you need help reagarding python there are thousands of youtube channels teaching you from how to install till datascience.If you really wanted to learn you would have already started to learn brother ,all you wanted to do was create Noise in the thread

**Comment by rahulmr** [comment]
> Pls anyone help me to automate sasonline trading..

Check if [this](https://github.com/algo2t/alphatrade) is helpful
