### ISSUE TITLE
How to get current active position for intraday

### ISSUE THREAD

**Issue by bhvarshn** [krishnavelu/alice_blue#406]
HI 

Could you please help to know which api to use to get current active position for intraday. I want to know if i traded 10 stocks using bracket order , how many position are still active with Stock nae and not squared off at a given time 
I checked below api and none of them have proper documentation . 

print(alice.get_daywise_positions()) # get daywise positions
print(alice.get_netwise_positions()) # get netwise positions
print(alice.get_holding_positions()) # get holding positions 

Thanks

**Comment by krishnavelu** [comment]
Try all and see which suits for you.
