### ISSUE TITLE
Error on modify a Bracket Order

### ISSUE THREAD

**Issue by RemyaAnin** [krishnavelu/alice_blue#412]
Hi Krishna,

I am facing an error when trying to I modify a bracket Order. Below is the error received. My requirement is to edit the fixed SL and Target, once my order is executed.  So I execute the order with a higher SL and Target, then Modify it to pass my fixed SL and Target, based on executed price.

modify_buy_order_id = alice.modify_order(transaction_type=TransactionType.Buy,
instrument=ins_scrip,
order_id=str(buy_order_id),
quantity=int(quantity),
order_type=OrderType.Limit,
product_type=ProductType.BracketOrder,
price=float(avg_pr),
trigger_price=None,
stop_loss=float(avg_pr - 150.0),
square_off=float(avg_pr + 28.0),
trailing_sl=None,
is_amo=False
)
TypeError Traceback (most recent call last)
in
----> 1 modify_buy_order_id = alice.modify_order(transaction_type=TransactionType.Buy,
2 instrument=ins_scrip,
3 order_id=str(buy_order_id),
4 quantity=int(quantity),
5 order_type=OrderType.Limit,

TypeError: modify_order() got an unexpected keyword argument 'stop_los

**Comment by krishnavelu** [comment]
This is python error. 

`TypeError: modify_order() got an unexpected keyword argument 'stop_los`

Read the document of modify_order or look at the code what arguments you can pass

**Comment by RemyaAnin** [comment]
Hi Krishna Sir,

I truly appreciate the response. My goal is to edit the Target and SL after I fetch the average price. I am repasting the error again. Is stoploss currently available on Modify bracket Order? I had reached out to api@aliceblueindia.com for initial support. https://abfspl.freshdesk.com/helpdesk/tickets/605833 was closed asking me to refer documentation. Unfortunately, I did not I get a documentation for **modify_order** on https://github.com/krishnavelu/alice_blue. Moreover api@aliceblueindia.com also stopped responding after the refer documentation statement. 

I am repasting the error again for your kind perusal. 

TypeError                                 Traceback (most recent call last)
<ipython-input-77-c36972292ef0> in <module>
----> 1 modify_buy_order_id = alice.modify_order(transaction_type=TransactionType.Sell,
      2                                          instrument=ins_scrip,
      3                                          order_id=str(buy_order_id),
      4                                          quantity=int(quantity),
      5                                          order_type=OrderType.Limit,

TypeError: modify_order() got an unexpected keyword argument **'stop_loss'**

************** **************** *************** *************** *************** **********

When reviewing the code, I do not find stop_loss argument. 

    def modify_order(self, transaction_type, instrument, product_type, order_id, order_type, quantity, price=0.0,
                     trigger_price=0.0):# I do not see the SL and square_off arguments to modify BO. Hence this issue was raised.

**Comment by krishnavelu** [comment]
```Is stoploss currently available on Modify bracket Order?```
stop_loss is currently not available on modify order. What you are trying to do through API, try to do the same in web interface. And then try using API. Web Interface and API should be the same.

**Comment by RemyaAnin** [comment]
Thanks

**Comment by RemyaAnin** [comment]
Hi Krishna Sir,

Modification is available for Bracket orders on web. This uses points not Price. AliceBlue has confirmed this on# https://abfspl.freshdesk.com/helpdesk/tickets/611796.

I request if you could

1. Take an enhancement request  for BO modification via API
2. Have the documentation updated for alice.modify_order().

**Comment by krishnavelu** [comment]
I cannot see that ticket.

**Comment by RemyaAnin** [comment]
Attaching their email on the ticket. 

They clarify that BO modification is to use Points not Price. 

[Content_611796.pdf](https://github.com/krishnavelu/alice_blue/files/8832292/Content_611796.pdf)

**Comment by krishnavelu** [comment]
So your issue is resolved?

**Comment by RemyaAnin** [comment]
No Sir,

The issue I am reporting is 

1. Kindly take an enhancement request, for BO order modification via API.
2. Have the documentation updated for alice.modify_order().

**Comment by krishnavelu** [comment]
Try the new 2.0.0 version.
