### ISSUE TITLE
Websocket is not working!!

### ISSUE THREAD

**Issue by RattanRainu** [krishnavelu/alice_blue#415]
Hello!! I am using the code described below I am trying to subscribe live data using websocket but unfortunately after spending couple of days no results coming. I need your support to fix this issue.

from alice_blue import *
import time
import datetime

uname = '####'
pwd = '######'
t_FA='####'

c_id = '#####'
c_secret = '##########'
r_url= 'https://ant.aliceblueonline.com/plugin/callback'

access_token = AliceBlue.login_and_get_access_token(username=uname, password=pwd, twoFA=t_FA, api_secret=c_secret, app_id=c_id)
alice = AliceBlue(username=uname, password=pwd,               
                  access_token = access_token,
                  master_contracts_to_download=['NSE', 'NFO','MCX'])

socket_opened= False

def event_handler_quote_update(message):
    print(f"quote update {message}")

def exchange_messages(message):
    print(f"exchange messages {message}")

def open_callback():
    global socket_opened
    socket_opened = True

 def testalice():
     print('function call')
     #print(AliceBlue.login_and_get_access_token(username=uname, password=pwd, twoFA=t_FA, api_secret=c_secret, app_id=c_id))
    
 alice.start_websocket(subscribe_callback=event_handler_quote_update,exchange_messages_callback=exchange_messages,socket_open_callback=open_callback, run_in_background=True)
   
    try:
        while(socket_opened==False):
            print("NOT OPEN**********")
            time.sleep(1)
            pass
        while(socket_opened== True):
            alice.subscribe(alice.get_instrument_by_token('MCX', 233318), LiveFeedType.MARKET_DATA)
            time.sleep(10)
    except Exception as e:
        print(e)

testalice()

**Comment by krishnavelu** [comment]
use the example mentioned here as it is.

https://github.com/krishnavelu/alice_blue#subscribe-to-a-live-feed

**Comment by RattanRainu** [comment]
> use the example mentioned here as it is.
> 
> https://github.com/krishnavelu/alice_blue#subscribe-to-a-live-feed

I have used this code and problem is with the blow code actually socket is not opening. I dont know why but I did lots of changes in the code but still it stuck in the loop. 

alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)

while(socket_opened==False):
    print('Socket not opened !!')
    pass

alice.subscribe(alice.get_instrument_by_symbol('NSE', 'ONGC'), LiveFeedType.MARKET_DATA)
sleep(10)

**Comment by RattanRainu** [comment]
I have used this code and problem is with the blow code actually socket is not opening. I dont know why but I did lots of changes in the code but still it stuck in the loop.

alice.start_websocket(subscribe_callback=event_handler_quote_update,
socket_open_callback=open_callback,
run_in_background=True)

while(socket_opened==False):
print('Socket not opened !!')
pass

alice.subscribe(alice.get_instrument_by_symbol('NSE', 'ONGC'), LiveFeedType.MARKET_DATA)
sleep(10)

**Comment by krishnavelu** [comment]
I said use the code as it is, without any modifications. It works for everyone, it should work for you too.
