### ISSUE TITLE
unable to square-off positions in equity-delivery

### ISSUE THREAD

**Issue by siwaugh** [krishnavelu/alice_blue#416]
Hi Sir,
Using the Alice Blue API, through python coding, I am able to buy shares in delivery. But I am unable to square-off them. I am unable to place stoploss order either.

However, this problem is not there for intraday trades. But we can't go for intraday always. I hope you are aware that exchange blocks intraday trading for the shares of some of the companies on some days. On such days we should go for delivery only.

Please do the needful.

Regards,
Siva

**Comment by krishnavelu** [comment]
check your POA. Also there is some limit in selling delivery across all brokers. Check with Alice on both.
