### ISSUE TITLE
atp is populated as 0 for all stocks in websocket feed 

### ISSUE THREAD

**Issue by nitishgupta08** [krishnavelu/alice_blue#417]
Hello Sir
ATP value is 0.0 for all the stocks when subscribing to the instruments using `LiveFeedType.MARKET_DATA`. Please look into it. 

Also when subscribing to the instruments using `LiveFeedType.FULL_SNAPQUOTE` , I am getting correct data for ATP but volume becomes 0. Is there to way to get atp value from `LiveFeedType.FULL_SNAPQUOTE`  to `LiveFeedType.MARKET_DATA`?

An example below :
{'exchange': 'NSE', 'token': 3426, 'ltp': 257.85, 'ltt': 1650271303, 'ltq': 1, 'volume': 71287500, 'best_bid_price': 257.85, 'best_bid_quantity': 163, 'best_ask_price': 257.95, 'best_ask_quantity': 1637, 'total_buy_quantity': 2946313, 'total_sell_quantity': 3989858, **`'atp': 0.0`**, 'exchange_time_stamp': 5070890, 'open': 259.65, 'high': 16502713.04, 'low': 267.9, 'close': 267.9, 'yearly_high': 252.0, 'yearly_low': 273.1, 'instrument': Instrument(exchange='NSE', token=3426, symbol='TATAPOWER', name='TATA POWER CO LTD', expiry=None, lot_size=None)}

**Comment by nitishgupta08** [comment]
I must also add that this works properly on windows but not on ubuntu

**Comment by nitishgupta08** [comment]
New Findings. This works properly on version `1.0.2` in both windows and ubuntu . I was on `1.0.4` when it was not working. For anyone having the same issue just downgrade to `alice_blue==1.0.2`

**Comment by krishnavelu** [comment]
Did you try the new version? 1.0.6. It's resolved.
