### ISSUE TITLE
Access token is getting expired.

### ISSUE THREAD

**Issue by jaydave1988** [krishnavelu/alice_blue#418]
Aliceblue has launched new portal url and app ant 2.0.
When user loges in to this new portal or app, generated access token is getting expired.

**Comment by jaydave1988** [comment]
https://v2api.aliceblueonline.com/introduction is having new APIs we need to add here to overcome this issue.

**Comment by krishnavelu** [comment]
No updates as of now.

**Comment by aeron7** [comment]
Hi @jaydave1988 , Right now there is no intention of updating or maintaining this API at all. We are an official strategic partner of Aliceblue and initially communicated and agreed to maintain and develop AliceBlue Python API along with its ecosystem.

@krishnavelu developed the API. They put this repo link on their main website. Now, they have removed it from the main website.

Now they have copied this code shamelessly and "tried" to make their own API.

**So, Either they have to put this library as an official library on their website. Or, they can make their own library themselves.**
