### ISSUE TITLE
Support for /ScripDetails/getScripQuoteDetails

### ISSUE THREAD

**Issue by vinitshetty** [krishnavelu/alice_blue#419]
https://v2api.aliceblueonline.com/marketWatch

/ScripDetails/getScripQuoteDetails

provides LTP which is missing now. Please support.

**Comment by krishnavelu** [comment]
https://github.com/krishnavelu/alice_blue/blob/5b9a3ef2aea25a72ea4edb1adb5c000af763dae2/alice_blue/alice_blue.py#L516

**Comment by vinitshetty** [comment]
getScripQuote is a new API which will provide LTP information. ScripInfo API doesn't provide the same details. They are two different APIs.

**Comment by krishnavelu** [comment]
Did you try different type of quotes?
What did you not get from these 4 which you are expecting?

https://github.com/krishnavelu/alice_blue#four-types-of-feed-data-are-available

**Comment by vinitshetty** [comment]
Websocket requires subscription. Whereas ad-hoc API calls will be easier in many use cases. 

So I was requesting if you have plans to support V3 APIs from alice. They look to be very different from V2. 

https://a3.aliceblueonline.com/rest/AliceBlueAPIService/api/

**Comment by krishnavelu** [comment]
Coming in V2
