### ISSUE TITLE
API Key generate for order processing 

### ISSUE THREAD

**Issue by Pawanmatade** [krishnavelu/alice_blue#42]
I need some small understanding we are trying generate the API key and which format alice blue reading ApI key for order processing need some understanding for encryption and decryption formula . we are trying to develop Auto Buy/Sell Order through MT4.

Thanks for your support in Advance.

**Comment by krishnavelu** [comment]
Didn’t understand your question. Rephrase.

**Comment by krishnavelu** [comment]
Closing now. Reopen if you need again.
