### ISSUE TITLE
Created standalone alice_blue algo app from py2app but websocket is not working

### ISSUE THREAD

**Issue by RRR008** [krishnavelu/alice_blue#420]
Hi Sir,
I have create standalone app from the help of py2app but when I run the app I am able to get the access_token but unfortunately socket is not getting connected. I searched everywhere and it's been more than a week. I don't know why socket is not connecting. It runs fine when I run the code from SublimeText but the case is not same for standalone app.
Anybody have any idea on this then please help me.

Thank You

**Comment by krishnavelu** [comment]
Sorry, I cannot help for your applications
