### ISSUE TITLE
Need to squareoff all existing positions

### ISSUE THREAD

**Issue by Jagan9494** [krishnavelu/alice_blue#422]
Hi Team,

can you please help me on python code  for .. need to square off all existing positions .

**Comment by krishnavelu** [comment]
I cannot help on your application.

**Comment by Jagan9494** [comment]
Ok thank Krishnavelu,
can you help on below one.

I have one open position with below details
symbol: BANKNIFTY2270734800CE
quantity: 25
            res = alice.place_order(TransactionType.Buy,
                                    instrument=symbol,
                                    quantity=quantity,
                                    order_type=OrderType.Market,
                                    product_type=ProductType.Intraday,
                                    price=0.0,
                                    trigger_price=None,
                                    stop_loss=None,
                                    square_off=None,
                                    trailing_sl=None,
                                    is_amo=False,
                                    order_tag=orderTag)

symbol: BANKNIFTY2270734800CE (Buy order running)
quantity: 25
order_id: 220701000059774

I want to close the above order with market price  and i am using below modify order but not working

response = alice.modify_order(transaction_type=TransactionType.Sell,
                                      instrument=symbol,
                                      order_id=order_id,
                                      quantity=quantity,
                                      order_type=OrderType.Market,
                                      product_type=ProductType.Intraday,
                                      price=0,
                                      trigger_price=0)

is some thing i am missing ?

**Comment by srinidhihebbar260297** [comment]
You will need to modify SL order ID or place a fresh sell order,you can fetch the sl id by open positions or passing it to a variable while passing order,In your code above you are not passing the order ID
