### ISSUE TITLE
Old API Discontinued

### ISSUE THREAD

**Issue by vinitshetty** [krishnavelu/alice_blue#427]
Alice has officially shared Aug 31st as an end date for old apis. Please let us know if you have plans to support new APIs.

**Comment by krishnavelu** [comment]
Where it's shared officially?

**Comment by jaydave1988** [comment]
![AliceblueSms](https://user-images.githubusercontent.com/20503868/178115518-09b84022-130b-4063-a715-8c000ce18c09.jpeg)
@krishnavelu Received SMS 2 days ago.

**Comment by vinitshetty** [comment]
@krishnavelu any plans to support latest APIs?

**Comment by krishnavelu** [comment]
Maybe, not sure about dates.

**Comment by aeron7** [comment]
Hi @vinitshetty, Right now there is no intention of updating or maintaining this API at all. We are an official strategic partner of Aliceblue and initially communicated and agreed to maintain and develop AliceBlue Python API along with its ecosystem.

@krishnavelu developed the API. They put this repo link on their main website. Now, they have removed it from the main website.

Now they have copied this code shamelessly and "tried" to make their own API.

**So, Either they have to put this library as an official library on their website. Or, they can make their own library themselves.**

**Comment by vinitshetty** [comment]
Attaching official email shared by Alice blue here in this email. Bottom of
the email you will find the date.

**Comment by krishnavelu** [comment]
??
