### ISSUE TITLE
Not able to place stoplossMarket order

### ISSUE THREAD

**Issue by ghost** [krishnavelu/alice_blue#43]
Facing issue with stoplossMarket order.

I am sending this-

`alice.place_order(transaction_type = TransactionType.Buy, instrument = alice.get_instrument_by_symbol('NSE', 'BHEL'), quantity = 1, order_type = OrderType.StopLossMarket, product_type = ProductType.Intraday, price = 0.0, trigger_price = 43.2, 
 stop_loss = None, square_off = None, trailing_sl = None, is_amo = False)
`

Although order is placed successfully with following message-

`{'status': 'success', 'message': 'Order placed successfully', 'data': {'oms_order_id': '20XXXXXXXXXXXX18'}}`

But order is getting rejected **REJECT REASON
Invalid price type**
![image](https://user-images.githubusercontent.com/59556194/71804964-f9a23a00-308a-11ea-9d1b-5de88c3cd88d.png)

**Comment by ghost** [comment]
need to change SLM to SL-M 
working fine after this
`class OrderType(enum.Enum):
    Market = 'MARKET'
    Limit = 'LIMIT'
    StopLossLimit = 'SL'
    StopLossMarket = 'SL-M'`

**Comment by krishnavelu** [comment]
@anoopjangra Fixed in develop branch. Please test it and let me know if this works

**Comment by krishnavelu** [comment]
@anoopjangra did you test it? is it working for you?
