### ISSUE TITLE
need live or historical data of option

### ISSUE THREAD

**Issue by Parth291** [krishnavelu/alice_blue#430]
hello sir,
My name is parth surani and i use your api since 3 month .
but i want live tick to tick data of option or also want historical data of option. suggest me which type of instrument name can i use for that process.
Thank You

**Comment by krishnavelu** [comment]
Read the document, there are examples of how to get live data.
https://github.com/krishnavelu/alice_blue.
Historical data is not supported by this library.

**Comment by Parth291** [comment]
Hello sir,
Which type of instrument name I need to use for option tick to tick
data(bank nifty option)

**Comment by krishnavelu** [comment]
Historical data is coming in V2
