### ISSUE TITLE
Not able to fetch live option chain stike data.

### ISSUE THREAD

**Issue by Leelamrutha** [krishnavelu/alice_blue#432]
Hi Krishna Sir,
I am able to get NSE cash Stock but not option chain Derivatives .
How to get live data of optionchain of particular stike and build ohlc candle in alice blue api.Can any one help me .
This the sample code i used.

**nifty50_nse_index = alice.get_instrument_by_symbol('NSE', 'NIFTY 04 AUG22 17450 CE') Cannot find symbol NSE NIFTY 04 AUG22 17450 CE in master contract**

Thanks in advance
Regards
Leela

**Comment by krishnavelu** [comment]
Read the document fully before you do something.

https://github.com/krishnavelu/alice_blue#get-tradable-instruments
