### ISSUE TITLE
V2 New API implementation

### ISSUE THREAD

**Issue by rajamurugan44** [krishnavelu/alice_blue#434]
Hi, Any tentative date by when we can get update on V2 connect.. My code is not running now due to API change from Aliceblue .

Please support us..

**Comment by krishnavelu** [comment]
Maybe around this month end.

**Comment by aeron7** [comment]
Hi @rajamurugan44 , Right now there is no intention of updating or maintaining this API at all. We are an official strategic partner of Aliceblue and initially communicated and agreed to maintain and develop AliceBlue Python API along with its ecosystem.

@krishnavelu developed the API. They put this repo link on their main website. **Now, they have removed it from the main website.**

Now they have copied this code shamelessly and "tried" to make their own API.

**So, Either they have to put this library as an official library on their website. Or, they can make their own library themselves.**

**Comment by rajamurugan44** [comment]
Raised this concern to Aliceblue team as well.. Those new API team is not working it properly.. If u guys can update ur code, then it would be helpful for lot many traders..

**Comment by aeron7** [comment]
Our issues with Aliceblue is resolved. Krishna is updating the API currently. Stay tuned. It will be updated shortly.

**Comment by Revanthsatyam** [comment]
First of all thank you so much for updating the API.  When can we expect this to be updated, any specific date ?
I'm asking this as we will able able to use the current API till 15th September only and the deadline is near-by.

**Comment by krishnavelu** [comment]
Before sept 15

**Comment by aeron7** [comment]
@Revanthsatyam We can release it right away but it will break in an unprofessional way. [Like they did themselves copying this library in a childish way]. Their current documentation is full of errors and missing context. If you peruse, you can see many grammatical errors everywhere.

**Comment by rajamurugan44** [comment]
Great and happy to see it as completed. When we can expect it live?

**Comment by krishnavelu** [comment]
Another 1 hour.
