### ISSUE TITLE
Support for Nifty Pre-open market data

### ISSUE THREAD

**Issue by enthu12** [krishnavelu/alice_blue#435]
Hi Krishna, 
Can you please confirm if this supports pre-open market data for NSE.
Primarily, I need to fetch Nifty50 Pre-open market value as displayed on https://www1.nseindia.com/live_market/dynaContent/live_watch/pre_open_market/pre_open_market.htm.

Thanks,

**Comment by krishnavelu** [comment]
Live data starts during pre-open time.

**Comment by enthu12** [comment]
Thanks for immediate response, @krishnavelu
