### ISSUE TITLE
MCX delivery with goldpetal futures

### ISSUE THREAD

**Issue by priyakumariengineer** [krishnavelu/alice_blue#44]
so if you try this order 
```
    r = alice.place_order(transaction_type = TransactionType.Buy,
             instrument = alice.get_instrument_by_symbol('MCX', 'GOLDPETAL FEB FUT'),
             quantity = 1,
             order_type = OrderType.StopLossLimit,
             product_type = ProductType.Delivery,
             price = 3961.0,
             trigger_price = 3961.0,
             stop_loss = None,
             square_off = None,
             trailing_sl = None,
             is_amo = False)
```

You will have issue putting order , as goldpetal is MCX commodity but only delivry is allowed , so ProductType should be NRML in this case , I have modified code as below and it is working now .

```
        elif(product_type == ProductType.Delivery):
            
            print(instrument.token)
            if(instrument.exchange == 'NFO'):
                product_type = 'NRML'
            elif(instrument.exchange == 'MCX' and str(instrument.symbol).split()[0] == 'GOLDPETAL'):
                product_type = 'NRML'
            else:
                product_type = 'CNC'
        elif(product_type == ProductType.CoverOrder):
```

sorry for fast write up , but hope you will understand.

**Comment by krishnavelu** [comment]
Will test and modify the library

**Comment by krishnavelu** [comment]
@priyakumariengineer  Fixed in develop branch. Please test it.

**Comment by priyakumariengineer** [comment]
@krishnavelu I seen code modification , I have personaly seen only that with GOLDPETAL cnc ( intraday ) margins are not allowed , is it true for all MCX commodities ? i.e do all MCX commoditity only allows NRML ?? 

I have heard about recent changes of margin requirnment for MCX commodities but not sure .

**Comment by krishnavelu** [comment]
I don’t know. I don’t do commodities. I thought its for all commodities. Can you please test and let me know, is it for all commodities?

**Comment by priyakumariengineer** [comment]
Ohk I will test and update you, thanks .

**Comment by krishnavelu** [comment]
@priyakumariengineer any updates?

**Comment by priyakumariengineer** [comment]
didn't got time sorry. I will update you soon.

**Comment by krishnavelu** [comment]
I'm waiting for your test results for 0.0.7 release. If this goes good. I'll make a new release which has many bug fixes & enhancements.

**Comment by krishnavelu** [comment]
@priyakumariengineer did you get time to test it?

**Comment by krishnavelu** [comment]
Closing this now. Reopen if needed.
