### ISSUE TITLE
Unable to get session ID

### ISSUE THREAD

**Issue by Revanthsatyam** [krishnavelu/alice_blue#440]
Unable to get session id from the below code and an error has occurred "TypeError: Object of type bytes is not JSON serializable"

session_id = AliceBlue.login_and_get_sessioID(   username    = "xxxxxx", 
                                                    password    = "xxxxxx", 
                                                    twoFA       = "xxxx",
                                                    app_id      = "xxxxxxx",
                                                    api_secret  = "xxxxxxx")

I have removed my account details from the above code to showcase the code i was using.

![Capture](https://user-images.githubusercontent.com/74353642/189514113-63b79ef7-9f28-4654-b7af-cdc42feb3ed1.PNG)

**Comment by ThejusGujj** [comment]
![image](https://user-images.githubusercontent.com/113293977/189529731-8d7d7090-0f35-4692-9d50-4cd4d3a61fc5.png)
addded this line at line number 203
checksum=checksum.decode("utf-8")
        data = {"userId" : username,
                "userData" : checksum}

**Comment by Revanthsatyam** [comment]
> ![image](https://user-images.githubusercontent.com/113293977/189529731-8d7d7090-0f35-4692-9d50-4cd4d3a61fc5.png) addded this line at line number 203 checksum=checksum.decode("utf-8") data = {"userId" : username, "userData" : checksum}

Thank you that has worked, but got new issue when trying to run below code

alice = AliceBlue(username = 'xxxxxxx', session_id = session_id)

![Capture](https://user-images.githubusercontent.com/74353642/189533232-309ef2a4-bd24-40bc-adc0-30f7e53c2826.PNG)

**Comment by krishnavelu** [comment]
@Revanthsatyam  what is the python version you are using and what's your OS?
the checksum will be in bytes. I don't get any error even though my checksum is in bytes. Print and see what's there in checksum.

It should be something like this.

`'userData': b'U2FsdGVkX19RA6WsfEok7n95RBNaiQWhhDzA4VTlwQk='`

**Comment by ThejusGujj** [comment]
I got the same error and issue resolved once its converted to UTF-8 from bytes. My python version is 3.10

**Comment by krishnavelu** [comment]
@ThejusGujj which os are you using?

**Comment by Revanthsatyam** [comment]
> @Revanthsatyam what is the python version you are using and what's your OS? the checksum will be in bytes. I don't get any error even though my checksum is in bytes. Print and see what's there in checksum.
> 
> It should be something like this.
> 
> `'userData': b'U2FsdGVkX19RA6WsfEok7n95RBNaiQWhhDzA4VTlwQk='`

I am using Windows 10 and python 3.10

**Comment by ThejusGujj** [comment]
> @ThejusGujj which os are you using?

I am using Windows 11 and python 3.10 . Please let me know which version of python is recommended.

**Comment by rajamurugan44** [comment]
You need to decode userData with "utf-8".. Then its working fine...

**Comment by Revanthsatyam** [comment]
> @Revanthsatyam what is the python version you are using and what's your OS? the checksum will be in bytes. I don't get any error even though my checksum is in bytes. Print and see what's there in checksum.
> 
> It should be something like this.
> 
> `'userData': b'U2FsdGVkX19RA6WsfEok7n95RBNaiQWhhDzA4VTlwQk='`

@krishnavelu i have tried to print checksum and it got printed something like the above only.

![Capture](https://user-images.githubusercontent.com/74353642/189656520-f0b246a5-d9b6-4e79-9adf-073034b57831.PNG)

**Comment by Revanthsatyam** [comment]
> You need to decode userData with "utf-8".. Then its working fine...

@rajamurugan44  May i know how you have resolved this issue.

**Comment by brijesh872** [comment]
Anyone can help with this error?

**Couldn't get profile info with credentials provided ''bse_fo''**

session_id generated successfully, Thanks to @ThejusGujj but get error when execute `alice = AliceBlue(username = username, session_id = session_id)` error

**Comment by krishnavelu** [comment]
@brijesh872  @Revanthsatyam enable logging and show me the output.

**Comment by brijesh872** [comment]
> @brijesh872 @Revanthsatyam enable logging and show me the output.

![Screenshot-from-2022-09-13-07-45-51](https://user-images.githubusercontent.com/53258820/189793513-b94111c5-9a5e-4806-a299-32ded76a5b9a.png)

**Comment by brijesh872** [comment]
**Couldn't get profile info with credentials provided ''bse_fo''** 

Issue solved, Check this
https://github.com/krishnavelu/alice_blue/issues/443#issuecomment-1244817035

**Comment by Revanthsatyam** [comment]
> **Couldn't get profile info with credentials provided ''bse_fo''**
> 
> Issue solved, Check this [#443 (comment)](https://github.com/krishnavelu/alice_blue/issues/443#issuecomment-1244817035)

Issue has been resolved. Thank you @brijesh872 @HardKothari @krishnavelu 

Closing this one as completed.

**Comment by krishnavelu** [comment]
@Revanthsatyam  How did you resolve?

**Comment by Revanthsatyam** [comment]
> @Revanthsatyam How did you resolve?

@krishnavelu I followed the steps mentioned in #443 by @HardKothari and replaced the code in line 525 with the below code
`self.__enabled_exchanges = []
for i in x:
    try:
        self.__enabled_exchanges.append(exch_dt[i])
    except:
        pass`

**Comment by krishnavelu** [comment]
@Revanthsatyam  that issue is related to "bse_fo". Your's is related to `Object of type bytes not JSON serializable`.
Is both same?

**Comment by Revanthsatyam** [comment]
> @Revanthsatyam that issue is related to "bse_fo". Your's is related to `Object of type bytes not JSON serializable`. Is both same?

@krishnavelu I came across with both issues. At first I got
`Object of type bytes not JSON serializable` issue and later I came across with "bse_fo" issue 

Json serializable issue was resolved by adding the below code at line 202
`checksum=checksum.decode("utf-8")`
and the other issues was resolved by following the steps mentioned in #443.

**Comment by aeron7** [comment]
For some reason, this issue comes on Jupyter Notebooks only, Google Collab too. Has anyone else faced it in normal IDEs?

Later I landed here - https://stackoverflow.com/a/69392446/11068088

When it involves a server, the server will decode the binary data to bytes. Summing up this thread, You need to do two things  - 

https://github.com/krishnavelu/alice_blue/issues/440#issuecomment-1242963418
https://github.com/krishnavelu/alice_blue/issues/443#issuecomment-1244817035
