### ISSUE TITLE
unable to fetch bank nifty and nifty futures or spot.

### ISSUE THREAD

**Issue by ThejusGujj** [krishnavelu/alice_blue#441]
for some reason not able to fetch the NIFTY BANKNIFTY future or spot instruments.
![image](https://user-images.githubusercontent.com/113293977/189562325-c71bc544-60ef-4b82-80b7-f8cffeb30433.png)

bnf_fut=alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=getMonthlyExpiryDayDate(), is_fut=True, strike=None, is_CE = False)
nifty_fut=alice.get_instrument_for_fno(symbol = 'NIFTY', expiry_date=getMonthlyExpiryDayDate(), is_fut=True, strike=None, is_CE = False)
nifty_spot =  alice.get_instrument_by_symbol('NSE', 'Nifty 50')
bnf_spot = alice.get_instrument_by_symbol('NSE', 'Nifty Bank')

**Comment by rajamurugan44** [comment]
Nifty and BankNifty moved to "Indices".. We need to download Indices contract and search as "Indices", "Nifty 50" to get Nifty instrument detail

**Comment by krishnavelu** [comment]
Fixed in develop branch. Install develop branch and try using this.

```python
nifty50_nse_index = alice.get_instrument_by_symbol('NSE', 'NIFTY 50')
banknifty_nse_index = alice.get_instrument_by_symbol('NSE', 'NIFTY Bank')
```

**Comment by ThejusGujj** [comment]
bnf_fut=alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=getMonthlyExpiryDayDate(), is_fut=True, strike=None, is_CE = False)
nifty_fut=alice.get_instrument_for_fno(symbol = 'NIFTY', expiry_date=getMonthlyExpiryDayDate(), is_fut=True, strike=None, is_CE = False)
nifty_spot = alice.get_instrument_by_symbol('NSE', 'NIFTY 50')
bnf_spot = alice.get_instrument_by_symbol('NSE', 'NIFTY BANK')

above code worked from develop branch
