### ISSUE TITLE
Websocker Evenhandler is not working

### ISSUE THREAD

**Issue by rajamurugan44** [krishnavelu/alice_blue#442]
{"t":"ck","s":"NOT_OK"}
{'t': 'ck', 's': 'NOT_OK'}

Getting NOT_OK message

**Comment by krishnavelu** [comment]
If you feel lazy to add more details while creating an issue, I'll also feel lazy to help you.

Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating a new issue...
