### ISSUE TITLE
Couldn't get profile info with credentials provided ''bse_fo''

### ISSUE THREAD

**Issue by brijesh872** [krishnavelu/alice_blue#443]
### Couldn't get profile info with credentials provided ''bse_fo''

when execute this line `alice = AliceBlue(username = username, session_id = session_id)` get the **error**  : Couldn't get profile info with credentials provided ''bse_fo'' 

Check everything `username, password, twoFA, app_id, api_secret` more than twice, but still facing this error.

my code:
```
        session_id = AliceBlue.login_and_get_sessioID(   username    = "63****", 
                                                            password    = "*********", 
                                                            twoFA       = ****,
                                                            app_id      = "***************",
                                                            api_secret  = "***-----***")
        
        print("\n SESSTION_ID: ", session_id)
        
        alice = AliceBlue(username = "63****", session_id = session_id)  # ERROR: Couldn't get profile info with credentials provided ''bse_fo''
        
        print("\n>>>>>>>>>>>>>>>>>>>>>")

        print(alice.get_balance())

```

**Comment by HardKothari** [comment]
I did get the same error which I was able to resolve by replacing below code of line in alice_blue.py in definition get_profile(self):

Original Code: (Line 525)
`self.__enabled_exchanges = [exch_dt[i] for i in x]`

Replaced with:
```
self.__enabled_exchanges = []
for i in x:
    try:
        self.__enabled_exchanges.append(exch_dt[i])
    except:
        pass
```

It seems we are receiving bse_fo as a symbol from alice_blue which is not mapped according to their official API document on their website.

**Comment by brijesh872** [comment]
> I did get the same error which I was able to resolve by replacing below code of line in alice_blue.py in definition get_profile(self):
> 
> Original Code: (Line 525) `self.__enabled_exchanges = [exch_dt[i] for i in x]`
> 
> Replaced with:
> 
> ```
> self.__enabled_exchanges = []
> for i in x:
>     try:
>         self.__enabled_exchanges.append(exch_dt[I])
>     except:
>         pass
> ```
> 
> It seems we are receiving bse_fo as a symbol from alice_blue which is not mapped according to their official API document on their website.

Thanks, bro, **it solved**

**Comment by HardKothari** [comment]
Glad it worked :)
I would still suggest this to be kept open so that this can be changed in the code officially if its required after review. Not sure if this is the optimum solution.

**Comment by krishnavelu** [comment]
This is just a temporary workaround.

**Comment by krishnavelu** [comment]
- [ ] Alice should not send "bse_fo" in exchange for profile response.

**Comment by brijesh872** [comment]
> This is just a temporary workaround.

So can we do anything for a permanent solution? 

because only 2 days left to move on to Alice's new version (a3)!

**Comment by krishnavelu** [comment]
@brijesh872 Fixed now.
