### ISSUE TITLE
Issue in getting live feed via websocket

### ISSUE THREAD

**Issue by Revanthsatyam** [krishnavelu/alice_blue#446]
@krishnavelu Whenever i tried to run the below code i ended up getting error "websocket run forever ended in exception"

`def event_handler_quote_update(message):
    print(f"quote update {message}")

alice.start_websocket(subscribe_callback=event_handler_quote_update)

alice.subscribe(alice.get_instrument_by_symbol('NSE', 'ONGC'), LiveFeedType.TICK_DATA)
sleep(10)`

![image](https://user-images.githubusercontent.com/74353642/190069138-9dced2a8-26db-499d-a6ea-fe16a96c51a9.png)

**Comment by AshweejaKR** [comment]
@krishnavelu @Revanthsatyam Same for me also getting same ERROR. I am using below code:

Even I tried both obj.subscribe(ins_scrip, LiveFeedType.COMPACT) & obj.subscribe(ins_scrip, LiveFeedType.TICK_DATA)


My Sample Code:
import requests, json
from alice_blue import *

print("Hello Auto Trading Start Here...\n\n")

USERNAME = " ***** "
PASSWORD = " ***** "
TWOFA = " ***** "
APP_ID = ' ***** '
API_SECRET = ' ***** '

def login(_app_id, _api_secret, _username, _password, _twofa):
    print("loging in ...")
    obj = "NA"
    try:
        access_token = AliceBlue.login_and_get_sessioID(username = _username, 
                                                        password = _password, 
                                                        twoFA = _twofa, 
                                                        app_id = APP_ID, 
                                                        api_secret = _api_secret)
        print('access_token: ', access_token, '\n')
        obj = AliceBlue(username = _username, 
                        session_id = access_token, 
                        master_contracts_to_download = ['NSE'])
        print("Login Successfull ...", obj)
    except Exception as err:
        print('ERROR: ', err)

    return obj

obj = login(APP_ID, API_SECRET, USERNAME, PASSWORD, TWOFA)

socket_opened = False
def event_handler_quote_update(message):
    print("message")

def open_callback():
    global socket_opened
    socket_opened = True 

print('Obj: ', obj);

ins_scrip = obj.get_instrument_by_symbol('NSE', 'INFY')

obj.start_websocket(subscribe_callback=event_handler_quote_update,
                          socket_open_callback=open_callback)

while(socket_opened==False):    # wait till socket open & then subscribe
        pass
    
obj.subscribe(ins_scrip, LiveFeedType.TICK_DATA)

print('THE END')

**Comment by krishnavelu** [comment]
what version of `websocket_client` do you guys have?

**Comment by Revanthsatyam** [comment]
> what version of `websocket_client` do you guys have?

@krishnavelu i am using '0.58.0' version. What should i do to resolve this issue

**Comment by Revanthsatyam** [comment]
> > what version of `websocket_client` do you guys have?
> 
> @krishnavelu i am using '0.58.0' version. What should i do to resolve this issue

@krishnavelu I have upgraded my websocket client version to 1.4.1 by doing so i am able to get live feed now thank you.

@AshweejaKR I would suggest you also to do the same anyways thank you for the help.
