### ISSUE TITLE
ERROR:websocket:Handshake status 502 Bad Gateway - goodbye

### ISSUE THREAD

**Issue by HardKothari** [krishnavelu/alice_blue#448]
It seems that Alice Blue changed the WebSocket url in their official documentation which resulted into below error:

```
ERROR:websocket:Handshake status 502 Bad Gateway - goodbye
```

old url on line 127 of code:
```
"ws"                    :   "wss://ws2.aliceblueonline.com/NorenWS/"
```

As per Alice Blue API documentation https://v2api.aliceblueonline.com/websocket

```
"ws"                    :   "wss://ws1.aliceblueonline.com/NorenWS/"
```

This change resolves the issue of Bad Gateway

**Comment by krishnavelu** [comment]
I don't get this error. Try again after some times.

**Comment by HardKothari** [comment]
Something is wrong from Alice Blue's end. They have updated documentation with a different link and its working as is now. Still the official documentation shows ws1 as the link and not the ws2. Both links are working for me as of now.
