### ISSUE TITLE
Any instruction to move from old version to new version

### ISSUE THREAD

**Issue by Dhanasekarts** [krishnavelu/alice_blue#449]
Hi Krishna,

I am not sure whether we need to make any change in our code to move to new version.

Can you please list out the differences you made in new version, so that we can change those parts alone in our code.

Please let us know if existing functionalities will work as it is

**Comment by Dhanasekarts** [comment]
Please update the sample program also to follow new version as it will clear understanding very well.

**Comment by krishnavelu** [comment]
I've clearly documented the usage of new version of the library. Read that.
