### ISSUE TITLE
NOT ABLE TO FETCH NIFTY SPOT

### ISSUE THREAD

**Issue by srinidhihebbar260297** [krishnavelu/alice_blue#45]
Respected sir, 
I am not able to fetch Nifty50 spot price nor able to subscribe to live spot data please do the needful regarding the same
ps
already reffered to issue 18 and 27 I am currently working algo for nifty options which wont be possible without the same,
thankyou

**Comment by krishnavelu** [comment]
You are just saying, “God, I’m having problems please help me”. Only god can help you, I cannot.
How would I know what code you’ve tried and what’s the result you are getting?

Refer issue #25

**Comment by srinidhihebbar260297** [comment]
Print(pd.DataFrame(alice.get_instrument_by_symbol('NSE', 'Nifty 50')))

**Comment by srinidhihebbar260297** [comment]
0
0       NSE
1     26000
2  Nifty 50
3  Nifty 50
4      None
5      None



OUTPUT

**Comment by srinidhihebbar260297** [comment]
not able to fetch the spot price

**Comment by krishnavelu** [comment]
Refer issue #25

**Comment by krishnavelu** [comment]
Your issue still not resolved?

**Comment by srinidhihebbar260297** [comment]
No sir It is still not able to fetch the spot price 
your help regarding the same is highly appreciated

**Comment by srinidhihebbar260297** [comment]
even if i try to fetch from the code


print(pd.DataFrame(alice.search_instruments('NFO', 'BANKNIFTY')[:10]))

It is still not Able to Fetch  the price 

OUTPUT

exchange  token                       symbol name      expiry lot_size
0      NFO  40963  BANKNIFTY 12 MAR20 29100 CE       2020-03-12       20
1      NFO  40965  BANKNIFTY 12 MAR20 29100 PE       2020-03-12       20
2      NFO  40985  BANKNIFTY 12 MAR20 29200 CE       2020-03-12       20
3      NFO  40986  BANKNIFTY 12 MAR20 29200 PE       2020-03-12       20
4      NFO  40988  BANKNIFTY 12 MAR20 29300 CE       2020-03-12       20
5      NFO  40990  BANKNIFTY 12 MAR20 29300 PE       2020-03-12       20
6      NFO  40992  BANKNIFTY 12 MAR20 29400 CE       2020-03-12       20
7      NFO  40993  BANKNIFTY 12 MAR20 29400 PE       2020-03-12       20
8      NFO  41004  BANKNIFTY 12 MAR20 29500 CE       2020-03-12       20
9      NFO  41005  BANKNIFTY 12 MAR20 29500 PE       2020-03-12       20

**Comment by krishnavelu** [comment]
print(pd.DataFrame(alice.search_instruments('NFO', 'BANKNIFTY')[:10]))
Why are you trying to convert to data frame?

**Comment by srinidhihebbar260297** [comment]
Then taking the data to excel using xlwing to calculate Greeks in a simpler way

**Comment by krishnavelu** [comment]
search_instruments Function will just search instruments and will return a list of instruments. Not the actual live data of an instrument.

**Comment by krishnavelu** [comment]
Read this [document](https://github.com/krishnavelu/alice_blue) and try out all function. Understand all functions which this library provides. And then try to implement your own strategies.

**Comment by srinidhihebbar260297** [comment]
Thank You Sir getting the Expected Output Now
