### ISSUE TITLE
Not able to get session Id, login_and_get_sessioID issue

### ISSUE THREAD

**Issue by youngking1686** [krishnavelu/alice_blue#451]
Getting the below json serializer error from the json encoder.py when trying to login and generate the session ID.

Error  : **raise TypeError(f'Object of type {o.__class__.__name__} ' 180 f'is not JSON serializable')**

TypeError: Object of type bytes is not JSON serializable

Not able to proceed further.

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating a new issue...
