### ISSUE TITLE
SSL Error from EC2 AWS

### ISSUE THREAD

**Issue by sam8716** [krishnavelu/alice_blue#453]
2022-09-19 13:27:30,817 | [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129) - goodbye 
2022-09-19 13:27:30,942 | [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129) - goodbye 

above logs generated while running exe from AWS EC2 whereas it is running fine on PC whether in request portion i append verify=false

**Comment by gpaneers** [comment]
This issue is because of your web-browser. Internet explorer is not supported. Download new Microsoft edge and make it as default browser to get this issue fixed.

**Comment by gpaneers** [comment]
> 2022-09-19 13:27:30,817 | [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129) - goodbye 2022-09-19 13:27:30,942 | [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129) - goodbye
> 
> above logs generated while running exe from AWS EC2 whereas it is running fine on PC whether in request portion i append verify=false

This issue is because of your web-browser. Internet explorer is not supported. Download new Microsoft edge and make it as default browser to get this issue fixed.

**Comment by krishnavelu** [comment]
Closing this as it looks like resolved and not related this library.
