### ISSUE TITLE
When logged into Alice Blue API both web and app logins are invalidated. Is that expected?

### ISSUE THREAD

**Issue by nrameshy** [krishnavelu/alice_blue#455]

**Comment by nrameshy** [comment]
I am not able to use Web app, Mobile App and API simultaneously. Currently it is allowing to use only one of the three apps at any point of time.

**Comment by aeron7** [comment]
It should not happen as per AliceBlue Team if You use the updated library. [Happens with the old app]

**Comment by nrameshy** [comment]
@aeron7 Thank you for the response. I have uninstalled the old library and installed the new library as per the instructions given. Even between Web app and Mobile App, when I log in to one of them, the other session is getting invalidated

**Comment by aeron7** [comment]
"Even between Web app and Mobile App, when I log in to one of them, the other session is getting invalidated" - Then it is beyond the scope of us right? 

Literally in this morning I was told that web, mobile and API is different.

**Comment by nrameshy** [comment]
I mean at a time I can use only one of the three apps. Is it only happening to me? Or others too experiencing the same? Atleast the login to API should not invalidate the sessions of other apps

**Comment by nrameshy** [comment]
Sorry.. This is happening when logged into https://ant.aliceblueonline.com/ but working fine when logged into https://a3.aliceblueonline.com
