### ISSUE TITLE
Cover order Problem with a specific trigger price

### ISSUE THREAD

**Issue by ghost** [krishnavelu/alice_blue#46]
I am trying to place cover order-

- when trigger price is 4099: order placed successfully
- when trigger price is 4100: **Error Occurred :Enter Valid Trigger Price**
- when trigger price is 4101: order placed successfully
see the screenshots below. Am I missing anything?
![image](https://user-images.githubusercontent.com/59556194/72367657-96677600-3722-11ea-84dc-9b67f4064a95.png)
![image](https://user-images.githubusercontent.com/59556194/72367754-c1ea6080-3722-11ea-950a-c11d674b003f.png)
![image](https://user-images.githubusercontent.com/59556194/72367809-dd556b80-3722-11ea-8306-c6be400d568d.png)

**Comment by krishnavelu** [comment]
Can you please try once the same manually in alice's app or web?

**Comment by ghost** [comment]
> Can you please try once the same manually in alice's app or web?
its working in web. I am able to get orderID
![image](https://user-images.githubusercontent.com/59556194/72507044-21528880-3869-11ea-8aa7-53f1f82d1c14.png)

**Comment by krishnavelu** [comment]
In a CO market order you should specify stop loss. Why are you trying to specify trigger price?

![image](https://user-images.githubusercontent.com/38440742/72683630-0ec59280-3aa7-11ea-8b0e-a9e84cd56538.png)

**Comment by ghost** [comment]
This is what readme.MD says and it works well when trigger price is other than 4100.00.-
![image](https://user-images.githubusercontent.com/59556194/72684525-482dea80-3b07-11ea-989a-9ae91e105e8a.png)

and this is what I get When I specify stoploss-
![image](https://user-images.githubusercontent.com/59556194/72684574-bc688e00-3b07-11ea-99fb-ce19487217a5.png)

**Comment by krishnavelu** [comment]
Sorry missed it.
Then try providing actual amount as mentioned in document. Not near trading price. 
`# trigger_price Here the trigger_price is taken as stop loss (provide stop loss in actual amount)`

**Comment by krishnavelu** [comment]
@anoopjangra is this solved?

**Comment by ghost** [comment]
> @anoopjangra is this solved?

no

**Comment by krishnavelu** [comment]
What was the result of this?
> Then try providing actual amount as mentioned in document. Not near trading price.
  trigger_price Here the trigger_price is taken as stop loss (provide stop loss in actual amount)
