### ISSUE TITLE
Getting Error "you have reached the request per hour" 

### ISSUE THREAD

**Issue by Revanthsatyam** [krishnavelu/alice_blue#462]
Assume that I have an open order with order id : 123456678906474 when it gets executed this order id would appear in the trade book tab. I was continuesly checking whether the above order is in the trade book tab but whenever I do that I ended up getting the below error.

Error :  "you have reached the request per hour" 

In the old API I was doing the same thing as mentioned above but I didn't came across with this issue.

I don't know whether i can address this issue here, if yes could you please help me.

![IMG-20220921-WA0005](https://user-images.githubusercontent.com/74353642/191575335-1c43f615-444b-41a9-bc3b-09f1bf9d9c2b.jpg)

**Comment by jaydave1988** [comment]
Aliceblue team has added rate limit.
1. Orders - NOT LIMITED. Placing a new order, Modifying an existing order, square off positions and Cancelling an order are all not limited.
2. All other requests - Limited to 1800 requests per 15 mins. This limit will be reset every 15 minutes to 1800 again.
https://v2api.aliceblueonline.com/rates
