### ISSUE TITLE
"ATP-Average Traded Price " not coming in websocket

### ISSUE THREAD

**Issue by ThejusGujj** [krishnavelu/alice_blue#463]
Not able to get ATP value through WebSocket. Could you please check. I checked the API doc from aliceblue and they are sending it as part of message.

bnf_opt=alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=weekly_expiry(), is_fut=False, strike=41000, is_CE = True)
alice.subscribe([bnf_opt], LiveFeedType.DEPTH_DATA)

 {'ml': '1',
  'instrument': Instrument(exchange='NFO', token=59050, symbol='BANKNIFTY2292241000CE', name='BANKNIFTY 22SEP22 41000 CE', expiry=datetime.date(2022, 9, 22), lot_size='25'),
  'ltp': 458.0,
  'percent_change': 0.0,
  'close': 458.0,
  'tick_increment': 0.05,
  'lot_size': 25,
  'price_precision': 2,
  'bid_prices': [None, None, None, None, None],
  'ask_prices': [None, None, None, None, None],
  'bid_quantities': [None, None, None, None, None],
  'ask_quantities': [None, None, None, None, None],
  'buy_orders': [None, None, None, None, None],
  'sell_orders': [None, None, None, None, None],
  'upper_circuit': 2012.05,
  'lower_circuit': 0.05}}

**Comment by krishnavelu** [comment]
Did you check during market time?

**Comment by krishnavelu** [comment]
Average price is already handled.

https://github.com/krishnavelu/alice_blue/blob/master/alice_blue/alice_blue.py#L273-L274

It should come during market ours. If not contact Alice directly.

**Comment by krishnavelu** [comment]
@ThejusGujj  did you check in market hours?

**Comment by krishnavelu** [comment]
- [x] All elements in both tick data and depth data should be latch. Because only few comes in some tick/depth data and causes exception.

**Comment by krishnavelu** [comment]
[058e7f09ace53b5fd0a483ea2bab5d3107c68702](https://github.com/krishnavelu/alice_blue/commit/058e7f09ace53b5fd0a483ea2bab5d3107c68702)

Fixed in this commit
