### ISSUE TITLE
Websocket Not working, unexpected keyword argument "ping_payload"

### ISSUE THREAD

**Issue by youngking1686** [krishnavelu/alice_blue#464]
continuously getting the below message when trying to get data feed from websocket. 

WARNING:alice_blue.alice_blue:websocket run forever ended in exception, run_forever() got an unexpected keyword argument 'ping_payload'

__ws_run_forever method in the AliceBlue erorring, not able to send hearbeat message. Please look into it.

**Comment by youngking1686** [comment]
my bad, updated my websocket client and websocket versions, its working now.

**Comment by Kishore4b5** [comment]
facing same issue. How to update websocket client and websocket versions?

**Comment by Kishore4b5** [comment]
> my bad, updated my websocket client and websocket versions, its working now.

Thank you it was helpful
