### ISSUE TITLE
Unable to retrieve access token

### ISSUE THREAD

**Issue by akpfs** [krishnavelu/alice_blue#47]
When trying to authenticate and retrieve the access token, getting the following error:
line 247, in login_and_get_access_token
    code = resp.url[resp.url.index('=')+1:resp.url.index('&')]

ValueError: substring not found

I'm just following the steps mentioned and nothing has been changed in the code. I'm just trying to print the access token. Does this error mean that the access token isn't created, hence unable to retrieve. I have the antplus activated and have received the api secret. 
Any help would be appreciated. Thanks

**Comment by srinidhihebbar260297** [comment]
I had the same Error if this Keeps on happening download rest API such as insomnia and use OATH2
as Authorisation

**Comment by akpfs** [comment]
Thanks for the suggestion. I've tried the steps mentioned by you but I'm getting the following error:
OAuth 2.0 Error invalid_state
The state is missing or has less than 8 characters and is therefore considered too weak
null

Am I missing something...there's a state field in Advanced Options but I don't know the parameter.
Thanks for the help

**Comment by srinidhihebbar260297** [comment]
state_test will get the job done

**Comment by akpfs** [comment]
Thanks very much, it worked.

**Comment by PRAKSH24884** [comment]
Sir please help me my access token is not generated yet sir please help

**Comment by krishnavelu** [comment]
Refer issue #13 & #47

**Comment by APRATIMMANDAL** [comment]
Hi Team,

I am unable to generate access token even with the provided api-secret.
Can you please let me know why am I getting this error ?
![alice_appconfig](https://user-images.githubusercontent.com/49467176/107126958-ecccc700-68d8-11eb-8574-e05dd5c78c95.JPG)

![image](https://user-images.githubusercontent.com/49467176/107126928-bc852880-68d8-11eb-9d49-27bfb703057a.png)

Thanks in advance.
