### ISSUE TITLE
Unable to get instrument

### ISSUE THREAD

**Issue by sree161** [krishnavelu/alice_blue#470]
using this code to fetch live data

   alice = AliceBlue(username=Credentials.UserName.value, session_id=session_id, master_contracts_to_download=['NSE', 'BSE'])

   alice.start_websocket(subscribe_callback=event_handler_quote_update,
                          socket_open_callback=open_callback)

    while (socket_opened == False):
        pass
    for script in SCRIPT_LIST:
        print(alice.get_instrument_by_symbol('NSE', script))
        alice.subscribe(alice.get_instrument_by_symbol('NSE', script), LiveFeedType.MARKET_DATA)
        
It returns this error,
Socket opened
WARNING:websocket:websocket connected
WARNING:alice_blue.alice_blue:Cannot find symbol ADANIPORTS in master contract NSE
WARNING:alice_blue.alice_blue:Cannot find symbol ADANIPORTS in master contract NSE
Traceback (most recent call last):
  File "C:\Users\sreek\Downloads\Python\live_data_collector.py", line 206, in <module>
    alice = login()
  File "C:\Users\sreek\Downloads\Python\live_data_collector.py", line 94, in login
    alice.subscribe(alice.get_instrument_by_symbol('NSE', script), LiveFeedType.DEPTH_DATA)
  File "C:\Users\sreek\Downloads\Python\venv\lib\site-packages\alice_blue\alice_blue.py", line 740, in subscribe
    raise TypeError("Required parameter instrument is not of type Instrument")
TypeError: Required parameter instrument is not of type Instrument

Can u let me know what's wrong in this?
the same script used to work fine before.

**Comment by krishnavelu** [comment]
Read the document fully

**Comment by sree161** [comment]
Unable to find my mistake.
Can you point me to the area where it goes wrong so that i can go through that part?
It fails at 
  print(alice.get_instrument_by_symbol('NSE', script))

but i'm using code similar to the given readme file

**Comment by krishnavelu** [comment]
```
while (socket_opened == False):
    pass

```

This shows that you didn't copy code from readme.

**Comment by krishnavelu** [comment]
There are many hints in the errors you pasted itself. Use the latest readme code.

**Comment by aeron7** [comment]
Note - You are doing "ADANIPORTS". Try "ADANIPORTS-EQ". It may solve your problem
Note2 - Refer this for getting LTP. https://github.com/aeron7/alice_blue_pro The program 2 there.

**Comment by aeron7** [comment]
> Unable to find my mistake. Can you point me to the area where it goes wrong so that i can go through that part? It fails at print(alice.get_instrument_by_symbol('NSE', script))
> 
> but i'm using code similar to the given readme file

Note - You are doing "ADANIPORTS". Try "ADANIPORTS-EQ". It may solve your problem
Note2 - Refer this for getting LTP. https://github.com/aeron7/alice_blue_pro The program 2 there.

**Comment by RRR008** [comment]
Hi @krishnavelu ,

I am trying to get instrument for BANKNIFTY but unable to get anydata:
WARNING:alice_blue.alice_blue:Cannot find symbol BANK Nifty in master contract NSE
instrument : None

Code:
alice = AliceBlue(username = 'XXXXXX', session_id = session_id, master_contracts_to_download=['NSE','NFO','MCX'])

socket_opened = False
stock = alice.get_instrument_by_symbol('NSE', 'BANK Nifty')
print('instrument :',stock)

**Comment by krishnavelu** [comment]
Its `banknifty_nse_index = alice.get_instrument_by_symbol('NSE', 'NIFTY Bank')` read the document fully.
