### ISSUE TITLE
NameError: name 'AliceBlue' is not defined

### ISSUE THREAD

**Issue by hbr8218** [krishnavelu/alice_blue#471]
Getting this when trying to import everything(*) from alice_blue library.
`from alice_blue import *`
![Screenshot from 2022-09-30 07-05-00](https://user-images.githubusercontent.com/42790586/193171292-0eee3643-7363-456a-9a5b-f747b57c5a3a.png)

**Comment by aeron7** [comment]
Upgrade aliceblue package. Its modified recently. And then crosscheck with the sample programs here https://github.com/aeron7/alice_blue_pro
