### ISSUE TITLE
Modify order is Not working in new update

### ISSUE THREAD

**Issue by codewithraviteja** [krishnavelu/alice_blue#472]
I've been trying to modify the pending order but I am unable to update  it. Please help me

Code : 

`print(alice.modify_order(    
                            transaction_type = TransactionType.Buy,
                            order_id = '220930000126579',
                            instrument = bn_call, 
                            quantity = 25, 
                            order_type = OrderType.StopLossLimit,
                            product_type = ProductType.Delivery, 
                            price = 4.00,
                            trigger_price = 8.00))`

Error message : `{'stat': 'Not_Ok', 'Emsg': 'Error Occurred!'}`

![Screenshot_1aaa](https://user-images.githubusercontent.com/57951049/193225957-5f940244-e43c-43a5-89a8-aea185ad17b2.png)

**Comment by krishnavelu** [comment]
Try the same with web interface. If web interface working it should work on api also.

**Comment by codewithraviteja** [comment]
Yes, I did checked it and it is working in Web interface

**Comment by aeron7** [comment]
@krishnavelu in web interface, there is no term named "instrument".  
@droidmaniac31 just delete the line where its written instrument. it will work

Alice team changed it in web without updating the main API documentation.

**Comment by droidmaniac31** [comment]
Thank you so much Aeron. Krishnavelu never care about what we try to say. I think he has some pre typed text messages. He always send those messages whenever somebody asks a question. 

Krishna velu, you are seriously dumb enough to be in this role. I clearly sent you my question. Why don't you put your pridefulness aside and try to think once of what I have questioned you. ek baar thumaara Dimaak lagao ispe

Haa, comment delete mat karna. Aur log bhi dhekna hai.

**Comment by codewithraviteja** [comment]
Thank you Krishna :)
