### ISSUE TITLE
latest version 2.0.2 is not working

### ISSUE THREAD

**Issue by selvaks030** [krishnavelu/alice_blue#473]
I have upgraded alice-blue latest version today and getting the below error. Could you please help

(Till yesterday i was able to use older version )

File "C:\Users\mypcname\AppData\Roaming\Python\Python310\site-packages\alice_blue\alice_blue.py", line 216, in login_and_get_sessionID
    isAuthorized = r.json()['isAuthorized']
KeyError: 'isAuthorized'

**Comment by krishnavelu** [comment]
Check your credentials

**Comment by selvaks030** [comment]
Thanks for your response Krishna..

credentials are correct only as I am able to login in mobile app / web with same cred

This error is coming only after version upgrade

**Comment by selvaks030** [comment]
I just localized your full code and printed Json msg and isAuthorized key is not present in result.
Please refer the below response msg ( posted only few lines due to personal data)

Could you pls help to understand

'userPrivileges': 'all', 'ySXorderEntry': 'NO', 'criteriaAttribute_array': [], 'emsg_DFlogin': None}, 'is_mob': False, 'dob': None, 'scripList': None, 'validAnsResponse': None, 'webSocketID': '6236563574', 'authorizationStatus': 0, 'expiryDate': 0, 'userApiKey': None, 'vendorId': 0, 'vendorApiKey': None, 'vendorSecret': None, 'deviceId': None, 'loginType': None, 'callBackUrl': None, 'loginMode': None, 'vendor': None, 'authCode': None, 'version': None, 'checkSum': None, 'emsg': None, 'v2': False}

**Comment by krishnavelu** [comment]
It's working for everyone. "isAuthorized" is related to credentials. Only if credentials is wrong this error comes.

**Comment by selvaks030** [comment]
Okay.. I have changed my code ( Temporally ) by creating session id manually and use it further task.

Will try after some days

**Comment by aabhi922** [comment]
This error is coming very  frequently and seems to be related with alieceblue itself. Same time login on web is also not working

**Comment by krishnavelu** [comment]
If web is not able to login server is not up during that time.
