### ISSUE TITLE
Auto login - OTP in web

### ISSUE THREAD

**Issue by rajamurugan44** [krishnavelu/alice_blue#474]
From coming monday, as per SEBI rule we need to login with OTP..

Will our Auto login work fine without any issue as web login required OTP from aliceblue mobile app..

**Comment by aeron7** [comment]
No Clue. When Alice will do something, We will see.

**Comment by aeron7** [comment]
Refer https://github.com/krishnavelu/alice_blue/issues/500#issuecomment-1386357865
