### ISSUE TITLE
KeyError: 'isAuthorized'

### ISSUE THREAD

**Issue by amolc** [krishnavelu/alice_blue#478]
access_token = AliceBlue.login_and_get_sessionID(username,password,twoFA, api_secret=api_secret,app_id=app_id)
  File "/Users/amolc/2020/finance/env/lib/python3.9/site-packages/alice_blue/alice_blue.py", line 216, in login_and_get_sessionID
    isAuthorized = r.json()['isAuthorized']
KeyError: 'isAuthorized'

**Comment by rajeshrapally** [comment]
Im also getting this error suddenly,
for working code,
is there any technical issue @krishnavelu  ?

**Comment by amolc** [comment]
Hello, 

Is there any discord group which we can form to solve the technical errors quickly.

**Comment by selvaks030** [comment]
Am also facing same issue

**Comment by krishnavelu** [comment]
This is due to wrong credentials.

**Comment by aabhi922** [comment]
We are seeing this error very frequently but this seems to be an issue with Aliceblue because at the same time web login is also failing

**Comment by selvaks030** [comment]
any alternative method we can use to avoid **KeyError: 'isAuthorized** error ?

**Comment by krishnavelu** [comment]
No

**Comment by anilalur** [comment]
This is happening after TOTP. It works if you login from web/app using TOTP before the running the script. @krishnavelu how to work around this ?

**Comment by krishnavelu** [comment]
Totp doesn't affects api.

**Comment by selvaks030** [comment]
am facing this issue only after our git version 2.0

now I use diff code to generate session Id alone and using that session id with our git code

**Comment by PythonNovice5** [comment]
> Totp doesn't affects api.

It does and I verified it multiple times, do we have some work around please?

**Comment by anilalur** [comment]
> 

Yes, there is a auto TOTP code, so you can add that for authentication. You can check with Alice API support and they will help you out.

**Comment by Kittu21082002** [comment]
In twoFA what  should i have to give?

**Comment by PythonNovice5** [comment]
> > 
> 
> Yes, there is a auto TOTP code, so you can add that for authentication. You can check with Alice API support and they will help you out.

@anilalur Thank you so much for the response, I sent an email and raised a ticket with Aliceblue support and waiting for their response on the matter. If possible can you please share the code snippet here? I can directly use it in my code. 

Also Alice blue support team replied like this :- Dear eshant garg,

As per SEBI guidelines we are not providing auto-login.

**Comment by amolc** [comment]
Still facing the same issue. I guess, we need a workaround to solve this.

**Comment by anilalur** [comment]
t.me/aliceblueapi

**Comment by aeron7** [comment]
Refer https://github.com/krishnavelu/alice_blue/issues/500#issuecomment-1386357865
