### ISSUE TITLE
Unable to generate access_token

### ISSUE THREAD

**Issue by Vijendra3087** [krishnavelu/alice_blue#48]
Hello Sir,

I have received api secret key and alice blue has enabled the API for my client ID.

I have tried to generate the access_token using below syntax, but access_token has 'NoneType'.

access_token = AliceBlue.login_and_get_access_token('username', 'password', 'twoFA', 'api_secret', redirect_url='http://127.0.0.1/')

I will be very grateful for any inputs assisting me to develop the connection to my trading account.

As a result of above, the below code can not be operated as well

alice = AliceBlue('username', 'password', access_token='access_token')

**Comment by krishnavelu** [comment]
Refer issue #13 & #47
