### ISSUE TITLE
Issue while using Get_historical while others work fine. 

### ISSUE THREAD

**Issue by pk1762012** [krishnavelu/alice_blue#480]
```
sessionID = alice.get_session_id()['sessionID']
#print(sessionID)
alice.get_contract_master("NSE")

instrument = alice.get_instrument_by_symbol("NSE", "RELIANCE")
start_date = '2010-09-14'
end_date = '2022-09-21'
from_datetime = datetime.strptime(start_date, '%Y-%m-%d')
#datetime.timedelta(days = 2) - datetime.timedelta(days=5)     # From last & days
to_datetime = datetime.strptime(end_date, '%Y-%m-%d')                                 # To now
interval = "D"       # ["1", "2", "3", "4", "5", "10", "15", "30", "60", "120", "180", "240", "D", "1W", "1M"]
indices = False      # For Getting index data
print(alice.get_historical(instrument, from_datetime, to_datetime, interval, indices))
```

In AliceBlue, this line probably doesnt work - please check how to resolve this. Earlier the same code used to work.

`lst = requests.get(f"https://a3.aliceblueonline.com/rest/AliceBlueAPIService/chart/history?", params=params).json()
`As it gives 401 error if I check using requests.get(f"https://a3.aliceblueonline.com/rest/AliceBlueAPIService/chart/history?", params=params)

**Comment by pk1762012** [comment]
I have not added the initiation code, but I have written that in my code and it initiates fine.

**Comment by pk1762012** [comment]
Historical data, trading, etc. doesnt seem to work

**Comment by krishnavelu** [comment]
Did you read the document fully?
