### ISSUE TITLE
AttributeError: module 'websocket' has no attribute 'WebSocketApp'

### ISSUE THREAD

**Issue by aabhi922** [krishnavelu/alice_blue#481]
I am getting below error while subscribing the data.

C:\Users\aabhi\PycharmProjects\pythonProject\venv\Scripts\python.exe C:/Users/aabhi/PycharmProjects/pythonProject/main.py
Traceback (most recent call last):
  File "C:/Users/aabhi/PycharmProjects/pythonProject/main.py", line 20, in <module>
    alice.start_websocket(subscribe_callback=event_handler_quote_update)
  File "C:\Users\aabhi\PycharmProjects\pythonProject\venv\lib\site-packages\alice_blue\alice_blue.py", line 533, in start_websocket
    self.__websocket = websocket.WebSocketApp(self.__urls['ws'],
AttributeError: module 'websocket' has no attribute 'WebSocketApp'

Process finished with exit code 1

Below is the code I am using. Can you please help on this? Thanks in advance

`access_token = AliceBlue.login_and_get_sessionID(username=username, password=password, twoFA=twoFA,
                                                     api_secret=api_secret,app_id=app_id)
alice = AliceBlue(username=username, session_id=access_token,master_contracts_to_download=['NSE'])

def event_handler_quote_update(message):
    print(f"quote update {message}")

alice.start_websocket(subscribe_callback=event_handler_quote_update)

alice.subscribe(alice.get_instrument_by_symbol('NSE', 'ONGC-EQ'), LiveFeedType.TICK_DATA)
sleep(10)`

**Comment by krishnavelu** [comment]
Install websocket-client, not websocket

**Comment by aabhi922** [comment]
Thanks for the quick response . I had installed both but even after removing websocket its same


C:\Users\aabhi\PycharmProjects\pythonProject\venv\Scripts>**pip uninstall websocke
t**
WARNING: Skipping websocket as it is not installed.

C:\Users\aabhi\PycharmProjects\pythonProject\venv\Scripts>pip install websocket-
client
Requirement already satisfied: websocket-client in c:\users\aabhi\pycharmproject
s\pythonproject\venv\lib\site-packages (1.4.1)
WARNING: You are using pip version 21.3.1; however, version 22.3 is available.
You should consider upgrading via the 'C:\Users\aabhi\PycharmProjects\pythonProj
ect\venv\Scripts\python.exe -m pip install --upgrade pip' command.

C:\Users\aabhi\PycharmProjects\pythonProject\venv\Scripts>python C:\Users\aabhi\
PycharmProjects\pythonProject\main.py
Traceback (most recent call last):
  File "C:\Users\aabhi\PycharmProjects\pythonProject\main.py", line 21, in <modu
le>
    alice.start_websocket(subscribe_callback=event_handler_quote_update)
  File "C:\Users\aabhi\PycharmProjects\pythonProject\venv\lib\site-packages\alic
e_blue\alice_blue.py", line 533, in start_websocket
    self.__websocket = websocket.WebSocketApp(self.__urls['ws'],
AttributeError: module 'websocket' has no attribute 'WebSocketApp'

C:\Users\aabhi\PycharmProjects\pythonProject\venv\Scripts>

**Comment by krishnavelu** [comment]
Uninstall and reinstall alice-blue

**Comment by aabhi922** [comment]
it worked.. thanks..
 now getting websocket connected msg but not any data. i guess it work during market hours only.. Right??

DEBUG:urllib3.connectionpool:https://a3.aliceblueonline.com:443 "POST /rest/AliceBlueAPIService/api/ws/createSocketSess HTTP/1.1" 200 47
WARNING:websocket:websocket connected

**Comment by aabhi922** [comment]
Thanks
