### ISSUE TITLE
Web Socket Not Working on AWS Server

### ISSUE THREAD

**Issue by vgoyal72** [krishnavelu/alice_blue#482]
Hi 

I upgraded my API Code with new Python Library alice_blue and everything is working fine on my local laptop after making required code changes. 

When I deployed the new code at AWS Server its getting stuck at function alice.start_websocket(subscribe_callback=event_handler_quote_update).

Old version was working fine at AWS. Any reason for this?

Thanks

**Comment by krishnavelu** [comment]
No reason. It's not anything to with this library. Check your AWS instance. Mine works in AWS.

**Comment by vgoyal72** [comment]
Thanks krishnavelu!

I just logged into Alice Blue Web App on AWS Server and now it's working fine. Thanks.
