### ISSUE TITLE
Enhancement : Please provide an option to pass proxy dictionary as a parameter while calling the requests GET and POST

### ISSUE THREAD

**Issue by sai061242** [krishnavelu/alice_blue#483]
Please enhance the API to send proxy dictionary as a parameter when invoking the GET and POST requests.

**proxyDict = {"https": <proxy1>, "http": <proxy2>}**
**requests.get(url, headers=headers, proxies=proxyDict)**

**Comment by krishnavelu** [comment]
why this is needed?

**Comment by sai061242** [comment]
I work and code. My work needs active VPN connection and the client doesn't work on VPN. 
I am tring to run my algo trading manually with out Clould and I am facing this issue.
I tried calling sample requests GET using a proxy server and it is working fine. So if there is a way to pass in proxy server as a parameter to requests it will be very helpful.

I know deploying in cloud will resolve this but if you can make this change It might help others too who are working and doing manual algo trading. Please consider this :)

**Comment by krishnavelu** [comment]
You can fork my library and do this modification.
