### ISSUE TITLE
Aliceblue: Login very slow

### ISSUE THREAD

**Issue by kamaleshvm** [krishnavelu/alice_blue#485]
The each access login and data access taking more than 30sec to 1 min, its waiting for long time to get the response from the aliceblue for each request.

**Comment by kamaleshvm** [comment]
--- 43.18732690811157 seconds ---session id creation time
--- 87.99276161193848 seconds ---Alice object creation
--- 131.24053049087524 seconds ---to get the profile
To just access the profile it taking more than 2+ min. .

**Comment by krishnavelu** [comment]
This is just 1 time. First time of the day.
Because all master contracts of exchanges enabled under your profile will get downloaded. If you need to reduce the time, you can select which master contract to download. That way it will only download that particular exchange's master contract.
