### ISSUE TITLE
Issues while downloading NFO contracts

### ISSUE THREAD

**Issue by rajindersingh041** [krishnavelu/alice_blue#487]
![image](https://user-images.githubusercontent.com/10490016/203080569-968785af-34bf-4cb9-8edd-d586ce40fd79.png)

**Comment by krishnavelu** [comment]
did you try again?

**Comment by rajindersingh041** [comment]
Working fine from couple of day, will report again if issue persist. May I know what was the problem? Did you fix anything?

**Comment by krishnavelu** [comment]
I didn't fix anything. It's your internet.

**Comment by aeron7** [comment]
JSONDECODERROR means the JSON you are getting from that URL, it has some incorrect structure. It is a common problem on broker's end or sometimes it happens due to connectivity issue.

he API code has not been changed as you can verify the same from this GitHub repo.
