### ISSUE TITLE
Order history throwing an error

### ISSUE THREAD

**Issue by srinidhihebbar260297** [krishnavelu/alice_blue#488]
print(alice.get_order_history())

Output:
""" <!DOCTYPE html>

 <html class="no-js" lang="en-US"> 
<head>
<meta http-equiv="refresh" content="0">

<title>a3.aliceblueonline.com | 502: Bad gateway</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />

"""

**Comment by krishnavelu** [comment]
Try again during market time.

**Comment by srinidhihebbar260297** [comment]
Working, Thank you !!
