### ISSUE TITLE
unable to get access token

### ISSUE THREAD

**Issue by yogesh1236** [krishnavelu/alice_blue#49]
dear sir
i have opened account with aliceblue and am following your python script for getting access toke .with same credentials i am able to login in ant web .but am unable to get access token with api secret given by alice blue.
i am getting response to print access token as 'none'
will you please help

**Comment by yogesh1236** [comment]
code wrtten in  python is

from alice_blue import *
access_token=AliceBlue.login_and_get_access_token(username='AB049083',password='YKK12369',twoFA='y',api_secret='1ULL4D3FYDRUFQUIO3UUU1VBOH2PJM9L6OJUFUSA1MZNA8QF4ZYP85X99J7XKO6L',redirect_url='https://ant.aliceblueonline.com')
print(access_token)

is there anything wrong.
please guide.

**Comment by PRAKSH24884** [comment]
sir i also facing a same issue 'none' 
if you get access token successfully please help me

**Comment by krishnavelu** [comment]
Check your redirect url. @yogesh1236.
Its working if you don’t give redirect url.

**Comment by yogesh1236** [comment]
Ok sirI will try without redirect urlThanks

Sent from Yahoo Mail on Android 
 
  On Fri, Jan 24, 2020 at 6:10 PM, Krishna Velu<notifications@github.com> wrote:   
Check your redirect url. @yogesh1236.
Its working if you don’t give redirect url.

**Comment by ns931** [comment]
Hi Krishnavelu,
Cant we generate the access token during the weekends?
I tried generating on 26th jan (Sunday)
![Screenshot 2020-01-26 at 9 50 50 AM](https://user-images.githubusercontent.com/60307871/73130657-b2242380-4022-11ea-880d-419a6e0017fc.png)

**Comment by PRAKSH24884** [comment]
i also facing same issue for last 4 days . mene market hours me bhi try
kiya but the result is 'none' please help

**Comment by krishnavelu** [comment]
It works some times on offmarket hours but not all time. When you are trying first time, try only on market hours. Once you got familiar, you can try off market time.

**Comment by PRAKSH24884** [comment]
Print (access_token) mt likho or run karo

**Comment by jaydave1988** [comment]
@Kapil22-bot refer Issue #62 .
You have to authorize your app for the first time then only you will be able to get access_token.

**Comment by jaydave1988** [comment]
@Kapil22-bot 
Add below line:

print(resp.url)

at 247 line number After this line resp = r.post(resp.url,data={'answer1':twoFA,'question_id1':question_ids,'answer2':twoFA,'login_challenge':login_challenge,'_csrf_token':csrf_token})
in login_and_get_access_token in alice_blue.py file.

Open that URL and authorize your app.

**Comment by krishnavelu** [comment]
This gets fixed along with #62

**Comment by canikalayugandhar** [comment]
Hello Seniors... i am also facing a same issue ...I am unable to get access token with api secret given by alice blue... Plz Help me ....

**Comment by krishnavelu** [comment]
This issue is fixed in develop. Take latest develop and try.
