### ISSUE TITLE
Unable to get the historical data for Nifty and Bank Nifty {'emsg': 'No data available', 'stat': 'Not_Ok'}. But able to get data for stocks

### ISSUE THREAD

**Issue by Niranjanb14** [krishnavelu/alice_blue#492]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/40052038/206752457-19cfd8a3-e3bc-46e8-bda9-e7b87df91aa3.png">
Unable to get the historical data for Nifty and Bank Nifty. But able to get data for stocks

**Comment by krishnavelu** [comment]
There are some limitations for historical data. Try after 5:30pm
