### ISSUE TITLE
Unable retrieve  live data using web sockets

### ISSUE THREAD

**Issue by THUMMAMARREDDY** [krishnavelu/alice_blue#497]
Facing below error while fetching live data 

`ERROR:websocket:[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1051) - goodbye`

**Code used** 
```
def event_handler_quote_update(message):  
    print(f"quote update {message}")

alice.start_websocket(subscribe_callback=event_handler_quote_update)

alice.subscribe(alice.get_instrument_by_symbol('NSE', 'ONGC-EQ'), LiveFeedType.TICK_DATA)
time.sleep(10)
```

Please help me to fix this, Thanks!!

**Comment by aeron7** [comment]
Refer https://stackoverflow.com/a/51408997
