### ISSUE TITLE
How to find LTP?

### ISSUE THREAD

**Issue by ns931** [krishnavelu/alice_blue#50]
Hi Krishnavelu,

How to find Open, high, low, LTP of any given scrip?
Attached is the screenshot of how it works in zerodha
pls help with this.
![Screenshot 2020-01-26 at 10 12 34 AM](https://user-images.githubusercontent.com/60307871/73130779-bcdfb800-4024-11ea-9c84-bbd3b820702e.png)

**Comment by krishnavelu** [comment]
Refer this [document](https://github.com/krishnavelu/alice_blue)

**Comment by ns931** [comment]
In the screen shot if you see the second cell its keep on running without throwing any output.
Do i need to make any modifications to the code?

![Screenshot 2020-01-27 at 9 19 25 AM](https://user-images.githubusercontent.com/60307871/73150099-91270580-40ea-11ea-8705-e989c518b79a.png)

**Comment by krishnavelu** [comment]
It works for everyone.

**Comment by ns931** [comment]
I have verified even now the issue still exists, its a show stopper for me. 
could you please let me know the solution ASAP?

**Comment by krishnavelu** [comment]
Download [this](https://gist.github.com/krishnavelu/e0df312ccf5f022edb1823461ff4230e) py file and run in command prompt. Not in jupiter notebook. Also which internet you are using? Home or office.
Office internet block something. So may not work.
