### ISSUE TITLE
Status 404 Not found - While logging in with session ID (was working until Yesterday)

### ISSUE THREAD

**Issue by PythonNovice5** [krishnavelu/alice_blue#500]
Hi,

I got the following error this morning, when after 2FA authentication I executed the login API of aliceblue using sessionID.

Code used: 
`sessionID = AliceBlue.login_and_get_sessionID('AB072690', 'MyPassword','MYYOB','my_appID','my_api-secret')`

**Can some one please help?** 

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): a3.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://a3.aliceblueonline.com:443 "POST /rest/AliceBlueAPIService/customer/getEncryptionK
ey HTTP/1.1" 200 None
INFO:root:Get Encryption Key response {"userId":null,"userData":null,"encKey":"VJCOHO75UOJP","apikey":null,"stat":null,
"emsg":null,"loginType":null,"version":null,"fcmToken":null,"imei":null,"login":false}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): a3.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://a3.aliceblueonline.com:443 "POST /rest/AliceBlueAPIService/customer/webLogin HTTP/
1.1" 200 None
INFO:root:Web Login response {"userId":"AB072690","accountId":null,"password":null,"newPassword":null,"oldPassword":nul
l,"userSessionID":null,"userToken":null,"publicKey4":null,"stringPkey4":null,"publicKey3":null,"stringPkey3":null,"priv
atekey2":null,"stringPK2":null,"tomcatcount":null,"stat":"Ok","tdata":"Answer the questions","sQuestions":"Year Of Birt
h","sCount":"1","sIndex":"1","ques_Ans":null,"answer1":null,"answer2":null,"sUserToken":null,"sPasswordReset":null,"mes
sage":null,"exch":null,"symbol":null,"mwName":null,"email":null,"pan":null,"list":null,"preLogin":null,"userSettingDto"
:null,"is_mob":false,"dob":null,"scripList":null,"validAnsResponse":null,"webSocketID":null,"authorizationStatus":0,"ex
piryDate":0,"userApiKey":null,"vendorId":0,"vendorApiKey":null,"vendorSecret":null,"deviceId":null,"loginType":null,"ca
llBackUrl":null,"loginMode":null,"vendor":null,"authCode":null,"version":null,"checkSum":null,"fcmToken":null,"imei":nu
ll,"v2":false,"emsg":null}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): a3.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://a3.aliceblueonline.com:443 "POST /rest/AliceBlueAPIService/sso/validAnswer HTTP/1.
1" 404 None
INFO:root:Web Login 2FA response <!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style
type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:blac
k;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Not Found</p><p><b>Descr
iption</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/9.0.65</h3><script defer src="ht
tps://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993" integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==" data
-cf-beacon='{"rayId":"787bdea84fcc84ef","token":"46191df1e0324e209e0003a259ebc24f","version":"2022.11.3","si":100}' crossorigin="anonymous"></script>
</body></html>
Traceback (most recent call last):
  File "Login_alice.py", line 10, in <module>
    sessionID = AliceBlue.login_and_get_sessionID('AB072690', 'xxxxxx@519','1980','xxxxxx','xxxxNfxHXZxeOWWGzhKJfziNCvLzquYLbDOZpIAqMSOJrECVfeVgSKlkipMkqxZoXXxpSMpMjoivzHNdeUTYRixPIygUcBUXKJAi')
  File "/home/angel/.local/lib/python3.6/site-packages/alice_blue/alice_blue.py", line 216, in login_and_get_sessionID
    isAuthorized = r.json()['isAuthorized']
  File "/home/angel/.local/lib/python3.6/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/angel/.local/lib/python3.6/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/angel/.local/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/angel/.local/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by aeron7** [comment]
Refer https://github.com/krishnavelu/alice_blue/issues/498

-> No change in code as You can see in GitHub. 
-> Lord IT team from their side has either misconfigured the Apache server or changed some URL structure [From what's understandable from the error generated].

**Comment by PythonNovice5** [comment]
> Refer #498
> 
> -> No change in code as You can see in GitHub. -> Lord IT team from their side has either misconfigured the Apache server or changed some URL structure [From what's understandable from the error generated].

Yeah, I even tried your commit where you changed the host but that didn't help either. 
This is so frustrating, I missed a very profitable trade today because of this.

**Comment by aeron7** [comment]
I moved most of my clients from this stupid church (Aliceblue does sound like a church) to SASonline. Otherwise, I did not have other solutions as they keep breaking working codes from time to time and having disfunctional IT team.

**Comment by PythonNovice5** [comment]
> I moved most of my clients from this stupid church (Aliceblue does sound like a church) to SASonline. Otherwise, I did not have other solutions as they keep breaking working codes from time to time and having disfunctional IT team.

Live quote data streaming (feed) is accurate and consistent in SASonline? 

I opened accounts n Angel, Samco and then Alice. Only Alice was giving accurate streaming, I mean it doesn't miss the ticks and other brokers were missing ticks. However the library change issue I also faced in Alice 2 months back when suddenly they changed the code for login and creating session id, without informing anyone. 

Right now I take the stream from Alice and execute my orders using API of another broker, basically using 2 brokers to get the job done, but today that system also failed because of this Login failure.

My major requirement is accurate live data feed, so that I can create accurate timeframe candles out of it

**Comment by aeron7** [comment]
> Live quote data streaming (feed) is accurate and consistent in SASonline?

Why.. Why.. Why.. Use Zerodha's ? 

Just execute in other brokers. Take everything else from Zerodha only.

**Comment by aeron7** [comment]
Even in Aliceblue Office, I have seen them keeping Zerodha terminal opened to see prices man.

**Comment by PythonNovice5** [comment]
> > Live quote data streaming (feed) is accurate and consistent in SASonline?
> 
> Why.. Why.. Why.. Use Zerodha's ?
> 
> Just execute in other brokers. Take everything else from Zerodha only.

Because Zerodha charges were too much for me as I was testing Algo's by putting real money, and all the brokers I mentioned provide free APIs.

But if it's reliable enough I think I will have to switch now. Currently I am using Zerodha for investment only.

One more off the topic - I have seen people share their Algo with clients, client just has to login with his broker and that's it. I don't understand if I am using Zerodha how my zerodha api will trigger orders in client's broker (as the api methods etc are all different). As you mentioned you have clients, can you put some light on this?

**Comment by PythonNovice5** [comment]
> Even in Aliceblue Office, I have seen them keeping Zerodha terminal opened to see prices man.

Yeah Zerodha is actually very convenient and accurate at least on their terminal. I am not sure about their APIs, but they are the most expensive in India right now

**Comment by aeron7** [comment]
> Because Zerodha charges were too much for me as I was testing Algo's by putting real money, and all the brokers I mentioned provide free APIs.

It's free. Just google around :) 

> One more off the topic - I have seen people share their Algo with clients, client just has to login with his broker and that's it. I don't understand if I am using Zerodha how my zerodha api will trigger orders in client's broker (as the api methods etc are all different). As you mentioned you have clients, can you put some light on this?

If I talk too much, I will get legal notice. It is somewhat in the grey area. If you're my client then ping me in slack.

**Comment by aeron7** [comment]
> most expensive

You are already losing 5x of that money by using Church AliceBlue.

**Comment by PythonNovice5** [comment]
> . Just google around :)

Yes but for startups, I am an individual 👎

**Comment by aeron7** [comment]
> > . Just google around :)
> 
> Yes but for startups, I am an individual 👎

Free for you too. Google more :)

**Comment by PythonNovice5** [comment]
> > > . Just google around :)
> > 
> > 
> > Yes but for startups, I am an individual 👎
> 
> Free for you too. Google more :)

Thank you so much man, God bless you!! :-)

**Comment by rajeshbagavathy** [comment]
Any resolution or workaround for this issue?

**Comment by tapasyabhushan** [comment]
No one from Alice Blue developer team has commented so far. What a response.

**Comment by saransen** [comment]
Now its working fine, after made a few corrections. 
Need to change the alice_blue.py library as per API documentation.
changed the urls,
`host = "https://ant.aliceblueonline.com/rest/AliceBlueAPIService/api"
    __urls = {"webLogin": f"{host}/customer/webLogin",
              "twoFA": f"{host}/sso/validAnswer",
              "sessionID": f"{host}/customer/getUserSID",
              "getEncKey": f"{host}/customer/getEncryptionKey",
              "authorizeVendor": f"{host}/sso/authorizeVendor",
              "apiGetEncKey": f"{host}/customer/getAPIEncpkey",
              "profile": f"{host}/customer/accountDetails",
              "placeOrder": f"{host}/placeOrder/executePlaceOrder",
              "logout": f"{host}/customer/logout",
              "logoutFromAllDevices": f"{host}/customer/logOutFromAllDevice",
              "fetchMWList": f"{host}/marketWatch/fetchMWList",
              "fetchMWScrips": f"{host}/marketWatch/fetchMWScrips",
              "addScripToMW": f"{host}/marketWatch/addScripToMW",
              "deleteMWScrip": f"{host}/marketWatch/deleteMWScrip",
              "scripDetails": f"{host}/ScripDetails/getScripQuoteDetails",
              "positions": f"{host}/positionAndHoldings/positionBook",
              "holdings": f"{host}/positionAndHoldings/holdings",
              "sqrOfPosition": f"{host}/positionAndHoldings/sqrOofPosition",
              "fetchOrder": f"{host}/placeOrder/fetchOrderBook",
              "fetchTrade": f"{host}/placeOrder/fetchTradeBook",
              "exitBracketOrder": f"{host}/placeOrder/exitBracketOrder",
              "modifyOrder": f"{host}/placeOrder/modifyOrder",
              "cancelOrder": f"{host}/placeOrder/cancelOrder",
              "orderHistory": f"{host}/placeOrder/orderHistory",
              "getRmsLimits": f"{host}/limits/getRmsLimits",
              "createWsSession": f"{host}/ws/createSocketSess",
              "history": f"{host}/chart/history",
              "master_contract": "https://v2api.aliceblueonline.com/restpy/contract_master?exch={exchange}",
              "ws": "wss://ws2.aliceblueonline.com/NorenWS/"
              }`

removed,
`# Get Encryption Key
        # data = {"userId": username}
        # r = requests.post(AliceBlue.__urls['getEncKey'], headers=header, json=data)
        # logging.info(f"Get Encryption Key response {r.text}")
        # encKey = r.json()["encKey"]
        # print ("EncKey: " + encKey)`

removed,
`# Web Login
        # checksum = CryptoJsAES.encrypt(password.encode(), encKey.encode())
        # data = {"userId": username,
        #         "userData": checksum.decode()}
        # print("data: ")
        # print(data)
        # r = requests.post(AliceBlue.__urls["webLogin"], json=data)
        # logging.info(f"Web Login response {r.text}")
        # print("web Login response " + r.text)`

removed,
`# Web Login 2FA
        # data = {"answer1": twoFA,
        #         "sCount": "1",
        #         "sIndex": "1",
        #         "userId": username,
        #         "vendor": app_id}
        # r = requests.post(AliceBlue.__urls["twoFA"], json=data)
        # logging.info(f"Web Login 2FA response {r.text}")
        # print("Web Login 2FA response " + r.text)
        # isAuthorized = r.json()['isAuthorized']
        # authCode = parse_qs(urlparse(r.json()["redirectUrl"]).query)['authCode'][0]
        # logging.info(f"isAuthorized {isAuthorized}")
        # logging.info(f"authCode {authCode}")`

modified,
`# Get API Encryption Key
        data = {"userId": username}
        print(AliceBlue.__urls["apiGetEncKey"])
        r = requests.post(AliceBlue.__urls["apiGetEncKey"], headers=header, data=json.dumps(data))
        logging.info(f"Get API Encryption Key response {r.text}")
        encKey = r.json()["encKey"]`

modified (API Key-Get it from ANT Web application),
`checksum = hashlib.sha256(f"{username}{api_key}{encKey}".encode()).hexdigest()`

removed,
`# Authorize vendor app
        # if (isAuthorized == False):
        #     data = {"userId": username,
        #             "vendor": app_id}
        #     print("Authorizing vendor app")
        #     r = requests.post(AliceBlue.__urls["authorizeVendor"], headers=header, data=json.dumps(data))`

Everything remains same. My script worked fine with these changes.

**Comment by tapasyabhushan** [comment]
@saransen Tried with these changes, now getting error api_key is not defined from line 
checksum = hashlib.sha256(f"{username}{api_key}{encKey}".encode()).hexdigest()

**Comment by aeron7** [comment]
> No one from Alice Blue developer team has commented so far. What a response.

They don't have a developer team. They have copied our repo shamelessly and did not bother to attribute @krishnavelu at all. So our obligation is limited to our own clients only as of now, right?

But there are only 10-15 clients left and the rest all moved here and there.  So will you after few days after suffering deep headache with them.

**Comment by aeron7** [comment]
> Now its working fine, after made a few corrections.

Hi bro, Can you please make a commit to this main repo changing those stuff? @krishnavelu will be happy to merge it forward if it works flawlessly.

**Comment by saransen** [comment]
> @saransen Tried with these changes, now getting error api_key is not defined from line checksum = hashlib.sha256(f"{username}{api_key}{encKey}".encode()).hexdigest()

just define variable api_key just above the line like,
api_key = "Your API Key"
checksum = hashlib.sha256(f"{username}{api_key}{encKey}".encode()).hexdigest()

**Comment by saransen** [comment]
> > Now its working fine, after made a few corrections.
> 
> Hi bro, Can you please make a commit to this main repo changing those stuff? @krishnavelu will be happy to merge it forward if it works flawlessly.

sure !

**Comment by PythonNovice5** [comment]
> > @saransen Tried with these changes, now getting error api_key is not defined from line checksum = hashlib.sha256(f"{username}{api_key}{encKey}".encode()).hexdigest()
> 
> just define variable api_key just above the line like, api_key = "Your API Key" checksum = hashlib.sha256(f"{username}{api_key}{encKey}".encode()).hexdigest()

I replaced my API secret from Aliceblue developer console into this one (we have app id and API secret there) and when I ran the Login file, I got the following error:

```
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "POST /rest/AliceBlueAPIService/api/customer/getUserSID HTTP/1.1" 400 414
INFO:root:Session ID response Unrecognized field "checkSum" (class com.sas.dto.EncDataDTO), not marked as ignorable (11 known properties: , "loginType", "encKey", "apikey", "userId", "imei", "fcmToken", "login", "stat", "userData", "version", "emsg"])


```

Can you please help brother?

**Comment by kanudutta** [comment]
Api key u will get from ant web trading site , login and then click apps and then click api key and copy that

**Comment by rajeshbagavathy** [comment]
I contacted the Alice blue api support. This repo is no longer supported. Please use the below repo, this needs new installation as well. Sharing the link for youtube video as well which tells what is really changed.


https://github.com/jerokpradeep/pya3

https://www.youtube.com/watch?v=CQMneD9W7mQ&ab_channel=Technical

Happy Trading!

**Comment by divbcodeit** [comment]
I was able to get it working without the user input of api_key. The login system for the aliceblue has changed. It asks for totp as compulsory. Only input required is totp authorization key and it will generate the totp.

Following are the changes:
 - Package Import:
`import pyotp`
- Url modified: host, twoFA, sessionID, ws
- Url Added: verifyTotp, getApiKey


```
    host = "https://ant.aliceblueonline.com/rest/AliceBlueAPIService/"
    __urls = {  "webLogin"              :   f"{host}/customer/webLogin",
                "twoFA"                 :   f"{host}/sso/2fa",
                "sessionID"             :   f"{host}/api/customer/getUserSID",
                "getEncKey"             :   f"{host}/customer/getEncryptionKey",
                "verifyTotp"            :   f"{host}/sso/verifyTotp",
                "getApiKey"             :   f"{host}/api/getApiKey",
                "authorizeVendor"       :   f"{host}/sso/authorizeVendor",
                "apiGetEncKey"          :   f"{host}/api/customer/getAPIEncpkey",
                "profile"               :   f"{host}/api/customer/accountDetails",
                "placeOrder"            :   f"{host}/api/placeOrder/executePlaceOrder",
                "logout"                :   f"{host}/api/customer/logout",
                "logoutFromAllDevices"  :   f"{host}/api/customer/logOutFromAllDevice",
                "fetchMWList"           :   f"{host}/api/marketWatch/fetchMWList",
                "fetchMWScrips"         :   f"{host}/api/marketWatch/fetchMWScrips",
                "addScripToMW"          :   f"{host}/api/marketWatch/addScripToMW",
                "deleteMWScrip"         :   f"{host}/api/marketWatch/deleteMWScrip",
                "scripDetails"          :   f"{host}/api/ScripDetails/getScripQuoteDetails",
                "positions"             :   f"{host}/api/positionAndHoldings/positionBook",
                "holdings"              :   f"{host}/api/positionAndHoldings/holdings",
                "sqrOfPosition"         :   f"{host}/api/positionAndHoldings/sqrOofPosition",
                "fetchOrder"            :   f"{host}/api/placeOrder/fetchOrderBook",
                "fetchTrade"            :   f"{host}/api/placeOrder/fetchTradeBook",
                "exitBracketOrder"      :   f"{host}/api/placeOrder/exitBracketOrder",
                "modifyOrder"           :   f"{host}/api/placeOrder/modifyOrder",
                "cancelOrder"           :   f"{host}/api/placeOrder/cancelOrder",
                "orderHistory"          :   f"{host}/api/placeOrder/orderHistory",
                "getRmsLimits"          :   f"{host}/api/limits/getRmsLimits",
                "createWsSession"       :   f"{host}/api/ws/createSocketSess",
                "history"               :   f"{host}/api/chart/history",
                "master_contract"       :   "https://v2api.aliceblueonline.com/restpy/contract_master?exch={exchange}",
                "ws"                    :   "wss://ws1.aliceblueonline.com/NorenWS/"
            }

```
- login_and_get_sessionID: Addition of another input totp_key
`def login_and_get_sessionID(username, password, twoFA, app_id, api_secret, totp_key):`

- Change after Web Login 2FA Code
```
       # Web Login 2FA
        data = {"answer1" : twoFA,
                "sCount" : "1",
                "sIndex" : "1",
                "userId" : username,
                "vendor" : app_id}
        r = requests.post(AliceBlue.__urls["twoFA"], json=data)
        logging.info(f"Web Login 2FA response {r.text}")
        auth_us = r.json()['us']
        
        # Web Login Totp
        totp = str(pyotp.TOTP(totp_key).now())
        data = {"userId" : username,'tOtp':totp}
        header['Authorization'] = f"Bearer {username} {auth_us}"
        r = requests.post(AliceBlue.__urls["verifyTotp"], headers=header, data=json.dumps(data))
        logging.info(f"Totp Login response {r.text}")
        
        # Web Login Api Key
        userSessionID = r.json()['userSessionID']
        header['Authorization'] = f"Bearer {username} {userSessionID}"
        r = requests.post(AliceBlue.__urls["getApiKey"], headers=header)
        logging.info(f"Api Key response {r.text}")
        api_key = r.json()['api_key']

        # Get API Encryption Key
        data = {"userId" : username}
        r = requests.post(AliceBlue.__urls["apiGetEncKey"], headers=header, data=json.dumps(data))
        logging.info(f"Get API Encryption Key response {r.text}")
        encKey = r.json()["encKey"]

        # Get User Details/Session ID
        checksum = hashlib.sha256(f"{username}{api_key}{encKey}".encode()).hexdigest()
        data = {"userId" : username, 'userData':checksum}
        r = requests.post(AliceBlue.__urls["sessionID"], headers=header, data=json.dumps(data))
        logging.info(f"Session ID response {r.text}")
        session_id = r.json()['sessionID']
        logging.info(f"Session ID is {session_id}")

        # Write session_id in temp file for next time usage
        with open(tmp_file, 'w') as fo:
            d = {"session_id" : session_id}
            fo.write(json.dumps(d))
        return session_id
```

Check if this change is working for you.

**Comment by Revanthsatyam** [comment]
@divbcodeit I have updated the library as you said, but getting the below error. Can you please help me ?

Traceback (most recent call last):
  File "C:\Users\satya\OneDrive\Desktop\Algo_v2\tripple_straddle.py", line 154, in <module>
    strategy()
  File "C:\Users\satya\OneDrive\Desktop\Algo_v2\tripple_straddle.py", line 120, in strategy
    login()
  File "C:\Users\satya\OneDrive\Desktop\Algo_v2\tripple_straddle.py", line 34, in login
    alice = AliceBlue(username = "307931", session_id = session_id)
  File "C:\Users\satya\AppData\Local\Programs\Python\Python310\lib\site-packages\alice_blue\alice_blue.py", line 164, in __init__
    self.__get_master_contract(e)
  File "C:\Users\satya\AppData\Local\Programs\Python\Python310\lib\site-packages\alice_blue\alice_blue.py", line 978, in __get_master_contract
    expiry = datetime.datetime.fromtimestamp(scrip['expiry_date']/1000, tz=pytz.utc).date()
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

**Comment by divbcodeit** [comment]
> @divbcodeit I have updated the library as you said, but getting the below error. Can you please help me ?
> 
> Traceback (most recent call last): File "C:\Users\satya\OneDrive\Desktop\Algo_v2\tripple_straddle.py", line 154, in strategy() File "C:\Users\satya\OneDrive\Desktop\Algo_v2\tripple_straddle.py", line 120, in strategy login() File "C:\Users\satya\OneDrive\Desktop\Algo_v2\tripple_straddle.py", line 34, in login alice = AliceBlue(username = "307931", session_id = session_id) File "C:\Users\satya\AppData\Local\Programs\Python\Python310\lib\site-packages\alice_blue\alice_blue.py", line 164, in **init** self.__get_master_contract(e) File "C:\Users\satya\AppData\Local\Programs\Python\Python310\lib\site-packages\alice_blue\alice_blue.py", line 978, in __get_master_contract expiry = datetime.datetime.fromtimestamp(scrip['expiry_date']/1000, tz=pytz.utc).date() TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

Could you check if you made changes in this code section in __get_master_contract function:
```
if("expiry_date" in scrip):
    expiry = datetime.datetime.fromtimestamp(scrip['expiry_date']/1000, tz=pytz.utc).date()
else:
    expiry = None
```

If it is like this, could you give a print statement to see 'scrip' variable by printing it out to tell which script is giving an issue

**Comment by Revanthsatyam** [comment]
Hi,

Can you please share the updated library with me so that i will use that
one instead of me modifying the existing one.

Regards,
Revanth

**Comment by aeron7** [comment]
We have no intention of updating it provided Aliceblue unethically stole the base of the code without acknowledging it. You will also change the broker after sometime after facing 500 issues. 

_**Sooner or Later. It's Inevitable.**_

**Comment by MaheshKok** [comment]
[divbcodeit](https://github.com/divbcodeit)

thanks so much ...

I have been heavily relying on alice blue for trading

and to be honest ..i used your code and it worked like charm...

I am wondering how did you manage to get the URL to verify totp

can we have the same method for zerodha
