### ISSUE TITLE
Alice Blue Api - Login Help

### ISSUE THREAD

**Issue by VikramBangre** [krishnavelu/alice_blue#501]
Hi,

I was using the old API and suddenly it stopped working, later when I checked here the API was updated. So when trying to setup the code for new API but not sure of what is APP_ID ? Kindly help.

First we need to "session_id" and then create "alice" object, as per new procedure.

username    = "this is my alice blue login ID", 
password    = "password", 
twoFA       = "my two fa year",
**_app_id      = "app_id", ????  what is this ?_**
api_secret  = "I can get this from 3rd Party Integrations page - API Key section")   **_is that correct ?_**

Regards,
Vikram

**Comment by krishnavelu** [comment]
App Code from developer console is your app_id. It's not from 3rd part integration page, it's from Alice blue's developer console.
