### ISSUE TITLE
DEPTH_DATA ( Null Values )

### ISSUE THREAD

**Issue by vijayraj-saaras** [krishnavelu/alice_blue#502]
<img width="764" alt="image" src="https://user-images.githubusercontent.com/34841305/226987549-96e89574-0a12-454a-b0d6-6be8dc6865e9.png">

Why this Alice blue market depth data is showing all these null values ??

**Comment by krishnavelu** [comment]
Because data is not available.
are you using this library? Or making your own code?

**Comment by vijayraj-saaras** [comment]
But ideally we should get the market depth details in each and every tick  right ? 
or else there is no point using this depth data from alice blue isn't?
No Using this library I am getting error ,so I am developing my own code

**Comment by krishnavelu** [comment]
If there is no update in that particular tick, there is no point in sending previous data. It'll just consume and choke network bandwidth. In my code there is a latching mechanism. You can also implement the same.

**Comment by vijayraj-saaras** [comment]
Thanks @krishnavelu
