### ISSUE TITLE
AliceBlue API login error

### ISSUE THREAD

**Issue by anuditkala** [krishnavelu/alice_blue#504]
When I call AliceBlue.login_and_get_sessionID() method with appropriate arguments, I get this error. Cipher class is expecting backend for initialiation
`Traceback (most recent call last):
  File "loginAliceBlue.py", line 3, in <module>
    session_id = AliceBlue.login_and_get_sessionID(   username    = "xxxxxx",
  File "/home/anudit/.local/lib/python3.8/site-packages/alice_blue/alice_blue.py", line 201, in login_and_get_sessionID
    checksum = CryptoJsAES.encrypt(password.encode(), encKey.encode())
  File "/home/anudit/.local/lib/python3.8/site-packages/alice_blue/alice_blue.py", line 80, in encrypt
    aes = Cipher(algorithms.AES(key), modes.CBC(iv))
TypeError: __init__() missing 1 required positional argument: 'backend'
`

**Comment by aeron7** [comment]
Refer https://github.com/krishnavelu/alice_blue/issues/500#issuecomment-1386357865

**Comment by SarathKumarGandla** [comment]
@anuditkala : was this issue resolved? I followed the instructions given in above link, but still getiing same error. If your issue is fixed, can you please let me know what were the changes you made
