### ISSUE TITLE
#Issue in generating EncKey

### ISSUE THREAD

**Issue by pavan1414** [krishnavelu/alice_blue#508]
Hi @krishnavelu ,

I'm new to ALice BLue, Yesterday I have cloned the repo and tried to create session id and it is throwing me error(screenshot attached)

I tried to change the base url from **https://a3.aliceblueonline.com/rest/AliceBlueAPIService**  to **https://ant.aliceblueonline.com/rest/AliceBlueAPIService/api/** still the issue persists and getting Error 404 as response while fetching getEncKey.

Request you please help on this.

Thanks!
Pavan

![AliceBLue Error](https://github.com/krishnavelu/alice_blue/assets/85120921/36b6c32b-9148-4650-985f-c71da56138eb)

**Comment by Parth971** [comment]
Hi @pavan1414, Can you show your code? 

Please write properly where you changed the URL and what is your current version, etc. It will be easier to debug If you provide some details.

Thank you
