### ISSUE TITLE
can you please update documentation or readme for all order status in orderbook ?

### ISSUE THREAD

**Issue by priyakumariengineer** [krishnavelu/alice_blue#51]
Hi,

I have hard time finding what is possibility of 'order_status' when i use  alice.get_order_history() endpoint.

I mean I am able to figure out that 'complete' , 'rejected' , 'pending' are posibilities.
but what is possiblity for partially executed ?? is it "partially executed".

I belive correct place for this update should be :
https://antplus.aliceblueonline.com/#appendix

**Comment by krishnavelu** [comment]
‘complete’ ‘cancelled’ ‘rejected’ ‘open’ are the really important once. Ignore the remaining. If you want place order during market time and list down all you’ll come to know.
Half filled orders also will be in open status.

**Comment by priyakumariengineer** [comment]
Ohk , make sense @krishnavelu .
closing this.
