### ISSUE TITLE
Error for option symbol

### ISSUE THREAD

**Issue by keerthankumar** [krishnavelu/alice_blue#514]
Hi Im using below code

`            bn_call = alice_object.get_instrument_for_fno(exch = "NFO", symbol = 'BANKNIFTY', expiry_date="2023-11-02", is_fut=False, strike=30000, is_CE = True)`

I get response like
{'stat': 'Not_ok', 'emsg': 'No Data'}

Please help if there is any change in the syntax, in tried giving the datetime type expiry_date, but it started throwing error to input string. Let me know what is the correct type of command

**Comment by krishnavelu** [comment]
NSE stopped Thursday expiry long ago. Now expiry is wednesday.
