### ISSUE TITLE
Need Help: Reading or parsing the message data 

### ISSUE THREAD

**Issue by grsb007** [krishnavelu/alice_blue#53]
Hello,

could you please help how to get the symbol from Instrument, I have tried using json package but is not working. 

{'exchange': 'NSE', 'token': 26009, 'ltp': 30761.4, 'ltt': 1580209829, 'ltq': 0, 'volume': 0, 'best_bid_price': 0.0, 'best_bid_quantity': 0, 'best_ask_price': 0.0, 'best_ask_quantity': 0, 'total_buy_quantity': 0, 'total_sell_quantity': 0, 'atp': 0.0, 'exchange_time_stamp': 1580209829, 'open': 30922.0, 'high': 31048.45, 'low': 30656.35, 'close': 30761.4, 'yearly_high': 32613.1, 'yearly_low': 26560.6, 'instrument': Instrument(exchange='NSE', token='26009', symbol='Nifty Bank', name='Nifty Bank', expiry=None, lot_size=None)}

Thanks,

**Comment by krishnavelu** [comment]
data[‘instrument’][‘symbol’]

**Comment by grsb007** [comment]
I have already tried the following 
print(message['instrument']['symbol'])

But getting below error
ERROR:websocket:error from callback <bound method AliceBlue.__on_data_callback of <alice_blue.alice_blue.AliceBlue object at 0x00000000092F7208>>: tuple indices must be integers or slices, not str

I believe that "Instrument" is added, don't know why it has been added. I tried to remove and convert it. But could not get the symbol, could you please help me on this 

I have tried as per below. but could not get the desired result

dataInstrumnet = message['instrument']
dataInstrumnet = repr(dataInstrumnet).replace('Instrument', "")
print(dataInstrumnet)
print(dataInstrumnet.split(','))

(exchange='NSE', token='26009', symbol='Nifty Bank', name='Nifty Bank', expiry=None, lot_size=None)
["(exchange='NSE'", " token='26009'", " symbol='Nifty Bank'", " name='Nifty Bank'", ' expiry=None', ' lot_size=None)']

**Comment by grsb007** [comment]
Is there any best way to read token, symbol, ltp etc for following data 
{26009: {'exchange': 'NSE', 'token': 26009, 'ltp': 30700.7, 'ltt': 1580203965, 'ltq': 0, 'volume': 0, 'best_bid_price': 0.0, 'best_bid_quantity': 0, 'best_ask_price': 0.0, 'best_ask_quantity': 0, 'total_buy_quantity': 0, 'total_sell_quantity': 0, 'atp': 0.0, 'exchange_time_stamp': 1580203965, 'open': 30922.0, 'high': 31048.45, 'low': 30656.35, 'close': 30837.4, 'yearly_high': 32613.1, 'yearly_low': 26560.6, 'instrument': Instrument(exchange='NSE', token='26009', symbol='Nifty Bank', name='Nifty Bank', expiry=None, lot_size=None)}, 
48166: {'exchange': 'NFO', 'token': 48166, 'ltp': 322.7, 'ltt': 1580203941, 'ltq': 20, 'volume': 417960, 'best_bid_price': 322.7, 'best_bid_quantity': 40, 'best_ask_price': 325.1, 'best_ask_quantity': 100, 'total_buy_quantity': 274740, 'total_sell_quantity': 43140, 'atp': 457.82, 'exchange_time_stamp': 1580203947, 'open': 464.0, 'high': 607.45, 'low': 305.15, 'close': 473.55, 'yearly_high': 16348693.49, 'yearly_low': 5435165.26, 'instrument': Instrument(exchange='NFO', token='48166', symbol='BANKNIFTY JAN 30500 CE', name='', expiry=datetime.date(2020, 1, 30), lot_size='20')}, 
48204: {'exchange': 'NFO', 'token': 48204, 'ltp': 300.6, 'ltt': 1580203954, 'ltq': 120, 'volume': 10441100, 'best_bid_price': 300.15, 'best_bid_quantity': 40, 'best_ask_price': 301.8, 'best_ask_quantity': 80, 'total_buy_quantity': 92760, 'total_sell_quantity': 52640, 'atp': 204.47, 'exchange_time_stamp': 1580203954, 'open': 222.85, 'high': 331.8, 'low': 122.0, 'close': 236.5, 'yearly_high': 16348693.49, 'yearly_low': 5435165.26, 'instrument': Instrument(exchange='NFO', token='48204', symbol='BANKNIFTY JAN 30900 PE', name='', expiry=datetime.date(2020, 1, 30), lot_size='20')}
}

Is it possible to store dict object based on the token, for above message

**Comment by krishnavelu** [comment]
Try this data[‘instrument’].symbol

**Comment by grsb007** [comment]
data[‘instrument’].symbol is giving  Symbol

**Comment by grsb007** [comment]
Could you please help me below , to store into dict object based on the token

{26009: {'exchange': 'NSE', 'token': 26009, 'ltp': 30700.7, 'ltt': 1580203965, 'ltq': 0, 'volume': 0, 'best_bid_price': 0.0, 'best_bid_quantity': 0, 'best_ask_price': 0.0, 'best_ask_quantity': 0, 'total_buy_quantity': 0, 'total_sell_quantity': 0, 'atp': 0.0, 'exchange_time_stamp': 1580203965, 'open': 30922.0, 'high': 31048.45, 'low': 30656.35, 'close': 30837.4, 'yearly_high': 32613.1, 'yearly_low': 26560.6, 'instrument': Instrument(exchange='NSE', token='26009', symbol='Nifty Bank', name='Nifty Bank', expiry=None, lot_size=None)}, 
48166: {'exchange': 'NFO', 'token': 48166, 'ltp': 322.7, 'ltt': 1580203941, 'ltq': 20, 'volume': 417960, 'best_bid_price': 322.7, 'best_bid_quantity': 40, 'best_ask_price': 325.1, 'best_ask_quantity': 100, 'total_buy_quantity': 274740, 'total_sell_quantity': 43140, 'atp': 457.82, 'exchange_time_stamp': 1580203947, 'open': 464.0, 'high': 607.45, 'low': 305.15, 'close': 473.55, 'yearly_high': 16348693.49, 'yearly_low': 5435165.26, 'instrument': Instrument(exchange='NFO', token='48166', symbol='BANKNIFTY JAN 30500 CE', name='', expiry=datetime.date(2020, 1, 30), lot_size='20')}, 
48204: {'exchange': 'NFO', 'token': 48204, 'ltp': 300.6, 'ltt': 1580203954, 'ltq': 120, 'volume': 10441100, 'best_bid_price': 300.15, 'best_bid_quantity': 40, 'best_ask_price': 301.8, 'best_ask_quantity': 80, 'total_buy_quantity': 92760, 'total_sell_quantity': 52640, 'atp': 204.47, 'exchange_time_stamp': 1580203954, 'open': 222.85, 'high': 331.8, 'low': 122.0, 'close': 236.5, 'yearly_high': 16348693.49, 'yearly_low': 5435165.26, 'instrument': Instrument(exchange='NFO', token='48204', symbol='BANKNIFTY JAN 30900 PE', name='', expiry=datetime.date(2020, 1, 30), lot_size='20')}
}

**Comment by krishnavelu** [comment]
This is general python question. You’ll find so many help outside this forum for a general python question than me.

**Comment by ns931** [comment]
Hi grsb007,

{'exchange': 'NSE', 'token': 26009, 'ltp': 30761.4, 'ltt': 1580209829, 'ltq': 0, 'volume': 0, 'best_bid_price': 0.0, 'best_bid_quantity': 0, 'best_ask_price': 0.0, 'best_ask_quantity': 0, 'total_buy_quantity': 0, 'total_sell_quantity': 0, 'atp': 0.0, 'exchange_time_stamp': 1580209829, 'open': 30922.0, 'high': 31048.45, 'low': 30656.35, 'close': 30761.4, 'yearly_high': 32613.1, 'yearly_low': 26560.6, 'instrument': Instrument(exchange='NSE', token='26009', symbol='Nifty Bank', name='Nifty Bank', expiry=None, lot_size=None)}

i could see you posting the above output. May i know the code that u have executed to get this output?
Requesting you to please help me on this. when i executed the code it keeps on running with out throwing any error or output
![Screenshot 2020-01-27 at 9 19 25 AM](https://user-images.githubusercontent.com/60307871/73379327-0f9cc680-42e8-11ea-9e04-38ae1506a0c6.png)

**Comment by grsb007** [comment]
Hello ns931,
Please use the code as per the below link code, already krishnavelu baba is explained in the main page

socket_opened = False
def event_handler_quote_update(message):
    print(f"quote update {message}")

def open_callback():
    global socket_opened
    socket_opened = True

alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
while(socket_opened==False):
    pass
alice.subscribe(alice.get_instrument_by_symbol('NSE', 'ONGC'), LiveFeedType.MARKET_DATA)
sleep(10)

**Comment by grsb007** [comment]
Thanks a lot, for your help

**Comment by krishnavelu** [comment]
“Could you please help me below , to store into dict object based on the token“
You’ve already made a dict based on token. What else you need?
