### ISSUE TITLE
Video tutorial required

### ISSUE THREAD

**Issue by sailoo121** [krishnavelu/alice_blue#54]
Hi sir

Your documentation page how to get api key and access token not clearly shown.

Can you please upload videos on official youtube channel of alice blue.

Like zerodha they use kite.trade to get api credentials, in aliceblue i can't find any url for get api key, token

Thanks

**Comment by krishnavelu** [comment]
Here is the official [documentation](http://antplus.aliceblueonline.com/#introduction) from alice blue. They’ve given very clearly how to communicate with their servers. Please refer it.

Call alice and ask to upload an official video of how to * in their official channel.
