### ISSUE TITLE
How to cancel exit CO and BO order with python code?

### ISSUE THREAD

**Issue by MoraleJ** [krishnavelu/alice_blue#56]
I tried to use reference code

I can't cancel or exit BO or CO orde with given example code

Alice.cancel_order('oms order id')

This code does not cancel or exit BO or CO order.

**Comment by krishnavelu** [comment]
What’s the error you are getting if you cancel?
Also give the order id as single legs order id. Not the common order id.

**Comment by MoraleJ** [comment]
I used oms order id and even leg order id but order does not get cancelled or exited... Finally i exited order manually...

I get success message in code when i use oms order id but order does not get cancelled from order book

**Comment by krishnavelu** [comment]
I don’t have an immediate answer for this.

**Comment by MoraleJ** [comment]
This issue is resolved

**Comment by krishnavelu** [comment]
Can you post what you did to solve this? It may be useful for remaining people.

**Comment by MoraleJ** [comment]
@krishnavelu Yes sure...
I just added leg order id into alice.cancel_order()

**Comment by krishnavelu** [comment]
`I just added leg order id into alice.cancel_order()`
Give me more details on this. What did you do? You mean you passed the leg order id in cancel_order()?
