### ISSUE TITLE
Need help or inputs about order messages 

### ISSUE THREAD

**Issue by grsb007** [krishnavelu/alice_blue#57]
Hello,

Requesting please update also add that what is a success or failure messages once we have to place the order so that it saves lot of time for development. 

for example, once placing the market order, success message like below 

{'status': 'success', 'message': 'Order placed successfully', 'data': {'oms_order_id': '20xx'}}

it will be greatly helpful and implement algos based on the order status  

Requesting you please consider this request

**Comment by krishnavelu** [comment]
List down all the success/failure messages here. I’ll add it in document.

**Comment by grsb007** [comment]
I am working on this will be posting as soon as possible, currently, I have only 2 messages only. I request others also please update on this.

**Comment by krishnavelu** [comment]
closing this as of now. Reopen if needed.
