### ISSUE TITLE
Add cancel_all_order method. 

### ISSUE THREAD

**Issue by jaydave1988** [krishnavelu/alice_blue#58]
We can have cancel_all_order method similarly upstox are providing. 
I know alice blue is not giving REST API for that. I mailed them to support it.
Till they support, you can add below code:

def cancel_all_order(self):
        orders = self.get_order_history()['data']
        if not orders:
            return

        for c_order in orders['pending_orders']:
            self.cancel_order(c_order['oms_order_id'])

**Comment by jaydave1988** [comment]
Any update? What is your opinion?

**Comment by krishnavelu** [comment]
Will implement in free time. But you need to test it and let me know if that's working

**Comment by jaydave1988** [comment]
Sure. If you want then I can also contribute in this code base. After your review approval, I can commit.

**Comment by krishnavelu** [comment]
Create a pull request.

**Comment by krishnavelu** [comment]
@jaydave1988 did you create a pull request?

**Comment by krishnavelu** [comment]
I've added a new function cancel_all_orders(). Please take the latest of develop and test it.

**Comment by krishnavelu** [comment]
hi @jaydave1988 did you test it?

**Comment by jaydave1988** [comment]
Yes.. It is working fine.
