### ISSUE TITLE
Tick update is slow for nifty/banknifty futures or stops randomly

### ISSUE THREAD

**Issue by vischenera** [krishnavelu/alice_blue#59]
Tick update is slow for nifty/banknifty futures and stops randomly after sometime. Tick updates are faster in mcx and rarely stops(had couple Once it is stopped I need to restart the code I have tested the code in my computer as well as google virtual machine. Is anyone facing this issue? or what might be wrong ?

**Comment by ns931** [comment]
When i have subscribed for scrips close to 100 (Equity) the tick update stops after some time not sure why this is happening.  
In The docx they have mentioned that the limit for subscription is 220.

**Comment by krishnavelu** [comment]
I'm getting ticks for whole day. No problems yet. I subscribe all nifty50.

**Comment by vischenera** [comment]
@krishnavelu 
-Are you handling network issues/ data issues with separate logic? 
First of all what i noticed is that we need to restart websocket if updates are not available for sometime. Right now using kite api for data and aliceblue for placing orders

**Comment by krishnavelu** [comment]
I don’t use separate logic in my application. Whatever restart needed is implemented in library itself.

**Comment by yogesh1236** [comment]
sir 
how can we convert tickdata to ohlc.
please guide

**Comment by krishnavelu** [comment]
If you understand what is OHLC, you can easily convert tick to OHLC.
Take any time frame you want (time frame of tick data)
O - open
H - High
L - Low
C - Close

**Comment by yogesh1236** [comment]
Sir will you please explain how to get the tick data and how to print it. Using livefeed.
Can we assign a variable to tick.
Please give a small code if possible.

**Comment by krishnavelu** [comment]
Here is an [example](https://gist.github.com/krishnavelu/e0df312ccf5f022edb1823461ff4230e)

**Comment by krishnavelu** [comment]
Closing this as of now.

**Comment by RajeshSivadasan** [comment]
Hi @krishnavelu ,
I am facing this tick missing issue.  I have implemented error_callback(error) and close_callback(). I observed that once the error comes up in connection it stops receiving ticks. The initial error I got today is:
_[WinError 10054] An existing connection was forcibly closed by the remote host_
Then later on below error:
_Connection is already closed._   

I have only subscribed to two instruments Nifty and Crude current future.

Pls advise.

**Comment by krishnavelu** [comment]
As I told you already.

Theses are volatile days & even a perfectly working system will break on these volatile days. 
Wait for non-volatile days for LTP data without any problems.

Also use a VPS instead of home internet connection and a laptop. That will give you more reliable connection.

**Comment by RajeshSivadasan** [comment]
Thanks Krishna for the inputs. But what I have noticed is that whenever there is a reconnection the ticks stops comming. Can you please check this at your side? I would suggest to check one scrip say NIFTY futures for the entire day.  I have to restart the program altogether manually or I need to find a way to re trigger the program in case of reconnection. Thanks and as always, appreciate the great work you have put in, to build this package!

**Comment by vischenera** [comment]
@krishnavelu 
I tested this on google cloud when I reported this. I think issue is specific to NFO segment. I dint face any issue with MCX. I couldn't test equity segment as it is not enabled. 
Usually delay starts after 10-15 mins and just stop random. And requires a restart. But on budget day which was highly volatile I dint face any issue. Later I shifted to kite API so dint test this in current volatility

**Comment by krishnavelu** [comment]
@RajeshSivadasan enable logging in debug level. You'll get logs of when It's getting disconnected and when its getting reconnected. As I'm telling this many times, these are volatile days and its bound to happen. I don't face any serious issue in reconnecting. I was facing some reconnecting issue before, which are all solved.

**Comment by krishnavelu** [comment]
@vischenera If you feel you have a serious issue in this, I guess you need to contact alice. This library just bridges the alice server. If alice server doesn't send packets, the library also won't.
As I always say these are all volatile days. So wait for volatility cools down. Or contact alice.

**Comment by RajeshSivadasan** [comment]
@krishnavelu I am subscribing the instruments in the open_callback() event as a workaround for the ticks discontinuation issue once reconnect happens. This worked for me today as I faced websocket re connection multiple times today. Can this be taken care in the package or Alice Blue has to do anything in the server?

**Comment by krishnavelu** [comment]
Disconnection / reconnection is already taken care in the library.
