### ISSUE TITLE
Alice Blue server disconnects the Websocket connection randomly.

### ISSUE THREAD

**Issue by krishnavelu** [krishnavelu/alice_blue#6]
There is a [requirement](http://antplus.aliceblueonline.com/#heartbeat) that heartbeat should be sent every 10 seconds. 
This library was sending heartbeat every 10 seconds. Now its changed to 5 seconds. Still Alice Blue server disconnects the webserver connection randomly.

Here is the [log](https://gist.github.com/krishnavelu/f7f9bc5836f8071f4809a51b2c0dc811).

**Comment by krishnavelu** [comment]
This is fixed now by #9

**Comment by munivoltarc** [comment]
Hi, ran the code of connection for WebSocket given by yours as it is but it is giving this following error please solve the issue immediately please:
STAGE 1: Invalidate the previous session : Ok
STAGE 2: Create the new session : Ok
Connecting to Socket ...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], line 44
     40         LTP = feed_message[
     41             'lp'] if 'lp' in feed_message else LTP  # If LTP in the response it will store in LTP variable
     43 # Socket Connection Request
---> 44 alice.start_websocket(socket_open_callback=socket_open, socket_close_callback=socket_close,
     45                       socket_error_callback=socket_error, subscription_callback=feed_data, run_in_background=True,market_depth=False)
     47 while not socket_opened:
     48     pass

File [~\AppData\Roaming\Python\Python311\site-packages\pya3\alicebluepy.py:802](https://file+.vscode-resource.vscode-cdn.net/c%3A/BMB%2025022023/PYTHON%20PROJECTS/PR1/Aliceblue/Alicelogin/~/AppData/Roaming/Python/Python311/site-packages/pya3/alicebluepy.py:802), in Aliceblue.start_websocket(self, socket_open_callback, socket_close_callback, socket_error_callback, subscription_callback, check_subscription_callback, run_in_background, market_depth)
    800 print("Connecting to Socket ...")
    801 self.__stop_event = threading.Event()
--> 802 websocket.enableTrace(False)
    803 self.ws = websocket.WebSocketApp(self._sub_urls['base_url_socket'],
    804                             on_open=self.on_open,
    805                             on_message=self.on_message,
    806                             on_close=self.on_close,
    807                             on_error=self.on_error)
    809 # if run_in_background:
    810 #         print("Running background!")
    811 #         self.__ws_thread = threading.Thread(target=self.__ws_run_forever())
   (...)
    819 #     except Exception as e:
    820 #         print("Error:",e)

AttributeError: module 'websocket' has no attribute 'enableTrace'
