### ISSUE TITLE
An example to store incoming websocket price data

### ISSUE THREAD

**Issue by akpfs** [krishnavelu/alice_blue#60]
I'm new to coding but have years of experience in trading. Is it possible for someone to share an example of code to store incoming websocket instrument livefeed data? There are examples provided to use a MA and I've also checked the Zerodha articles but still I'm unable to store it in a dict or a pandas dataframe. It always shows as empty. Any help would be really appreciated to store it directly to a parquet file.Thanks

**Comment by krishnavelu** [comment]
This is the only [example](https://gist.github.com/krishnavelu/e0df312ccf5f022edb1823461ff4230e) I have

**Comment by akpfs** [comment]
Thanks for the reply. Yes, I've seen your example previously and the event handler updates the incoming data, is it possible to store the incoming data. When I subscribe multiple instruments,the data is showing in the output field in Jupyter notebook and Spyder. I want to save this data to db or parquet instead. I believe threading is enabled in alice_blue class itself, so it should be able to write to db and also manage orders. Hence, redis wouldn't be required. Please correct me if I'm wrong.

**Comment by krishnavelu** [comment]
I can only help on how to get data from alice server. After getting the data, how you are processing/storing is up to you.

**Comment by akpfs** [comment]
ok, thanks
