### ISSUE TITLE
Exiting positions

### ISSUE THREAD

**Issue by srinidhihebbar260297** [krishnavelu/alice_blue#61]
Hey krishnavelu is there any way I can Exit all the positons at once?

If no you can directly close the issue

thanks and regards

**Comment by krishnavelu** [comment]
Are you referring to close all button in upstox?
You have more powers than that close all button in upstox.
This is what you can do for now, get positions, close one by one in a for loop.

**Comment by srinidhihebbar260297** [comment]
I don't use upstox,Thank you,will try it out

**Comment by jaydave1988** [comment]
It is the same as issue #58

**Comment by srinidhihebbar260297** [comment]
Yeah found it, thanks

**Comment by bhushanjawle** [comment]
@jaydave1988 I believe #58 cancels 'pending' orders and this issue is about closing open positions, convenient kill switch as I understand. I believe currently there no such function in code, as @krishnavelu mentioned may need to exit one by one in  loop.

**Comment by nagarajtheprogrammer** [comment]
@krishnavelu what is the method to use to exit or square off the open position? I am not able to find anything in documentation.

**Comment by krishnavelu** [comment]
@nagarajtheprogrammer, 
`get positions, close one by one in a for loop.`

**Comment by nagarajtheprogrammer** [comment]
@krishnavelu when you say close, what is the method or api that you are referring to ?

**Comment by krishnavelu** [comment]
`what is the method or api that you are referring to ?`
Order placing API, Buy/Sell.

**Comment by nagarajtheprogrammer** [comment]
@krishnavelu let’s say I have a Sell order position for nifty futures. How can I close this position ? What would be the right order attributes ?  Appreciate your inputs

**Comment by krishnavelu** [comment]
Buy the same position/quantity. Same as you do in alice app or web.
