### ISSUE TITLE
Getting exception when user tries to use API for the first time.

### ISSUE THREAD

**Issue by jaydave1988** [krishnavelu/alice_blue#62]
When user try to use APIs, it is giving below exception.
File "***\AppData\Local\Programs\Python\Python36-32\lib\site-packages\alice_blue\alice_blue.py", line 247, in login_and_get_access_token
    code = resp.url[resp.url.index('=')+1:resp.url.index('&')]
ValueError: substring not found

User has to authorize the app for the first time. That's why resp.url is not containing '&'. User has to run the consent link provided in resp.url.
So above exception should be handled gracefully, it should print message like you have to open this url and authorize app.

**Comment by krishnavelu** [comment]
Will fix this in free time.

**Comment by balramzc** [comment]
After authorizing the consent url it is giving internal server error.

**Comment by balramzc** [comment]
I got the access token. Its working fine. Thanks a lot for providing this interface sir.
