### ISSUE TITLE
modify_order requires more than just order_id

### ISSUE THREAD

**Issue by priyakumariengineer** [krishnavelu/alice_blue#63]
In following code , comment right befow function defination says that it just requires order_id ,
but we can clearly see that there are more number of compulsory arguments than just order_id.

somehow I belive that instrument and product_type can be avoided , in upstox it is same.

```
    def modify_order(self, transaction_type, instrument, product_type, order_id, order_type, quantity=None, price=0.0,
                     trigger_price=0.0):
        """ modify an order, only order id is required, rest are optional, use only when
            when you want to change that attribute
        """
```

**Comment by priyakumariengineer** [comment]
Also with my best knowledge I tried to use modify_order but I am receiving :
{'status': 'error', 'message': 'Not able to Retrieve ModifyOrder ', 'data': {}}

Does ModifyOrder endpoint works correct ??

**Comment by krishnavelu** [comment]
Will modify the comment
