### ISSUE TITLE
how to build a strategy using python script?

### ISSUE THREAD

**Issue by rahulmr** [krishnavelu/alice_blue#64]
Do you have any example on how to build a strategy using python script which will run from 9.15 am to 3.15 pm?
It will exit all position at 3.15pm

Has anyone created any strategy scripts using python?

How to get LTP using the API?

Thanks in advance.

**Comment by krishnavelu** [comment]
Here is an [example](https://gist.github.com/krishnavelu/e0df312ccf5f022edb1823461ff4230e).

**Comment by krishnavelu** [comment]
Closing this.
