### ISSUE TITLE
alice.cancel_order('leg_order_indicator') doesn't cancel CO order...

### ISSUE THREAD

**Issue by MoraleJ** [krishnavelu/alice_blue#65]
Hello,
I am able to cancel BO order with Leg Order indicator but I can not cancel CO order with 'leg order indicator' or 'oms order id'...

Can someone help??

Thanks

**Comment by krishnavelu** [comment]
Issue #56 is also related. You've mentioned its solved.

**Comment by MoraleJ** [comment]
It's solved for BO order but CO order 'leg_order_indicator' is not working...

Aliceblue people are saying... We need to have 

DELETE   /api/v2/coverorder?oms_order_id=<val1>&leg_order_indicator=<val2>

But alice.cancel_order function is using

DELETE   /api/v2/order?oms_order_id=<val1>&leg_order_indicator=<val2>

Method when cover is not used...

**Comment by krishnavelu** [comment]
@MoraleJ Added feature for cancelling bo and co orders. Didn't test it because I won't be able to test it. Please test and let me know. Take the develop latest.

**Comment by krishnavelu** [comment]
This fix related to BO order #56  also which you opened.

**Comment by MoraleJ** [comment]
Hello Krishna,

I can't install latest Alice blue library with changes u made as library is not updated . So I updated "alice_blue.py" file like u changed it... But I am getting error saying api_helper doesn't have function which I am calling to cancel CO order...

Please find attached screenshot with live market error. 
![IMG_20200302_145312](https://user-images.githubusercontent.com/34776230/75663352-a61d2880-5c96-11ea-93a2-ed60a4a2026a
![IMG_20200302_150222](https://user-images.githubusercontent.com/34776230/75663468-db297b00-5c96-11ea-9505-c90950e1a3d0.jpg)

**Comment by krishnavelu** [comment]
Try this to install from develop branch

`pip install git+ https://github.com/krishnavelu/alice_blue.git/tree/develop`

**Comment by MoraleJ** [comment]
Sir, 
This  link is not working..

![Screenshot_2020-03-02-23-02-53-244_com android chrome](https://user-images.githubusercontent.com/34776230/75701683-30d34700-5cda-11ea-98c6-b989c5481efe.jpg)

**Comment by MoraleJ** [comment]
![IMG_20200302_230812](https://user-images.githubusercontent.com/34776230/75702017-bbb44180-5cda-11ea-8955-4e6d99ab1675.jpg)

**Comment by MoraleJ** [comment]
root@jeevanworld:~# pip install git+https://github.com/krishnavelu/alice_blue.git/tree/develop
Collecting git+https://github.com/krishnavelu/alice_blue.git/tree/develop
  Cloning https://github.com/krishnavelu/alice_blue.git/tree/develop to /tmp/pip-req-build-lft5z5yd
  Running command git clone -q https://github.com/krishnavelu/alice_blue.git/tree/develop /tmp/pip-req-build-lft5z5yd
  **fatal: repository 'https://github.com/krishnavelu/alice_blue.git/tree/develop/' not found**
ERROR: Command errored out with exit status 128: git clone -q https://github.com/krishnavelu/alice_blue.git/tree/develop /tmp/pip-req-build-lft5z5yd Check the logs for full command output

**Comment by MoraleJ** [comment]
Hello Krishna Sir,

Any update on this??

Thanks..

**Comment by krishnavelu** [comment]
uninstall the old version
`pip uninstall alice-blue`
install develop branch
`pip install https://github.com/krishnavelu/alice_blue/archive/develop.zip`

**Comment by MoraleJ** [comment]
Sir,
I installed devloped version but it's not cancelling CO order even I tried after changing "Cancel_bo_order" reference to "cancel_co_order" in python file in my directory where alice_blue is installed..

I am seeing cancel order function is not using "coverorder" call...

![IMG_20200304_125813](https://user-images.githubusercontent.com/34776230/75855732-e6a4af80-5e18-11ea-866c-accdeb245bbe.jpg)
![IMG_20200304_130054](https://user-images.githubusercontent.com/34776230/75855737-e9070980-5e18-11ea-834b-b0980cc18c33.jpg)
![IMG_20200304_125845](https://user-images.githubusercontent.com/34776230/75855739-e99fa000-5e18-11ea-9c72-b972af15c22c.jpg)

**Comment by MoraleJ** [comment]
I am getting success message... But in reality it doesn't cancel my CO order from order book...

**Comment by MoraleJ** [comment]
Krishna Sir,

Close this issue.. I created new function based your update and used it like as per screenshots..
![IMG_20200304_145004](https://user-images.githubusercontent.com/34776230/75864148-97b24680-5e27-11ea-94ff-96bf761a2d2e.jpg)
![IMG_20200304_145047](https://user-images.githubusercontent.com/34776230/75864158-9b45cd80-5e27-11ea-8d1f-252e62ca0a84.jpg)

Thanks a lot for your support...

**Comment by MoraleJ** [comment]
Issue resolved

**Comment by krishnavelu** [comment]
Sorry for the 'co' 'bo' typo. I've fixed it now. This is should work without the need of a separate `cancle_co_order` function.
Could you please test it once more with the new modification?

**Comment by MoraleJ** [comment]
Ok sir,

Can you provide me Devloped library installation link the updated one once again??
So that I can test.

**Comment by krishnavelu** [comment]
Its the same link as posted above.

> uninstall the old version
pip uninstall alice-blue
install develop branch
pip install https://github.com/krishnavelu/alice_blue/archive/develop.zip

**Comment by MoraleJ** [comment]
Ok Sir, I will test this in live market on Monday & will let you know...

**Comment by krishnavelu** [comment]
I'm waiting for your test results on 0.0.7 release. If this goes good. I'll make a new release which has many bug fixes & enhancements.

**Comment by MoraleJ** [comment]
Yes, I will update you for sure tomorrow (Monday Indian market hours)...

**Comment by MoraleJ** [comment]
@krishnavelu Sir,

Can you redefine this Cancel all orders function for CO and BO order as well with leg_order_id.

def cancel_all_orders(self):
        orders = self.get_order_history()['data']
        if not orders:
            return
        for c_order in orders['pending_orders']:
            self.cancel_order(c_order['oms_order_id'])

**Comment by krishnavelu** [comment]
@MoraleJ Can you please give me some get_order_history() results with CO BO as pending orders.?
For implementing cancel_all_orders() for CO & BO.
I cannot get this during market time.

**Comment by Chawdavijay** [comment]
Dear Sir,

Can you please guide me how to start streaming live data in aliceblue through API

**Comment by MoraleJ** [comment]
@Chawdavijay I use this attached program to stream live 1 second data for bank nifty...
I have removed my login, password & api secret...

U can replace urs...
![IMG_20200417_183800](https://user-images.githubusercontent.com/34776230/79572586-d3088c00-80da-11ea-9154-c94539b61530.jpg)

**Comment by Chawdavijay** [comment]
Thank you so much sir... 
Appreciate your quick response.

**Comment by Chawdavijay** [comment]
> @Chawdavijay I use this attached program to stream live 1 second data for bank nifty...
> I have removed my login, password & api secret...
> 
> U can replace urs...
> ![IMG_20200417_183800](https://user-images.githubusercontent.com/34776230/79572586-d3088c00-80da-11ea-9154-c94539b61530.jpg)

Hey, 
I am still not unable to fetched the LTP.. Can please guide me process Or steps to follow for getting LTP

**Comment by krishnavelu** [comment]
[Here](https://gist.github.com/krishnavelu/e0df312ccf5f022edb1823461ff4230e) Is an example strategy code.

**Comment by Chawdavijay** [comment]
> @Chawdavijay I use this attached program to stream live 1 second data for bank nifty...
> I have removed my login, password & api secret...
> 
> U can replace urs...
> ![IMG_20200417_183800](https://user-images.githubusercontent.com/34776230/79572586-d3088c00-80da-11ea-9154-c94539b61530.jpg)

Dear Moralej,

I have already install Pandas and numpy but also i am getting below error while running code given by you.
![image](https://user-images.githubusercontent.com/63785799/79831162-810a8380-83c4-11ea-8dc7-6555ef84a0b8.png)


After comment the "Import Pandas as pd" I am getting below error while i running the code.
![image](https://user-images.githubusercontent.com/63785799/79830400-e9f0fc00-83c2-11ea-9933-6367c92f3102.png)

Please check and let me what wrong i have done here

**Comment by Chawdavijay** [comment]
@MoraleJ 
@krishnavelu 

Hello Experts, 

Finally I am able to fetched the LTP... Thanks for your kind support .☺

I need one more and last help🙏

If I have place buy order successfully through python using API in aliceblue then how can i get Or print the Avg buy price of last transaction... (I need Avg buy price for comparing entry of new signal with Avg buying price of last trade). 

Can you please guide me something on this.. . 🙏

**Comment by jaydave1988** [comment]
> @MoraleJ Can you please give me some get_order_history() results with CO BO as pending orders.?
> For implementing cancel_all_orders() for CO & BO.
> I cannot get this during market time.

{'pending_orders': [{'validity': 'DAY', 'user_order_id': '1', 'trigger_price': 0.0, 'transaction_type': 'SELL', 'trading_symbol': 'SILVERM20APRFUT', 'remaining_quantity': 1, 'rejection_reason': '--', 'quantity': 1, 'product': 'BO', 'price': 41780.0, 'order_type': 'LIMIT', 'order_tag': '', 'order_status': 'open', 'order_entry_time': 1588067685, 'oms_order_id': '200428000249221', 'nest_request_id': '1', 'lotsize': 5, 'login_id': 'AB052386', 'leg_order_indicator': '200428000249220', 'instrument_token': '214541', 'filled_quantity': 0, 'exchange_time': 1588067685, 'exchange_order_id': '242011900070286', 'exchange': 'MCX', 'disclosed_quantity': 1, 'client_id': 'AB052386', 'average_price': 0.0}, 
{'validity': 'DAY', 'user_order_id': '1', 'trigger_price': 41380.0, 'transaction_type': 'SELL', 'trading_symbol': 'SILVERM20APRFUT', 'remaining_quantity': 1, 'rejection_reason': '--', 'quantity': 1, 'product': 'BO', 'price': 0.0, 'order_type': 'SL-M', 'order_tag': '', 'order_status': 'trigger pending', 'order_entry_time': 1588067685, 'oms_order_id': '200428000249222', 'nest_request_id': '1', 'lotsize': 5, 'login_id': 'AB052386', 'leg_order_indicator': '200428000249220', 'instrument_token': '214541', 'filled_quantity': 0, 'exchange_time': 1588067685, 'exchange_order_id': '242011900070287', 'exchange': 'MCX', 'disclosed_quantity': 1, 'client_id': 'AB052386', 'average_price': 0.0}],

'completed_orders': [{'validity': 'DAY', 'user_order_id': '1', 'trigger_price': 41580.0, 'transaction_type': 'BUY', 'trading_symbol': 'SILVERM20APRFUT', 'remaining_quantity': 0, 'rejection_reason': '--', 'quantity': 1, 'product': 'BO', 'price': 41580.0, 'order_type': 'LIMIT', 'order_tag': '', 'order_status': 'complete', 'order_entry_time': 1588067685, 'oms_order_id': '200428000249220', 'nest_request_id': '1', 'lotsize': 5, 'login_id': 'AB052386', 'leg_order_indicator': '', 'instrument_token': '214541', 'filled_quantity': 1, 'exchange_time': 1588067685, 'exchange_order_id': '242011900070285', 'exchange': 'MCX', 'disclosed_quantity': 0, 'client_id': 'AB052386', 'average_price': 41580.0}]}

**Comment by jaydave1988** [comment]
Hi @MoraleJ, What will be leg_order_id in cancel_order for BO orders? I am not able to cancel the order with leg_order_indicator coming in order history.

**Comment by krishnavelu** [comment]
@jaydave1988 I guess leg order id worked for @MoraleJ 
Did you gave the correct leg order id and oms order id?

**Comment by jaydave1988** [comment]
Hi @krishnavelu , I have posted order book in above comment. I used 'leg_order_indicator': '200428000249220' and 'oms_order_id': '200428000249221' from pending orders. But it was giving error. Am I making any mistake? Is there any other way to find leg_order_id?

**Comment by krishnavelu** [comment]
It should work. What was the error message?

**Comment by jaydave1988** [comment]
dict: {'status': 'error', 'message': 'Error Occurred :API ERROR , ErrorCode : 16', 'data': {}}

**Comment by krishnavelu** [comment]
This you told for cancel-all method. Not for individual cancel.
Individual cancel should work, try again.

**Comment by jaydave1988** [comment]
Ultimately you are calling cancel_order method from cancel_all. So I tweak that and add lag_indicator in that. I attach the debugger and found that error.

**Comment by jaydave1988** [comment]
One thing I noticed from @MoraleJ 's screenshots, he is passing same order_id in oms_order_id and lag_order_id and it is working. Why it is working in that case? See... https://github.com/krishnavelu/alice_blue/issues/65#issuecomment-594370475

**Comment by jaydave1988** [comment]
So, I have tried with order_id=lag_order_id to cancel bo order and it is working.

**Comment by MoraleJ** [comment]
I have used cancel CO order function

It works for me...

Nowdays I am not able to trade as co bo orders are blocked

**Comment by MoraleJ** [comment]
![IMG_20200429_123745](https://user-images.githubusercontent.com/34776230/80569312-5187f680-8a16-11ea-9c54-f6cca45f9dae.jpg)
![IMG_20200429_123708](https://user-images.githubusercontent.com/34776230/80569325-5a78c800-8a16-11ea-87db-b6e99767b142.jpg)

**Comment by MoraleJ** [comment]
Check these functions and verify them there was one big in CO order class and function

**Comment by MoraleJ** [comment]
> @MoraleJ Can you please give me some get_order_history() results with CO BO as pending orders.?
> For implementing cancel_all_orders() for CO & BO.
> I cannot get this during market time.

I am not able to trade nowdays.. as co bo orders are blocked mostly

**Comment by krishnavelu** [comment]
@jaydave1988 @MoraleJ 
What do you guys give for order_id and leg_order_id for cancelling co/bo orders?
Which is correct?

**Comment by jaydave1988** [comment]
I have tried for BO only, order_id and leg_order_id both should be same to cancel order i.e. leg_order_indicator field from pending orders.

**Comment by krishnavelu** [comment]
Both should be same ? Are you sure? Can you try CO also?

**Comment by jaydave1988** [comment]
It is working for me in BO. I will try for CO on Monday.

**Comment by MoraleJ** [comment]
> It is working for me in BO. I will try for CO on Monday.

Yes when I was playing it was working for me with BO order but same thing was not working for me for CO order so I edited python file after installation and added separate CO function to cancel CO order which worked for me...

But yes @jaydave1988 provide ur inputs on Monday and if possible provide required information to @krishnavelu for cancel all order function so he will update it and we will have latest update in this library

**Comment by jaydave1988** [comment]
I am not able to find CO order in portal.
![1](https://user-images.githubusercontent.com/20503868/81158851-0174db00-8fa6-11ea-95a4-3263b8d0cfd2.png)

**Comment by krishnavelu** [comment]
Contact alice for app related things.

**Comment by krishnavelu** [comment]
@jaydave1988 @MoraleJ @Chawdavijay 
I added functionality to cancel CO and BO in cancel_all_orders(). Please test and let me know.
I'm relying on you guys because I cannot test this market time.

**Comment by jaydave1988** [comment]
Hi @krishnavelu , There is a problem in BO. I have verified that.. Actual code should like below.
def cancel_all_orders(self):
        ret = []
        orders = self.get_order_history()['data']
        if not orders:
            return
        for c_order in orders['pending_orders']:
            if(c_order['product'] == 'BO' and c_order['leg_order_indicator']):
                r = self.cancel_order(c_order['leg_order_indicator'],
                                      leg_order_id = c_order['leg_order_indicator'])
            elif(c_order['product'] == 'CO'):
                r = self.cancel_order(c_order['oms_order_id'], leg_order_id = c_order['leg_order_indicator'], is_co = True)
            else:
                r = self.cancel_order(c_order['oms_order_id'])
            ret.append(f'{r} => {c_order}')
        return ret

P.S - I have not verified CO orders.

**Comment by krishnavelu** [comment]
@jaydave1988 I've fixed it. Can you please verify CO also?

**Comment by MoraleJ** [comment]
> @jaydave1988 I've fixed it. Can you please verify CO also?

@krishnavelu 
Today I checked CO order cancellation with
alice.cancel_all_orders()

It's working well..

Please close this issue and release your this development version to production..

Sorry for delay..

Thanks a lot for your continuous support..
