### ISSUE TITLE
Need Renko/Range Bars with EMA

### ISSUE THREAD

**Issue by balramzc** [krishnavelu/alice_blue#67]
Can you please provide me Renko with EMA strategy to place orders in BankNiftyWeekly options

**Comment by krishnavelu** [comment]
The base information needed for all technical analysis indicator is tick data. This library can only provide tick data. You can search for some other python library which converts tick data to whatever indicator you want. And create a strategy out of it. This is purely application part which I cannot support.

**Comment by PreneeshAV** [comment]
> Can you please provide me Renko with EMA strategy to place orders in BankNiftyWeekly options

Hi, i would like to discuss about the requirement you have posted. How can i contact you.

**Comment by krishnavelu** [comment]
There comes a business proposal...

**Comment by PreneeshAV** [comment]
Am working on renko bars and
strategies in python. I think balram is also working on similar project. So
wanted to get associated for mutual benefit.
