### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by srinidhihebbar260297** [krishnavelu/alice_blue#68]
TypeError: Required parameter live_feed_type not of type LiveFeedType

Code used:

instrument=(alice.get_instrument_by_symbol('NSE', 'Nifty Bank'))
socket_opened = False
def event_handler_quote_update(message):
    print(f"quote update {message}")

def open_callback():
    global socket_opened
    socket_opened = True

alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
while(socket_opened==False):
    pass
alice.subscribe(instrument, LiveFeedType.MARKET_DATA)
sleep(10)

**Comment by krishnavelu** [comment]
The above code works for me. Just test the above code without anything else. Or post your full code along with your imports. 
You are mixing upstox import with alice.

**Comment by srinidhihebbar260297** [comment]
Hey krishnavelu Please find the code below I am getting this error after Updating the library






from alice_blue import *
import datetime
import threading
import numpy as np
import pandas as pd






now = datetime.datetime.now()
timenow = now.strftime("%H:%M:%S")
comparetime = now.replace(hour=9, minute=39, second=0, microsecond=0)
ninethirty = comparetime.strftime("%H:%M:%S")
date_today = datetime.datetime.now()
currentdatetoday = date_today.date()
comparetime1 = now.replace(hour=3, minute=0, second=0, microsecond=0)
three = comparetime1.strftime("%H:%M:%S")
count=0
ltp=0
df_list=[]
call_ss=[]
put_ss=[]

def call_sell(bn_call):
    
    global alice
    global ltp
    print(alice.place_order(transaction_type = TransactionType.Sell,
                     instrument = bn_call,
                     quantity = 1,
                     order_type = OrderType.Market,
                     product_type = ProductType.Delivery,
                     price = 0.0,
                     trigger_price = None,
                     stop_loss = None,
                     square_off = None,
                     trailing_sl = None,
                     is_amo = False))
def put_sell(bn_put):
    global alice
    global ltp
    print(alice.place_order(transaction_type = TransactionType.Sell,
                     instrument = bn_put,
                     quantity = 1,
                     order_type = OrderType.Market,
                     product_type = ProductType.Delivery,
                     price = 0.0,
                     trigger_price = None,
                     stop_loss = None,
                     square_off = None,
                     trailing_sl = None,
                     is_amo = False))
    
    
def event_handler_quote_update(message):
    global ltp
    ltp = message['ltp']
    df_list.append(ltp)


def open_callback():
    global socket_opened
    socket_opened = True



def main():
    global socket_opened
    global alice
    global username
    global password
    global accesstoken
    global ltp
    global count
    global call_ss
    global put_ss
    global df_list
    username=""
    password=""
    accesstoken = ""
    alice = AliceBlue(username=username, password=password, access_token=accesstoken)    
     
    ins_scrip = alice.get_instrument_by_symbol('NSE', "Nifty Bank")
    
    socket_opened = False
    alice.start_websocket(subscribe_callback=event_handler_quote_update,
                          socket_open_callback=open_callback,
                          run_in_background=True)
    while(socket_opened==False):
        pass
    alice.subscribe(ins_scrip, LiveFeedType.COMPACT)

    
    
   
    while True:
        alice.start_websocket(subscribe_callback=event_handler_quote_update,
                          socket_open_callback=open_callback,
                          run_in_background=True)
        
        
        while len(df_list)>0:
            print(ltp )
            print("round ltp is",(round(ltp/100)*100))
            bn_call = alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=datetime.date(2020, 3, 12), is_fut=False, strike=(round(ltp/100)*100)+300, is_CE = True)
            bn_put=alice.get_instrument_for_fno(symbol = 'BANKNIFTY', expiry_date=datetime.date(2020, 3, 12), is_fut=False, strike=(round(ltp/100)*100)-300, is_CE = False)
            alice.start_websocket(subscribe_callback=event_handler_quote_update,
                          socket_open_callback=open_callback,
                          run_in_background=True)
            df_list.append(ltp)
            
           
    
    
main()

**Comment by srinidhihebbar260297** [comment]
I have been fetching accesstoken from client rest api and Have gotten rid of sensitive information in the Above code

**Comment by srinidhihebbar260297** [comment]
After force upgrading the installation,the issue has been resolved


Thanks for the Reply and Support
