### ISSUE TITLE
Add Method for finding nearest expiry.

### ISSUE THREAD

**Issue by jaydave1988** [krishnavelu/alice_blue#69]
How about adding method for finding nearest expiry. like below:

    def get_nearest_expiry_for_fno(self, symbol, is_fut=False, strike=None, exchange = 'NFO'):
        res = self.search_instruments(exchange, symbol)
        ret_list = []
        matches = []
        for i in res:
            if i.expiry is None:
                continue
            if(is_fut == True):
                if('FUT' in i.symbol):
                    matches.append(i)
            elif ('FUT' not in i.symbol):
                sp = i.symbol.split(' ')
                if(strike is None):
                    matches.append(i)
                else:
                    if(float(sp[-2]) == float(strike)):
                        matches.append(i)

        matches.sort(key=lambda x: x.expiry, reverse=False)

        for i in matches:
            if i.expiry == matches[0].expiry:
                ret_list.append(i)
            else:
                break
        return ret_list

**Comment by krishnavelu** [comment]
This doesn't communicate with alice server. This library is made to make the communicate easy with alice server. 
This can be done in application part.
