### ISSUE TITLE
How to implement heart-beat function in  sample main.py

### ISSUE THREAD

**Issue by vikram477** [krishnavelu/alice_blue#71]
KrishNa Sir
I write algo in python using your reference code(main.py) and deploy it on amazon cloud 15 day ago .
But as I start program in morning after some time LTP not get refreshed web socket already closed appear. I come to know there need to send heartbeat every 10 second otherwise web socket get closed .
My problem is how to code in PYTHON to send heart beats and rectify this problem completely plz help me on this issue

**Comment by krishnavelu** [comment]
I remember I already replied to thus query. Did you re-create this?
That 10 second heart beat is already implemented in library. Also take the latest develop branch and deploy in AWS.
If even that didn’t help, wait for volatility to get reduced. I don’t see any problem in daily ticks. But even a good working system will be broken in these high volatile days.

**Comment by daxusanboposis494** [comment]
Same issue is happening with me. I have subscribe for banknifty future.
ltp is is not updating.I am attaching log here.
[tick.txt](https://github.com/krishnavelu/alice_blue/files/4392203/tick.txt)

**Comment by daxusanboposis494** [comment]
Attached are the more detailed logs. Connection is getting closed for banknifty.
[log.txt](https://github.com/krishnavelu/alice_blue/files/4413241/log.txt)

**Comment by krishnavelu** [comment]
Which internet do you use?
Is it residential or commercial? Is it stable?

Also try one in any VPS.
Normally VPS’s internet connection will be pretty stable.

**Comment by daxusanboposis494** [comment]
I am using residential internet. As i mentioned script is working fine with mcx crude.
seems like this is faced by other users also #59 
@vischenera are you still facing this issue?

**Comment by krishnavelu** [comment]
Closing this as Heart beat is already implemented.

**Comment by rishiajmera** [comment]
Hi Krishna,
I am also facing this issue. My WebSocket feed stops working after some time.
I have been testing it for the last 5 days. Out of 5 days, on one day web socket worked for the whole day and on other days it stopped working after some time. This is very strange behaviour. 
Any suggestion?

**Comment by krishnavelu** [comment]
1 day it worked without any problem. This proves your code and library is doing the right job.

Remaining is in server’s hand and in your internet connection.
The library will reconnect automatically.
