### ISSUE TITLE
Delay is websocket streaming

### ISSUE THREAD

**Issue by developersb** [krishnavelu/alice_blue#72]
Hello,

We are using your library to stream live data on our web application.Till date, everything is working fine and we appreciate this library very much. But we are facing a problem, That we are fetching data from this function.

def event_handler_quote_update(message):

		formatted = json.dumps(message)
		livedata = json.loads(formatted)

		currentTime = datetime.now(pytz.timezone('Asia/Kolkata')).strftime('%H:%M:%S')
		current = datetime.strptime(currentTime, '%H:%M:%S').time()	

		instrumentlog = alice.get_instrument_by_token(int(livedata['token']))
	

		#return
		liverecords = {
			"time":current,
			"token":livedata['token'],
			"ltp":livedata['ltp'],
			"ltt":livedata['ltt']
		}

           logging.info(f"===={liverecords}-:===============================================")

	
Now ae are getting live records, But compare to the terminal side record, Our live records are delay or late. We have tried to check this issue by the Aliceblue team but they said that issues are with our code and not with the API. I am not having an idea to solve this issue and stuck in it. Any help or solution from your side will be highly appreciated.

**Comment by krishnavelu** [comment]
How are you measuring the delay? That matters most. If you need, try to measure everything in milliseconds level and try reducing unwanted things in your application.
If you found something in this library, which is lousy or taking much time, feel free to report it and I’ll be happy to fix it if there are any solutions.

**Comment by developersb** [comment]
Hello,

We are measuring delay by getting the difference of time between terminal side records and live records( records got by using a library).
Ex: Let say for 30 minutes the time of terminal side records and live records are the same, there is no delay, But after that time we are getting the difference in time and delay from both of the times.
Is there any memory-related issue in python? Are we supposed to reconnect the web-socket again and again after a certain amount of time?

Also, we are not having any idea how to get rid of this issue. If you can help us then it would be really great.
Also, let us know if there is any personal platform where we can connect with you regarding this. Ex: Slack, Skype, etc.
Awaiting your response, Thanks for all.

**Comment by developersb** [comment]
Can someone help us here with delayed live rates?  is it possible that it might be because of limited memory limit?

**Comment by krishnavelu** [comment]
This is not memory issue. In all the above explanation you didn’t mention how much is the delay.
Delay might not be more than few milliseconds.
Are you going to do HFT? Only if you are doing HFT you need to go milliseconds/microseconds level.

You can join this [unofficed](https://unofficed.com/chat/) group

**Comment by developersb** [comment]
Unfortunately, there isn’t any defined delay but it is getting increased after getting accurate data for approx 30-40 min 
Can you advise which channel to use after joining the group?

**Comment by developersb** [comment]
Also, we encountered an error while WebSocket mode was on

Error is:
ERROR:websocket:error from callback <bound method AliceBlue.__on_error_callback of <alice_blue.alice_blue.AliceBlue object at 0x7fa1d861e9b0>>: error_callback() missing 1 required positional argument: 'error'

**Comment by krishnavelu** [comment]
You can use #general or #daytraders in slack.
Also I’m available in slack.

**Comment by avnkailash** [comment]
@developersb Can you share some details on the processing you are doing with the messages recieved on the websocket? 

Basically try to calculate the following metrics:
Average no.of updates recieved on the websocket per second. Average processing time for each update received. These two values should help you to investigate further about the possible delay getting added.

And if I am not wrong, the delay is quite visible from 10-15 min time itself. Not even 30 min. It all depends on the processing logic you have.

**Comment by developersb** [comment]
@krishnavelu  Is it possible to get ` alice.get_order_history() ` from websocket in this library?

**Comment by krishnavelu** [comment]
@developersb First this has to be there in alice-server. Then only we can implement in this library.
I already have an open [issue](https://github.com/krishnavelu/alice_blue/issues/2) related to this.

**Comment by Chawdavijay** [comment]
Hey Sir, 
Can you please provide me a code to print LTP of reliance for every second. 
Please🙏

**Comment by krishnavelu** [comment]
[Here](https://gist.github.com/krishnavelu/e0df312ccf5f022edb1823461ff4230e) is an example strategy code. Not exactly what you’ve asked for but you can get a idea.
