### ISSUE TITLE
Unable to place SL-M Order.

### ISSUE THREAD

**Issue by pangalanrao** [krishnavelu/alice_blue#74]
Hi,
  Below is the code 
                            order_id=alice.place_order(transaction_type = TransactionType.Sell,
                                                 instrument = alice.get_instrument_by_symbol(symbol['exchange'][x],tradingsymbol),
                                                 quantity =quantity,
                                                 order_type = OrderType.StopLossMarket,
                                                 product_type = ProductType.Intraday,
                                                 price = 0,
                                                 trigger_price = low,
                                                 stop_loss = None,
                                                 square_off = None,
                                                 trailing_sl = None,
                                                 is_amo = False
                                                 )
                            print(now,tradingsymbol,quantity,'SELL',order_id)
I used exact same syntax as in the documentation. When I run this in Market hours, in the trading order screen it gets rejected saying Invalid Price Type. However when I run in other time that reason is not shown. Please look into it

**Comment by krishnavelu** [comment]
Price type should be float. You are passing integer.
Also I’ve solved an issue related to SL-M, which is not yet released and still in develop.
Take the latest develop and use it.
