### ISSUE TITLE
Start Websocket works only in Python Shell but not in Commond Prompt of Windows nor in Ubuntu

### ISSUE THREAD

**Issue by pangalanrao** [krishnavelu/alice_blue#75]
Hi,
  Below is the code

socket_opened = False
def event_handler_quote_update(ticks):
    print(ticks)
    c=db.cursor()
    c.execute(insert_into_table,{'tradingsymbol':ticks['instrument'][2],
                                    'date':ticks['exchange_time_stamp'],'last_price':ticks['ltp']})
    try:
        db.commit()
        print("4")
    except Exception:
        print("X")
        db.rollback()

def open_callback():
    global socket_opened
    socket_opened = True

alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
while (socket_opened==False):
    print("Y")
    break
alice.subscribe(instruments_tradingsymbol, LiveFeedType.COMPACT)

This code works when I run in IDLE Python Shell. However when I run same file in commond prompt of windows or ubuntu (AWS) websocket doesn't open. Please look into it.

**Comment by krishnavelu** [comment]
> def event_handler_quote_update(ticks):
print(ticks)
c=db.cursor()
c.execute(insert_into_table,{'tradingsymbol':ticks['instrument'][2],
'date':ticks['exchange_time_stamp'],'last_price':ticks['ltp']})
try:
db.commit()

Thats a half cooked code. No one can use this.
What is `db.cursor` ?
What is `c.execute` ?
I don’t understand where the function `event_handler_quote_update` starts and where it ends?
