### ISSUE TITLE
ValueError: substring not found

### ISSUE THREAD

**Issue by rajnikantkumbhar** [krishnavelu/alice_blue#76]
```
#import logging
#logging.basicConfig(level=logging.DEBUG)
from alice_blue import *

access_token = AliceBlue.login_and_get_access_token(username='', password='', twoFA='a',  api_secret='')

alice = AliceBlue(username='', password='', access_token=access_token)

print(alice.get_balance()) # get balance / margin limits
print(alice.get_profile()) # get profile
```

Following error shown for above simple login and session generation code.
Please check. It is error at line no 247 in alice_blue.py.

 File "/home/rajnikant/.local/lib/python3.8/site-packages/alice_blue/alice_blue.py", line 247, in login_and_get_access_token
    code = resp.url[resp.url.index('=')+1:resp.url.index('&')]
ValueError: substring not found

**Comment by dextrus123** [comment]
same error with same line # i.e. 247

krishna sir please help

**Comment by krishnavelu** [comment]
This is fixed in develop and not yet released. Take the latest develop and use.

**Comment by rajnikantkumbhar** [comment]
Issue is same even after using latest develop. Please help.

**Comment by krishnavelu** [comment]
print the url which it is trying to authorize & try it manually.
You need to authorize the app manually once.
After that this problem won’t be there.

**Comment by rajnikantkumbhar** [comment]
Sorry Sir,
I don't understand what is manual app authorization. Following is my simple code to get access token and print user profile. I have not developed any web app for it. Please guide what is missing.

```
#import logging
#logging.basicConfig(level=logging.DEBUG)
from alice_blue import *

access_token = AliceBlue.login_and_get_access_token(username='', password='', twoFA='a',  api_secret='')

alice = AliceBlue(username='', password='', access_token=access_token)

print(alice.get_balance()) # get balance / margin limits
print(alice.get_profile()) # get profile
```

**Comment by krishnavelu** [comment]
Post me the logging results of errors/warning when you execute this. Enable logging first.

**Comment by rajnikantkumbhar** [comment]
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth2/auth?response_type=code&state=test_state&client_id=AB078153&redirect_uri=https://ant.aliceblueonline.com/plugin/callback HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth/login?login_challenge=fd5d87777e3144d98ce69b133adcdcaa HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "POST /oauth/login?login_challenge=fd5d87777e3144d98ce69b133adcdcaa HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth/twofa?login_challenge=fd5d87777e3144d98ce69b133adcdcaa&login_id=AB078153&question_ids=48%7C2&questions=Which+brand+of+Mobile+Phone+do+you+use%3F+%28e.g.+Nokia%2C+LG+etc%29%7CWhat+is+your+first+Mobile+brand%3F HTTP/1.1" 200 None
INFO:root:Assuming answers for all 2FA questions are 'a', Please change it to 'a' if not
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "POST /oauth/twofa?login_challenge=fd5d87777e3144d98ce69b133adcdcaa&login_id=AB078153&question_ids=48%7C2&questions=Which+brand+of+Mobile+Phone+do+you+use%3F+%28e.g.+Nokia%2C+LG+etc%29%7CWhat+is+your+first+Mobile+brand%3F HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth2/auth?client_id=AB078153&login_verifier=d1e3fa62bdac48f99ec2d9c59bffc583&redirect_uri=https%3A%2F%2Fant.aliceblueonline.com%2Fplugin%2Fcallback&response_type=code&state=test_state HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth/consent?consent_challenge=e45bd4d8c93e4c43805d494f0d80f2f6 HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/home/rajnikant/Code/sample.py", line 5, in <module>
    access_token = AliceBlue.login_and_get_access_token(username='AB078153', password='Shriya@123', twoFA='a',  api_secret='PXAKUSCDLTPWX2F39BG9MKNYWTX8I5OA8ATIF6GHS5XEKRD35NKWS78FKMYB4D5Q')
  File "/home/rajnikant/.local/lib/python3.8/site-packages/alice_blue/alice_blue.py", line 247, in login_and_get_access_token
    code = resp.url[resp.url.index('=')+1:resp.url.index('&')]
ValueError: substring not found

**Comment by rajnikantkumbhar** [comment]
@krishnavelu 
Please check above logging result.

**Comment by rajnikantkumbhar** [comment]
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth2/auth?response_type=code&state=test_state&client_id=AB078153&redirect_uri=https://ant.aliceblueonline.com/plugin/callback HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth/login?login_challenge=fd5d87777e3144d98ce69b133adcdcaa HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "POST /oauth/login?login_challenge=fd5d87777e3144d98ce69b133adcdcaa HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth/twofa?login_challenge=fd5d87777e3144d98ce69b133adcdcaa&login_id=AB078153&question_ids=48%7C2&questions=Which+brand+of+Mobile+Phone+do+you+use%3F+%28e.g.+Nokia%2C+LG+etc%29%7CWhat+is+your+first+Mobile+brand%3F HTTP/1.1" 200 None
INFO:root:Assuming answers for all 2FA questions are 'a', Please change it to 'a' if not
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "POST /oauth/twofa?login_challenge=fd5d87777e3144d98ce69b133adcdcaa&login_id=AB078153&question_ids=48%7C2&questions=Which+brand+of+Mobile+Phone+do+you+use%3F+%28e.g.+Nokia%2C+LG+etc%29%7CWhat+is+your+first+Mobile+brand%3F HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth2/auth?client_id=AB078153&login_verifier=d1e3fa62bdac48f99ec2d9c59bffc583&redirect_uri=https%3A%2F%2Fant.aliceblueonline.com%2Fplugin%2Fcallback&response_type=code&state=test_state HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth/consent?consent_challenge=e45bd4d8c93e4c43805d494f0d80f2f6 HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/home/rajnikant/Code/sample.py", line 5, in <module>
    access_token = AliceBlue.login_and_get_access_token(username='xxx', password='xxx', twoFA='a',  api_secret='xxx')
  File "/home/rajnikant/.local/lib/python3.8/site-packages/alice_blue/alice_blue.py", line 247, in login_and_get_access_token
    code = resp.url[resp.url.index('=')+1:resp.url.index('&')]
ValueError: substring not found

**Comment by rajnikantkumbhar** [comment]
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth2/auth?response_type=code&state=test_state&client_id=AB078153&redirect_uri=https://ant.aliceblueonline.com/plugin/callback HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth/login?login_challenge=fd5d87777e3144d98ce69b133adcdcaa HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "POST /oauth/login?login_challenge=fd5d87777e3144d98ce69b133adcdcaa HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth/twofa?login_challenge=fd5d87777e3144d98ce69b133adcdcaa&login_id=AB078153&question_ids=48%7C2&questions=Which+brand+of+Mobile+Phone+do+you+use%3F+%28e.g.+Nokia%2C+LG+etc%29%7CWhat+is+your+first+Mobile+brand%3F HTTP/1.1" 200 None
INFO:root:Assuming answers for all 2FA questions are 'a', Please change it to 'a' if not
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "POST /oauth/twofa?login_challenge=fd5d87777e3144d98ce69b133adcdcaa&login_id=AB078153&question_ids=48%7C2&questions=Which+brand+of+Mobile+Phone+do+you+use%3F+%28e.g.+Nokia%2C+LG+etc%29%7CWhat+is+your+first+Mobile+brand%3F HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth2/auth?client_id=AB078153&login_verifier=d1e3fa62bdac48f99ec2d9c59bffc583&redirect_uri=https%3A%2F%2Fant.aliceblueonline.com%2Fplugin%2Fcallback&response_type=code&state=test_state HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth/consent?consent_challenge=e45bd4d8c93e4c43805d494f0d80f2f6 HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/home/rajnikant/Code/sample.py", line 5, in <module>
    access_token = AliceBlue.login_and_get_access_token(username='AB078153', password='xxx', twoFA='a',  api_secret='PXAKUSCDLTPWX2F39BG9MKNYWTX8I5OA8ATIF6GHS5XEKRD35NKWS78FKMYB4D5Q')
  File "/home/rajnikant/.local/lib/python3.8/site-packages/alice_blue/alice_blue.py", line 247, in login_and_get_access_token
    code = resp.url[resp.url.index('=')+1:resp.url.index('&')]
ValueError: substring not found

**Comment by rajnikantkumbhar** [comment]
@krishnavelu 
Please check above logging result. I have replaced user password with xxx.

**Comment by aeron7** [comment]
@rajnikantkumbhar Hey, Please follow this thread http://forum.unofficed.com/t/how-to-authorize-aliceblue-oauth-app-first-time/341

Let me know if the problem persists.

**Comment by rajnikantkumbhar** [comment]
@aeron7 @krishnavelu 
Issue resolved. Thanks.
