### ISSUE TITLE
Unable to edit or delete order

### ISSUE THREAD

**Issue by imdkbj** [krishnavelu/alice_blue#77]
I am getting error for subjected issue on rest api, not python expert so using rest API. Pls help someone on this.

**Comment by krishnavelu** [comment]
What do you mean be subjected issue?
What error are you getting?

**Comment by imdkbj** [comment]
Hi, i mean to that : after CO/BO orders execution a new order id assigned  so that editing from initial order_id is not working.

**Comment by krishnavelu** [comment]
Try new version 0.0.7.
Leg order is introduced in cancel-order()
