### ISSUE TITLE
Please add the MarketStatus

### ISSUE THREAD

**Issue by simucentral** [krishnavelu/alice_blue#78]
Please add the feature to retrieve the market status.

**Comment by krishnavelu** [comment]
Will add this when I get time.

**Comment by krishnavelu** [comment]
@simucentral Can you please enable logging upto `info` level and get me the message during market open & close? There is already logging [code](https://github.com/krishnavelu/alice_blue/blob/c50c8e5d44a35adbff540f110c8c89ac44fa5583/alice_blue/alice_blue.py#L330) for market status.

**Comment by krishnavelu** [comment]
@simucentral any updates?

**Comment by simucentral** [comment]
I have added the following codes in the code.

import logging
logging.basicConfig(level=logging.DEBUG)

I didn't receive any INFO on market status, when I tried just now before market opening.

Do you have a code snippet to check that one? I must be doing something wrong.
Because I am not sure which part of the code calls this "def __on_data_callback ..."

**Comment by krishnavelu** [comment]
We need to subscribe to market status. I’ll add code for subscribing market status. After that we can get it.

**Comment by simucentral** [comment]
Thank you. I look forward to the feature.

**Comment by krishnavelu** [comment]
@simucentral Added subscription of market status and exchange messages. If you subscribe to market status or exchange messages, you'll get logging.info whenever there is a market status change or exchange messages.

**Comment by krishnavelu** [comment]
@simucentral added functions to get market messages and exchange messages.
See this [document](https://github.com/krishnavelu/alice_blue/tree/develop#market-status-messages--exchange-messages) for more details. 
Let me know if you need any help.

**Comment by krishnavelu** [comment]
@simucentral also added callbacks.

**Comment by simucentral** [comment]
Thank you so much. Very useful feature. 👍
