### ISSUE TITLE
unable to get access_token

### ISSUE THREAD

**Issue by akshay951228** [krishnavelu/alice_blue#79]
AliceBlue.login_and_get_access_token(username='AB082998', password="*****", twoFA='a',  api_secret="client_secret") 

I'm unable to get the access token using the above, please help me

**Comment by krishnavelu** [comment]
Take the latest develop and try.

**Comment by akshay951228** [comment]
socket_opened = False
def event_handler_quote_update(message):
    print(f"quote update {message}")

def open_callback():
    global socket_opened
    socket_opened = True

alice.start_websocket(subscribe_callback=event_handler_quote_update,
                      socket_open_callback=open_callback,
                      run_in_background=True)
while(socket_opened==False):
    pass
alice.subscribe(alice.get_instrument_by_symbol('NSE', 'ONGC'), LiveFeedType.MARKET_DATA)
sleep(10)

cannot able to get live stream data

when I debug the code ,

https://github.com/krishnavelu/alice_blue/blob/master/alice_blue/alice_blue.py#L371
in this line it causing infinte loop 
and is was not get thru below subscribe function 

could be please tell how to solve this.

looking forward for your answer

if there is  any update snippet for live data feed, please post it

**Comment by Bobby136** [comment]
> Take the latest develop and try.

What do you mean by latest develop ????

**Comment by krishnavelu** [comment]
> What do you mean by latest develop ????

Develop branch
