### ISSUE TITLE
ticks getting skipped

### ISSUE THREAD

**Issue by nickphelis** [krishnavelu/alice_blue#81]
Dear Sir,
             I have observed that once you subscribe to more than 3-4 instruments the ticks are getting skipped. I have compared it with live ticks from ANT web and many ticks get skipped and hence it is impossible to make precise candles from the provided tick data. 
![ticks list](https://user-images.githubusercontent.com/61717484/78005830-c275b900-7359-11ea-88bf-3746802a8da2.png)
please check the screenshot. The ticks are for 'RELIANCE'. As you can see that the ticks were missing for almost 20 seconds. Also many ticks in between are missing as a stock like Reliance ticks multiple times a second and all those ticks are not received from the socket. Please note that I have tested this code by subscribing different number of instruments from 1 to 20 and have found that this issue only starts once the number of instruments subscribed are more than 3 or 4. Here is the link for the gist:https://gist.github.com/nickphelis. 
Please check it and let me know how this issue can be fixed

**Comment by krishnavelu** [comment]
I have some tick data. Will post it here.

**Comment by krishnavelu** [comment]
Sorry I thought I had some tick data. But that was from Zerodha. I don't have a full day tick data.

**Comment by krishnavelu** [comment]
@nickphelis Try this in a VPS environment. Home internet will be lagging. VPS internet will be pretty stable. 
This can be an issue on internet side too.
Closing this for now. If needed reopen.
