### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by Kishan1464** [krishnavelu/alice_blue#82]
import logging
from alice_blue import *
username = "******"
password = "*******"
twoFA = '*'
api_secret = "*****"

AliceBlue.login_and_get_access_token(username=username, password=password, twoFA=twoFA,  api_secret=api_secret)
print("done")

print()

------------------------------------------------------

this error is showing

Traceback (most recent call last):
  File "D:/pycharm project/mycode/alice.py", line 8, in <module>
    AliceBlue.login_and_get_access_token(username=username, password=password, twoFA=twoFA,  api_secret=api_secret)
  File "C:\Users\kishan\AppData\Local\Programs\Python\Python37\lib\site-packages\alice_blue\alice_blue.py", line 247, in login_and_get_access_token
    code = resp.url[resp.url.index('=')+1:resp.url.index('&')]
ValueError: substring not found

Process finished with exit code 1

**Comment by krishnavelu** [comment]
This issue is solved in develop branch. Not yet released. Take latest develop branch and install.

**Comment by krishnavelu** [comment]
@Kishan1464  Closing this for now. Reopen if needed.
