### ISSUE TITLE
How can we pass tag while placing order?

### ISSUE THREAD

**Issue by rishiajmera** [krishnavelu/alice_blue#86]

**Comment by rishiajmera** [comment]
I don't see any option to pass tag in place_order method. How can we pass order tag?

**Comment by krishnavelu** [comment]
Why do you need a tag? If you place order you get order_id in return.

**Comment by rishiajmera** [comment]
I'm placing multiple orders at the same time in threads. So sometimes, it gets difficult to figure out which order is which. Tag helps for that. Anyhow, I have done the change in the library but please provide an option to pass order ID in next update.

**Comment by krishnavelu** [comment]
You get order_id in return while you place order. You cannot pass order_id while placing order.
Even if you place multiple orders in thread for each and every place_order you’ll get an order_id in return.

**Comment by rishiajmera** [comment]
What if due to network error, I didn't receive order ID but the order is actually placed? This has happened with Zerodha API. so passing a tag is important. If I don't receive order ID, I will first check with order book if any order present with the tag I had passed. If yes, the order was successful otherwise it will retry placing order.

**Comment by krishnavelu** [comment]
Does zerodha provides order tags? Give me example.

**Comment by rishiajmera** [comment]
Aliceblue already has that functionality of tag. Its just that order placement function doesn't have any argument for it. "order_1" is passed every time. In Zerodha API, they are just allowing the users to pass their own unique order ID. You can do that too. 
This is just a suggestion for improvement. Hope you're not taking it wrong.

**Comment by krishnavelu** [comment]
@rishiajmera Added `order_tag` default argument in `place_order()` function

**Comment by rishiajmera** [comment]
Thanks, Krishna for adding it. Cheers!
