### ISSUE TITLE
Adding an Error Exception for Dumb People.

### ISSUE THREAD

**Issue by aeron7** [krishnavelu/alice_blue#89]
Make an Error Notification - 

If the User ID is not authorized by the app manually and it throws not authorized error, Maybe we can throw this error - 

Please open this link in a web browser and authorize - https://ant.aliceblueonline.com/oauth2/auth?response_type=code&state=test_state&client_id=**UNOFFICED**&redirect_uri=**https://www.unofficed.com/alice/fallback/** 

I have marked two variables here

https://ant.aliceblueonline.com/oauth2/auth?response_type=code&state=test_state&client_id="+client_id+"&redirect_uri="+redirect_url+"

**Comment by krishnavelu** [comment]
This is already solved for normal case app name=username. But in different app name I don’t know how it behaves.

**Comment by aeron7** [comment]
It will throw same error. Just tested. Closing the issue.
