### ISSUE TITLE
No APR MAY NIFTY contracts

### ISSUE THREAD

**Issue by keerthankumar** [krishnavelu/alice_blue#90]
im running below command

 alice.search_instruments('NFO', 'NIFTY')
 
It gives me all the instruments of JUNE JULY AUG SEP but NOT APR and MAY. I this bug?
If i change the script to BANKNIFTY It gives all the instruments from APR. Please help me to resolve this..

**Comment by krishnavelu** [comment]
Didn’t get time to test this. Will update you later.

**Comment by keerthankumar** [comment]
hi any update ?

**Comment by krishnavelu** [comment]
[Here](https://gist.github.com/krishnavelu/fc4234525d44d4d3711787d2271e7269) is the response I got for nifty. May is there.
