### ISSUE TITLE
How to restart websocket when it breaks in the middle?

### ISSUE THREAD

**Issue by rishiajmera** [krishnavelu/alice_blue#93]
Hello,
I have observed that WebSocket stops working due to some reason. I am able to capture it with "socket_close_callback". How can I re-subscribe to it after that? Using the same start_websocket method? It gives a warning that the web socket is already subscribed. Let me know if any other details required.

Thanks,
Regards,
Rishi A.

**Comment by krishnavelu** [comment]
@rishiajmera when the websocket disconnects don’t panic and terminate the program. The library will reconnect automatically.
Enable logging and see when the web socket is disconnecting and reconnecting.

**Comment by krishnavelu** [comment]
Closing this as of now. Reopen if its not yet solved.

**Comment by rishiajmera** [comment]
Hi Krishna, This issue is not solved yet. Web socket still breaks abruptly.

**Comment by krishnavelu** [comment]
It breaks because of server, the library automatically reconnects. We cannot do anything about server disconnects.
