### ISSUE TITLE
Unable to cancel bo orders using cancel_all_orders method.

### ISSUE THREAD

**Issue by jaydave1988** [krishnavelu/alice_blue#94]
1. Not able to cancel Bo orders. Getting this error. 
dict: {'status': 'error', 'message': 'Error Occurred  :API ERROR , ErrorCode : 16', 'data': {}}

2. Please add logger.error if any error is coming while canceling order in cancel_all_orders method, so that user can get to know whether all orders are cancelled or not.

**Comment by jaydave1988** [comment]
I think this is related to https://github.com/krishnavelu/alice_blue/issues/65#issuecomment-599238995

**Comment by jaydave1988** [comment]
Please take it on priority. Unnecessarily, aliceblue is charging 20rs cancellation charges per order.

**Comment by krishnavelu** [comment]
For now you can cancel one by one.
Will implement cancel all order for bo and co.

**Comment by krishnavelu** [comment]
@jaydave1988 is cancel all working for you for both CO and BO?

**Comment by jaydave1988** [comment]
I did not get a chance to test for CO... Will update you soon
