### ISSUE TITLE
websocket errors even when running 

### ISSUE THREAD

**Issue by agujrathi** [krishnavelu/alice_blue#95]
Team,

When a websocket closed, I am starting.. If it again closed, started again..
Everything is smooth..

However, below warnings are popped up in thousands.. Almost each second, 50 such logs on screen..

```
WARNING:alice_blue.alice_blue:websocket run forever ended in exception, socket is already opened
WARNING:alice_blue.alice_blue:websocket run forever ended in exception, socket is already opened
WARNING:alice_blue.alice_blue:websocket run forever ended in exception, socket is already opened
WARNING:alice_blue.alice_blue:websocket run forever ended in exception, socket is already opened
WARNING:alice_blue.alice_blue:websocket run forever ended in exception, socket is already opened
WARNING:alice_blue.alice_blue:websocket run forever ended in exception, socket is already opened
WARNING:alice_blue.alice_blue:websocket run forever ended in exception, socket is alr
```

Please look at this.. whats the issue... I also checked by giving a delay on 1-2 seconds after connection closed and restart a new sonnection.. still no progress.
Data ticks are received succesfully though..

**Comment by krishnavelu** [comment]
You don’t need to restart websocket manually. The library automatically does it.

**Comment by agujrathi** [comment]
If I dont restart on socket disconnect, here is what happens..
Socket closed every 10-30 seconds again and again..
My subscribed symbols are lost and I need to subscribe again and again..

here is sample log flow... 

![image](https://user-images.githubusercontent.com/26158721/80695588-c0874d00-8af3-11ea-864e-c17142d93c26.png)

So its stuck without doing anything...
library connects socket again.. but it again and again disconnects...

**Comment by krishnavelu** [comment]
You don’t need to subscribe too...
How many are you subscribing?

**Comment by agujrathi** [comment]
Around 15-20 scripts only for NFO. 

relevant piece of code..
  ```
alice.start_websocket(subscribe_callback=on_ticks2,
                      socket_open_callback=open_callback,
                      socket_close_callback = on_disconnect,
                      run_in_background=True)

    while(socket_opened==False):
        pass
```
```

def on_disconnect(*args, **kwargs):

    global socket_opened

    socket_opened = False

    msg = "error: in on_disconnect args=%s, kwargs=%s" % (args, kwargs)
    print(msg)
    logger.debug(msg)
    logger.debug("not reconnecting...")

    return
```
```
def open_callback():
    global socket_opened
    logger.debug("websocket opened again")
    socket_opened = True

socket_opened = False
```

**Comment by krishnavelu** [comment]
Home internet may be problematic some time.

**Comment by agujrathi** [comment]
No-No ...
I am running on cloud server with 16 GB RAM and 4 core CPUs.. and high
grade network speed..
Today also all day disconnects and connects....

Let me know if any more sample code I need to send.. ?
There is issue for sure something around this..

**Comment by krishnavelu** [comment]
For me also it disconnects, but it connects again smoothly. In these volatile days disconnections are expected.

**Comment by jaydave1988** [comment]
My point is if it got disconnect for few seconds, how will we get correct OHLC data for that minute? Is there any suggestion/solution?

**Comment by krishnavelu** [comment]
You won’t get correct for that minute. It’s not possible. Disconnects are expected, especially in this volatile times.
Upstox, zerodha may be better than alice (I’m not sure)
If you need more rock solid data (100% uninterrupted) you need to get a leased line and live data from NSE.

**Comment by developersb** [comment]
Hello @krishnavelu,

We've had a few errors while running WebSocket so I can't be sure how it works and the only script is running but the WebSocket live feed won't work after that error.

`websocket._exceptions.websocketconnectionclosedexception connection is already closed  `

Is it possible to stop the script when I got the error or reconnect `alice.start_websocket(` function 
Would you please advise us?

**Comment by marirs** [comment]
Yes - I'm facing the same problem. the websocket connection is closed, because after sometime the ws becomes a str. If you do type(ws) it shows as str and not websocket any more. So there is no way it can get reconnected. Please check and advice

**Comment by krishnavelu** [comment]
You need to do `alice.start_websocket` only once. The library sends heartbeat & reconnects itself if disconnected. If you try to reconnect manually using your code, you'll receive this error.

**Comment by developersb** [comment]
Thanks for your response,
Btw, How can I handle it because WebSocket live feed does not work after that error?
can u please advise us?

**Comment by krishnavelu** [comment]
It’s supposed to work. We don’t need to do anything.
If you doubt it’s not working, enable logging of alice module to info level and provide me logs in a gist. I’ll look into that.

**Comment by hyndex** [comment]
i am also facing this problem too

**Comment by krishnavelu** [comment]
resubscribe implemented after reconnection. Take the latest develop and let me know if it works for you guys. I'll also test it.

**Comment by marirs** [comment]
1st test - It got stopped and re-connected automatically! Works so far

**Comment by marirs** [comment]
2nd test - it times out and starts after a long time:
>> 2020-06-15 15:24:45 | MCX:CRUDEOIL JUN FUT          | Last trading price: 2723.0
>> !! ticker:Error = [Errno 60] Operation timed out
>> ticker:Websocket disconnected
>> ticker:Websocket connected
>> 2020-06-15 15:51:49 | NSE:MARUTI                    | Last trading price: 5475.75

**Comment by krishnavelu** [comment]
The server was not up that time.

**Comment by marirs** [comment]
Got it - it got disconnected 4 times yesterday and got reconnected immediately from what I ran yesterday. Will keep posted if anything different happens!
Thanks

**Comment by marirs** [comment]
Works well - yesterday 2 disconnects and re connected immediately!

**Comment by yogeshhrathod** [comment]
are this new fixes are in the **pip alice-blue** ?

**Comment by krishnavelu** [comment]
yes

**Comment by rajukiranlr** [comment]
Hi Sir, 
i am try to extract the live data to excel file, which is working fine, if there is no internet connection also it stops and reconnects correctly, 
problem i am facing is i have converted the script into to single exe and running it, it is working fine for few hours, and then immediately it stops without any error.  enabled the debug also nothing it shows.  not sure what is the issues. 

i can see around 7000 to 8000 ticks data in excel file, but suddenly it stops. without any error, please suggest. 
python 3.8.5 64bit and windows 10 64 bit.

**Comment by krishnavelu** [comment]
There should be some memory leakage issue.

**Comment by rajukiranlr** [comment]
i was thinking it might be excel file issues, changed the data store to database sqlite3, but still after converting to exe, it failed, witout any errror.  
for memory issues i checked the below , but no error there also. 
Go to Search, type Memory Diagnostic Tool and open it.
Choose Restart now and check for problems and don’t forget to save your work before restarting.

**Comment by krishnavelu** [comment]
I cannot help on your application problems. I can help only problems related to this library.

**Comment by ABHISHEK830STAR** [comment]
> You don’t need to subscribe too... How many are you subscribing?

I am also subscribed, any other code for live market data? what is the code  to export it into CSV or excel .

**Comment by nithishkailas** [comment]
2022-02-14 12:21:35.560 : ERROR : error from callback <bound method AliceBlue.__on_close_callback of <alice_blue.alice_blue.AliceBlue object at 0x000002862AB436D0>>: __on_close_callback() takes from 1 to 2 positional arguments but 4 were given

When internet gets disconnected, it gets reconnected automatically.
It works fine but this error comes up from time to time till the end of the day

**Comment by Akshattanishq** [comment]
<img width="465" alt="image" src="https://user-images.githubusercontent.com/102853523/162559850-3822c3eb-1631-4a58-8a63-4ad10abd1332.png">
HOW DO I FIX THIS SIR?

**Comment by himanshunayak1974** [comment]
I am getting below error related to websocket:
websocket run forever ended in exception got an unexpected keyword arguement 'ping_payload'
