### ISSUE TITLE
Facing issue connection error

### ISSUE THREAD

**Issue by keerthankumar** [krishnavelu/alice_blue#98]
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ant.aliceblueonline.com', port=443): Max retries exceeded with url: /oauth2/auth?response_type=code&state=test_state&client_id=AB059409&redirect_uri=https://ant.aliceblueonline.com/plugin/callback (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0C678E50>: Failed to establish a new connection:
[Errno 11002] getaddrinfo failed'))

**Comment by krishnavelu** [comment]
This is internet connection error. Must be problem with your internet.
