### ISSUE TITLE
place_basket_order() raises exception for data type of price as float

### ISSUE THREAD

**Issue by proritu** [krishnavelu/alice_blue#99]
While placing basket order getting the below error.

TypeError: Element price in orders should be of type float

Below is the code:

order1 = {  "instrument"        : alice.get_instrument_by_symbol('NSE', 'INFY'),
            "order_type"        : OrderType.Market,
            "quantity"          : 1,
            "transaction_type"  : TransactionType.Buy,
            "product_type"      : ProductType.Delivery}
order2 = {  "instrument"        : alice.get_instrument_by_symbol('NSE', 'SBIN'),
            "order_type"        : OrderType.Limit,
            "quantity"          : 2,
            "price"             : 280.0,
            "transaction_type"  : TransactionType.Sell,
            "product_type"      : ProductType.Intraday}
order = [order1, order2]
print(alice.place_basket_order(order))

**Comment by akashrajcashrayz** [comment]
sir when this issue will be fixed?

**Comment by akashrajcashrayz** [comment]
sir still getting issue
   raise TypeError("Element price in orders should be of type float")
TypeError: Element price in orders should be of type float

**Comment by proritu** [comment]
@akashrajcashrayz you are getting the issue still now because it has been fixed but not published yet, version 0.0.8 will be released soon, please update when that is available.

**Comment by krishnavelu** [comment]
@akashrajcashrayz its now fixed in develop. Take latest develop branch and install.
